### ISSUE TITLE
Missing title in mirrored RSS feed

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#10015]
- [X] I have searched open and closed issues for duplicates

### Bug Description
When mirroring this feed https://www.filmdienst.de/rss/mediatheken the title isn't shown in the friendica post 

### Steps to Reproduce
1.  add rss feed
2.  mirror a post
3.  watch things happen

- Actual Result: Title is missing
- Expected Result: The title (in this case) "Serie: Solsidan" should appear as title or inline text.

### Screenshots

Feed
![00_temp00](https://user-images.githubusercontent.com/24474762/110444329-2c93f380-80bd-11eb-826e-057b2b811e52.jpg)

Friendica post
![00_temp01](https://user-images.githubusercontent.com/24474762/110444442-4c2b1c00-80bd-11eb-95b7-e6edbf72c60e.jpg)

### Platform Info

Friendica Version: 2021.03-rc
Friendica Source:  git
PHP version: 7.4
SQL version:  mariaandjosephDB

**Comment by annando** [comment]
You have enabled the fetching of additional information. In this situation the title isn't used.

**Comment by hoergen** [comment]
But why not?

**Comment by annando** [comment]
A title is more suitable for longer texts. So when you mirror feeds where the feed item contains the whole story, then a title looks great. But when you fetch the additional data then the text from the feed isn't used at all. Instead the system fetches the data via OpenGraph and similar. Then the attached data is providing the title in the attached data itself.

**Comment by hoergen** [comment]
But the logic is completely inconsistent. Because the way you explained, there shouldn't be ANY text above the link opengraph (see the screenshots above) . 

![grafik](https://user-images.githubusercontent.com/24474762/110507300-2c691780-8100-11eb-953a-ad663dcec105.png)

I pasted this screenshot, because on the one above were some pixels missing. 

So IF opengraph would be used (that is normally shown in the link preview, isn't it?) then this should be reflected in the text above. But it doesn't. So there is a mixture of feed and opengraph (maybe, but i can't find it).

As far as I can see, the only thing that there happens is, that the title is thrown away,. Everything else is used, where it shouldn't. According your explanation.

So, by having a function that says "fetch further information for feeds" it is weird that some present information is thrown away. It would  make more sense, if it would follow the logic of the description that information will be enriched with, maybe additional available information.

![grafik](https://user-images.githubusercontent.com/24474762/110508965-e3b25e00-8101-11eb-8709-fa2051d5a4fd.png)

![grafik](https://user-images.githubusercontent.com/24474762/110509027-f62c9780-8101-11eb-9f11-3a4f33a179de.png)

**Comment by hoergen** [comment]
btw the "normal" behaviour is broken for UX reasons.
![grafik](https://user-images.githubusercontent.com/24474762/110521130-a785fa00-810f-11eb-849b-20799d5fc21e.png)

There is an Image in the RSS feed and friendica adds it as an attachment.  :(

**Comment by annando** [comment]
The image from the last post appeared as image on my system. 

The thing with throwing away the title is done since the attached data then provides some kind of headline as well. When further information are fetched, the text can be taken from different sources. Some feeds only provide a link without any text. Then mostly the headline is taken as text. Or if everything is missing, the fetched text is taken (then the attached information doesn't contain this text to avoid duplicate text).

The thing with the title is done because a title indicates that a longer (blog-) text is following. Also it looks better on other systems like Mastodon and Pleroma.

**Comment by hoergen** [comment]
OK, now I know why it is broken. Thank you for the explanation of the causes.

**Comment by annando** [comment]
For your information, this is how these different types do look like on Mastodon:
![Bildschirmfoto vom 2021-03-10 20-42-00](https://user-images.githubusercontent.com/844208/110687883-44fd2e80-81e1-11eb-9548-d567890fb76e.png)
![Bildschirmfoto vom 2021-03-10 20-41-39](https://user-images.githubusercontent.com/844208/110687890-4595c500-81e1-11eb-9ac4-9c7c58c673ec.png)
![Bildschirmfoto vom 2021-03-10 20-41-11](https://user-images.githubusercontent.com/844208/110687894-46c6f200-81e1-11eb-97a1-89d88f71aa03.png)

**Comment by hoergen** [comment]
Yes I see. Thanks. This is a bigger bug than I expected.

**Comment by annando** [comment]
It's all about how Mastodon interprets our content. The first picture is the "fetch information" type - which I think look the best. The other look more weird since they are sent as the "article" not as a "note" (we have to sent it as "article" since otherwise we cannot transmit a title). Sadly Mastodon decided to display the "article" type that way. Normally it even would only display it with the title and the link to the article, not even with some text. We managed to transmit some text in some other field that is displayed as well.

**Comment by hoergen** [comment]
The more important is, that friendica formats the the post more precise internally and for sure then for exporting to other platforms. I would suggest the KISS principle like :

1. define the structure of the result
2. Do you we need the title of an RSS entry? Isn't it enough to put it as first line followed by an empty line?
3. fetch information
4. optional fetch more information (or even more)
5. sort, format, remove double information
6. Layout the information of the RSS entry and create the post

That's a clean structure on how to setup such a workflow and will mostly avoid any complications on other platforms.

**Comment by annando** [comment]
Well, I would say that we are doing exactly this. And most important: We aren't *exporting to other platforms* - the content that is transmitted to Mastodon via AP is transmitted exactly that way to other Friendica servers as well since we now mostly use AP even for inter-Friendica communication (and that content can't be different for different receivers with the same protocol). So when you suggest removing the title then we would remove it for Friendica as well.

But: I have the feeling as if we should discuss about this topic per voice, so that we avoid misunderstandings.

**Comment by hoergen** [comment]
No way that it is done like I described ;) Just see step 3-6 are different. According your description, the code is currently doing something else. ;) 
If you like , we can talk about this via voice. Via phone or mumble server. Give me a ping on element.

**Comment by hoergen** [comment]
I am recalling this Bug report with a wont fix.
