### ISSUE TITLE
Disable Googles FLoC

### ISSUE THREAD

**Issue by ghost** [friendica/friendica#10151]
Please disable Googles Federated Learning of Cohorts (FLoC) by adding `Permissions-Policy: interest-cohort=()` to the header files. See e.g. https://cleanuptheweb.org/ for some more information.

**Comment by AlfredSK** [comment]
> disable Googles Federated Learning of Cohorts (FLoC) by adding ...

This is not how it works. It's not that easy. Please read https://seirdy.one/2021/04/16/permissions-policy-floc-misinfo.html for more information.

**Comment by ghost** [comment]
Well, the specific implementations might be different, but as a network that consists to a larger degree of people that moved away from surveillance capitalism by GAFAM ;) I think it is a good idea to implement something that deals with this new technique by Google.

**Comment by nupplaphil** [comment]
As far as I understand the article, we "just" have to be sure to not call 3rd party libraries, which are either call `document.interestCohort()` or are loading Google-Ad services.

> If your website does not include JS that calls document.interestCohort(), it will not leverage Google’s FLoC. Explicitly opting out will not change this.

> As per a post on Google’s web development blog, web.dev, FLoC also will be enabled during an origin trial if the page “loads ads or ads-related resource”; i.e., anything that Chromium’s ad tagger classifies as an ad. If your website loads third-party ads, it might end up getting opted-in even if those ads don’t call document.interestCohort().

I don't think we're using such 3rd libraries, but maybe @MrPetovan can have a look at our dependencies :)

**Comment by ghost** [comment]
I'm not sure about that... Maybe not calling FLoC is enough to not need to opt-out. But who says that Google will not change its default behaviour silently at some point? 
Explicitly stating to opt-out might be the safe way...

**Comment by Seirdy** [comment]
I'm the author of the linked article. Here's a [Fediverse thread](https://pleroma.envs.net/notice/A6LSBaN7ztfpZFj8Yy) where I addressed some concerns.

There are two concerns:

- Making sure your own site doesn't leverage Google's FLoC
- Reducing the size of a user's fingerprint on other websites.

The first concern is a non-issue on Friendica since Friendica doesn't load untrusted third-party scripts with antifeatures like tracking/fingerprinting.

As for the second concern: excluding yourself from cohort calculation doesn't necessarily reduce the size of a user's fingerprint; other sites in a user's history will fill the gap. Additionally, Google could just do what all the adtech companies did to the Do Not Track header; plenty of companies (e.g., Reddit) generated some good PR by obeying it before backpedaling when their shareholders called.

If you want to start a coordinated anti-Google effort, picking something more effectively and less easily undermined is probably worthwhile. I'd recommend helping get people off Chrome and Chromium-based browsers that haven't patched out FLoC (or all Chromium-based browsers altogether). I admit this is harder, but I think it's more worthwhile.

You're free to do this on your own site, but making it the default on upstream software just galvanizes Google to start ignoring this non-standard use of the Permissions Policy header.

**Comment by AlfredSK** [comment]
Thanks for taking part here. :-)

From my point of view - after reading a lot about it - we don't have a scenario where that header does add something to our user's privacy (you cannot opt-out of something you don't use :-) ). On the other hand it doesn't do any harm. 

There is one thing where we need to consider the privacy of our users - third party content. For example some embedded content like video players (e.g. Youtube) and URL previews can pull in scripts from third party sites. 

We already have the proxy feature which helps to not expose client IPs to those third party sources. Also, I see scripts being blocked by my content security policy. Some embedded content is trying to load JS from ad-related third party sites. A CSP that sets 'script-src' 'self' really blocks those third party scripts for user clients.

**Comment by MrPetovan** [comment]
@ingoj , you are operating a web server, and as such you can add yourself arbitrary headers to all the pages your web server is serving. Like @Seirdy said it well, this header isn't relevant to Friendica because we don't run Google Ads.

**Comment by ghost** [comment]
As per discussion the header doesn't seem to be necessary... closing...
