### ISSUE TITLE
Problem with LDAP Auth and Active Directory "Add on not configured or missing php-ldap extension"

### ISSUE THREAD

**Issue by twicechild** [friendica/friendica#10188]
Hello everyone!

I seem to have a problem connecting friendica with my Active directory for user authentication. I'm using the docker version `friendica:latest` with a  `mariadb:latest` database.

I have:

- enabled the addon through the admin page
- Filled addon.config.php with the LDAP info as suggested by the configuration

> return [
>         'ldapauth' => [
>                 'ldap_server' => '192.168.x.x',
>                 'ldap_binddn' => ''CN=ldapread,OU=ITUSERS,DC=mydomain,DC=tld',
>                 'ldap_bindpw' => 'verysecretpassword',
>                 'ldap_searchdn' => 'OU=SUSERS,DC=mydomain,DC=tld',
>                 'ldap_userattr' => 'sAMAccountName',
>                 'ldap_group' => ''CN=friends,OU=SERVICES,OU=GROUPS,DC=mydomain,DC=tld',
>                 'ldap_autocreateaccount' => true,
>                 'ldap_autocreateaccount_emailattribute' => 'mail',
>                 'ldap_autocreateaccount_nameattribute' => 'sAMAccountName',
>         ],
> ];

I also tried using the hostname for the AD.

- I checked the addon table in the database and the addon is installed = 1
- I made sure the php-ldap extension is present (in case the docker image had this missing)

After all those I still get this log messages:

```
2021-05-01T10:06:18Z index [ERROR]: Addon not configured or missing php-ldap extension {"extension_loaded":true,"server":""} - {"file":"ldapauth.php","line":97,"function":"ldapauth_authenticate","uid":"261d17","process_id":45}
2021-05-01T10:06:18Z index [WARNING]: authenticate: failed login attempt {"action":"login","username":"user@mydomain.ltd","ip":"192.168.42.20"} - {"file":"Authentication.php","line":271,"function":"withPassword","uid":"261d17","process_id":45}
```

I really hope I havved missed anything profound like Active directory not being supported by the plugin. I don't use secure conection with the AD. I also am not sure if I should use a hostname, an IP or an IP:PORT for `ldap_server` but I did try all f those.

Nevertheless I thing the log error shows that the addon doesn't get recognized as `Enabled` so it won't even try to connect.
Unfortunately I couldn't find any similar issues posted.

Thanks in advance for your time. Any nudge to the right direction will be much appreciated! :)

**Comment by very-ape** [comment]
Have you tried filling in 'config/ldapauth.config.php' instead? That error message means that it thinks the 'ldap_server' value isn't filled in, which likely means it's not reading the file you think it is.

**Comment by very-ape** [comment]
That error means that it thinks "ldap_server" is empty, which means it's probably not seeing your configuration. You've filled out "config/addon.config.php" in the root Friendica directory, right? And have you also made sure the file can be read by whatever user is running PHP? (E.g., www-data under Debian running Nginx.)

**Comment by very-ape** [comment]
Yep, the addon documentation is wrong. So, the code that loads the config file is in "Util/ConfigFileLoader.php". *That* wants the config file to be at "addon/ldapauth/config/ldapauth.config.php".

Put your config there and you should be golden.

Edit: Oh wait, there's already a file there that explicitly says *not* to put your config there. Bah. I think this addon is broken in a few ways. Imma fix it.

**Comment by very-ape** [comment]
The crux of the problem is that 'loadAddonConfig' doesn't work the way this addon seems to think it works. Maybe it did work that way once, but *now* it loads whatever configuration is in the addon's config directory *after* it loads the config/addon.config.php file, which means the defaults totally wipe out whatever the user has defined there. Basically this addon doesn't look like it should be working *for anyone* unless they go against the instructions in ldapauth.config.php and change its contents.

I'm going to make a pull request for a fix along with some enhancements, but in the meantime you can solve your own problem by either editing the contents of that file *or* commenting out [line 72 of the addon](https://github.com/friendica/friendica-addons/blob/develop/ldapauth/ldapauth.php#L72). If you do the latter, make sure your settings array has every key defined (even if it's just given an empty value), as you're commenting out the line that's supposed to load the defaults.

**Comment by xundeenergie** [comment]
I faced the same problem last year... 

https://github.com/friendica/friendica/issues/10379

**Comment by xundeenergie** [comment]
Just tested it again...

if the section in the addon.config.php is called "ldapauth" and variable has underscore "_" in it, the variables will not be recognized.

Change the section name to "ldapa" and remove the underscores from the variables (in config.addon.php and where the variables are read in addon/ldapauth/ldapauth.php, then the addon works... not as expected... but the configuration is read. 

Don't know, why the section must not be names ldapauth, and why underscores are not allowed in variable-names...

**Comment by MrPetovan** [comment]
I wish I could help, but I don't have an LDAP server I could test with.

**Comment by xundeenergie** [comment]
It ist not a ldap problem, it's a config-parsing problem!

**Comment by MrPetovan** [comment]
The config is correctly parsed in every other places that we know about, so there's something specific with this addon, and if I don't have a relevant test case, I'm not sure I can troubleshoot this issue.

**Comment by xundeenergie** [comment]
I just made a grep over the config-files in addons submenu.

The "auth" in the name of config-sections is only in the ldapauth-addon.

And this is one part of the parsing-problem. I wrote in my issue, how you can reproduce the problem. You do not need a ldap-Server to reproduce the issue!

If you insert a logger-line in function ldapauth_authenticate which prints only $ldap_server from this function, you can vary

Just try it yourself (as said, no ldap-server is needed!!)

Insert the Logger::error-Line in the addons function ldapauth_authenticate
```
  function ldapauth_authenticate($username, $password)
  {
          $ldap_server   = DI::config()->get('ldapauth', 'ldap_server');
         Logger::error('LDAP_SERVER', ['ldap_server' => $ldap_server]);
```

activate the addon and fill in something for "ldap_server"
Then try to login in friendica with some random username and random password (user does not have to exist. i took "öalskdjf" and "söfdlkjb")
you will then get in the friendica.log this:
```
2022-11-11T10:17:32Z index [ERROR]: LDAP_SERVER {"ldap_server":null} - {"file":"ldapauth.php","line":88,"function":"ldapauth_authenticate","uid":"4dfd36","process_id":1775297}
```
Then change the function to (remove the underscore in ldap_server to ldapserver)

```
  function ldapauth_authenticate($username, $password)
  {
         $ldap_server   = DI::config()->get('ldapauth', 'ldapserver');
         Logger::error('LDAP_SERVER', ['ldap_server' => $ldap_server]);
```

And change the config/addon.config.php also to

```
        'ldapauth' => [
            // This file is not read for ldapauth!!!!
            // use config in addon directly
            // ldap hostname server - required
            'ldapserver' => 'blafoobar',
```

Try to login again, you get:

```
2022-11-11T10:21:30Z index [ERROR]: LDAP_SERVER {"ldap_server":"blafoobar"} - {"file":"ldapauth.php","line":88,"function":"ldapauth_authenticate","uid":"e7f917","process_id":1776143}
```

It is the underscore "_" in the variable-name in addon.config.php and the parsing. It is nothing with the plugin itself. 

This works with all the variables. You can try it.

**Comment by MrPetovan** [comment]
Thank you for the elaboration, I'll look into it.

**Comment by MrPetovan** [comment]
Alright, I was able to find the problem. Any config value set in the `<Base Friendica folder>/config/ldapauth.config.php` file will be overwritten by the default values set in `<Base Friendica folder>/addon/ldapauth/config/ldapauth.config.php`.

@xundeenergie We need a way to change the order config files are loaded to fix this issue, but it isn't straightforward. In the meantime, you can delete your `<Base Friendica folder>/addon/ldapauth/config/ldapauth.config.php` file or fill it with the production configuration values to fix this issue for you.

@nupplaphil Currently the files in the `config/` folder are loaded before the `load_config` hooks are called which isn't ideal.

Here's the expected config file loading order:
1. Default core files (`static/defaults.config.php` and `static/settings.config.php`)
2. Default addon files (`addon/<addon name>/config/<addon name>.config.php`) through the `load_config` hook.
3. Custom config files (the non-sample config files in `config/`)
4. Environment-set config

Currently 3 happens before 2 which means custom addon config are overwritten by the default addon config. I'm a little confused about where I should make this change. I tried to move the `Hook::callAll('load_config', $this);` call before the `$this->loadCoreConfig($config);` call in `ConfigFileLoader::setupCache()` but now the addon hook function is never called because the first time the Cache is instantiated it is before loading the addons. 😖

Help 😰

**Comment by xundeenergie** [comment]
Ok!

This is, why i found out, the settings in the `addon/<addon name>/config/<addon name>.config.php` are taken and in config/addon.config.php not.

If use the default-config-file, it is not upgrade-save.

**Comment by MrPetovan** [comment]
If you are using the archive upgrade method, you're right (and you'll have to delete the `addon/ldapauth/config/ldapauth.config.php` again on upgrade). If you're using the git upgrade method, you're safe.
