### ISSUE TITLE
timeline can be scrolled sideways

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#10215]
Regression as I cannot recall previously running into this: timeline can be scrolled sideways resulting in timeline and left column overlapping and other oddities.

Behavior seems to be limited to Friendica Support Forum and not limited to one instance as it was reproduced on two instances both on version 2021.06-dev. The database version is 1414/1414, the post update version is 1400/1400.

Does not appear to affect all forums as it is not happening in developers forum.

### Steps to Reproduce

Visit Friendica Support Forum

Actual Result:

Sideways scrolling possible

Expected Result:

no sideways scrolling

### Screenshots

<img width="1344" alt="timeline can be scrolled sideways" src="https://user-images.githubusercontent.com/5708172/117289502-f7adde00-ae6c-11eb-88e3-0ece03118f9a.png">

**Comment by AlfredSK** [comment]
This happens when someone was sending a post or comment with a very long line w/o spaces (like a long URL) in a code block. I'm pretty sure when you scroll down you'll find such a line which is breaking out of the right border of the post.
I think it is probably theme specific on the sender's side. I wasn't able to (re-)produce such a loooong line w/o line breaks having been automatically inserted when displaying.
But I can confirm that I stumbled upon those theme breaking lines.

**Comment by AlfredSK** [comment]
Here is an example: A code block with long lines of dashes (SQL output)

![grafik](https://user-images.githubusercontent.com/3656054/117348360-665d5c80-aeaa-11eb-9188-0cd89237b656.png)

**Comment by foss-** [comment]
Closing. I don't think this is an issue any longer as posts seem to be line wrapped now. @AlfredSK can you confirm?
