### ISSUE TITLE
Receiving unwanted posts from Hubzilla followers

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#10262]
This is the second time in a couple days that I've received posts from Hubzilla addressed to me in Bcc. In both cases the account is following me but I am not following them. First time felt like a bug, the second time feels like spam.

I feel like we should check whether the target local user is following a remote account before delivering any post. Further than that, I suggest we drop the post entirely so that it can't show in the community pages either, since it looks like an easy way to spread spam: follow a single account on all the Friendica nodes you can think of, post something with all the accounts in Bcc, even if the target users don't receive it in their timeline, it still is recorded by the Friendica node and displayed in the global community page.

**Comment by annando** [comment]
So the header information is this "you received this message via BCC" thing?

It's complicated. for example when you and this person are commenting on the same discussion of a third person then you should receive the comments as well. And what are you doing when a person is adressing you via `@` because - for example - this person is currently in some discussion and knows that you are an expert in this field and requests your help?

The only thing that I could imagine was that we block incoming top level messages that are only sent via BCC to someone who isn't following that person. But when it is a comment in a thread or adresses via `to` or `cc` then I think we shouldn't block it.

**Comment by MrPetovan** [comment]
Both were top level posts, I don't mind replies on top level posts I meant to receive. Your solution would be acceptable to me.

**Comment by annando** [comment]
Okay, so remind me of doing this :-) However I would like to postpone it to the following release since there is still much work to do in the API. There are still a handful of (essential) endpoints that are waiting to be put into code. And possibly we could even repurpose some endpoints that we cannot use for their original purpose to use them for other stuff. For example we could use the voting feature for events. So this "attend", "maybe attend" and "not attend" could be transmitted as vote to the client.

**Comment by MrPetovan** [comment]
Got it, thank you for taking this on, I updated the issue assignment and milestone according to what you said.

**Comment by MrPetovan** [comment]
The first two unwanted posts were from Hubzilla followers, but today I received several with the same stated reason (mentioned in Bcc) from a Zot! profile I have absolutely no relationships with.
