### ISSUE TITLE
Friendica doesn't detect Persian language in posts

### ISSUE THREAD

**Issue by ahangarha** [friendica/friendica#10511]
- [x] I have searched open and closed issues for duplicates

### Bug Description

I have noticed the language option under `more...` button doesn't detect Persian language. My instance is venera.social.

### Steps to Reproduce

1.  Open a post written in Persian language. (maybe [this](https://venera.social/display/9b22c8a2-3e38fb2ab698e3ef-65951561))
2.  Click on `More...`
3.  Click on `Languages`

Actual Result:

It cannot detect Persian at all. It is not with low percentage but completely missing.

Expected Result:

To detect Persian language

### Screenshots

![image](https://user-images.githubusercontent.com/11241315/126042666-243d36d0-3a74-49da-9560-e4952407844d.png)

### Platform Info

Friendica Version: 2021.07

Friendica Source: -

PHP version: -

SQL version: -

**Comment by annando** [comment]
We are using this library for language detection: https://github.com/patrickschur/language-detection

It supports Persian, it seems. But to improve the quality of the language detection we limit the detection to the languages for that we have translations for. Before we did so, the detection rate was much lower since there are many languages that are really similar.

However, since Persian is really different from the ones that we do support, we could add it to the list. Or possibly we could make the list configurable.

**Comment by MrPetovan** [comment]
Let's add the language and move on, making it configurable is a completely different can of worms.
