### ISSUE TITLE
Extension of notification to include "like, dislike, share". 

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#10546]
### Is the feature request related to a problem? Please describe.

Notifications for "like", "dislike", "share" are not displayed under notifications. Currently only "mentions" and "comments" are signalled there.

A differentiated presentation of other notifications that are not "mentions" and "comments" can currently only be presented via the Mastodon API. 

Alternative UI like https://cuckoo.social presents all interactions with a post below the notifications

### Describe the feature you'd like

I'm always frustrated when I try to find out which post an interaction followed that triggered a "like, dislike, share".

### Describe alternatives you've considered

The existing notification should be extended so that every interaction with one of my posts can be tracked.
The signalling of interactions on "like, dislike, share" via the Post & Talk icon should be removed

### Additional context

**Comment by MrPetovan** [comment]
> I'm always frustrated when I try to find out which post an interaction followed that triggered a "like, dislike, share".

I'm not sure I understand the friction, what is "an interaction followed"?

The following is my general opinion about (dis-)like and share notifications: I don't like them, because they aren't actionable, I can't reply to them, they do not contribute anything to a conversation, so it is a waste of my attention. I like seeing the interactions when I stumble upon a post of mine after I've published it, but in this context it's a pleasant surprise, probably because I disabled dislikes on my account.

**Comment by annando** [comment]
We already do have the notification settings. It would be no problem to add some configuration if one wants to get notified about activities as well. I also don't like to receive a notification for each like.

Concerning the topic: We already do have the `notification` table that is the base of the notifications for the API. On the frontend we currently are using the notifications from the `notify` table. At the moment the `notifiy` table can display some notifications that `notification` can't. So the goal is to display the frontend notifications based upon the `notification` table.

**Comment by MrPetovan** [comment]
> I'm always frustrated when I try to find out which post an interaction followed that triggered a "like, dislike, share".

I'm not sure I understand the friction, what is "an interaction followed"?

And this is my general opinion about (dis-)like and share notifications: I don't like them, because they aren't actionable, I can't reply to them, they do not contribute anything to a conversation, so it is a waste of my attention. I like seeing the interactions when I stumble upon a post of mine after I've published it, but in this context it's a pleasant surprise, probably because I disabled dislikes on my account.

**Comment by tio-trom** [comment]
I am also not interested in seeing all of the interactions, but I see why some may want and if this could be activate/deactivate in settings then could be a good idea. 

Speaking of that, it seems that whenever someone likes/shares any of my posts I get a notification on the home icon, but that's all it is. Clicking it does nothing just opens my homepage. I suggest removing that maybe!?

**Comment by MrPetovan** [comment]
YES.

**Comment by annando** [comment]
@loma-one in the current RC this is solved. Can you have a look at it?

**Comment by tobiasd** [comment]
The subject lines of the notification emails are wrong. E.g. for a like I'm getting a mail with the following header -> Comment by Marco R.

```
Subject: Kommentar von Marco R. 
```

In the mail itself, the context is correctly written out

```
Marco R. mag deinen Beitrag.
```

**Comment by foss-** [comment]
As this bug is closed the remaining email notification problem should be a new followup bug to ensure the info is not lost?
