### ISSUE TITLE
Change Contact avatar URL pattern to remove auto-increment parameter

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#10726]
Offshoot from #10721

See https://github.com/friendica/friendica/pull/10721#discussion_r711422798
> We shouldn't publish URLs using any of our auto-incremented IDs as it makes them easily enumerable. In this case, we could be using the nickname since it's unique and already formatted for URLs.

This Issue is blocked until the `contact` table only holds the public contacts and we can assign them GUIDs that will be used for avatars.

**Comment by MrPetovan** [comment]
Closed by https://github.com/friendica/friendica/pull/10823

**Comment by AlfredSK** [comment]
I guess the change described here is responsible for a report from a user of my node. The avatar (300px and 80px) is showing the wrong image. Instead of the uploaded and stored image the old 'catavatar' is shown as profile photo and thumbnail in the posts and comments. I will open a new issue about that.

**Comment by MrPetovan** [comment]
Thank you, please add as much detail as possible about where the avatar is showing.
