### ISSUE TITLE
Logs cannot be read.

### ISSUE THREAD

**Issue by Pavvlik** [friendica/friendica#10777]
![2021-09](https://user-images.githubusercontent.com/18744163/135237847-8e1642f3-0691-49f8-9ded-b7900a608fbc.png)

**Comment by MrPetovan** [comment]
Thank you for your report, I have a couple of questions:
- Can you confirm you have activated logging in the first place?
- The search box isn't empty (it shows `/admin/logs/view` at the moment), can you click on "Clear" to start over?
- What version of Friendica are you currently running?

**Comment by Pavvlik** [comment]
My logs have been activated for 2 years. Fail2ban works so the logs are ok. I have the latest version of friendica. - Friendica 'Siberian Iris' 2021.09 - 1434. Yes, I can click on these buttons but it won't change anything.

**Comment by fabrixxm** [comment]
log filter uses "q=" query string parameter for search box.
firendica used to use "q=" param rewirtting url to index.php, which has been changed a while ago to "pagename=".
please chech your .htaccess, or equivalent server config, that is not using "q=" instead of "pagename="
(that's should explain the page path in search box (and the empties of the logs view, it's searching for "/admin/logs/view" in logs)

**Comment by MrPetovan** [comment]
Oooh, sneaky.

**Comment by Pavvlik** [comment]
> log filter uses "q=" query string parameter for search box. firendica used to use "q=" param rewirtting url to index.php, which has been changed a while ago to "pagename=". please chech your .htaccess, or equivalent server config, that is not using "q=" instead of "pagename=" (that's should explain the page path in search box (and the empties of the logs view, it's searching for "/admin/logs/view" in logs)

Exactly as you write in my nginx configuration it was "q ="
Thank you very much.

**Comment by MrPetovan** [comment]
Closing here since it seems to be fixed.
