### ISSUE TITLE
Can't follow Zap account, ActivityPub not detected

### ISSUE THREAD

**Issue by asherpen** [friendica/friendica#10947]
- [X ] I have searched open and closed issues for duplicates

### Bug Description

Can't follow Zap contact,

### Steps to Reproduce

1.  follow a zap account, eg. https://z.fedipen.xyz/channel/asherpen

Actual Result:

Failed. "The network type couldn't be detected. Contact can't be added."

Expected Result:

Succeeded in following a Zap account

### Screenshots

![9xd4MI43rS](https://user-images.githubusercontent.com/8214569/139779531-9ebf2662-c4a7-43cc-a1fa-c2c6364642e0.jpg)

### Platform Info

Friendica Version: 2021.09

Friendica Source: I think it's from git

PHP version: 7.2.24-0ubuntu0.18.04.9

SQL version: I'm not quite sure

Probe Diagnostic:

> Array
(
    [name] => https://z.fedipen.xyz/channel/asherpen
    [nick] => https://z.fedipen.xyz/channel/asherpen
    [guid] => 
    [url] => https://z.fedipen.xyz/channel/asherpen
    [addr] => 
    [alias] => 
    [photo] => https://letus.inspiredlife.fun/images/person-300.jpg
    [header] => 
    [account-type] => 
    [community] => 
    [keywords] => 
    [location] => 
    [about] => 
    [xmpp] => 
    [matrix] => 
    [hide] => 
    [batch] => 
    [notify] => 
    [poll] => 
    [request] => 
    [confirm] => 
    [subscribe] => https://z.fedipen.xyz/follow?url={uri}
    [poco] => 
    [following] => 
    [followers] => 
    [inbox] => 
    [outbox] => 
    [sharedinbox] => 
    [priority] => 0
    [network] => unkn
    [pubkey] => 
    [manually-approve] => 
    [baseurl] => https://z.fedipen.xyz
    [gsid] => 150186
)

**Comment by tobiasd** [comment]
As the zap protocol is currently not supported by Friendica, I've removed the "bug" label and re-filed this ticket as feature request.

**Comment by asherpen** [comment]
But it can be added some days ago as an ActivityPub account...

**Comment by MrPetovan** [comment]
Not sure if it's relevant here, but if it's an account on a Hubzilla server, ActivityPub needs to be activated on a per-account basis. Until then it will not be correctly probed by Friendica.

**Comment by asherpen** [comment]
Zap has been able to supports ActivityPub since last year (not by addon). and this account can be followed on Mastodon/Pleroma/Misskey.
I think it's just that Friendica can't probe a Zap account as an ActivityPub account now. 
Maybe this is due to Zap's recently update, I'm sure Friendica can follow Zap some day in last October...

**Comment by MrPetovan** [comment]
Thank you for the extra information!

**Comment by tobiasd** [comment]
Aha, so it is a bug then

**Comment by annando** [comment]
I saw this comment and I hope that the automatic translation is okay: https://chokecherry.cc/notes/296316351503400960

I understood that Zap seems to have problems with us sending two values for the accept header. On my system I just flipped the two values and detection works. But I think that this should be fixed there.

**Comment by redmatrix** [comment]
I haven't dug into Guzzle to see if it is actually sending multiple 'Accept' headers. If so, it's quite possible this is not handled elegantly by PHP. I just assumed that multiple fields would be folded into a single $_SERVER['HTTP_ACCEPT'] in the CGI layer (on the receiving end) since having multiple array keys called $_SERVER['HTTP_ACCEPT'] would not be supported by the PHP language. Later values would over-write earlier ones. This isn't something I can fix in the application layer and would be dependent on the precise server stack involved.  Industry best practice is to avoid doing this, and 'Accept:' supports multiple values separated by commas. In any event, I'll dig further into why it isn't seeing application/activity+json (which Zap also supports); but if the reason is because Friendica is sending more than one Accept header per HTTP request, it's doubtful I can do anything to fix it, and it might be worthwhile re-evaluating this design decision - as it could be problematic for a number of projects.

Still, that doesn't change this:

https://www.w3.org/TR/activitypub/

3.2 Retrieving objects

The HTTP GET method may be dereferenced against an object's id property to retrieve the activity. Servers MAY use HTTP content negotiation as defined in [RFC7231] to select the type of data to return in response to a request, but MUST present the ActivityStreams object representation in response to application/ld+json; profile="https://www.w3.org/ns/activitystreams",
and SHOULD also present the ActivityStreams representation in response to application/activity+json as well.
**The client MUST specify an Accept header with the
application/ld+json; profile="https://www.w3.org/ns/activitystreams" media type in order to retrieve the activity.**

Servers MAY implement other behavior for requests which do not comply with the above requirement.
(For example, servers may implement additional legacy protocols, or may use the same URI for both
HTML and ActivityStreams representations of a resource). 


Edit: therefore if multiple Accept headers are being transmitted, it wouldn't necessarily be a problem as long as the  very last one is precisely

    Accept: application/ld+json; profile="https://www.w3.org/ns/activitystreams"

**Comment by annando** [comment]
I haven't checked if we are sending multiple `Accept` headers or if the two values are put in the same line. I just checked with a remote system, there it seemed to be added to a single field. But as you pointed out, possibly PHP is adding these values in a single field.

I just had a look at https://www.w3.org/TR/activitystreams-core/ and found these lines:
> Because Activity Streams 2.0 can be considered a restricted profile of JSON-LD, Implementations SHOULD consider the `application/ld+json; profile="https://www.w3.org/ns/activitystreams"` media type as being equivalent to `application/activity+json`. 

It seems as if the specification is unclear or at least misleading.

**Comment by redmatrix** [comment]
> It seems as if the specification is unclear or at least misleading.

Agreed. application/activity+json was a recent change to the activitystreams protocol at just about the same time that the activitypub spec was being frozen and the change didn't make it back to the ActivityPub spec. 

Zap supports both application/activity+json and application/ld+json; profile="https://www.w3.org/ns/activitystreams" but we do check for the profile option since it is a MUST according to the ActivityPub spec. We also accept it with http in the profile string as well as https. And I've tested with Friendica in the past, so it's possible my LAMP stack is also folding header lines, but it's entirely possible @asherpen 's system isn't (folding header lines) and is therefore not seeing application/activity+json if it was the first one in the list (which it is in the Friendica code from my last pull several hours ago).

If you send Accept as a comma separated string it should just work, even without the profile, as we should then pick up the activity+json version no matter the server stack involved. But technically the profile option is required, so probably best to provide it also. 

Slightly off topic but related:

I also noticed somewhere in the probe code that any url with '/channel/' in it is assumed to be a Hubzilla node and the protocol is automatically set to Diaspora. This could cause problems as there are now at least a half dozen platforms using that particular string and only one has ever worked with Diaspora. I don't know what the impact of this is, but if it isn't a bug today, it's a bug waiting to be discovered. You can also throw out all the old zot protocol discovery stuff (also somewhere in the probe code). That method hasn't worked for years.

**Comment by annando** [comment]
This "channel" stuff (when I found the correct place) is just used for incoming posts via the Diaspora protocol, I haven't found it in the "probe" related code.

Concerning the header stuff i'm pinging @nupplaphil here, since the behaviour had been changed with his commit https://github.com/friendica/friendica/commit/2356221abaa5d9ea2eb86174e91b0d43913f413c. I hope that he can tell how the system behaves here - and if we should change it back to transmitting a single comma separated string.

**Comment by redmatrix** [comment]
I tested my own code to verify it could properly recognise application/activity+json and this was successful. According to established web specs, multiple Accepts are allowed as long as the field in question allows comma-separated values. CGI implementations are supposed to fold them.  However there is an open issue specifically w/r/t nginx and php-fpm where this has been broken for at least 2-3 years. I thought this would be the definitive answer, but according to the bug, only the first value is kept and later values ignored.  So I cannot explain the current behaviour completely; but this matches my experience with multiple headers. They can't always be relied on and it's probably best to avoid them.  

https://trac.nginx.org/nginx/ticket/1316

I've added support in zap for application/ld+json with no profile; which should make federation work between these platforms, but I don't consider it to be a correct fix. It's a work around. It will also take a few days or weeks before this gets pushed to the release branch.

**Comment by annando** [comment]
Thanks for digging into this!

**Comment by dranii** [comment]
"I've added support in **zap** for application/ld+json with no profile;"

@redmatrix  That's great. Can the issues section at codeberg dot org for zot/**zap** be brought back again or has it moved somewhere else? Or should we use Roadhouse over Zap in scenarios such as this https://github.com/friendica/friendica/issues/10947 I mean the one that can be consistently used with backward and forward compatibility with such Activitypub issues persistently over the years to come.

**Comment by redmatrix** [comment]
This is far off-topic for the friendica issues list, so I'll just say that we use the fediverse for all project communications. Issues should be raised in the Zap group (currently zap@z.macgirvin.com).
