### ISSUE TITLE
Some Log Stuff

### ISSUE THREAD

**Issue by BrokenGabe** [friendica/friendica#10995]
Not sure if these are anything important, but they are showing up in my log file for friendica.
```
2021-11-06T14:37:59Z index [DEBUG]: DELETE FROM `session`  WHERE (`expire` < 1636209479) {"callstack":"Database::gc, session_start, Native::start, Dice::Dice\\{closure}, Dice::create, Dice::Dice\\{closure}"} - {"file":"Database.php","line":1242,"function":"delete","uid":"e8ba9f","process_id":30804}
2021-11-06T14:37:59Z index [INFO]: No HTTP_SIGNATURE header [] - {"file":"HTTPSignature.php","line":479,"function":"getSigner","uid":"e8ba9f","process_id":30804}
```

Version: Friendica 'Siberian Iris' 2021.09 - 1434
Mysql: Server version: 5.7.36-0ubuntu0.18.04.1
PHP:
PHP 7.2.24-0ubuntu0.18.04.10 (cli) (built: Oct 25 2021 17:47:59) ( NTS )
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.24-0ubuntu0.18.04.10, Copyright (c) 1999-2018, by Zend Technologies

**Comment by MrPetovan** [comment]
First is about the periodic session garbage collection routine, which deletes expired session data. The "DEBUG" label shows it's only informative for developers.

The second is about incoming HTTP requests missing a potentially expected HTTP_SIGNATURE header. The "INFO" label shows it's purely informative, we currently don't reject requests without HTTP signatures because not all remote platforms have implemented it. We do reject HTTP requests with a provided signature that doesn't check out, though.

My advice for you would be to reduce the log level to Notice or Warning so that your log will show messages that are more relevant to you.

**Comment by BrokenGabe** [comment]
> First is about the periodic session garbage collection routine, which deletes expired session data. The "DEBUG" label shows it's only informative for developers.
> 
> The second is about incoming HTTP requests missing a potentially expected HTTP_SIGNATURE header. The "INFO" label shows it's purely informative, we currently don't reject requests without HTTP signatures because not all remote platforms have implemented it. We do reject HTTP requests with a provided signature that doesn't check out, though.
> 
> My advice for you would be to reduce the log level to Notice or Warning so that your log will show messages that are more relevant to you.

Thank you for your response, wasn't sure if either one were informational for devs, I did do a search and didn't see anything related to them.

**Comment by MrPetovan** [comment]
The INFO and DEBUG levels are meant to be used temporarily by developers during their work, but the signal/noise ratio is too low for regular Friendica administrators to meaningfully enable them on a permanent basis.
