### ISSUE TITLE
add ability to sync undone reshares to connected twitter account

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#11022]
**Currently**

When unsharing a post while having setup the twitter connector, the unshare is not forwarded to twitter.

**Expected**

After sharing a post and then unsharing on friendica, all changes should be forwarded to twitter, no matter how often a user decides to change their mind.

This also goes for like / unlike and star / unstar. Not sure if those are affected as well.

**Additional Context**

Technical background (thanks Hypolite): Problem is that `notifier_normal` hook is not called when share is undone.

Example to illustrate severity: User sees some offensive content in their timeline and while fiddling around trying to find out why such a post even made it to their timeline (e.g. Mastodon for iOS does not show who reshared a post). During that they accidentally tap on share. Notice the mistake and unshare. Both on friendica. After a few weeks they discover the offensive post is happily and unexpectedly sitting in their twitter profile as a post they reshared (making it look like they promoted problematic content).

**Comment by MrPetovan** [comment]
I went ahead and enabled deletion for posts and comments, with one exception: Comments posted on Twitter and imported in Friendica do not trigger any Notifier task, possibly because they are private to the user and don't require any remote deletion notifications sent. Comments posted on Friendica and mirrored on Twitter trigger the Notifier task and the Twitter counter-part will be deleted accordingly.
