### ISSUE TITLE
reshared comment only visible on mastodon

### ISSUE THREAD

**Issue by haheute** [friendica/friendica#11094]
- [X] I have searched open and closed issues for duplicates

### Bug Description

I have recently reshared a comment and nothing seemed to have happened. I could not find it in my stream or in the network stream or on diaspora. Today I found it appeared on mastodon ( https://machteburch.social/web/statuses/107417350321550475 ).

### Steps to Reproduce

1. reshare a comment (from a friendica post) (just "share", not "quote reshare")
2. look if it appears in /network or /profile.. or somewhere else (i.e. on diaspora or mastodon)

Actual Result:

I could not find the reshared comment in my stream, that irritated me.

Expected Result:

I don't know how exactly it should appear, as a new post or just marked as "user shared this", but I expected the comment to show up on the network stream and profile stream.

### Platform Info

"Diese Friendica-Instanz verwendet die Version 2021.12-rc, sie ist unter der folgenden Adresse im Web zu finden https://libranet.de. Die Datenbankversion ist 1445/1445 und die Post-Update-Version 1427/1427."

**Comment by MrPetovan** [comment]
Thank you for the report! There are a couple things to unpack about this issue. 

### Reshare mechanism

Resharing works differently between Mastodon and Disapora, so when you click the "Reshare" button, it only reshares to the same network. If you want to reshare to all the networks, you have to create a new post using "Quote Share". The "Reshare" button is an implicit native reshare that will only be distributed to your contacts using the same protocol as was used to distribute the reshared content.

### Comment display

Friendica has a conversation-based display like Facebook rather than single object-based like Twitter and Mastodon. This means comments will rarely be displayed on their own, only in search results so far. If you go back to the original conversation in Friendica, it should indicate that you reshared that particular comment in the comment display inside the conversation.

Again, the solution to show it independently of the conversation is to create a Quote Share post from the comment. This will pull a copy of it in a new post that will be distributed to Mastodon and Disapora.

**Comment by haheute** [comment]
okay .. thanks for the explanation

**Comment by SpcCw** [comment]
@haheute It was confusing for me as well so I'll elaborate a bit how it works in practice.

If you reshare a comment and the conversation is already loaded for you or someone then nothing happens (except the comment is displayed as reshared). It doesn't pop up on its own.

However if the conversation was not loaded for someone who is your subscriber then resharing the comment will either bring this previously unseen comment to their feed or entire conversation - depending on their platform. So resharing comments still makes sense but it is mostly useful to reshare either old comments or comments made by other people - this makes the conversation seen by your contacts who are not following the poster.
