### ISSUE TITLE
Database Problem - Account cannot be created

### ISSUE THREAD

**Issue by ZwoVierZwo** [friendica/friendica#11121]
After deleting an Account an my own Instance - i cannot recreate this account.
There is always the message, that the account is already there but the account isn't in the account list.

maybe a bug in the delete function!

**Comment by tobiasd** [comment]
This is not a bug. You cannot re-use a once used user nickname. If the user did never interact with another account, you can remove the block from the `userd` table.

**Comment by ZwoVierZwo** [comment]
Why can't I re-use the account? There is no logical reason for ...

**Comment by MrPetovan** [comment]
How about you ask if there's any logical reason for this behavior first?

**Comment by annando** [comment]
This behaviour is intended. Besides all the possible impersonating problems there is also the fact that at least Diaspora by intention does store an account key only once. Means: When an account name would be reused, then the there will be no working communication with - at least - Diaspora. If you consider this to be a bug, then please open an issue there.

**Comment by ZwoVierZwo** [comment]
Ok this is a good description but can this not be changed?
This would be the same if a cellular number cannot be used twice.
As I understand this main problem is a problem with Diaspora?

Ok MrPetovan this is my fault but I didn't thought that this could be real and this is really a bug.

Thank you for your patience 🖖🏻

**Comment by annando** [comment]
If we would want to mimic the cell phone behaviour, then we had to introduce a grace period of a few months in which an account name can't be used again.

**Comment by MrPetovan** [comment]
> Ok this is a good description but can this not be changed?

It isn't just a Friendica problem. Your profile details are sent to remote servers that keep a local copy of it, including your public key which was randomly generated when you created your account. Since recreating an account, even with the same username, would create a different cryptographic key pair, remote servers running various software may or may not accept it based on the previous record they had of the account with the same username.

This would create communication issues that would be hard to debug since your account would work fine with remote servers that did not know about your profile before the recreation, or with servers that do not enforce public key authentication, but not with specific servers that both had a previous record of your profile and enforce authentication.

The easiest way to avoid these issues is having a Friendica policy of not reusing username from deleted user accounts.

**Comment by ZwoVierZwo** [comment]
@annando sure only with an grace period (the same as with celluar phone numbers) - the numbers are also locked for some time.

@MrPetovan 
Urgh - I understood the root problem (the design problem) with the cached keys.
This has to be a general problem with an global solution in future.

But is it so that the keys will be cached in other systems until the end of the internet, or will the key be deleted some time.
On the other side - if there will be a problem with an big instance (maybe database problem) and the data has gone to nirvana. 
In that case this instance can never come back with his name? Is this a good solution? In my opinion this isn't

Are there no think about how this can be handled
Maybe an auto refresh after x months or maybe if the account wasn't seen for x month he will get a check key flag. Or the key will be cleaned from the cache with the account (after a grace period) and if the account will be there again, it will be pushed into the cache (with his actual key)

Hasn't really nobody thought about an solution?

**Comment by MrPetovan** [comment]
So, it isn't as much a technical problem than a conceptual + social one. When you register a given user name on a given domain (called handle), the combination is unique and is conceptually associated with you as a person. You can have several of these accounts on several servers, but these handles will only ever describe you.

This means that many systems will ensure that nobody else can publish under the same handle. It can be a security/safety feature for your followers who don't expect anyone else to impersonate you, and this is technically insured with cryptographic key pairs authentication. Nobody without your own private key and your server's private key can craft a message that will look like it came from you behind the handle.

Both the conceptual and the security concerns implies that systems enforcing authentication will never, ever update the public key of a remote account because they simply cannot distinguish between "a Friendica user deleted their account and recreated it under the same user name" and "someone else is trying to impersonate their account" when a remote profile provides a different public key than their existing record.

This also means that if any system goes down without a database backup, all the handles registered on that domain should be considered lost forever, and the easiest way to restart a server is to use a different domain name that will allow a fresh start with a set of entirely new handles.

**Comment by ZwoVierZwo** [comment]
Ok I understood that this is not possible or not wanted. Not from the creators and operators of Friendica, so do not misunderstand.

But how about a Friendica internal solution?
For example, that you can save your ID (and the key) for your own account with password as a file and if necessary import this again.

Or you generally don't delete any identifiers, so that you would have the possibility to reactivate them, or what would be also possible would be to redirect them (and use them as alias). 
Then one would have implemented two things at once. Deactivate/activate identifiers and redirect identifiers.
The system will no longer respond to the deactivated identifiers, unless they are redirected or activated. (The redirection of course only related to one instance).

**Comment by MrPetovan** [comment]
A few things:
- We want to honor a user's wish to delete their account and all their associated data. This means not keeping any data pertaining to their account beyond the user name to prevent anyone else to register again with the same user name.
- The obvious solution to keep one's account is therefore not to delete it. I believe we already warn users that this operation is irreversible and we mean it.
- There still is a grace period after users chose to delete their account and before the data is effectively purged during which an account can be restored in case of a mistake.
