### ISSUE TITLE
[frio] Imported Twitter posts don't show they are private, still won't load for other people than me

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#11152]
I'm used to private posts having the little lock next to the author's display name, but it doesn't seem to appear (anymore?) for Twitter posts imported from my timeline.

So I checked if these posts had mistakenly become public, but it isn't the case, they aren't accessible by anyone but myself when I'm logged in.

Is this intended? I'm using the value of the template variable `{{$item.lock}}` to verify the scope of a post in the template and currently it is inaccurate on timeline-imported Twitter posts.

**Comment by annando** [comment]
Currently this behaviour is intended. Out of my head I think only posts from protected accounts are set to private.

**Comment by MrPetovan** [comment]
Ok, how can I know if a post is public from the template? Do I have to add another template variable? What is the item field I should base it on?

**Comment by annando** [comment]
You can have a look at the content of the `global` field. This is normally set with posts from federated networks but not set with posts from connectors.

**Comment by MrPetovan** [comment]
Thanks.

**Comment by annando** [comment]
BTW: The field is mostly used for the search mechanism. We have to avoid returning connector posts when the searching person hasn't connected to that network. It would be some ugly handling if you would see the post but couldn't interact - or even worse: You interact but nothing happens because you aren't connected to that network. So its easier to not return these posts at all.
