### ISSUE TITLE
Return Pleroma-like version in /api/v1/instance

### ISSUE THREAD

**Issue by mkljczk** [friendica/friendica#11264]
### Describe the feature you'd like

In `/api/v1/instance`, Pleroma [exposes software version in a format](https://docs.pleroma.social/backend/development/API/differences_in_mastoapi_responses/) consisting of Mastodon version it is compliant with, the name of software and its version, like `2.7.2 (compatible; Pleroma 2.4.51-477-g2744c4c5-develop`. Currently, it's not possible to identify Friendica just using the version field. This format is also used by other Fediverse platforms implementing Mastodon API, like [Mitra](https://codeberg.org/silverpill/mitra/src/branch/main/src/mastodon_api/instance/types.rs#L22). This might be helpful for clients supporting multiple backends.

It might also be helpful to provide a semver-like version software, I think simply using something like 2022.5.0 would be enough

**Comment by MrPetovan** [comment]
Thank you for the suggestion, and now I'm wondering what virtual Mastodon version we are compliant with.

**Comment by annando** [comment]
I don't really like this "compatible" stuff. By now I haven't had any issues with systems that had complained.

**Comment by MrPetovan** [comment]
I would like to add that semver doesn't make sense for Friendica, this is why we abandoned it a couple years ago. `2022.05` is the current Friendica version string, and it cannot match any semver meaning because we don't have major/minor versions, we are on a rolling release schedule and we strive to provide upgrade paths from older versions to the newer ones.

**Comment by mkljczk** [comment]
I didn’t ask to switch versioning system to actual semantic versioning. But presenting it (just in `/api/v1/instance`) in a way that simply looks like semver would help if client software uses something like [npm `semver` package](https://www.npmjs.com/package/semver) to detect feature support

**Comment by MrPetovan** [comment]
I got you, but I still don't think it's a good idea. Release tags (like `2021.09` or `2022.02`) are enough to detect feature support with exact matches.

**Comment by nikclayton** [comment]
Hello, Pachli (https://pachli.app) developer here, and I'd like to request that you reconsider this, specifically the suggestion by @mkljczk :

> I didn’t ask to switch versioning system to actual semantic versioning. But presenting it (just in /api/v1/instance) in a way that simply looks like semver would help if client software uses something like [npm semver package](https://www.npmjs.com/package/semver) to detect feature support

It would make my life that little bit easier if server software exported a semver-compatible version string so I don't have to hand-roll parsers for every server type that Pachli supports.

As far as I can tell it's sufficient to change your version string to include a third dotted component; given your versioning scheme that could be `0` before the formal release, then you could set it to the day of the release as part of the release process and be compatible with semver. Or simply start at 0 and increment by 1 with every release that happens in the same month.

As a bonus this makes it easier if you ever have to roll out an emergency release in the same month as you do a regular release (e.g., when you discover that one of your dependencies has a critical vulnerability -- it's not a question of if that will happen, but when).

Right now it's not clear how you would do that with your yyyy.mm release numbering, yyyy.mm.dd allows that, and is compatible with semver.

https://github.com/pachli/pachli-android/issues/372 is the issue I'm having to work around because of the current Friendica behaviour.

**Comment by annando** [comment]
Can you give an example how we should provide that data in the future?

As you know, currently that string looks like this:
`2.8.0 (compatible; Friendica 2024.03-dev)`

The version `2024.03-dev` is the current development version. Somewhere around March we will have a `2024.03-rc` for the release candidate version, followed by `2024.03` when the release is done. How can we press that into a scheme that both fits into the `semver` scheme and also provides the same information?

**Comment by foss-** [comment]
Thanks for providing feedback @nikclayton 👍
Was not aware of the secret friendica version scheme of `2.8.0`. While I saw it in mastodon clients, it is not mentioned in release notes. Find that odd, especially considering the fact that a ton of unrelated info makes it into the release notes each time (e.g. `what is friendica`).

Not entirely sure about the expected version scheme but think it would be preferable for friendica to make a decision which scheme to use. Either go with major.minor.point (2.8.0) OR go with yyyy.mm.dd with suffix `-dev`, `-rc` and optinoal additional info like post update version `-1544`.

Personally I'd prefer the latter as that is, what users and admins are familiar with due to the way releases were communicated in release notes and blog in the past.

**Comment by tobiasd** [comment]
> Right now it's not clear how you would do that with your yyyy.mm release numbering

In the past we hat 2020.07 and 2020.07-1 and in 14 years of project history it happened twice so far that we had to add the release number with this dash notation. We can just append .00 to the version number from now on to make your life easier. I don't think it has any impact with our internal procedures.

**Comment by nikclayton** [comment]
I wasn't quite specific enough in my first comment, sorry about that. Semver does not like leading `0`s in the components of a version number, so e.g., `2023.05` would need to become `2023.5.0` to be compatible with semver.

@annando Pachli used to pull the version number out of the `compatible` block from the server's instance info API endpoint (as discussed earlier in this issue), but I've changed it to chase down the `/.well-known/nodeinfo` endpoints and pull it out of the `software.name` and `software.version` keys exposed there.

That seems to me to the path clients should go down to accurately determine the type of server they're talking to, as `/.well-known/nodeinfo` is properly versioned and documented, Continuing to stuff data in to response returned from the `instance` endpoint is how we get to browser useragents like `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36`, and I hope we all agree that's a bad idea...

**Comment by MrPetovan** [comment]
Thank you for the write-up! Friendica doesn't use semantic versioning because we don't have any use for it. We only maintain the latest software version that we release on an almost quarterly schedule, hence the version string based on a year and month. It is meant to be compared as a string, which we would not be able to do anymore if we drop the leading zeros.

That said, Pachli is a good example why we have to expose a composite version string in the `instance` data, as we are implementing the Mastodon API at a more or less specific version. If Pachli or any other Mastodon-compatible client is checking the version number for capabilities, then Friendica needs to provide the Mastodon-relevant version, whatever the actual Friendica version is.
