### ISSUE TITLE
Language-Filter for relais-settings

### ISSUE THREAD

**Issue by xundeenergie** [friendica/friendica#11365]
### Is the feature request related to a problem? Please describe.

In my global timeline i have a lot of cyrillic and chinese postings... i'm the only user on my instance and i'm not able to read this languages... 

### Describe the feature you'd like

In Relais-Setting a Filter for Languages (international language-codes). Whitelist and/or Blacklisting

**Comment by MrPetovan** [comment]
I'm not sure relays expose their primary language or any language at all?

**Comment by annando** [comment]
The idea is to enable language filtering for incoming relay posts. Means you could define (for example) to not accept incoming posts from relay servers that mostly contain Japanese, since no one on your server can read this. Or you could define that you only accept relay posts where the given languages are detected.

**Comment by annando** [comment]
We have got a setting to deny unknown languages and to add languages that should be denied completely: https://github.com/friendica/friendica/blob/develop/static/defaults.config.php#L565C6-L571C45

My settings are:
```
                'relay_deny_languages' => ['ja', 'ru', 'fa', 'ar'],
                'relay_deny_undetected_language' => true,
```
