### ISSUE TITLE
/poco?

### ISSUE THREAD

**Issue by ne20002** [friendica/friendica#11399]
Hi
I find many requests to /poco or /poco?fields=urls&count=1000 in my logs. All are answered with a 403 response from my Friendica 2022.03.

I did a bit searching for it and I believe that this is an old interface that already should be removed from Frinedica. But I don't get requests from older versions only but also from a number of 'User-Agents: Friendica 'Siberian Iris' 2022.05-dev-1452;'

I also get a few with a user agent 'Mozilla/4.0 (compatible; MSIE 5.01; Windows NT 5.0)' and wonder what this is.

**Comment by ne20002** [comment]
I have a nginx with ModSecurity and OWASP core rules set running in front of my Friendica instance and the /poco requests are the only logged after I disabled one for an exception in the home page and the checks for known user-agents.

It's a sign of quality. :smiley:

**Comment by annando** [comment]
We are using the `poco` endpoint to determine the server type of a remote system and to discover new contacts.

**Comment by ne20002** [comment]
Hmmm.
But why is my Friendica then allways returning 403?

**Comment by annando** [comment]
This is another problem :-) I have to check that. What is the name of your instance?

**Comment by ne20002** [comment]
fm2.0x42.ch

**Comment by annando** [comment]
I just had a look at why the system can return `403` at the `/poco` endpoint. it can be one of these 3 reasons:
1. You activated the "block_public" setting ("Check to block public access to all otherwise public personal pages on this site unless you are currently logged in." in the "site" settings)
2. You activated the "block_local_dir" setting ("Deny public access to the local user directory." in the config file)
3. You only have got users that don't want to publish their profile

**Comment by ne20002** [comment]
Ok, thank you.
That explains the issue.
