### ISSUE TITLE
Sorts the stream chronologically according to the date the posts were created

### ISSUE THREAD

**Issue by Ravenbird** [friendica/friendica#11425]
### Is the feature request related to a problem? Please describe.

When I look at my Friendica streams, there is quite a bit of chaos there from a chronological sorting point of view, as the posts are not sorted chronologically according to when they were created. So it can happen that at the very top, where the current posts are, you suddenly have posts that are years old. Here is a suitable screenshot: https://pic.metaversum.wtf/T6FYKNL8/DRBo7Rdt.jpg

### Describe the feature you'd like

A possible solution would be another stream in which the contributions are sorted chronologically according to the time of their creation. And that the user can choose which of the streams is displayed first.

**Comment by MrPetovan** [comment]
We used to order by creation date, but it was deemed unsuitable, because in the case of direct reshares (with ActivityPub), there's no newly created post which date we could use to show you the reshared post in your timeline at the time it was reshared (unlike with Diaspora). We are only receiving the original post, which means that it would get buried in your timeline at whatever time it was created and you would miss on it.

Instead, we sort by the order the posts were received by your local node. This means you will not miss on an older post that would have received recently. Still, we need to show the post creation date as part of the post context, but it doesn't make much sense to sort your timeline on it.

This way, your timeline order is consistent, items don't get randomly inserted between existing items a few pages down.

**Comment by annando** [comment]
We could implement a third way of sorting. Downside is that this will require additional indexes.

**Comment by MrPetovan** [comment]
No, I don't believe it matches any actual use case. Even when a post is older, there always a good reason why it shows in the timeline alongside newly created posts. Either it was recently reshared by a followed account, or recently liked by a followed accounts, or recently commented on by a followed account. In all cases this "refresh" is intended through follows.

**Comment by annando** [comment]
I know at least two users who want to have exactly this behaviour. Interesting side note: Diaspora behaves exactly this way. It is a behaviour that I don't prefer. But it seems as if there is some demand.

**Comment by MrPetovan** [comment]
I don't understand their motivation beyond a simple ordering fetish that I kind of share, and the problem is that as an available option it would mislead and/or confuse all the others users unaware of the caveats of this particular ordering. I am strongly opposed to this ordering as it only makes sense in theory, but in practice it's unwieldy, which doesn't justify its cost in work + indices.

**Comment by Ravenbird** [comment]
The reason is that many prefer a chronological order according to the date of creation. Posts that were created a long time ago or even years ago are not so relevant that you want them at the top of the stream. One key difference with Diaspora is that in Diaspora, when a post is forwarded, a new post is created, which then has a new date anyway. Say, does not break with the chronological order. I had a pretty heated discussion years ago with Dennis, who was still involved in the development of Diaspora at the time, about stream order and forwarded posts. At the time, we also discussed that one of the reasons people like Diaspora is the clear, chronologically ordered stream. Basically I see it that way too, I was just annoyed by all the repeating posts that came up many times in my stream.

**Comment by MrPetovan** [comment]
As I said above, when an older post shows up in your Friendica timeline, there's always a good and recent reason from one of the accounts you follow. If the post isn't relevant to you, you should just stop following the accounts interacting with older posts, this has nothing to do with Friendica itself.

This is particularly clear in the case of reshares: whether a new post is visibly created (like in Diaspora) or not (like in most other protocols/platforms), the result is exactly the same, you get older content at the top of your timeline which "breaks the chronological order". So why the latter bothers you more than the former?

I do not believe we should accommodate this particular idiosyncrasy. If the date a post shows in your timeline differs too much from the date it was published, we do display both dates, and we always show the reason why a post showed up in your timeline. So you never have to guess why older content shows in your timeline, it's always going to be the "fault" of an account you follow. If this behavior bothers you, please stop following these accounts.

Lastly, a "created chronological order" option would break most other users' expectations for their timeline, but also of all the accounts you can follow from Friendica who expect content they published recently (even if it was originally created much earlier in the case of a reshare) to show first in their followers' feed. And given the cross-compatibility of Friendica, this represents a lot of people's expectations to disappoint.

**Comment by annando** [comment]
Of course this should not replace any of the existing sorting orders. It has to be a new one. And possibly you even have to enable it in the settings. So this wouldn't be a problem for anyone who hadn't activated it.

**Comment by annando** [comment]
BTW: I just realized that I already had prepared that ordering in the past. Most stuff is already done for this.
