### ISSUE TITLE
Facebook Connector Issue

### ISSUE THREAD

**Issue by BenLiyanage** [friendica/friendica#1145]
I have a new Facebook app that I set up for the Facebook API.  It is complaining that fql is depreciated.  I will take a look at this for fixing it, but if I could get a little help I'd appreciate it.

When I try to sync users I get this error:

```
2014-09-13 17:35:20@	[NORMAL]:fbsync.php:180:fbsync_cron	fbsync_cron: importing timeline from user 1
2014-09-13 17:35:20@	[NORMAL]:fbsync.php:1008:fbsync_fetchfeed	fbsync_fetchfeed: fetching content for user 10152264990160899
2014-09-13 17:35:20@	[DATA]:network.php:75:fetch_url	fetch_url https://graph.facebook.com/fql?q=%7B%22posts%22%3A%22SELECT+action_links%2C+actor_id%2C+app_data%2C+app_id%2C+attachment%2C+attribution%2C+comment_info%2C+created_time%2C+filter_key%2C+like_info%2C+message%2C+message_tags%2C+parent_post_id%2C+permalink%2C+place%2C+post_id%2C+privacy%2C+share_count%2C+share_info%2C+source_id%2C+subscribed%2C+tagged_ids%2C+type%2C+updated_time%2C+with_tags+FROM+stream+where+filter_key+in+%28SELECT+filter_key+FROM+stream_filter+WHERE+uid%3Dme%28%29+AND+type%3D%27newsfeed%27%29+AND+updated_time+%3E+0+ORDER+BY+updated_time+DESC+LIMIT+500%22%2C%22comments%22%3A%22SELECT+app_id%2C+attachment%2C+post_id%2C+id%2C+likes%2C+fromid%2C+time%2C+text%2C+text_tags%2C+user_likes%2C+likes+FROM+comment+WHERE+post_id+IN+%28SELECT+post_id+FROM+%23posts%29+ORDER+BY+time+DESC+LIMIT+500%22%2C%22profiles%22%3A%22SELECT+id%2C+name%2C+username%2C+url%2C+pic_square+FROM+profile+WHERE+id+IN+%28SELECT+actor_id+FROM+%23posts%29+OR+id+IN+%28SELECT+fromid+FROM+%23comments%29+OR+id+IN+%28SELECT+source_id+FROM+%23posts%29+LIMIT+500%22%2C%22applications%22%3A%22SELECT+app_id%2C+display_name+FROM+application+WHERE+app_id+IN+%28SELECT+app_id+FROM+%23posts%29+OR+app_id+IN+%28SELECT+app_id+FROM+%23comments%29+LIMIT+500%22%2C%22avatars%22%3A%22SELECT+id%2C+real_size%2C+size%2C+url+FROM+square_profile_pic+WHERE+id+IN+%28SELECT+id+FROM+%23profiles%29+AND+size+%3D+256+LIMIT+500%22%7D&access_token=CAAU5slZAjIM4BAJcvV3rszdJz7pkex87RBVGSFP0WVB8gsX7BfXEtc5OZAp2pRQdJRf6ZBxjFodSfZBa32OqtUlE17ZA7SzFogXPOAesD5b0EYpjw36tbGqjDR47b8U71ZCYyyEhdpew4Y5KTQ6O7EFQdxeouCBhYRa3IjXZALYeFZAkD9e3vOfpB1NlGyGRZA0EwdjoYc97aHg808XdnUiNM: 400 HTTP/1.1 400 Bad Request
WWW-Authenticate: OAuth "Facebook Platform" "invalid_request" "(#12) fql is deprecated for versions v2.1 and higher"
Facebook-API-Version: v2.1
Content-Type: application/json; charset=UTF-8
Pragma: no-cache
Access-Control-Allow-Origin: *
X-FB-Rev: 1412053
Cache-Control: no-store
Expires: Sat, 01 Jan 2000 00:00:00 GMT
X-FB-Debug: kOJ3m+hLvfze1XU2V1c+f7EMFLMvqOHrIg8nfBP7eMpzmM7/lO1enr0BIqmdcV96OljAdEX1Cukqr+RQEcoCxA==
Date: Sat, 13 Sep 2014 17:35:20 GMT
Connection: keep-alive
Content-Length: 110

{"error":{"message":"(#12) fql is deprecated for versions v2.1 and higher","type":"OAuthException","code":12}}
2014-09-13 17:35:20@	[NORMAL]:fbsync.php:1028:fbsync_fetchfeed	fbsync_fetchfeed: Error fetching data for user 1: stdClass Object
(
    [error] => stdClass Object
        (
            [message] => (#12) fql is deprecated for versions v2.1 and higher
            [type] => OAuthException
            [code] => 12
        )

)

2014-09-13 17:35:20@	[NORMAL]:fbsync.php:185:fbsync_cron	fbsync_cron: cron_end
```

**Comment by aymhce** [comment]
Hello, there is news about this issue resolution ? Thanks (https://github.com/friendica/friendica-addons/pull/213)
@BenLiyanage

**Comment by silke** [comment]
Adding this to the 3.4 milestone but not sure if anyone can have a closer look before 3.4 release. (I'm not able to solve it myself.)

**Comment by BenLiyanage** [comment]
Hey,

I can do a feature branch and commit the code I wrote so far.  I was having
a some trouble fiddling with the formatting.  The old and new API do not
match one to one, but I remember figuring out a couple of the corresponding
api calls.

-Ben

**Comment by annando** [comment]
@BenLiyanage Maybe you could add this code as a new addon? I would like to preserve the old one as long as possible.

**Comment by BenLiyanage** [comment]
Take a look at my changes here:

https://github.com/friendica/friendica-addons/compare/master...BenLiyanage:master

I was trying to maintain two versions of the pluggin for each api version.
I needed to change the base code some to do that.

-Ben

**Comment by annando** [comment]
It looks like you still want to support FQL. I really would prefer a second addon (without touching the existing "fbsync"-addon) just for the code cleanness. FQL is deprecated, it doesn't make sense to support it any longer as long as there is a replacement. But until the new addon is stable, the old one should be usable for the users who depend upon it.

The only thing I would prefers: Please use the same values for the contacts, so a change would be without pain. (I made that failure with the change from the old to the new one and it generated duplicated contacts for the users who changed the addon).

You could call the addon "fbsyncgraph" since it will be using the "graph" api.

**Comment by BenLiyanage** [comment]
Honestly, I will not be putting much more effort into this pluggin.  I've
lost a lot of steam for getting this working.  Beyond that, it's never
worked for me so its hard for me to get it to work the way the old one did.

-Ben

**Comment by annando** [comment]
Okay. We should remove the "3.4" milestone from this issue since we will not be able to finish it in time. Does anyone agree on that?

**Comment by fabrixxm** [comment]
:+1:

**Comment by annando** [comment]
I just assigned this to the 3.5 milestone. I don't want to have this as a blocker here.

if anyone disagree, please tell.

**Comment by annando** [comment]
According to the [Facebook documentation](https://developers.facebook.com/docs/apps/changelog), we can close this issue. We won't be able to create another sync app anymore.

**Comment by Nold360** [comment]
This is really sucks...
FYI: https://developers.facebook.com/docs/facebook-login/permissions/v2.3#reference-read_stream

**Comment by annando** [comment]
@Nold360 You are absolutely right. It sucks.

**Comment by BenLiyanage** [comment]
FWIW I was able to sign up and get the token, though it has big scary
letters about how its not legit.  I think only administrators have to agree
to that though.

-Ben

**Comment by annando** [comment]
I think after 30th of April it won't work anymore.

**Comment by treellama** [comment]
From https://developers.facebook.com/docs/apps/review/login

> Note: People who are listed in your app's Roles tab will have access to extended permissions without going through review (e.g. publish_actions or manage_pages). For example, if you use the Facebook Plugin for Wordpress to publish your blog posts to your Facebook Page or Profile, you do not need to submit for review so long as all your publishers are listed in your app's Roles tab.

> Also, if you're the developer of an app and are the only person using it, then your app doesn't need to go through review. Since you're the developer, all app capabilities should be available. You will still need to take your app out of developer mode, but you should be able to do that without going through review.

So, I think it's still feasible to develop a sync plugin for tiny deployments. I think I could just add my wife's Facebook account as a "Developer" and the app key should work with read_stream for both of us without review.

I'm interested enough to investigate further.

**Comment by PerigGouanvic** [comment]
I will be interested to know what you've discovered. If I can help for testing, I'm a beginner, I know very little, but managed to set up a friendica platform and to make my own posts (only) mirror from Fb to Friendica and conversely. I went through the lengthy process of making complete submissions for the missing permissions (publish_actions, publish_pages, user_posts, user_photos, user_status, user_videos, manage_pages). I have no idea if I'm doing things right. Will report. 

I have no idea how one sets the application for personal use and bypasses this review process.

**Comment by Keith2** [comment]
There is no need to bypass the review process, you just don't do it. I haven't had any problems with not having had a review for all my apps.

**Comment by PerigGouanvic** [comment]
Just got the answer from Fb. Unsurprisingly, I wasn't able to formulate a proper request. (I can go over the details of my submission, but it's probably crap.). Cf image below

PS : I'd be interested to know how you, @Keith2  , "didn't do it" (when did you make the request? that makes a difference : the rules are changing and will become even more strict in the weeks, as @annando mentioned ). 

@treellama , if you want to connect with me and investigate, I'm here: perig@friendica.hypericonotext.org

![friendica_hit_-_2015-04-21_01 55 11](https://cloud.githubusercontent.com/assets/9629687/7246450/d4630042-e7cb-11e4-9eed-95ec00a3f563.png)

**Comment by treellama** [comment]
It is now May, and I'm still able to use read_stream without passing Facebook review, since I am listed as the developer of the app. So, at the very least, Facebook sync is still possible with single user installations. I still intend to test it by adding Mrs Treellama as a developer, I believe she should have read_stream access as well.

The new API doesn't make things easy. For one thing, it's impossible, as far as I can tell, to retrieve a list of friends. I've hacked up the existing fbsync plugin to (exclusively) use the latest (2.3) Graph API and for now any time it sees a post by a new contact it just adds it. The "follow" functionality from the contacts page only works with public pages because there's no way to convert a Facebook username into an app-scoped id.

Still, I think it's in better-than-nothing territory. There's a considerable amount of polishing left, then I'll push it to my fork and solicit feedback.

**Comment by annando** [comment]
Should we leave this issue open or should we close it? I really would like to close it.

**Comment by treellama** [comment]
I regret I have yet to achieve the "considerable amount of polishing" to my code. I still think this concept is possible, but these restrictions would apply:

* It could only work for private deployments; all users have to be added to the Facebook app as developers
* There's no way to add Facebook friends manually; my plugin would add them automatically the first time they posted
* There's no way I could find to determine whether feed posts are by friends or not; the best I could do was retrieve a list of friends available for tagging, then use the first/last names to match them against incoming posts in order to determine whether to add to the Friendica side as friends. Otherwise mentions, likes, etc. by Facebook friends would add non-friends and even public pages
* The news feed isn't in sync with what's on the actual Facebook home page
* This API could change or go away at any time

That may still be better than nothing, but I have no objections to closing this bug. It certainly can't be implemented as well as it was.

**Comment by annando** [comment]
BTW: The most things that you listed were issues in the current connector as well :)

I would suggest that you add a functionality so that only selected users can use the connector. This would prevent disappointments to the users that aren't added as app developers in the corresponding Facebook app.

**Comment by annando** [comment]
I think we should close this issue.

**Comment by annando** [comment]
No one disagreed, so I'm closing it now.
