### ISSUE TITLE
Open and close new user registration automatic

### ISSUE THREAD

**Issue by utzer** [friendica/friendica#11535]
### Describe the feature you'd like

Open and close new user registration based on total number of users, this would help to maintain a maximum number of users on a server to ensure a good quality of service. 

### Describe alternatives you've considered

nope. 

### Additional context

Maybe the thread [here](https://social.yl.ms/display/e18176ef-1862-856d-9311-7da363608096).

**Comment by ghost** [comment]
Basically I would see this feature in a replacement/rewrite for/of the `public_server`, together with #9399. Adding this to the 2022.08 release would be nice, though, but the other features from #9399 makes sense in this as well, because limiting users automatically does only make sense, when users are cleaned up automatically as well. The logic to cleanup is already present in the `cleanup_friendica` script, but needs porting to PHP as a regular addon. 

The `public_server` addon states as well that it is poorly maintained. Maybe it should replaced anyway.
