### ISSUE TITLE
Create option to hide comment notifications on liked posts

### ISSUE THREAD

**Issue by rickgardner077** [friendica/friendica#11566]
### Is the feature request related to a problem? 
There is a notification whenever someone comments on a liked/upvoted post. Users should be able to disable these kinds of notifications

### Describe alternatives you've considered
Alternatively there could be an option to disable these notifications for single posts

### Additional context

**Comment by tobiasd** [comment]
You can deactivate the notification about "likes" in the user settings (`/settings`) in the "Notification Settings" section.

**Comment by MrPetovan** [comment]
It's different. Whenever you interact with a thread (with a like or a comment), you will be notified of every subsequent comment your node receive about this thread. It's an implicit "Follow Thread" that has to be manually turned off on a conversation basis with the "Ignore Thread" option.

**Comment by tio-trom** [comment]
I suggest the "follow thread" to always be deactivated for when you comment on a thread. Only when you get replies on your comment to be notified. And if you like a thread....well maybe in the settings users can select if that should automatically mean follow the thread or not. For me I'd like not to. I avoid liking posts simply because I get notifications for every single comment on that post.

**Comment by rickgardner077** [comment]
If I read this correctly the action of liking a post has a different connotation on Friendica than on other services, like Mastodon, Pleroma or Pixelfed.

On these services a like is a signal to the creator of a post of acknowledgement or agreement. For newbies some even refer to liking as a kind of bookmark to save interesting posts.

On Friendica being notified of all subsequent comments it seems to be more of a "follow this thread" action.

I am currently using Pleroma and Friendica side by side but refrain from liking on Friendica for this reason.

Maybe there should be two buttons, one for liking in the way of Mastodon/Pleroma/Pixelfed, one for following which notifies the user of all subsequent action on that post

**Comment by annando** [comment]
My idea is to have several options for when to get notified. For example:

- Notify whenever someone interacted with a comment in the thread where you interacted in any way
- Notify whenever someone interacted with a comment in the thread where you commented on
- Notify whenever someone commented directly to your post/comment
- Notify whenever someone interacted (comment/like) directly to your post/comment
- Don't notify at all

Additionally to a general setting this value can then be changed on a thread level. So you could have threads where you want to get notified all the time and other threads where you only want to get notified when someone talks to you directly.

Technically this is not a big deal. The biggest task is to integrate this in the user interface.

**Comment by tio-trom** [comment]
Those suggestions sound very good! Especially if this can also be applied generally or per post. Awesome Friendica!

**Comment by rickgardner077** [comment]
I'm amazed how a question from a newbie like myself in the support forum leads to a feature discussion like this in no time. Thanks everybody

**Comment by foss-** [comment]
What will be the default? Can we agree that the current default to notify user of replies to threads they did not comment on but only liked a post is not a good choice? Think either `Notify whenever someone interacted with a comment in the thread where you commented on` or `Notify whenever someone commented directly to your post/comment` would be preferable as default.

Twitter only notifies about followup comments when a thread was commented in. For likes they don't do this and I think that is a good design choice. A like doesn't mean a user wants to engage in a discussion that may follow in a thread.

While I like the options mentioned I am indeed worried they may result in a complex UI. Since most users will go with defaults, goes to show why good defaults are so important and current default should be adjusted.

**Comment by annando** [comment]
The default will be the current behaviour. Current users shouldn't need to adjust something to keep the same experience.

And yes, we should have a look to make the configuration easy to use and understand.

**Comment by SpcCw** [comment]
Currently it works as follows: any interaction means subscription to new comments and if you don't want to get new comments after "liking" you can "like" and then click "ignore thread". It is already simple. Most of the time I prefer to get further comments on liked posts because if I liked something I am usually interested on follow-ups.

So I think new user option could be added which would determine if this automatic subscription happens or not. E.g. "Get notifications about comments on liked posts" with default on.

I am not sure it should get more complicated than that because threads are not universally supported (e.g. Mastodon, Diaspora) and this will likely result in inconsistent behavior like someone on Mastodon replying to your comment which you see as part of thread but they just add reply as separate comment below so you don't get notification you expect.

Another possibility is user option "Get notifications about comments on posts you liked or commented" with "on" (default), "only commented", "off". The second option would disable subscription on likes and third would disable automatic subscription completely and only subsequent mentions would trigger new notifications.

**Comment by tio-trom** [comment]
I agree with @foss that the current default is too much. Liking a post should not necessarily mean you want to get notifications for all comments on that post. Up to the Friendica devs, but from my experience it makes you not want to like posts. Liking then clicking to ignore the thread from a drop down menu is not very comfortable. Plus, what if I comment to a post and I am only interested in whatever people reply to me but not whatever others comment on that post? If I ignore the thread will that ignore the replies to my comment on that thread too? 

In my mind if you comment you are interested in notifications when someone replies to your comment. If you like, this is a passive "I like it" and that's all.

**Comment by foss-** [comment]
Thanks for looking into this.

We now have `Settings > Account > Notification (sic! should be Notifications) > Someone commented in a thread where you interacted`

For me this setting is activated. But that doesn't inform about defaults. I would like to see this off by default, since it will increase usability for users and prevent overwhelming amount of notifications that mostly add noise and not value. The rational was [given](https://github.com/friendica/friendica/issues/11566#issuecomment-1140201722) [above](https://github.com/friendica/friendica/issues/11566#issuecomment-1139577637).

**Comment by SpcCw** [comment]
@foss- On the other hand the most common newbie complaint in my experience is that initially their feed is very quiet.

So maybe a bit of noise won't hurt and when/if it becomes irritating the option is there.

**Comment by annando** [comment]
The default is the current behaviour to simply not confuse the existing users. And new users will most likely have a look into the settings when they think that they receive too much notifications. The other thing is not really true. Normally you don't really recognize when something isn't happening so often anymore.

**Comment by tio-trom** [comment]
Can any of these be defaulted by the admin? Maybe on my instance I'd like to setup the default notifications in a specific way. I do think that the current default is way too much for anyone, but up to the Friendica devs to setup the defaults for the source code.

**Comment by foss-** [comment]
> @foss- On the other hand the most common newbie complaint in my experience is that initially their feed is very quiet. So maybe a bit of noise won't hurt and when/if it becomes irritating the option is there.

If the timeline is too quiet for new users, we need to improve the on-boarding experience, e.g. ask for 3 topics a user is interested in and show how to follow other users and especially how to find content and with that engagement get them into more topics / users to follow and engage with.

I agree it is not easy to get that momentum going but artificially cluttering notifications so that there is more noise is imo not a good idea. Especially if that behavior quickly turns into undesired behavior for most users once they follow a few users and have more interaction with their timeline. I think there is a good reason why Twitter does not behave this way when it comes to notifications and post interactions.

> The default is the current behaviour to simply not confuse the existing users. And new users will most likely have a look into the settings when they think that they receive too much notifications. 

Never suggested to change anything for existing users. So that is not what is being discussed. When debating defaults I am asking about new users *only*. I think it is a false assumption, that users will play with the rather complex settings of friendica, especially not new users or less tech-affine users. Many people struggle to even keep their windows computer updated. Most users go with defaults and a [recent poll in regards to a Fedilab feature](https://codeberg.org/tom79/Fedilab/issues/109#issuecomment-464180) even had 17 % answer `I don't understand the feature`. And while this is not about Fedilab, I think there is a tendency with many developers to overrate the skills of their users. Attached the current friendica notification settings:
![notifications](https://user-images.githubusercontent.com/5708172/172479710-440a5753-fcf8-4a3f-90ff-77905185d552.png)

Show this to a user and ask them how graspable those settings are on a scale from 1 - 10. There is a reason you won't find a comparable view in twitter settings. Friendica is much more complex than twitter and I don't even want to debate to remove any setting - I am sure they all have there reason to be there. But we are not doing a great job of confronting users with those options. And most users won't bother to even read through such a page.

Which is why most companies try to nudge their users into accepting invasive options on the initial setup and then never ask about that again. You can opt-out but most users will never do that. That is why good defaults are so important. And yes, debating good defaults is very difficult, but in this case I am rather certain, it is better to reduce the noise for a more pleasant and humane user-experience on friendica.

**Comment by foss-** [comment]
Had an interesting argument with @MrPetovan and their argument was, that notifications for discussions that a user interacted with (e.g. via a like) are actionable, meaning users can engage if they want. While a notification about a like is not actionable.

The reason surveillance capitalism social media notifies about likes probably mainly is, to ensure users receive their dose of dopamine and get hooked. So one could even argue to default like notifications to off while keeping notifications for post a user interacted with defaulting to on.

So there is good reasoning for both default options (on | off). Since we now have a setting this can be adjusted as needed and it is probably the easiest to go with current defaults unchanged.
