### ISSUE TITLE
Do not cross-post on Twitter when it exceeds the character limit

### ISSUE THREAD

**Issue by tio-trom** [friendica/friendica#11691]
I post on Twitter by default, and I even forgot about it haha. But would be a nice little addition to simply not post on Twitter if a post is longer than the characters accepted by Twitter. If anyone has it enabled to auto-post on twitter like I do, they will (very likely) post chopped posts from Friendica.

Either show a message while typing and exceeding the twitter characters, if it is selected to post on twitter, or simply refuse to post on twitter.

Thanks!

**Comment by MrPetovan** [comment]
Twitter counts their characters in a very specific way due to the way links are handled with a fixed 22 characters length after shortening. This number was current a few years back, I don't know what it is now. They provide an API endpoint where you can submit a text and it returns the number of characters it would take in a tweet.

Long story short, it isn't easy to figure out if we're over/under the limit in Friendica.

If you don't want longer posts to be chopped arbitrarily, you can add a title and the Twitter post will be the title and a link to the Friendica post.

The real problem is for replies from Friendica mirrored to Twitter. In this case the link to the Friendica post leads to a private conversation that nobody else but yourself can read.

**Comment by tio-trom** [comment]
Oh I see. So there is no way to know for sure, but can't we then use a "safe" margin of error? Between this and that amount of characters? And that to trigger at least a warning when people create a post?

> If you don't want longer posts to be chopped arbitrarily, you can add a title and the Twitter post will be the title and a link to the Friendica post.

This is good to know, thanks.

> The real problem is for replies from Friendica mirrored to Twitter. In this case the link to the Friendica post leads to a private conversation that nobody else but yourself can read.

Oh that's ugly :D. Maybe we do need a way of alerting the users about the character limitation within a certain safe margin. Seems like something is needed there.

**Comment by annando** [comment]
We have a check for the size and it mostly works fine. Because of the size check we are treating the post differently. Means: We need a better indicator for the frontend.

**Comment by MrPetovan** [comment]
> Oh I see. So there is no way to know for sure, but can't we then use a "safe" margin of error? Between this and that amount of characters? And that to trigger at least a warning when people create a post?

It's the other way around, since links are shortened, it's mostly fine to go over 280 characters with links. Same with BBCode formatting, the tags take up characters in the input form but do not in Twitter. So we can show a warning, but it won't be accurate.

**Comment by foss-** [comment]
Not sure about this. I tend to keep an eye on the 280 characters when composing posts for accounts cross-posting to twitter. I think the current behavior is fine to switch to a link once character link is exceeded.

As MrPetovan stated, this is hard to handle well and I think the overhead needed to get this right would not justify the benefit or gain from this.

I think it is fair to assume users who cross-post are aware of limitations of the platforms they cross-post to. So the character counter during compose feels sufficient.

**Comment by tio-trom** [comment]
I still think a warning of sorts could be very useful. Can't we ignore the BBCode can links and count the rest and showcase a warning? :D

**Comment by annando** [comment]
What we need is some JS callback routine that does the calculation. Technically it is possible, it just needs the JS part, the endpoint is really easy to code.

**Comment by foss-** [comment]
To avoid complex calculation and implementation, would turning the character counter number red as soon as the 280 mark is hit? And only doing this for accounts that have cross-posting to twitter enabled? It is not ideal and milage may vary but it is a nice indicator and easy to spot due to the color change.

**Comment by MrPetovan** [comment]
The problem is that it's dependent on an addon that may or may not be present, enabled or configured on the server, and may or may not be configured by the user. So it needs to be grafted on the writing form from the twitter addon, which increases complexity.

**Comment by annando** [comment]
We now support Twitter threads, so I guess we can define this issue as solved?

**Comment by tio-trom** [comment]
> We now support Twitter threads, so I guess we can define this issue as solved?

Sorry I am not at familiar with what this means. It means it will break long Friendica posts into threads on Twitter automatically?

**Comment by annando** [comment]
Yes.

**Comment by tio-trom** [comment]
Oh wow really? That's amazing. Yeah much better. Awesome! :)
