### ISSUE TITLE
Maintenance page - CSS missing/blocked

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#11723]
- [X ] I have searched open and closed issues for duplicates

### Bug Description

The maintenance page has no CSS and looks damaged. It seems that some CSS is blocked when maintenance mode is enabled.

### Steps to Reproduce

1.  enable maintenance mode
2.  look at the maintenance page

Actual Result:

![grafik](https://user-images.githubusercontent.com/3656054/178323468-722f3885-95d9-48ce-8129-6fa4dac54278.png)

Die Ressource von "https://libranet.de/view/theme/frio/style.pcss?puid=2&v=2022.09-dev" wurde wegen eines MIME-Typ-Konfliktes ("text/html") blockiert (X-Content-Type-Options: nosniff). libranet.de

Translation: The resource of "https://libranet.de/view/theme/frio/style.pcss?puid=2&v=2022.09-dev" was blocked because of a MIME type conflict ("text/html") (X-Content-Type-Options: nosniff). libranet.de

Expected Result:

Show the maintenance page with an intact theme.

### Platform Info

Friendica Version:
202x.xx and follow up versions, happens with current stable and develop too

Friendica Source: 
git

PHP version:
7.4

SQL version:
MariaDB 10.6

**Comment by MrPetovan** [comment]
The CSS call goes through the regular module because we vary the CSS based on the logged in user, which is why it ends up showing the maintenance page as well. We'd have to write an exception just for this module to be able to use the CSS with default theme setting, disregarding the user's and the site's settings.
