### ISSUE TITLE
Support import/export for domain blocks

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#11775]
Offshoot of https://github.com/friendica/friendica/issues/11773

This would enable anyone downloading the domain block list available at `/friendica` under a structured file format, and administrators to import such a file to either extend or replace their current block list.

**Comment by tobiasd** [comment]
Until this is implemented in the frontend/API it is already possible with the console tool.

So admins willing to do some exchange of the blocklist can already set up some automatically export of the list to a CSV file in the web-root of the Friendica instance via cron. The importing nodes would need to have a similar cron job to fetch the list and then import it.

**Comment by MrPetovan** [comment]
Ha, I didn't know about that, I went forward with a JSON file format instead for the UI tools, I should probably follow what already exists.

**Comment by tio-trom** [comment]
This would be good. Also, can you please add a feature so that it sends a notification to all of the users on that instance when the admin blocks another instance? I think that's the last thing on the list of transparency that will make Friendica above all other. If this would not be that difficult to add of course. What do you think? It is an important decision when an admin blocks another instance...

**Comment by MrPetovan** [comment]
This is possible.

**Comment by tio-trom** [comment]
That'd be really useful. Complete transparency. Should I open a new issue for it so maybe you can implement it in the future? :)

**Comment by MrPetovan** [comment]
Yes please!

**Comment by MrPetovan** [comment]
Follow-up in #11779
