### ISSUE TITLE
[twitter-crossposter] Long posts with images attached get truncated without linking to original source

### ISSUE THREAD

**Issue by kr428** [friendica/friendica#11953]
If writing "longer" posts that contain image attachments and crossposting this to Twitter, this will result in posts being truncated there and not even showing a link to the original source.

original link: https://loma.ml/display/373ebf56-1163-09b0-b093-c85993757342
Twitter crosspost: https://twitter.com/kr428/status/1563403676760539137

This is annoying especially because in most cases, writing such posts, I try to keep the char limit required for Twitter but apparently in this case that doesn't work at all. 

Solutions? Best would be to, similar to some of the Mastodon -> Twitter crossposter, to split up "long" posts and crosspost them to Twitter as a thread (1/x , 2/x, ...) - moa.party et al do that. Sufficient workaround would be adding a link pointing to the original Friendica post to have some context to read the full text.

**Comment by annando** [comment]
This is not a bug but an expected behaviour. Making it a "Twitter Thread" is a feature request.

**Comment by MrPetovan** [comment]
The missing link to the longer Friendica post replaced by the image embed sounds like a bug though.

**Comment by annando** [comment]
This behaviour can be changed in the social network settings.

**Comment by MrPetovan** [comment]
Is it by disabling "Intelligent shortening"?

**Comment by annando** [comment]
Yes.

**Comment by foss-** [comment]
Is that a good default (if that is the default that is)? Isn't it fair to expect a link to source post whenever content is shortened for whatever reason when cross-posting?

This issue indeed touches on two aspects:

- always include link to source post, when truncating a post
- split longer posts into multiple posts on platform cross-posting to (@kr428 can you file a separate issue for that feature request?)

**Comment by annando** [comment]
The focus of the default behaviour is to provide posts that just look like posts you would create on Twitter directly without any media discontinuity. Thing is: It is not the regular expectancy in Twitter, that you have to leave Twitter and go to another site to continue reading the post.

So the default behaviour has got some rules to decide how to shorten the post. When it is a text only post, then it is clear that the text is the most important part. Then the system will display the first few lines and will then provide a link to the post. When a link is attached, then that link is taken instead. And when media is attached, then the media is the main focus of the post, thus the text simply is shortened. By using  `[abstract]...[/abstract]` or `[abstract=twitter]...[/abstract]` this text is used instead, this making it possible to create posts to each network that look the best on each network.

Since nowadays the usage of "Twitter threads" are now common, of course this is a viable option.

**Comment by annando** [comment]
With PR https://github.com/friendica/friendica-addons/pull/1282 we now have the possibility to truncate posts into multiple tweets.

**Comment by kr428** [comment]
Sounds good, thanks. However, immediately relating to #11951 then: Are these multiple (top-level) tweets then, or will they appear as a thread on Twitter?

**Comment by annando** [comment]
It is looking that way: https://twitter.com/heluecht/status/1576720186241073154

**Comment by kr428** [comment]
Neat. Thanks. This one seems "closed" for me then.
