### ISSUE TITLE
[vier] Friendica can no longer post images

### ISSUE THREAD

**Issue by 4nanook** [friendica/friendica#12013]
- [x ] I have searched open and closed issues for duplicates

### Bug Description

I can no longer post an image.  When I choose the image Icon, it brings up the usual photos page except it's empty.  If I try to upload a new one, it does not show up in the page either, just a blank page with no images.
### Steps to Reproduce

1.  Under compose, select the image icon
2. Notice the resulting page is blank and all your previously uploaded pictures are gone.
3. Attempt to upload a new image

Actual Result:

All the previously uploaded images to the photo pages are gone.  If you upload a new one it does not show up.

Expected Result:

As it previously was, when you select the image icon it shows you the page of most recently uploaded photos, you can either select one or upload a new in which case the new would show up as the first image on this page.

### Platform Info

Friendica Version:

Friendica 'Giant Rhubarb' 2022.12-dev - 1485
Friendica Source: Giant Rhubarb' 2022.12-dev - 1485

PHP version:
PHP 7.4.32 (cli) (built: Sep 29 2022 22:25:17) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
![friendica](https://user-images.githubusercontent.com/3466797/196280609-5169cd1b-1361-45fa-98ad-f12abb2af6a6.png)

    with Zend OPcache v7.4.32, Copyright (c), by Zend Technologies

SQL version:
mysql  Ver 15.1 Distrib 10.6.7-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper

**Comment by MrPetovan** [comment]
We have a second report of the gallery not working since the release: https://friendicarg.nsupdate.info/display/69172192-1463-4dfa-bc60-5bb894469825

**Comment by tobiasd** [comment]
What theme are you using @4nanook ?

For me it worked only using frio, but does not work with any other theme.

**Comment by 4nanook** [comment]
I am using vier.

**Comment by roblen** [comment]
Hello! I installed Friendica (latest stable version) last days. Everything is running fine. I have only one problem with photos.

I save photos in the "Storage" directory. If I now create a new entry and try to upload a photo via the "Browser" tab, the upload is displayed ... then the photo is not to be found in the "Pictures" tab (https://micro.roblen.at/photos/roblen)

I have now looked in my database. In the table "photo" I find the column "allow_cid". Here you can find a value "<2>" at the "non-showed" photos. For my profile photo there is no value in the column. If I delete this value in "allow_cid", the non-showed photo is also displayed in the pictures.

That means, the photo is uploaded, but because of the entry in the database is not displayed to me.

**Comment by MrPetovan** [comment]
`allow_cid = "<2>"` means that the picture is only available for the contact with `id = 2`, which I assume is the contact associated with your own user account. What are your default posting permissions?

**Comment by roblen** [comment]
Posting Permission is "public". The strange thing is: When I upload a picture at the tab https://micro.roblen.at/photos/roblen, no User-ID is seen in the column "allow_cid". But I can see the picture at my friendica installation and can also use it for postings.

**Comment by MrPetovan** [comment]
No specific contact ID in the `allow_cid` column almost always means that it's a public item (if the `allow_gid`, `deny_cid` and `deny_gid` also are empty).

**Comment by roblen** [comment]
Yes, this columns are also empty. 

The problem is that one form of upload is assigned "<2>" in the allow_cid (and I still can't see the image as a logged-in user). In the other form of upload, nothing is entered there and I can see the image (logged in and not logged in).

In fact, everywhere I have seen, I have stated that postings etc. are public by default.

**Comment by 4nanook** [comment]
Any chance this issue is going to be addressed in this lifetime?  Kind of crappy do an upgrade and all the sudden lose the ability to post any images, even in comments.

**Comment by MrPetovan** [comment]
My long-standing opinion is that we should deprecate the vier theme to avoid this situation where developers have to check multiple themes every time they make a change but it isn't popular enough to be enacted just yet.

**Comment by tobiasd** [comment]
The file `view/templates/filebrowser.tpl` is missing a `"` in line 35. See #12129 for the exact difference.
