### ISSUE TITLE
[Advanced Content Filter] settings page - no rules, no fields, no buttons

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#12054]
- [X] I have searched open and closed issues for duplicates

### Bug Description

In current stable and develop versions the ACF settings page is broken. Nothing is displayed, just an empty "card".

### Steps to Reproduce

1.  go to settings -> addons -> advanced content filter

Actual Result:

![grafik](https://user-images.githubusercontent.com/3656054/197401089-e5f38942-1af8-473d-8802-77b453b6964e.png)

Expected Result:

A working settings page. ;-)

### Platform Info

Friendica Version:
2022.10
2022.12-dev

Friendica Source: 
git

PHP version:
7.4

SQL version:
MariaDB 10.6

**Comment by AlfredSK** [comment]
``GET https://libranet.de/view/asset/vue/dist/vue.min.js [HTTP/2 404 Not Found 175ms]``

``Resource of "https://libranet.de/view/asset/vue/dist/vue.min.js" blocked because of MIME-Type-Conflict ("text/html") (X-Content-Type-Options: nosniff). advancedcontentfilter``

``Uncaught ReferenceError: Vue is not defined
    <anonymous> https://libranet.de/addon/advancedcontentfilter/advancedcontentfilter.js:15
advancedcontentfilter.js:15:1``

**Comment by MrPetovan** [comment]
😓

**Comment by MrPetovan** [comment]
The Javascript ecosystem is utterly stupid.

**Comment by aki42** [comment]
> The Javascript ecosystem is utterly stupid.

Sorry for chiming in after the bug having been closed already. I ran into the same problem, found this bug report, didn't want to wait for 2022_12 - and therefore changed one line in `…/advancedcontentfilter/templates/settings.tpl`:
Old: `<script src="{{$baseurl}}/view/asset/vue/dist/vue.min.js"></script>`
New: `<script src="https://cdn.jsdelivr.net/npm/vue@2.6.10/dist/vue.js"></script>` (found somewhere in the vue install/usage guide)
Do you want to avoid that because of the external dependency? On the other hand this would address the worries expressed somewhere else (just can't find it again in the bug reports) about possibly missing security updates when using a standalone library.
(If I want to add a rule the addon complains about missing table $dbname."advancedcontentfilter_rules", but that's another topic I guess)

**Comment by MrPetovan** [comment]
Thanks for your message. I do not want the Friendica project to be depending on another 3rd-party service for a couple reasons:
- I don't want to spend time figuring out how reliable and trustworthy they are.
- Every Friendica user visit to the advancedcontentfilter page would be logged on a remote server owned by a 3rd-party with absolutely no control over what data is stored and what is done with it.

There are enough security and privacy concern for me to go the self-host route instead.

Please open a separate issue for the missing table message.

**Comment by aki42** [comment]
> * Every Friendica user visit to the advancedcontentfilter page would be logged on a remote server owned by a 3rd-party with absolutely no control over what data is stored and what is done with it.

Ok, that's a really good point I didn't think of. So staying on one's own server is indeed to prefer.
