### ISSUE TITLE
Enable users to opt out of server domain pattern block list update emails

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#12062]
See https://loma.ml/display/373ebf56-1763-57d9-6248-085142307935

**Comment by annando** [comment]
I hadn't really realized what this feature is about. Does this mean that my 5,000 users on squeet.me will receive a dedicated mail per server block? This would surely lead to an immediate block of my domain by some mail servers, since this resembles too much the known spam patterns.

**Comment by MrPetovan** [comment]
Each block list change change will send an email to each user, as it was requested by @tiotrom

**Comment by annando** [comment]
I can remember that PR, but I completely hadn't comprehended the impact at that time.

**Comment by loma-one** [comment]
I have since been blocked by spamhaus.org and am trying to get my domain unblocked.

The opt-out by the user will probably not be enough. This will be difficult to communicate. I will not reach many to have a sufficient effect on the amount of e-Mail sent.

Hence the following suggestion:
1. the admin gets control if an e-Mail should be sent when a change is made.
2. the user should have an opt-in function. The goal must be that the user only receives a notification if he requests it. 
3. changes to the locks are sent collected to 1 x a day at a fixed time.
4. if no changes have been made, the notification will not be sent.
5. the text of the notification must be improved. It is completely unclear what the user should check and what his action on it is.

Just one more comment:
There is no law that requires users to be informed. The GDPR does not require users to be notified. The transparent presentation under /friendica is perfectly sufficient.
Therefore, I cannot understand what this requirement is based on. I just see that the effect is devastating and we need a quick and good solution.

The admin's job is to inform and explain changes to the instance. Delegating this task to an email is not a good idea in my opinion.
We should seriously address this again. At the moment I can only recommend not to change the blocking list anymore, because it is not a good result in the direction of third parties (Spamhaus) and the users on my instance.

I think it is not wrong to equate the notification with a newsletter. There are corresponding jurisdictions in Germany

https://www.it-recht-kanzlei.de/abmahnung-unverlangt-zugesandter-email-newsletter.html

Anhand dieser Kriterien kommt das Gericht zur Ansetzung folgender Streitwerte:

Einmalige Zusendung bei privatem Empfänger:3.000,00 EUR
Einmalige Zusendung bei gewerblichem Empfänger:4.000,00 EUR
Mehrfache Zusendung bei privatem Empfänger:5.000,00 EUR
Mehrfache Zusendung bei gewerblichem Empfänger:bis 7.000,00 EUR
Ab fünf Zusendungen:zwischen 8.000,00 und 12.500,00 EUR

Thank you :)

**Comment by MrPetovan** [comment]
What do you think @tiotrom ?

**Comment by Quix0r** [comment]
@loma-one One solution is, to have a configuration entry, where the administrator can turn it off entirely. An other is that this feature as it already has caused harm is being dumped. Just imagine this on an instance with 1k, 2k and more users. A burst of emails are being sent out from a single server. Not the content matters here, but the burst of emails being sent.

**Comment by tio-trom** [comment]
> Each block list change change will send an email to each user, as it was requested by @tiotrom

I think what I had in mind was to send a notification and not an email. Isn't this going to fix the email issue?

Also, please do not make this optional else makes no sense. Admins should be "forced" to be transparent about their decisions I believe. Should be part of how the fediverse works, else we have a complete mess where no one knows who/what is blocked and when.

**Comment by MrPetovan** [comment]
A notification could be a nice middle ground, some users have email activated for their notifications but not all of them. Additionally, compounding notifications could be combined in a single one which wouldn't trigger additional emails.

**Comment by loma-one** [comment]
No contradiction with the question that the admin should explain his actions. But he also does that in other ways. 
My suggestion is to create an opt-in function. This is a conscious decision of the user and the user can handle the result well.

**Comment by tio-trom** [comment]
I "vote" for a notification. :) - Yes some users have emails enabled for notifications but if they are bothered they can disable that. And sure, if others prefer this, users should be able to disable notifications about the blocklist same way they disable it for other things.

**Comment by loma-one** [comment]
I think they continue to not oversee what damage has been done by the email notification.
We need a solution that does not undermine the autonomy of the admins and keeps damage away from the instances.
This is not about opinions.

Gladly an internal notification. But please, disable a sending via an e-Mail.

**Comment by MrPetovan** [comment]
I'm sorry about your trouble with Spamhaus. I can't take it back and it definitely isn't the regular case. However, all these emails were legit. There's only so much we can do about abiding by several opaque sets of rules to avoid landing on any spam list.

**Comment by Quix0r** [comment]
Nextcloud has solved it this way:
- a checkbox for each notification (in-program, no email) is being wanted by the individual user
- a 2nd checkbox if that notification is being sent out by email
- some are required to be notified/emailed about, some aren't, some can never be sent out by email

This is how it would be the most flexible way for each individual user to decide what is being notified about and for what event an email goes out. The user is back in control which emails are coming and the administrator has done the transparency part.

**Comment by loma-one** [comment]
@MrPetovan @Quix0r 
Then I assume that commenting out line 242 $this->emailer->send($email); (DomainPatternBlocklist.php) first prevents further mails? I don't want to leave my instance unmoderated. Currently, however, I can't do that because I risk slipping onto a spam list with every change.

**Comment by MrPetovan** [comment]
It's correct.

**Comment by annando** [comment]
In the discussion Mike made a suggestion that I think is a good middle ground. I think that in future we should send a notification (not a mail) only when the block pattern affects contacts from that user. This is of course slightly more complicated. So I suggest some asynchronous process that is called maybe once a day. And possibly some new frontend feature where users can see their contacts that are blocked by server rule.

**Comment by tio-trom** [comment]
> In the discussion Mike made a suggestion that I think is a good middle ground. I think that in future we should send a notification (not a mail) only when the block pattern affects contacts from that user. This is of course slightly more complicated. So I suggest some asynchronous process that is called maybe once a day. And possibly some new frontend feature where users can see their contacts that are blocked by server rule.

If you see my original request, I specifically talked about sending notifications and not emails - https://github.com/friendica/friendica/issues/11779 - so I 100% agree.
