### ISSUE TITLE
Domain move from Mastodon to Friendica

### ISSUE THREAD

**Issue by jakedfw** [friendica/friendica#12188]
I have a working Mastadon instance with one domain.
I have working Friendica instance with another domain.

I want to delete the Friendica domain and move the Mastadon domain over and then delete the Mastadon instance.

I see that I can do a domain change in the admin UI, which looks pretty simple. I can also do all the DNS stuff, so am not worried about that. My question is this:

Will people that are following me via Mastadon automatically follow the domain over the Friendica? Note that the actual address won't change at all, as I'm moving the domain. 

Perhaps more importantly, would this break anything via the ActivityPub connections?

**Comment by MrPetovan** [comment]
I'm not sure I understand what you're trying to do, can you please use your domain names to describe the starting state and the ending state?

**Comment by jakedfw** [comment]
Friendica: afriendly.place
User: @jake@afriendly.place

Mastadon: kerr.social
User: @jake@kerr.social

Desired solution:

Friendica: kerr.social
User: @jake@kerr.social

Mastadon: deleted
User: @jake@afriendly.place deleted

**Comment by MrPetovan** [comment]
Thank you for the elaboration. I would generally advise you against this move because of cryptographic keys. Your current Mastodon account `@jake@kerr.social` has generated a set of keys to authenticate its message. Your current Friendica account `@jake@afriendly.place` also has a set of different keys created for the same purpose.

If you move your Friendica account to `@jake@kerr.social`, you will clobber the Mastodon-generated cryptographic keys, but the account `@jake@kerr.social` is only known by remote servers via this now-deleted key, and they would have every reason to block any subsequent message signed with the Friendica-generated key.

Note that the move from `afriendly.place` to `kerr.social` can still happen, but you'd have to create a new Friendica account once the move is done to avoid federation issues with the specific account `@jake@kerr.social`.

**Comment by jakedfw** [comment]
Could I delete the @jake@kerr.social account on Mastadon? Would that delete the keys?

**Comment by MrPetovan** [comment]
Unfortunately I do not know enough about Mastodon to confirm. But in general federated deletion is unpredictable, creation works pretty well but anything after that (edit, removal) is iffy, so I wouldn't expect a complete compatibility.

**Comment by jakedfw** [comment]
So you can call me your guinea pig. I moved the set-up described above from Mastadon to Friendica. It seems to connect across all nodes other than mastadon.world. I can click "follow" there, but the user doesn't end up in my follow list. Every other one I tested does the following:

The user shows up in my follow list. 
If they were following me before, that connection is retained. 

I'll have to wait to see posts show up, but since the "connection" at the profile/user level looks good, I'm pretty sure that will work fine. 

Working instances I tested: 

fosstodon.org
mastadon.online
wandering.shop

**Comment by MrPetovan** [comment]
Thank you for the follow-up!

**Comment by jakedfw** [comment]
Found out that the 1 outlier had closed his account on the other server and changed profiles. I can now confirm--with no exceptions that I've seen--that moving from Mastadon to Friendica with the same profile works fine as long as you keep the same domain and profile name. 

Which now makes me wonder if a "migrate to Friendica from Mastadon" database script could be created. :)
