### ISSUE TITLE
Weird interaction between markdown being converted to BBCode

### ISSUE THREAD

**Issue by silverwizard** [friendica/friendica#12268]
- [X] I have searched open and closed issues for duplicates

### Bug Description
Basically if someone wraps a url in backticks, then the BBCode translator will do [code] Text [url=$url]$url[/url] more code[/code] and then will double the URL and put the BBcode in the display

### Steps to Reproduce
Send markdown from something that isn't friendica
Receive with friendica

Actual Result:

`[url=www.example.com]www.example.com[/url]`

Expected Result:

`www.example.com`

### Screenshots
![Friendica-Version](https://user-images.githubusercontent.com/4934062/204044208-f10eaae8-3c50-4e26-8803-cafdbd7ea821.png)
![Screenshot](https://user-images.githubusercontent.com/4934062/204044236-6f2c7eb2-45e1-4c81-ab77-e049a1fa44ca.png)

### Platform Info

Friendica Version:

This is Friendica, version 2022.09-dev that is running at the web location https://convenient.email. The database version is 1481/1481, the post update version is 1452/1452.

Friendica Source:  git

PHP version: PHP 7.4.30

SQL version: Server version: 10.5.15-MariaDB-0+deb11u1 Debian 11

**Comment by MrPetovan** [comment]
I guess I'll have to dig to find the source post formatting, huh.

**Comment by MrPetovan** [comment]
Found it, and, oh no, it's one of those corner cases. Code blocks are meant to be literal in Friendica, so it doesn't jive well with live hypertext links inside of them.

Plus I found a communication issue that prevents me from fetching the original AP objects from the source post (401 error), even with a signed request: https://fedi.underscore.world/notice/APyGPkYDKhlLAxJY7k

**Comment by MrPetovan** [comment]
I don't have a good solution for this. Since we expect inline code blocks to be literal, we can't accurately guess whether it's a wrongly converted link or intended literal HTML or BBCode. Any destructive action we would perform would have very confusing false positives.

Closing this as Won't Fix, it's an expectation mismatch that we can't solve because we don't have access to the text that was actually entered in the post box on the remote side.
