### ISSUE TITLE
[mastodon-api] Opening pixelfed posts by URL doesn't work.

### ISSUE THREAD

**Issue by kr428** [friendica/friendica#12273]
Current versions of fedilab and tusky, friendica 2022-10. Pixelfed account. 
- Copy link of the pixelfed post (in the app or a browser window).
- Post this link to search form in any of these apps.
- Search.

Doing so with a Mastodon account will find and open the particular post, just like the Friendica Web UI search. However, search in Friendica with any of the named apps will not retrieve anything but (tusky) run into an unqualified error after some moments.

**Comment by foss-** [comment]
Can you provide a sample link to help make testing / fixing this easier?

**Comment by kr428** [comment]
This as an example:
https://pixelfed.social/p/dmitry84/502099555470608886
On a closer look it doesn't seem limited to pixelfed posts, this one can't be found or opened either:
https://mstdn.jp/@omi_geek/109409964168100031

**Comment by foss-** [comment]
Edit: My bad, tested with friendica web. This issue here is about mastodon clients Fedilab, Tusky or rather mastodon API support in friendica.

**Comment by kr428** [comment]
But you're trying this in the _web_ user interface, right? My problem specifically occurred only on any of the Mastodon API clients (tusky, fedilab, yuito, ...). In the web, it generally works for me for all of these posts too...

**Comment by stom79** [comment]
Cross account actions are broken with Fedilab through friendica. Because searching for a user or a message will return sometimes several results instead of one and they are not ordered with the most matching one.
So taking the first result will break the whole logic.

**Comment by foss-** [comment]
Attempt to verify the fix was not successful:
Fedilab 3.8.0
This is Friendica, version 2022.12-dev that is running at the web location https://pirati.ca. The database version is 1493/1493, the post update version is 1484/1484.

Interestingly pasting `https://pixelfed.social/p/dmitry84/502099555470608886` into tusky search brings up the post. However the post is reported multiple times which is unexpected:
<img src="https://user-images.githubusercontent.com/5708172/204520950-760e5c51-9f63-4d20-9cda-8bd4de027a6d.png" width="400">

Fedilab issue: https://codeberg.org/tom79/Fedilab/issues/559
