### ISSUE TITLE
Image grid shouldn't break image ordering

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#12433]
A new challenge for @MarekBenjamin

Source post: https://weirder.earth/@dzuk/109518363110905437
Friendica post: https://friendica.mrpetovan.com/display/6bbbc60c-61ece685e69e76cd-c4de1563

In this case the order of the images is important, so I think the image grid should preserve the order the images were posted in, no matter how they are reorganized in two columns.

**Comment by MarekBenjamin** [comment]
Thanks. Jep I get it, In this case there is actually totally zero benefit of starting with the landscape for representation at all. 

The general question for me is therefore: Do we want a "balancing" -  in terms of keep the height of both columns roughly equal -  at all?

**Comment by MrPetovan** [comment]
I don't think so. It worked well but if it's breaking the semantics of image orders, then I don't think it's desirable.

Although it's been working really well like in this example:
Source post: https://octodon.social/@kingu_platypus_gidora/109518487266371332
Friendica display: https://friendica.mrpetovan.com/display/3ad700c4-b980cd666539106d-3dba653b

This isn't the order the images were posted in, but it looks like it could still work with the original order, the images would have to be added alternatively in each column.

**Comment by MarekBenjamin** [comment]
I get the point and there ARE many cases where the columns are not balanced well like here:

https://friendica.mbbit.de/display/b25b9f4f-7163-62e6-d7ae-8fe333987436 (Hope you see the images because of https://github.com/friendica/friendica/issues/12412 ;-) )

I was not sure if altering the order for column height balancing would be accepted, so I did not put too much effort on it to further optimize it.

But in your example everything looks nice regarding **balancing** :
![Screenshot 2022-12-15 203343](https://user-images.githubusercontent.com/117765478/207950984-5446c31c-2c7a-4a73-ba6f-c5148948fd52.png)

That's not a counter-speech, I just want to fully understand the problem :-)

Two things we can do:

1. [ ] I remove the balancing completely for now
2. [ ] We discuss how we can assure some kind of height equilibrium for the image grid. For example: Mastodon uses a landscape section only from portrait images.

**Comment by MrPetovan** [comment]
I can see the images!

I don't think we can have balancing and respect the order of the original images. Best thing you can to is alternate pictures in first and second column.

**Comment by MarekBenjamin** [comment]
On the other hand, one can discuss what the order in a two column grid actually **is** at the end: First all images top to bottom in the left and the top to bottom in the right column, like in double column text, or "reading"  the images "row by row" like word on a single column page.

**Comment by MrPetovan** [comment]
With two columns of images, it's still the reading order that's prevalent, in the Occident left to right and only then top to bottom.

**Comment by MarekBenjamin** [comment]
From my background, it is also my intuition. Still, this is not a universal constant and therefore subjective to some extent.

But, nevertheless, I agree that processing the images in a different order than the user attached them feels a bit "bad". And I have to admit that I felt so already while implementing the current balancing. But at that time I thought "They are just attachments and I do not alter the order completely by chance" :-)

I add a PR without the balancing in a sec.
