### ISSUE TITLE
Modal instead of comment field

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#12448]
### Describe the feature you'd like

The resources in Friendica could be used better, if essential functions are united on one editor. Functions like previewing links, embedding images or videos can be used when creating a new post and also when commenting.

The user thus gets a better usability of the application. The development for editing and commenting can be concentrated in one place in the code. Functions are developed only once and are available centrally.

- The creation of a new contribution is done as before

Create comment.
- Clicking on the comment link opens the modal instead of the comment editor under a post.
- In the modal a reference to the commented post is created
  - Avatar of the commented person, if applicable name and time of the post
  - commented text
  - if necessary embedded images in the text will be hidden
  - longer texts will be collapsed after a defined length
- In addition to the comment text, links, images and videos can be embedded. Links are generated as previews in the same way as in the contribution editor.
- By sending the comment the user gets back to the original view. 
- The comment is attached to the commented content

The composer editor for longer texts (blog posts) should be preserved.

![Modal_Kommenrar](https://user-images.githubusercontent.com/44441246/208230731-af6b0a51-c855-47f9-92ce-870852cecbcb.png)

The composer editor for longer texts (blog posts) should be preserved.

**Comment by MrPetovan** [comment]
This is an interesting suggestion, however posts can be pretty tall, and the modal height is a sensitive resource because there's no scrolling intended. I'm not sure what the gain would be to reproduce a tall comment in the modal and having to scroll all the way down to the comment form. Additionally, one might want to double-check additional replies in a conversation, which is now obscured by the modal window.

For these reasons, I don't this this feature is warranted. Worse, under the laudable intent of reducing the number of different forms from 3 to 2, it actually requires a significant amount of work to reach this point, which heavily hedges any future benefit from the feature surface reduction.

**Comment by loma-one** [comment]
Thank you for the review. The intention was to enable functions like embedding links, images & videos in all editors without having to resort to BBCode. 
Currently it is still very uncomfortable.
Hence the consideration to bundle everything into one editor and offer it at the different links. 

However, if it means extra work, then I withdraw this idea

**Comment by MrPetovan** [comment]
I appreciate the intent, but most of these tasks wouldn't be much more expensive to tackle with the current 3 forms than if there were only 2.
