### ISSUE TITLE
Newly uploaded Images via /compose allways have the "visible only to yourself" permission

### ISSUE THREAD

**Issue by Raroun** [friendica/friendica#12764]
- [X ] I have searched open and closed issues for duplicates

### Bug Description

Images can not be accessed publicly, so the photos are not available to anyone but myself. 
This happens when you upload new Images from /compose and the post is public.

### Steps to Reproduce

1.  Create a public post via /compose
2.  Upload a new Image
3.  Put the image into the post

Actual Result:

The Image is only visible to yourself

Expected Result:

The Image should be accessable for everyone

Workaround:
If you go to the gallery, you can adjust the permission of the image to be available to everyone.

### Platform Info

Friendica Version: 

2023-3 dev

Friendica Source: 

PHP version: 8.1

SQL version: Mariadb 10.6

**Comment by utzer** [comment]
I got that bug as well, if anyone tells me what to grep for I will provide which ever log is helpful! But I guess in this case it is "just" a bug that can only be solved by looking in the code. 


> Workaround:
> If you go to the gallery, you can adjust the permission of the image to be available to everyone.

This is the important part, the photos are really set to be only visible to yourself. This is the permission of a newly uploaded photo:
![Screenshot_2023-02-02_11-02-55](https://user-images.githubusercontent.com/8361662/216294432-c3877cb2-52cb-4d0f-bf49-67955e307179.png)

**Comment by annando** [comment]
Does this happen to you as well, when you don't use `/compose`? And what about the API?

**Comment by Raroun** [comment]
i testet it with a user from my instance, @Fynh@friendica.opensocial.space.
It only happens in the composer.
Don´t know about the API, i don´t use it actually.

**Comment by loma-one** [comment]
https://github.com/friendica/friendica/issues/12412 #

**Comment by loma-one** [comment]
https://github.com/friendica/friendica/issues/12764

**Comment by utzer** [comment]
> Does this happen to you as well, when you don't use `/compose`? And what about the API?

Upload via Fedilab works fine, the photo is visible in the Post when opened in Incognito Window with web browser. That is regarding the API question.

**Comment by Raroun** [comment]
i would love to see this issue resolved.
It actually eating up all my spare time explaining users why their pictures aren´t visible. :(

**Comment by gbraad** [comment]
Related to: https://github.com/friendica/friendica/issues/12554
Permissions need to be explicitly set or made public by posting.

---

As [mentioned by @tobiasd](https://github.com/friendica/friendica/issues/12554#issuecomment-1366407041): _You can make all posted pictures accessible in your account settings, the "Security and Privacy" section and there you find an option called "Make all posted pictures accessible"._

**Comment by MrPetovan** [comment]
I started looked into it, and photos uploaded in the file browser have been restricted to the owner since June 2011. This means there is another piece of code that updates the permissions of images that end up embedded in public posts to allow their display.

This is my next investigation direction but not tonight, it's getting late.

**Comment by Raroun** [comment]
Just tested it again - looks like it won't happen only to /compose, but always when you upload a new Image in the file browser.
Existing Images kept their permission.

**Comment by ghost** [comment]
I can confirm

**Comment by MrPetovan** [comment]
I've now determined that the photo permissions aren't adjusted to the permissions of the post they are embedded in since https://github.com/friendica/friendica/commit/20a2cec0b0fdaf1056cc65fc99570f0bc7dbd91e.

The key method `Model\Photo::setPermissionFromBody` that used to be called whenever a non-preview post was submitted has now been moved behind a `if ($notify) {` condition in `Model\Item::insert` that doesn't have the same meaning at all. In fact, the `$notify` flag is almost never set and its default value of `0` prevents `Photo::setPermissionFromBody` from being called.

I'm not sure what `$notify` means so I'm reluctant to make any changes. @annando , can you please assist? I believe the condition should be removed altogether because we never reach this stage in case of a preview post, but I'm not sure about potential side-effects.

**Comment by MrPetovan** [comment]
Caused by https://github.com/friendica/friendica/pull/12644

**Comment by annando** [comment]
The `$notify` is set at several places and in fact is needed. But possibly we have to test here for `origin` instead. I have to investigate.

**Comment by MrPetovan** [comment]
Please Obi Wan Annando, you're our only hope.

**Comment by annando** [comment]
I so much want to combine Princess Leia with the face of your avatar ... :grin:
