### ISSUE TITLE
Indentation of comments is wrong, when only one answer exists

### ISSUE THREAD

**Issue by xundeenergie** [friendica/friendica#12857]
- [x] I have searched open and closed issues for duplicates

### Bug Description

If i create a first answer on a comment (indipendend of answer-level), the first and only answer is shown on the same answer-level as the parent.

When i create a second answer on the same comment, both answers are shown correct on the next answer-level.

### Steps to Reproduce

1.  Choose a thread with answers.
2.  Create an answer on a comment
3.  the answer is on the same level
4. create a second answer on the same comment
5. the new and the answer from before are shown on the next level.

Actual Result:
I created "Antwort sechs" as answer on "Antwort fünf", which is on level 3.
I expected "Antwort sechs" on level 4, but it is the same on level 3 with indentation for level 3.
![grafik](https://user-images.githubusercontent.com/5894829/222372160-d2899896-5a44-42b7-87dd-982b4506fadb.png)

Then i created another answer "Antwort sieben" on "Antwort fünf", so "Antwort fünf" has now two answers. Now "Antwort sechs" and "Antwort sieben" are shown correctly on level 4 with the correct indentation.

![grafik](https://user-images.githubusercontent.com/5894829/222372774-ea48c379-9731-4f0f-936b-02e1ca0cf6f6.png)

Expected Result:

If there exists only one Answer on a comment, i expect, that the indentation is one level more, than the parent. Shown correctly as answer in the thread.

### Screenshots

see in "actual behaviour"

### Platform Info

Friendica Version: 2023.01

Friendica Source:  github

PHP version: 8.1

SQL version: mariadb 10.5.18

**Comment by MrPetovan** [comment]
This is part of the Smart Threading feature to reduce the overall number of indentation levels. as a result, strings of parent -> child will be displayed the same as strings of direct children of a single parent.

We simplify

1. Parent
     1. Child
          1. Grand-Child
               1. Grand-Grand-Child

To

1. Parent
1. Child
1. Grand-Child
1. Grand-Grand-Child

Since it's functionally the same and reduces the needed width to display the conversation. It gets more complicated when any of the posts except the last child gets more than one reply but in essence this is what it does.

However, you can disable this behavior and revert to a strictly hierarchical display in Settings -> Display -> Content Settings -> Enable Smart Threading

**Comment by xundeenergie** [comment]
I deactivated this... 

![grafik](https://user-images.githubusercontent.com/5894829/222464313-6df8965f-e8f5-443f-9562-a47406819078.png)

but "neunte Antwort" is answer to "vierte Antwort"... and it should be one level higher. (one indentation more)

**Comment by xundeenergie** [comment]
Oh sorry... saving changed settings could be a good idea :)

![grafik](https://user-images.githubusercontent.com/5894829/222470015-2be3d2b3-e793-4990-acf7-dc7f11b3d683.png)

it works.
