### ISSUE TITLE
Wrong /api/v2/instance HTTP status code

### ISSUE THREAD

**Issue by xmflsct** [friendica/friendica#12881]
- [x] I have searched open and closed issues for duplicates

### Steps to Reproduce

1.  Check this API https://venera.social/api/v2/instance

Actual Result:

Returns error in content, but with 200 HTTP status code

Expected Result:

Should return error HTTP status code

Friendica Version: 2.8.0

This breaks https://github.com/tooot-app/app/issues/719

**Comment by MrPetovan** [comment]
Thank you for the report, the expected output for unimplemented API calls is the following:
```
{
  error: "API endpoint GET api/v2/instance is not implemented but might be in the future.",
  code: "501 Not Implemented",
  request: "api/v2/instance"
}
```
Along with a 501 HTTP response code.

I'm not sure how the following output from venera.social is even possible:
```
{
  error: "API endpoint GET api/v2/instance is not implemented",
  error_description: "The API endpoint is currently not implemented but might be in the future."
}
```

In any case, this particular endpoint has been implemented since version 2023.01 and will be released in version 2023.03.

**Comment by xmflsct** [comment]
Thanks for the swift response!

**Comment by ne20002** [comment]
In my instance (Friendica 2023.01) I get the same result on the api endpoint.

**Comment by MrPetovan** [comment]
The provided URL now outputs the expected data, is this enough to close this issue?

**Comment by xmflsct** [comment]
Sure thanks!
