### ISSUE TITLE
Enable "Endless scrolling" & "Stay local" instance-wide

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#13015]
### Is the feature request related to a problem? Please describe.
From my point of view, it would be useful to be able to activate the setting "Endless scrolling" and "stay local" instance-wide.

Most new users feel that Friendica does not support these features. This is due to the fact that these features are very difficult to find. Friendica seems unattractive with the current pre-installations, which leads to many users preferring other platforms.

### Describe the feature you'd like

It should be possible for the admin of an instance to globally activate "Endless Scrolling" and "Stay Local".

The user should still have the option to deactivate these functions.

### Additional context

New users feel irritated when Friendica does not behave in the same way as other applications in the Fediverse. Endloss Scrolling and Stay localis a matter of course for users and a de facto standard.

The lack of this de facto standard is attributed negatively to the application and leads to a negative user experience.

**Comment by dranii** [comment]
Not sure what this issue is about but if its about Endless scrolling, imho this breaks the UI for many persons.
At best it should be an administrative **option** for the instance where the site admin can choose from pagination and endless scroll. Endless scrolling or mindless scrolling d**oes not help** the users of my site if I am using an important footer area (help files links, contact, faq, security links, About etc etc) and also does not let the user remember a page where he saw an item he wants to come back. Many users stopped using G of GAFAM and shifted to other search or work-around ways to avoid infinite endless scroll in result pages. Some sites adapting it never means its a good UI comfort for _all._

Please have a look 
https://hackernoon.com/stop-infinite-scrolling-on-your-website-now-ie6rg31eu
https://www.quora.com/Why-is-infinite-scrolling-bad
https://www.reddit.com/r/web_design/comments/cgrscr/infinite_scrolling_is_awful_please_for_the_love/
https://www.reddit.com/r/programming/comments/9pkz50/stop_building_websites_with_infinite_scroll/
There are thousand other articles and actual user experience data.
If Endless scrolling has to be there, it should not be forced upon the end-user/site member like some sites do almost brutally in a dictator-like attitude. It should be a choice ! There can be two choices/options imho
- the site admin chooses normal useful pagination or mindless endless scroll
- the site admin has both and enables the user choose (and the site admin choose the default option to present to end-users)

**Comment by MrPetovan** [comment]
We have a feature in Friendica (called "Additional Features") where specific on/off settings can be in either of two modes:
- User-controllable, with a default state set by the admin.
- Admin-set with no user input.

That said I'm also against infinite scroll in Friendica in general at least because we aren't doing it right. For example there's no way to navigate directly to a specific part of the scroll, so if you navigate away from the network page, you can't pick up where you left using the browser's Back button.

Like many other legacy features in Friendica, the endless scroll feature has been done "just so" with little to no regard for general usability, and I'd rather we removed these features than keeping them in a lackluster state where we have to ask for forgiveness every time they are brought up in support requests.

**Comment by loma-one** [comment]
That would indeed be a step backwards if they removed this function. That would be the worst of all solutions.

What may not look good from a developer's point of view is a standard from a user's point of view that I would not want to think away.
Get it right if it's not well integrated so far, ok. As long as nothing should be removed. Removing an in-demand and effective solution by scrolling through the timeline would not be a good decision? 

An alternative would be for the function to be easier to find and for the user to be able to activate or deactivate it independently, as before. 

The first port of call for new users is the settings. However, the function is located under /settings/display. How would it be if there were a reference (e.g. in the form of a link to the "Content settings") under the settings?

**Comment by MrPetovan** [comment]
I'm sorry if I wasn't clear. From a developer's standpoint, we can say "Friendica has endless scrolling". From a user standpoint, it's iffier. No pagination (going back to a specific window in the scroll) is possible, and if there's a configured footer it becomes inaccessible.

For example I have disabled it on my production node as a user because it is extremely annoying alongside the iOS Add to Home Screen experience. When navigating back from any 3rd-party link in my timeline that opens a Safari modal window, iOS reloads the previous Friendica URL. With regular pagination, I can find the same page of posts, but with endless scroll enabled, it always goes back to the top of the timeline, which requires several seconds of scrolling to come back to the place I was at.

> Get it right if it's not well integrated so far, ok

Getting it right has a significant work price tag, so unless you are ready to pay yourself, you basically expect someone else to do it. And until someone does so, the half-feature stays around, which isn't ideal both from an image and a support standpoint. I'd rather have fewer features but done right instead of having to support a bunch of awkward features few people end up using.

In particular, setting switches have been used a a crutch for all those features that we haven't taken the time to make better. We have so many separate settings page, we can't expect users to figure out where every setting is supposed to be.

However, both improving existing features and reworking the settings carry a heavy work price, so removing half-hearted features becomes a cheap solution to "fix" the feature and "fix" the associated setting by removing both.

**Comment by loma-one** [comment]
It is precisely this function that is in demand by many new users. Therefore, I regularly refer to it and explain how it can be activated. It may be that they have the technical arguments on their side. From the users' point of view, that would not be the right answer.

Since Friendica has strong APP support and is prioritised by most users, it should be acceptable to keep the feature. Especially since it has been part of the application for many years.

I have just checked again that there have been virtually no reported problems with this function. It does not seem to cause any problems in the current version. Presumably, therefore, maintaining it should not require any effort.

I therefore withdraw the issues
