### ISSUE TITLE
Change icon to accept profile image from `person` to `checkmark`

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#13035]
**Reproduce**

1. open Profile > Edit Profile
2. Profile Actions > Change Profile Photo
3. select photo

**Currently**

The icon to accept the new profile photo is a person:
![1](https://user-images.githubusercontent.com/5708172/234271269-1b7e0855-5ba3-4187-9b4e-7b96ade5b4b9.png)

**Expected**

This is very misleading and difficult to understand. Why not use a checkmark instead? I got stuck at that step and had to hoover all icons to get an idea how to even proceed with this dialog.

**Comment by MrPetovan** [comment]
As discussed on Signal:

> This isn't a specific display for picking your profile picture, when you click on "Change my profile picture", it's just a link to your photo gallery.
> Which means you could come to the gallery with a completely different idea and the checkmark icon wouldn't make any sense anymore.

**Comment by MrPetovan** [comment]
A little bit more context for the closure of this specific: Yes, this person icon is confusing because it's part of the regular gallery/photo display. However, to get rid of this confusion, instead of this awkward icon we would need a bespoke picture picker to allow re-using an existing photo as a profile picture. This includes past profile pictures that are saved in the special folder "Profile Photos".

It is possible, but it is completely different from an icon change.
