### ISSUE TITLE
Photo page do not exist

### ISSUE THREAD

**Issue by matthiasmoritz** [friendica/friendica#13108]
```

Exception thrown in /var/www/friendica/src/Module/HTTPException/PageNotFound.php:49
Stack trace:
#0 /var/www/friendica/src/BaseModule.php(244): Friendica\Module\HTTPException\PageNotFound->content()
#1 /var/www/friendica/src/Module/HTTPException/PageNotFound.php(80): Friendica\BaseModule->run()
#2 /var/www/friendica/src/App.php(700): Friendica\Module\HTTPException\PageNotFound->run()
#3 /var/www/friendica/index.php(52): Friendica\App->runFrontend()
#4 {main}

```

![image](https://github.com/friendica/friendica/assets/1984982/37d7b459-4f87-4343-984e-5e2f63b99b1d)

![image](https://github.com/friendica/friendica/assets/1984982/3ad117d3-0024-41cc-8117-427a32722144)

**Comment by MrPetovan** [comment]
What's the URL to that page?

**Comment by davidspring** [comment]
For the record, I was getting the identical error.  It turned out to be because I forgot to set the Home Page URL. To set the Home Page URL, go to Main Menu, Settings, Profile, MISC and enter the URL for your log in page in the box called Home Page URL. Then click Save.  Then revisit the link with the error and the link should work properly with no error. I therefore do not think there is a bug. But I think it is essential rather than optional to set the Home Page URL... Is this correct or am I wrong about this?

**Comment by MrPetovan** [comment]
@davidspring I don't think the profile field you are mentioning has something to do with the originally reported error, however the German language interface is making it slightly harder for me to figure out what exact link is failing.

**Comment by AlfredSK** [comment]
It's "view photos" – https://example.com/contact/redir/123456/photos

**Comment by MrPetovan** [comment]
Huh, this link only shows in mobile version 😓
