### ISSUE TITLE
Can we make the mobile feed font a tad larger?

### ISSUE THREAD

**Issue by anubis2814** [friendica/friendica#13122]
On the mobile apps and websites for FB, twitter and mastodon, I can read their font with no issue, I have to put my glasses on for Friendica.  I was going to try and wait until I had mastered HTML and css enough to do it myself but it really is a pain.  No font size I play with has any impact.  My guess is its related to "inherit from html" just one size up would probably ben enough.  the desktop size is just fine.  If its pretty easy please tell me how you did it. Thanks.

**Comment by MrPetovan** [comment]
Can you please take a screenshot of your mobile feed and show where you'd like the font size to be bigger?

**Comment by anubis2814** [comment]
https://friendica.myportal.social/photo/128224523864618ddba654d414918539-0.jpg
You can't see it on the big screen but only on the phone.  You may just need to increase the font-weight or the font color which almost seems gray.  The size might be just fine but the font with the gray back color lack of contrast makes it hard to read.

**Comment by MrPetovan** [comment]
What are your theme settings? It looks like the page background color is too dark, which is let through too much by the opacity of the panel background. The font color is the same for you and me but a darker background reduces the contrast indeed. Please use a lighter page background color or increase the content background opacity.

**Comment by anubis2814** [comment]
I cranked the opacity up to 100%, still the same issue.Background still has a gray effect.and the fonts are either too small or too light

**Comment by anubis2814** [comment]
I turned off the background image to white.  Its a little better but still have some issues reading it.

**Comment by MrPetovan** [comment]
It's hard to comment without being able to witness the changes by myself, can you please paste your scheme string from your custom theme settings so that I can have the same values you are currently using?

![image](https://github.com/friendica/friendica/assets/925415/99d2927b-5705-4080-8c8a-319b8c169898)

**Comment by anubis2814** [comment]
{"nav_bg":"#302aa4","nav_icon_color":"#23c2df","link_color":"#6f1b6e","background_color":"#ffffff","background_image":"","contentbg_transp":"100"}

**Comment by MrPetovan** [comment]
Thanks. The font size is the same in mobile and desktop, but switching between the two modes from the developer console, I can see a quick downsizing of the font when I switch towards mobile, so it's possible that the "14px" font size doesn't mean the same actual size in desktop vs mobile. It would make sense as we generally use mobile screen closer to our eyes than the desktop screens.

I'm not sure what to do about this specifically.

**Comment by anubis2814** [comment]
Hmmm, just increasing the font-weight for mobile might help assuming you can do that.  It looks just fine on desktop as it is but something about that font comes off as grey on the phone.

**Comment by MrPetovan** [comment]
We might be able to decrease its brightness a tad without reaching the opposite negative effect of over-contrast.

**Comment by anubis2814** [comment]
Let me know what you figure out if you do. and how you did. I want to learn what I couldn't figure out.

**Comment by anubis2814** [comment]
So I went into /view/theme/frio/styles.php and $font_color is `#444444` which is a mid level grade grey so it wasn't the font it was the color.  $font_color_darker on the other hand is `#222222` 
I switched Font_color_darker to `#000000` and font_color to `#111111`   
I can see much more clearly on my phone screen now.
Let me know if this is an acceptable change and try it out and see if you think it looks bad.

**Comment by anubis2814** [comment]
PS if you are getting this via email, I changed some of the things in the post so its different now.

**Comment by davidspring** [comment]
Please do not take this as criticism or complaining. I think Friendica is our best chance for replacing the two headed monster of Twitter and Facebook. I am a retired college instructor and I intent to spend a good part of my retirement helping improve the appearance and usability of Friendica. For more than 20 years, I taught courses in CSS. For the past year, I have been working on improving the CSS of the default Frio theme – mainly to improve its readability. I am only making changes in the Frio style dot CSS file. In about a month, I will be sending you a proposed revision for your feedback. But since someone else brought up this issue, I would like to throw in my two cents on this subject. 
Partly because I am an older person, I now have trouble reading small font sizes. One of the things I did months ago was to increase the font size of almost everything by about 10%. Readability is a challenging problem because the appearance of any font size is dependent on the pixel ratio to screen width and height ratio. For example, a 12 point font will appear much bigger on a 15 inch screen than a 13 inch screen even though both have a 1920 by 1080 resolution. This is because the pixels are jammed closer together on the 13 inch screen compared to the 15 inch screen. Still, I think Friendica is better off having fonts appear slightly too large rather than slightly too small. 
As for font color, I have always maintained that #111 or #000 is much more readable than #444. So I am in favor of changing to a darker font. However, as long as this issue is being considered, I want to raise a more important question. I see the two variables shown on  /view/theme/frio/styles.php Line 211 and 212, $font_color is #444  $font_color_darker which is #222. 
The proposal is to change Line 211 and Line 212 to #111 and #000. 
However, my question is why do we even have lines 211 and 212 in styles.php in the first place? 
#444 is almost never readable. And there is almost no difference between #111 and #000. 
To see how this change affected the CSS file, I went through and found these selectors would be affected. I will post these selectors in my next post in case you want to look at them. Bottom Line is that darker font wins by at least a three to one margin. 
I therefore propose we delete these two lines in the style dot php file and simply change the CSS in style dot CSS Line 13 (body) to color: #111. This should allow us to eliminate a large number of color equals dark or light lines in the style dot CSS file. 
If folks want a different font color, they can do it in the Frio CSS file where each selector also let’s them know what the background color is for that selector.

**Comment by davidspring** [comment]
Here is a summary of the Frio CSS file font colors (which are not spelled out with an exact value): 
Here are lines with color: $font_color;
Line 13
body {
color: $font_color;
Line 1052
aside .widget,
.nav-container .widget {
	color: $font_color;
Line 1537
.fbrowser .breadcrumb > li:last-of-type a {
	color: $font_color;
Line 1636
/* Thread hover effects */
.desktop-view .wall-item-container .wall-item-content a,
.desktop-view .wall-item-name,
.desktop-view .wall-item-container .fakelink,
.desktop-view .toplevel_item .fakelink,
.desktop-view .toplevel_item .wall-item-container .wall-item-responses a {
	color: $font_color;
Line 2799
.event-card .event-card-content {
	color: $font_color;
Line 3633
.event-card .event-hover-location .location {
	color: $font_color;

Here are lines with color: $font_color_darker;
Line 732 
#topbar-first #nav-notifications-menu a {
	color: $font_color_darker;
Line 736
#topbar-first #nav-notifications-menu li.notif-entry {
	color: $font_color_darker;
Line 1038: 
#photo-edit-link-wrap {
	color: $font_color_darker;
Line 1092 
aside .widget li:hover,
aside .widget li.selected,
.nav-container .widget li:hover {
	color: $font_color_darker;
Line 1101
aside .widget li a,
aside .widget li a:hover {
	color: $font_color_darker;
Line 1278
#nav-short-info .contact-wrapper .media-heading a {
	color: $font_color_darker;
Line 1323 
.faded-icon {
	color: $font_color_darker;
Line 1328 
.faded-icon:hover {
	color: $font_color_darker;
Line 1418 
#jot-modal .modal-header a,
#jot-modal .modal-header .btn-link,
#profile-jot-submit-wrapper a,
#profile-jot-submit-wrapper .btn-link {
	color: $font_color_darker;
Line 1456
#preview_profile-jot-text,
.comment-edit-form .preview {
color: $font_color_darker;
Line 1566
.fbrowser .folders li:hover {
	color: $font_color_darker;
Line 1783 
.media .media-body h4.media-heading {
	color: $font_color_darker;
Line 1867
 .wall-item-body .body-attach > a {
	color: $font_color_darker;
Line 1871
.wall-item-body .body-attach > a div {
	color: $font_color_darker;
Line 1949
.wall-item-tags a {
	color: $font_color_darker;
Line 1971
.wall-item-actions a,
.wall-item-actions button {
	color: $font_color_darker;
Line 1991
.wall-item-actions button:hover {
	color: $font_color_darker;
Line 2146 
.textcomplete-item > a {
	color: $font_color_darker !important;
Line 2254
.dropdown-menu li a,
.dropdown-menu li .btn-link {
	color: $font_color_darker;
Line 2276
p.wall-item-announce,
.media .time,
.media .shared-time,
.media .delivery,
.media .location,
.media .location a {
	color: $font_color_darker;

Line 2324
.help-block {
	color: $font_color_darker;
Line 2370
#search-header-wrapper {
	color: $font_color_darker;

Line 2388
section > .generic-page-wrapper,
.videos-content-wrapper,
.suggest-content-wrapper,
.help-content-wrapper,
.match-content-wrapper,
.dirfind-content-wrapper,
.delegation-content-wrapper,
.notes-content-wrapper,
.message-content-wrapper,
.apps-content-wrapper,
#adminpage,
.delegate-content-wrapper,
.uexport-content-wrapper,
.dfrn_request-content-wrapper,
.friendica-content-wrapper,
.credits-content-wrapper,
.nogroup-content-wrapper,
.profperm-content-wrapper,
.invite-content-wrapper,
.tos-content-wrapper,
.fsuggest-content-wrapper {
	color: $font_color_darker;
Line 2500
.contact-entry-desc {
	color: $font_color_darker;
Line 2514 

.contact-wrapper .contact-action-link,
.contact-wrapper .contact-action-link:hover,
.textcomplete-item .contact-wrapper .contact-action-link {
	padding: 0 5px;
	color: $font_color_darker;

Line 2743
#event-nav a {
	color: $font_color_darker;
Line 2812
.event-card .event-card-title {
	font-size: 14px;
	color: $font_color_darker;
Line 2891
.photo-comment-wrapper .wall-item-content {
	color: $font_color_darker;
Line 3049
.intro-wrapper button.intro-action-link,
.intro-wrapper button.intro-action-link:hover {
	color: $font_color_darker;
Line 3104
.notif-item .notif-desc-wrapper a {
	color: $font_color_darker;
Line 3118
.search-content-wrapper > ul.viewcontact_wrapper {
	color: $font_color_darker;
Line 3598 
.fc .fc-event {
	color: $font_color_darker;

**Comment by anubis2814** [comment]
In the future, adding font color option to the customization in the display section may not be terrible, but at the same time its probably unnecessary as most colors aren't that great, unless we decide to add a font size changing option too later on.

**Comment by MrPetovan** [comment]
A few points:
- Asking "why" about the frio theme won't yield any answers, the original creator isn't active anymore.
- I don't mind simplifying the two frio font colors to one.
- I will never allow admin or users to customize it, though. Like you said most colors aren't great.

**Comment by anubis2814** [comment]
@davidspring I agree, Friendica can truely be the one ring to rule them all if we can make certain changes.

**Comment by anubis2814** [comment]
I feel like this was fixed and the font color was changed. We can close this one.
