### ISSUE TITLE
Display the Profile background picture in the Friendica profile page

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#13179]
### Is the feature request related to a problem? Please describe.

Friendica allows you to upload a banner image via compatible mobile apps. The image is displayed in other Fediverse apps on the profile.
I would like the banner image that is uploaded and embedded via an mobile apps to be displayed in the profile view.
If necessary, the upload of the banner image is also supported directly via the Friendica web app.

Example
![2023-05-30_14-26](https://github.com/friendica/friendica/assets/44441246/076f9d93-e58c-43f9-948a-58ddeddb3013)

**Comment by MrPetovan** [comment]
This is a thorny design issue at least in the frio theme. By committing to a two-columns design with the account vcard in the left column, it doesn't allow for the common banner integration with the profile picture overlapping like on Mastodon, Tumblr, Twitter and Facebook.

This disconnect with the profile picture makes the banner integration pretty awkward as it will take a pretty sizable space on the page without providing the usual profile picture decoration.

**Comment by davidspring** [comment]
I agree that the banner is a big problem with the Frio theme. However, the banner is much less of a problem with the Vier theme. Just a few lines of CSS and the problem was solved. Wanting a banner to display on all Friendica pages was one of several reasons why I moved from the Frio theme to the Vier theme. Vier is also easier for me to work with because it is only 1MB versus Frio which is 11MB.

**Comment by loma-one** [comment]
I don't know where the two-column design starts. The banner image can also fit just below the template title. 
![2023-05-30_14-26](https://github.com/friendica/friendica/assets/44441246/38f46ee8-3b30-4089-a7f9-e42413c59939)

**Comment by MrPetovan** [comment]
You can see it on your screenshot, there's a left column with your profile vcard, and there's the main content column on the right. It is possible to put the banner where you put it, but it just takes space instead of serving as coherent decoration for your profile picture like on most other social media platforms.

**Comment by loma-one** [comment]
That is correct. But I wouldn't describe it as something that takes up space. The goal is to get the banner to display :) 
I would not have expected a decorative form here and personally don't like it that much.

**Comment by davidspring** [comment]
There is more to placing the banner because several elements have absolute positioning. You can get full width for the banner by using CSS to drop the aside a defined amount. You also need to drop the top nav bar and drop the tab bar by different amounts. There is also the Site Home Page to deal with and a log back in page as well as other pages. Then you need to define a different set of parameters for your mobile view.  I understand you may only want the image to appear on your profile page. But that does not appear to me to be easily accomplished using the way Friendica and Frio are coded. For example, I wanted to delete the left aside – but only on the site home page. I was not able to do this because Friendica seems to use the same layout for all pages. I was eventually able to use some graphic tricks to hide the left aside on the Site Home page – but it was not easy. Even then, it only worked with the Vier theme and not the Frio theme.

**Comment by davidspring** [comment]
On Line 64 of the file /static/settings.config.php, for setting the banner path, it states: 

**// HTML snippet of the top navigation banner. Not supported by frio.**

This could be why I could not get Frio to work with my banner. Thankfully, Vier is much easier to work with.  It will still be a problem for what you want however. I am not clear about how to do what you want given the current structure of Friendica.

**Comment by tobiasd** [comment]
> I agree that the banner is a big problem with the Frio theme. However, the banner is much less of a problem with the Vier theme. Just a few lines of CSS and the problem was solved. Wanting a banner to display on all Friendica pages was one of several reasons why I moved from the Frio theme to the Vier theme. Vier is also easier for me to work with because it is only 1MB versus Frio which is 11MB.

Are those changes already included in the core repository of Friendica?

Ah forget about the question ;-) I just realise that the term "banner image" is used in different contexts in this discussion I think. The one is the node wide image admins can set (except in Frio theme) and the other is a profile background image that users can set on a personal level.

**Comment by davidspring** [comment]
Good point. I agree that users should be able to set their own background images for their profile pages. I will try to work on that project for the Vier theme in the coming months. What I have been working on for the past few months and will submit for approval in about a week is a way for admins to set the site banner image which will display at the top of all pages. This will be a new theme as there were a lot of changes I made to the Vier theme. It will be up to the Friendica leaders if they want to accept the new theme into the core. They might also decide to adopt just some of the changes and add them to the Vier theme. In addition, if you want to try out the new theme, I will have a package available as a free download. It is under the GPL3 License like everything else in Friendica so you will be able to modify it however you want and I will be providing instructions on how to modify it. I am still about a week out in terms of finishing it because their is still a lot of work to be done. It will have four different color variations.

**Comment by davidspring** [comment]
By the way, I have been thinking about how to get a different custom banner image for each of the page types so that you can have one banner image on the Site Home Page, another on the Member Profile page and a third on the Network page. It would require different layout templates for the various pages and also some additional CSS in the default php file. I think it can be done. But there are a lot of other things that need doing first. So it will likely be months before anything happens on the Member Banner issue. But you can still submit it as a feature request just to get the ball rolling. I am sure others would also be interested in this feature to make Friendica more like Facebook.

**Comment by loma-one** [comment]
@tobiasd 
Thank you for the correction. That is exactly what is meant. 
The headline has been changed accordingly.
I understood that it is not easy. Nevertheless, thank you for the discussion.

**Comment by MrPetovan** [comment]
I believe the original title was more accurate. The term "banner picture" is used across a variety of platform, while "background image" is more often related to themes.

**Comment by davidspring** [comment]
I have been able to come up with a way for members to choose one of four banner images by selecting a theme variant. It is not as good as letting them upload their own profile banner image. But it is a step in the right direction. I should be able to submit the new theme in about a week.

**Comment by MrPetovan** [comment]
Now, if it's part of a theme it should be called a background image. This option is already offered to frio theme users if they choose custom theme settings instead of the pre-existing variants. See screenshot of my theme settings:
![2023-05-31 06 56 18 friendica mrpetovan com 48927332bf1b](https://github.com/friendica/friendica/assets/925415/28afe2b7-57b2-4795-aa7e-900d99eba1e9)
(The full page capture feature doesn't support fixed background images)

**Comment by davidspring** [comment]
I understand Frio offers a page background image option. However, I think what the OP wants is a customizable banner image or header image at the top of the page above the menu rather than a background image behind the posts. The new theme I will be submitting next week has the option for 4 different page background images with matching header banner background images and addon side panel background images - all of which can display not only on the logged in member pages but also on the logged out pages. In addition, it is not using an outdated version of bootstrap and it is only 1MB file size rather than the 11 MB for Frio.

**Comment by MrPetovan** [comment]
We aren't talking about the same thing. @loma-one is talking about the profile banner picture that most other social networking platform offer as a profile setting like in Mastodon (see after), Twitter, Facebook, Tumblr, etc...
![2023-05-31 07 22 13 mastodon social 857f3812b94a](https://github.com/friendica/friendica/assets/925415/f2abe821-f13d-4167-b2d0-ddd873e1b2b5)
Currently, we do support setting this banner picture from the API, which means it's only accessible from Mastodon-compatible mobile clients. This in turn allows Friendica profiles to be displayed with a custom banner picture in the relevant Mastodon pages. However so far there isn't a way to set or display this image in the Friendica UI itself and this is what this issue is about.

**Comment by tek-aevl** [comment]
So, you can sort of cheat to do this by pinning a photo post on your profile, available after clicking the more option on a post.

**Comment by loma-one** [comment]
@tek-aevl It is not a matter of cheating, but of executing an action that deposits such a profile banner image for external instances (independent of an external APP).

**Comment by loma-one** [comment]
I have noticed that in Friendica the two column concept is broken. This happens, for example, in the contact view.
So there seem to be technical solutions that enable the integration of content.
![2023-07-14_11-42](https://github.com/friendica/friendica/assets/44441246/83de013a-19c9-4c92-a6bd-7e912b96c8ad)

**Comment by loma-one** [comment]
No change is currently being considered. Therefore closed here.

**Comment by foss-** [comment]
This can always be added. A banner on top of the profile isn't rocket science. Why not keep it open? The back-end functionality itself is already in place.

**Comment by strk** [comment]
may I ask which Mastodon application allows you to upload a profile banner on a Friendica account ? I'd like to add a banner to an account of mine...

**Comment by foss-** [comment]
Pachli does on Android, I think most should cover this functionality.

**Comment by Copiis** [comment]
Fedilab, Tusky

**Comment by MrPetovan** [comment]
> This can always be added. A banner on top of the profile isn't rocket science. Why not keep it open? The back-end functionality itself is already in place.

I realized I didn't address this: Displaying an image is easy, but it currently doesn't fit in either Friendica themes. It would require heavy redesign work which definitely is rocket science for most of us here.
