### ISSUE TITLE
Set Vier back to being the default system theme

### ISSUE THREAD

**Issue by davidspring** [friendica/friendica#13209]
I am trying to reduce the file size of Friendica. I am using the Vier theme and therefore do not need the Frio theme. I could save 11MB on the Friendica installation file by deleting the Frio theme (which is 11 MB while Vier is only 1 MB). However, when I delete the Frio theme, and then install a new version of Friendica, while Vier is now set for the system theme, for some reason, Friendica does not apply the Vier theme until after I log in and go to Admin, Site, General Information and click the Save Settings button. 

A few years ago, Vier was the default system theme and Frio was an additional theme. So I know it is possible to have Vier be the default theme. I spent the past week trying to make this change. I downloaded a version of Friendica from 2018 (when Vier was default) and compared it to the current version of Friendica (2023 May). I looked closely at all of the Vier theme files and Frio theme files but I could not find where to roll Friendica back to having Vier be the default system theme. 

Any tips or steps you could provide to help me make this happen would be greatly appreciated.

**Comment by MrPetovan** [comment]
The themes your node allows users to set and the default theme are listed in the `system.allowed_themes` and `system.theme` setting values. Their default value in new nodes are set in the following places:
https://github.com/friendica/friendica/blob/d0b8d78cad8e8defe1799b9a674bc49f7c58f9a1/static/settings.config.php#L59-L61

https://github.com/friendica/friendica/blob/d0b8d78cad8e8defe1799b9a674bc49f7c58f9a1/static/settings.config.php#L203-L205

If you just want vier without having to set this in the admin, you can manually change these values to just `'vier'`. However these changes will be lost when you upgrade your node, so I recommend still doing it from the Admin Settings page since it will be carried over during upgrades.

**Comment by davidspring** [comment]
Thanks. I am aware of Line 61 in static/settings.config.php. And I had changed the allowed_themes from frio, vier to just vier. This did set vier as the system theme. However, when I then created a test site, and logged in for the first time as admin, the vier theme was not active. The page was completely unstyled with a horizontal menu on the top. I clicked on Admin in the horizontal menu which then switched to a side menu where I clicked on Site. I could then see that vier was set as the system theme. But vier only took effect after I clicked the Save Settings button. 

For some reason I have not been able to figure out, Vier is not active even when it is the only option. I know that Vier used to be the active system theme. There must be some way of making it the active system theme and I am wondering what files in the past made Vier the active theme and what changes were made in what files to switch from Vier being the initial active to Frio being the initial active theme. 

The reason I want to reduce the Friendica file size is because I am a teacher working with students who have very limited space on the server. When one takes into account backups and other data, plus the fact that Friendica is only one of several open source PHP based applications I am introducing students to, I need to do everything I can to keep the file size of Friendica as low as possible. 

Any tips or steps or directions on what happened to change the active initial theme from Vier to Frio would be greatly appreciated.

**Comment by MrPetovan** [comment]
I have identified the other settings value that governs the currently selected theme. I have updated my former reply to this effect, please check it out.

A word about disk space, though, Friendica isn’t meant to be a lightweight application. We store a large amount of data from local and remote places like contacts, posts and especially images. These will quickly dwarf the 11 MB you would save from physically removing the frio theme which makes the measure somewhat pointless.

For reference, my single-user node I’ve been running since 2016 has a disk space footprint of 15GB and counting.

**Comment by foss-** [comment]
Can this be closed? I don't see vier being the default for friendica anytime soon. Users interested in this can always thumbs up the request - even in closed state.
