### ISSUE TITLE
Create a new boilerplate, simplified theme

### ISSUE THREAD

**Issue by vinzv** [friendica/friendica#13322]
### Is the feature request related to a problem? Please describe.

I tried to wrap my head around F's theming a few times in the past. With pretty little outcome, tbh. Frio seems to be fine for many node admins. But if you want to build something really custom for your node not to look like all the others, chances are high you get lost somewhere with your feet deep in CSS, JS and Smarty stuff. :-)

### Describe the feature you'd like

My idea is *not* to replace either Vier or Frio at all. I do not intend to break known looks and behavior. What I do want to build is a theme with two aspects:

1. Major goal: Create a all new theme
Friendica has always been a mighty tool with lots of features. Many more than GNU Social or it's successors. I'm aware there are different use cases and Friendica serves them quite well. Still quite a few features are either dated or intimidating - or just unnecessary (looking at you, calendar). So with another theme besides the existing ones, this could offer a simplified UI and reduce the visual clutter to put the feed content at focus for users. Think of it in a way of newbie vs. expert view modes many complex programs offer.

2. Minor goal: Give other theme designers some bare bones
I always wondered why there are so few _really_ different themes for Friendica. So as a side product, having a very simplified file and design structure could attract others to start their on themes based on this one as well. Being a bonus for the overall project, I assume.

### Additional context

I dribbled a few conceptual (not designed!) mockups on how I would like to see the primary pages of Friendica. Nothing polished or even finished, but as a boilerplate to get discussions and even work started.

#### Feed view
![konzept_grundgeruest](https://github.com/friendica/friendica/assets/74432/46dd5217-839e-4a48-ae16-4bb17ab01a1b)

#### Post composing view
![konzept_grundgeruest2](https://github.com/friendica/friendica/assets/74432/c1b27bf1-5a2f-4c51-9f2b-dcfca3bcc73f)

#### "hidden" Features Menu
![konzept_grundgeruest3](https://github.com/friendica/friendica/assets/74432/16d965ec-67ab-4734-aca6-e2a8a0389707)

And the same for mobile devices:

#### Feed view
![konzept_grundgeruest_mobil](https://github.com/friendica/friendica/assets/74432/fa911fd0-40bf-4c89-a9c1-3dcecbb34dea)

#### Post composing view
![konzept_grundgeruest_mobil2](https://github.com/friendica/friendica/assets/74432/38718e82-e5bc-4b24-b694-4498ca2b72e3)

#### "hidden" Features Menu
![konzept_grundgeruest_mobil3](https://github.com/friendica/friendica/assets/74432/190a93fe-bd25-44f2-812e-8ca5e21b82b3)

**Comment by MrPetovan** [comment]
Thank you for your work! A word of warning for anyone interesting in creating a new theme from scratch. There are currently 260 templates files declared in Friendica. These templates were created with a specific design in mind and the template variables set by the PHP modules have been tailored to that end.

This means that creating a theme that would not match the same intent requires extra work, either with workarounds or by editing the PHP module output and checking it still works in the two remaining supported themes. For example, the frio theme makes heavy use of the former and its original creator isn't around anymore, hopefully for different reasons, but I can't help to think it had to do with how difficult it was to create a new Friendica theme with different design decisions.

**Comment by foss-** [comment]
While attempts to start from scratch are likely motivated by the best intentions, in practice I believe, time is better invested in improving frio.

The amount of work required to make a theme usable is insane and then there is the aspect, that a theme needs active maintenance to keep up with changes. This is already an issue with frio (current default). Thanks to the work of @MrPetovan frio is usable and received many important improvements. But I also know he is not doing that work because he enjoys tinkering with frontend. So since there is so much room for improving frio, I'd rather see that optimized than having yet another unmaintained third theme which is half functional.

Personally I like what tio did for https://trom.tf/social/. However that theme never was send upstream.

> I always wondered why there are so few really different themes for Friendica.

The simple answer is, because no one is willing to do the work to make a theme functional and usable and keep it functional over time. And I am not saying that is an easy task, quite the opposite and I understand, people are hesitant to commit to such a task. And as MrPetovan mentioned, Rabuzarus (frio creator) no longer is working on frio.

On the danger of repeating myself: if you want to improve friendica theme / UI, consider improving frio. Your work will be seen by a majority of all friendica users and have big impact. And I don't see core devs hesitant to pick up good proposals. The changes how images are displayed by @MarekBenjamin (https://github.com/friendica/friendica/pull/12334) or improvements around spacing of frio UI elements by @damianwajer (https://github.com/friendica/friendica/pull/12836) or the added image upload by @xundeenergie (https://github.com/friendica/friendica/pull/12883) were fairly minor but had huge impact and tremendously improved usability. There are many more contributors I forgot to mention, but this is three recent examples of much needed improvements with big impact greatly improving the default theme. I think that is the way forward.

**Comment by vinzv** [comment]
Alright, while this is not encouraging for my particular idea I complete understand the reasons. I'll close this issue as it does not make sense and most likely would only distract others.
Thank you both for your detailed thoughts and explanations!

**Comment by annando** [comment]
Concerning new themes, I think we should completely rebuild the whole frontend and not only write some new templates.

**Comment by MrPetovan** [comment]
I would like to be involved in the conversation when you decide to start this project.

**Comment by annando** [comment]
The only thing that I can provide for that task is the backend. My plan is to check if the API is sufficient already or if we have to improve it. And then at some later point in time, someone else can create some great frontend.
