### ISSUE TITLE
Real name (username) is used instead of displayname (nickname) for posts of users and under moderation /users 

### ISSUE THREAD

**Issue by Raroun** [friendica/friendica#13332]
- [X] I have searched open and closed issues for duplicates

### Steps to Reproduce

1.  Switch do devlop branch
2.  do a 'git pull'

Actual Result:

The real names of the users are used as display name.
Both in Posts, and under / Moderation / Users.
As it seems, the field "username" and not "nickname" is pulled from the database.
It doesn't affect all users either, some still show the nickname under moderation / users.
I think it's because those users haven't looged in since the change.

i assume this was introduced somewhere around this merged pull request:

[#13328](https://github.com/friendica/friendica/commit/bf2c19b2e04031604c4a007f16fc7b2ba3c80137)

Expected Result:

Don´t show 'username' aka real name.

### Platform Info

Friendica Version:
2023-09.dev, latest commit
Friendica Source: from github
PHP version: 8.0 
SQL version: 10.5

**Comment by AlfredSK** [comment]
I think we always used the full name in mentions and in the user list.

**Comment by Raroun** [comment]
The database field "nickname" from the table "user" was used for posts and in the user list.
Now the field "username" from the table "user" is used which - in the worst case - is now the real first name and surname.
I had like 6 users already complain about it.

**Comment by MrPetovan** [comment]
I thought the `user.nickname` field was the username part of username@domain.tld. 🤔

**Comment by Raroun** [comment]
Sorry for the confusion - but it is confusing.
i mean the database field `user.username` which is apparently the displayed name on posts.
In the gui under `preferences / account / basic settings` it is called `Full Name`.
Somehow the displayed name in threads of some users and in private messages were changed to the value of `user.username` aka `Full Name`.
😵‍💫

**Comment by MrPetovan** [comment]
Yes, the `user.username` should be used as a display name. When we retired the multi-profile feature, we unfortunately kept a duplicate display name field in the `profile` table. Both the user and profile field should be the same but due to a leftover bug, only the profile table field was used and the Settings -> Full Name field was silently ignored.

My plan is to retire the `profile` field but not before migrating its last value to override the so-called “Full Name” value in the `user` table which has never been used as an official name field despite the misleading form field name.

**Comment by AlfredSK** [comment]
> ...a duplicate display name field in the profile table. Both the user and profile field should be the same but due to a leftover bug...

Ah! Yes. While trying to find out what this issue is about I stumbled over the two possibilities to set a name.

A) settings -> account -> basic information -> full name
B) profile -> edit profile -> display name

In current stable I can change both and the display name (B) is used as the name of the user in the UI.
In current develop I can't change the profile display name (B) and the full name (A) is used in the UI 

I guess that's the reason for the confusion. 🙂
