### ISSUE TITLE
[frio] Exceptions page display is broken on home page

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#13333]
**Currently**

<img width="1282" alt="1" src="https://github.com/friendica/friendica/assets/5708172/f79cb941-2c37-45f9-a231-5f8648c4e2e5">

**Expected**

Top maintenance text should use different color to improve readability.

**Comment by MrPetovan** [comment]
~~It’s just missing a content wrapper element.~~

Edit: This is specifically about the home page, the wrapper is present on other pages and the display is correct.

**Comment by Raroun** [comment]
I know this is some kind of ugly, but would this be acceptable?

The template used is the exception.tpl, so i can´t change the font color without messing up the exceptions - so i change the background color to white, which doesnt interfere with the other exceptions..

![image](https://github.com/friendica/friendica/assets/10846157/8e025605-d40c-4c10-97f3-f6756868afc2)

**Comment by MrPetovan** [comment]
How did you set up the background image? In your custom theme settings? When I do it y user theme settings are ignored when I hit the "System down for maintenance" page.

**Comment by Raroun** [comment]
I didn´t change anything except the BG-color in the  `/* Exception page */` Section in `/view/global.css`
The Background Image is only added at the document root domain

like here:
[https://dev.opensocial.space](https://dev.opensocial.space)

if you open another site like
[https://dev.opensocial.space/community](https://dev.opensocial.space/community)

The background image is not added. Seems like this is the standard behavior.

The grey front color is ok for every other exception, but the document root of the webserver uses the background image so i added a white background. This doesn´t interfere with the other exceptions because all the exception i saw are already on white background.

**Comment by MrPetovan** [comment]
Oh, it's for the home page I don't get to see on my single-user instance, it redirects automatically to my profile.
