### ISSUE TITLE
[frio] Display enabled / disabled "reshare" icon in interactions (rather than removing it)

### ISSUE THREAD

**Issue by kr428** [friendica/friendica#13615]
With the current changes to Frio interactions bar in 2023.09-rc, this has an ... interesting behaviour now:

Interactions for "public posts":

![image](https://github.com/friendica/friendica/assets/685879/ac62655e-b1b7-4e96-86d4-f8045be96aa5)

Interactions for "private posts":

![image](https://github.com/friendica/friendica/assets/685879/211b965a-893c-40e2-861c-eb0de419f541)

For posts one isn't allowed to reshare, the menu bar "rearranges", with the "Like" button moving to where the "Quote-share" button is for most other posts. That's a somewhat minor issue but it feels a bit unexpected. Would it be possible to, for posts that may not be re-shared, either 

- just "hide" the sharing-related buttons but leave the "Like" buttons where it usually is, or
- leave the sharing buttons in place and visualize that they aren't active for this post?

In Mastodon, this looks like that ...

![image](https://github.com/friendica/friendica/assets/685879/89055d9f-a271-409e-8572-8da7c6944a3f)

... and this doesn't feel all too off as it prevents layout changes and makes "missing features" a bit more explicit. 🙂

**Comment by MrPetovan** [comment]
I would prefer a disabled state with a tooltip explaining why it's disabled.

**Comment by annando** [comment]
Do we want to show all possible actions? I did some quick tests:

Here is an event:
![grafik](https://github.com/friendica/friendica/assets/844208/9d9b460c-6c54-4af3-9d4f-1413599ced5e)

A regular ActivityPub post:
![grafik](https://github.com/friendica/friendica/assets/844208/4f471064-6a50-44b7-967a-d76733f0e57d)

A RSS/Atom feed entry:
![grafik](https://github.com/friendica/friendica/assets/844208/91a592e9-24c3-42a7-b367-49f9d5b51aca)

**Comment by MrPetovan** [comment]
This looks pretty cool! Although I believe attendance buttons should still be grouped closer together.

**Comment by annando** [comment]
I don't think that it looks good, having different spacing here. But I guess that we have to experiment a little bit. At least it doesn't look like we have got space issues. Even when the column is really narrow, it seems to work:
![grafik](https://github.com/friendica/friendica/assets/844208/0d1e5271-be75-4c6f-8c06-26e1c14f1b72)

**Comment by foss-** [comment]
Not a fan of adding more icons. This looks overwhelming to my eyes and I have not missed the "new" icons. I see them on pirati.ca but since they still lack a tooltip I can't say what they do.

@annando  if you are playing with the icons, could you tweak the checkbox tooltip from `Select` to `Remove locally`?

**Comment by annando** [comment]
pirati.ca is currently in some "mock up" state, concerning the buttons. I guess that this evening I can do it right.

**Comment by MrPetovan** [comment]
> I don't think that it looks good, having different spacing here.

Normally I'd agree but in my mind the attendance buttons are meant to be one feature, not three features separated by the regular spacing.

**Comment by annando** [comment]
With the numbers it doesn't look so nice, I think:
![grafik](https://github.com/friendica/friendica/assets/844208/3b3c51b6-8359-4154-955f-53cbf3393d86)

**Comment by MrPetovan** [comment]
Oh I remember we had this conversation before (probably more than once). I don't have a problem with this particular display, I believe it's the right grouping.

**Comment by loma-one** [comment]
I assume that all possible statuses are displayed here so that you can get an overview. 

It would be too much for me to see so many icons in production if they don't make any sense.
I therefore assume that posts only show the interaction options for posts and calendar posts also show actions such as approval, rejection, etc.

---

Thank you for only showing the icons that are relevant in context. 
However, I still have a problem with the colouring of the non-functional icons. I wouldn't have expected dark colours here, just a light grey. 

![2023-11-07_23-20](https://github.com/friendica/friendica/assets/44441246/fb1ecb9c-0f1d-461c-9655-f6bc047fcc92)

**Comment by MrPetovan** [comment]
Please clear your browser's cache, there are CSS changes in the latest PR.

**Comment by loma-one** [comment]
CTRL+F5, clear browser cache manually. 
Tested with different browsers (firefox, brave, konqueror) on different computers. No change.
Inactive buttons have a black border. 

![2023-11-08_07-02](https://github.com/friendica/friendica/assets/44441246/b5c36715-86e5-47aa-a5a9-11d1a3ca4fe1)

**Comment by annando** [comment]
Which colour settings do you use?

**Comment by loma-one** [comment]
for the test: akzentuiert > hell
I also notice that when Server Config 'emoji_activities' => false is set, no more likes, dislikes, etc. are displayed. The clickable profiles are no longer available.

Image was liked - after 2 minute
![grafik](https://github.com/friendica/friendica/assets/44441246/a04abf19-529b-4248-affc-28207c7a4df7)

**Comment by annando** [comment]
"emoji_activities" isn't active any more. That "not updating after liking" is an unrelated issue.

**Comment by loma-one** [comment]
Oh, I had reactivated it after receiving many complaints. The users are missing a clickable link instead of the MouseOver.

---

After a reboot the likes, no likes are available again. 'emoji_activities' => false, should be removed in the config, if I have understood it correctly.

---

The new Config value is `'legacy_activities' => true,`
By setting the new config value, the icons are displayed correctly
![grafik](https://github.com/friendica/friendica/assets/44441246/0f747ec1-3775-456a-ad73-b6a33673d7a8)

**Comment by kr428** [comment]
> Oh, I had reactivated it after receiving many complaints. The users are missing a clickable link instead of the MouseOver.
> 

I'm on the same page with this. Generally speaking, the mouseover has two issues for my personal use cases: I'm not able to navigate into a contact profile this way anymore, and, worse, mouseover itself doesn't seem to have any meaningful counterpart on mobile devices.

**Comment by loma-one** [comment]
@kr428 please look again on your profile. It should fit like this

**Comment by kr428** [comment]
> @kr428 please look again on your profile. It should fit like this

Yes, confirmed. Thanks. :)

**Comment by foss-** [comment]
Mouseover on mobile issue: https://github.com/friendica/friendica/issues/13620

**Comment by MrPetovan** [comment]
Closed by https://github.com/friendica/friendica/pull/13618
