### ISSUE TITLE
[frio] Combine Link to Source with Platform icon in post view

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#13624]
The recent effort to improve the post view was an overdue and welcome change. Such changes will always be controversial as any UI change is. But whatever your stance on the change is, arguably the overall look is a lot cleaner now.

Which made me think about the `Link to source` UI.

**Currently**
`Link to source` is located in the top right of each post / comment and consists of the network icon (non-interactive) and a link icon (actual link to source).
<img src="https://github.com/friendica/friendica/assets/5708172/a69cb597-8e29-4df3-a339-1fade8ce851e" width="350">

**Expected**
This proposes to
- move the network icon to the left
- make the network icon interactive and link to source
- remove the link icon
- move the post info icon (public / not-listed / ...) to the second row

resulting in a less cluttered UI. Having elements to interact with in evry corner of the post is not great UX.
<img src="https://github.com/friendica/friendica/assets/5708172/d9a9d62a-f187-490d-8705-293fdb2d7505" width="350">

**Comment by MrPetovan** [comment]
I don't think the external link to the post should be tied with the display name of the author. The display name already is a link to the local or remote profile, so having a dangling icon linking to a completely different page is unwelcome. Additionally, the variable width of the display names makes it harder to spot at a glance what platform the post originated from compared to the current fixed position.

Maybe we can combine the Link to Source and Platform icon but moving it to the left is a step too far in my opinion.

Otherwise, I agree with the other suggested change, moving the post publicity information on the second row.

**Comment by foss-** [comment]
Would have to see this. Both changes you propose would improve post UI I think. You got some valid points there about keeping the platform icon in the top right corner.

**Comment by Raroun** [comment]
I would like to see this feature as described by MrPetovan.
 - Remove top right "link to source"
 - Add the link from "link to source" to the Network-Indicator
 - move post publicity Information to the second row.
 
I wild do this - but not before Monday (im a little bit busy the next 2 days.)

**Comment by Raroun** [comment]
@annando 
This happens because i set the "fakelink" attribute to the Icons.
Otherwise they would be underlined and allways hilighted, which doesn´t look good.
There are some browsers like Safari which are ignoring the fakelink attribute tho.
