### ISSUE TITLE
Threads: Selective instance filter for the public timeline

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#13725]
### Is the feature request related to a problem? Please describe.

With the entry of threads into the Fediverse, I suspect that posts from threads will quickly dominate the public timeline. One option is to lock threads for the instance. However, this would mean that no contacts can be followed.

It would therefore be an advantage if the instance operator is able to selectively influence the public timeline. 
It is conceivable that there is a quantity limit (x posts per hour), or that threads are completely hidden.

The result should be transparent for all users on the instance. 

This should not affect the personal timeline of users who may be in contact with threaded users.

I know that this idea can be controversial. So please feel free to make further suggestions. I see potentially 10 - 100 million users, compared to 1.8 million users.

### Describe the feature you'd like

Give the instance operator the option to filter thread content
- x posts per h
- Discard threads posts for the public timeline
- Customise the optional message in the public timeline. 

Today: This community page shows all public posts that have been received on this node. The content does not necessarily reflect the opinion of the users of this server.

**Comment by ne20002** [comment]
Actually an instance will (hopefully) not be flooded with posts from Threads. It will receive posts from accounts that are followed by your users. And also replies on those posts.
It's the idea that all this (if it is public) is shown in the public timeline.
As long as Thread is not adding advertising or otherwise manipulates the posts I see threads.net as a compliant but big fediverse instance.
I'm more curious about if Threads will use data received from the fediverse for building profiles as this, I assume, is illegal by GDPR due to missing consent from fediverse users.

But a bit more filtering on the timelines may be helpful. More a user thing than an instance thing.

**Comment by loma-one** [comment]
@ne20002 
With the public timeline, a contact is sufficient to establish a connection to a remote server. As a result, their posts are listed in the **public timeline**. 

This is not about the personal timeline or the timeline of the instance.
Please correct me if I am wrong about this.

My idea also goes in the direction of being able to protect an instance from overload. It's hard to imagine if a post goes viral and tens of thousands of likes per minute have to be processed by the instance.

Limiting data traffic can be very helpful here. 
Threads is of course a player in the Fediverse. But not one that we have known before. If only because of the number of users.

**Comment by ne20002** [comment]
Yes, a single user following someone from Threads is sufficiant to connect to threads.net.
But this will not result in Threads flooding your public timeline. Only the public post of the contacts followed on Threads will appear on the public timeline of your instance.

The point about a post going viral is valid. But I wouldn't call this limiting the timeline rather than limiting traffic (in my instance rate limiting is handled by the reverse proxy).

**Comment by loma-one** [comment]
@ne20002 
Rate limiting should be a function in the Friendica core. Please bear in mind that many operators are not technically savvy.

Please also bear in mind that one post can result in hundreds or thousands of comments. Even if the public timeline only shows the sum of all contacts across all users, this is a whole new level of quality.

**Comment by loma-one** [comment]
https://github.com/friendica/friendica/issues/13733
The objective of this idea is fully realised with the issues from @annando

**Comment by ne20002** [comment]
Rate limiting is not an easy thing. And it is always done by the web server accepting the connections, not the web application.
One can't limit the number of incoming connections. Only the number of accepted connections and handled requests can be limited on the web server.
A web server will always forward accepted requests to the web application, maybe with a delay (queued).
If you don't want you're server to overexceeding its limits, rate limiting is the way to go.
If a post gets viral on another system you may receive a huge amount of requests. There is nothing you can do to prevent this.
Handling limits in Friendica would mean to already accept the requests and drop them, thus processing them.
If you want to limit the number of incoming requests as you're worried about the resources of your system, a reverse proxy is the way to go.
Reverse proxies handle rate limiting quite well be limiting connections and requests overall, by source IP, based on URL and so far.
I have a global limit based on my overall resources. And a limit by source address preventing a single source to block all available resources. And a third limit with queuing request for the /inbox.
