### ISSUE TITLE
Expanding a thread of threads "Comments - Show more" without function

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#13722]
- [x] I have searched open and closed issues for duplicates

### Bug Description

After the federation with threads is now possible, I have received commented posts. I noticed that expanding the "Comments - Show more" does not work. Strangely, this only happens on posts that come from threads. For all other posts with more than 3 comments that come from the Fediverse, I can safely use the "Comments - Show more" function.
https://www.threads.net/@mosseri/post/C01zMgWp4V-

Actual Result:

The comments cannot be expanded in threads of threads

Expected Result:

For threads of threads, the additional comments should be displayed

### Screenshots
![2023-12-15_10-08](https://github.com/friendica/friendica/assets/44441246/f123d892-ab37-48c0-a2f3-303e4d396ba9)

![2023-12-15_10-09](https://github.com/friendica/friendica/assets/44441246/6672904d-fbf0-4e99-8fde-c3d5bcbedca7)

### Platform Info

Friendica Version: 2023.09-rc 1541

Friendica Source:  git

PHP version: 8.1

SQL version: 10.5

**Comment by sekretaerbaer** [comment]
It works for me as long as the posts come from Fediverse users. Threads user comment cards are not displayed for me, but this is probably because only[ 3 or 4 accounts can use AP from Threads at the moment](https://sekretaerbaer.de/display/2311486f-abc023b931e46d9a-47096c14).

![Bildschirmfoto 2023-12-15 um 11 25 27](https://github.com/friendica/friendica/assets/116861232/61669346-b144-44b4-8067-331ece908fde)

![Bildschirmfoto 2023-12-15 um 11 30 39](https://github.com/friendica/friendica/assets/116861232/cc43e695-8b4d-41b7-87d9-f5a1ef4c7b05)

**Comment by loma-one** [comment]
Yes, correct. I also just realised this when I was able to check it on two other instances that have different post threads. If the post comes from one thread account, it is not possible to expand the thread. If it comes from another instance, then it works. Your assumption could be correct.

I have to rethink, because Threads is now also in Fediverse and Fediverse provides accounts ;)
