### ISSUE TITLE
Can't register new user

### ISSUE THREAD

**Issue by oculos** [friendica/friendica#13765]
Hi,

I run Friendica 2023.9-rc on a kubernetes cluster.

I suddenly started to get this error  "An error occurred creating your self * contact. Please try again." when attempting to create a new user.

How could I debug this and fix it? 

Best,

Francis
<img width="288" alt="Screenshot 2023-12-25 at 12 11 07" src="https://github.com/friendica/friendica/assets/6791923/abb47a94-ae6d-4156-9a85-38915c469b88">

**Comment by oculos** [comment]
The only error I find on the logs is the "no_http_signature"

**Comment by annando** [comment]
How do you create the new user?

**Comment by oculos** [comment]
Using the “sign-up” page.

**Comment by oculos** [comment]
It seems that suddenly a few things in my instance stopped working. Most of all, any interaction on my side does not reflect on other instances, except following someone. Sending a message does not work (the person doesn't get a message), liking does not show on the other instance, etc.
Common to it all is that I get a lot of "no_http_signature". 
How can I fix this, @MrPetovan ?

**Comment by annando** [comment]
Please execute `bin/console dbstructure dryrun` in the console and tell, if the system returned something there.

**Comment by oculos** [comment]
> Please execute `bin/console dbstructure dryrun` in the console and tell, if the system returned something there.

@annando nope, it doesn't return anything: 
```
root@friendica-546c96c5b6-6vfjl:/var/www/html# bin/console dbstructure dryrun

```
I just upgraded to 2023-12=fpm, btw. Same thing.

Creating a new user via admin interface works, but not self-registration.  Every non-local interaction doesn't seem to propagate outside my instance.

**Comment by informapirata** [comment]
> Hi,
> 
> I run Friendica 2023.9-rc on a kubernetes cluster.
> 
> I suddenly started to get this error "An error occurred creating your self * contact. Please try again." when attempting to create a new user.
> 
> How could I debug this and fix it?
> 
> Best,
> 
> Francis <img alt="Screenshot 2023-12-25 at 12 11 07" width="288" src="https://private-user-images.githubusercontent.com/6791923/292751411-abb47a94-ae6d-4156-9a85-38915c469b88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxMjQ3MTAsIm5iZiI6MTcwNDEyNDQxMCwicGF0aCI6Ii82NzkxOTIzLzI5Mjc1MTQxMS1hYmI0N2E5NC1hZTZkLTQxNTYtOWE4NS0zODkxNWM0NjliODgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDFUMTU1MzMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzE0Nzc4MDYxNWQ5MmYwMDNjNTdiMmQ4Njk1Yzk5ZGMzOGJlMDkxM2EyNzhmY2JmYjBjYzY3NmMzMGZhZGI1MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.rjhpRt1gNn1vmL9bBv82z9B57544Gca5tDU0oUdY-zg">

Unfortunately I also have the same problem on my poliverso.org instance, which runs version 2023.12 (dB: 1542/1542, - post-update: 1507/1507.
Users receive an unspecified error message that is not reflected in the administrator log. I currently had to disable on-demand registration, but this leaves it open to bots and trolls signing up

**Comment by informapirata** [comment]
> Most of all, any interaction on my side does not reflect on other instances, except following someone. Sending a message does not work (the person doesn't get a message), liking does not show on the other instance, etc.
> Common to it all is that I get a lot of "no_http_signature".
> How can I fix this, @MrPetovan ?

Damn! I also encountered this problem...

I think it is appropriate to open a new issue for this bug...

PS: Actually, I found that I only received them late

**Comment by emkamau** [comment]
I'm also getting the same error message as the OP and cannot register new users. This is on a brand new instance of: Friendica 'Yellow Archangel' 2023.12 - 1542. Running on Ubuntu 22.04 with PHP 8.1.2-1ubuntu2.14 and PHP-FPM. I was able to register the admin user on install but nobody else. The site is running on https behind a Caddy reverse proxy which terminates tls. I'm also seeing the error: 
".well-known/host-meta is not reachable on your system." even though I'm able to reach it and download host-meta via the browser.
Running bin/console dbstructure dryrun also returns nothing.
The logs are set to NOTICE and only show the repeated NOTICE Context: app Message: no data for session.

**Comment by annando** [comment]
The ".well-known/host-meta is not reachable on your system." message tells you, that your own system can't reach itself via the hostname. This can happen for example, when you use some forward proxy.

**Comment by genius6** [comment]
Same issue on my side: Friendica 'Yellow Archangel' 2023.12 - 1542, although I don't see anything about "no-http-signature" and other errors. I just can't have new registrations since a "An error occurred creating your self contact. Please try again." error message appears. I also tried the "bin/console dbstructure dryrun" suggestion, but it returns nothing...

Pretty sure this started after I updated to 2023.12, since I had registrations before.

**Comment by emkamau** [comment]
This is only happening when registration is set to "requires approval" in the registration admin settings. With registration set to "open" I can register new users.

**Comment by annando** [comment]
Please have got a look into the log. Is there something with "WARNING" or "ERROR", when you try to register?

**Comment by emkamau** [comment]
@annando there is one warning and no errors. Only the NOTICE app No data for session". Over the past few days i've had one WARNING in the logs from the worker with the message "No item with uri-id found - we better quit here". THe rest are repeats of the NOTICE above and worker start and end messages.
I've installed two test sites, both with the same result. They are on the same server though so the configuration is the same. I will install another test site on a different server without the caddy reverse proxy see what happens and report back.

**Comment by genius6** [comment]
No Warning or Errors on my side as well. Only Notices.

I did try a few things in the meantime, and I think I might have found something that could hint towards the problem, but I don't consider myself as 100% knowledgeable so please take it with a grain of salt.

1) First, I tested if the User was created in the first place. I took a look a the "user" table in the Database. When I try to register a new account with "Approval Required", I still get the error message about the Self Contact unable to be created, but I can confirm the User itself gets created and deleted right after. The incremental ID is increased, and I made sure the record was created at one point using a trigger.

2) Second, I asked myself what could trigger the error message. So I took a look at the /src/Model/Contact.php file, and found out that the createSelfFromUserId function was first looking for a user with the same uid, _that was verified and not blocked_. This would be against the "Approval Required" configuration, since all users created when approval is required are with Verified = False and Blocked = True. So I think the issue is that since the function is unable to find the user still pending verification, it fails. The Verified = False + Blocked = True filters were added since 2023.12, and weren't there in 2023.05...

Again, I could be wrong, but that's what I came up with...

**Comment by emkamau** [comment]
Looks promising. I've tested this on a couple of different systems now with the same result. So I hope the devs can take a look at it.

**Comment by annando** [comment]
@genius6 thanks for your investigation! That helped a lot. I created the pull request #13961 based on your research. I haven't tested it because of time constraints. Can you check if this solves the issue?

**Comment by tobiasd** [comment]
Could someone of you please check the latest 2024.03-RC code to see if the changes in #13961 solved the issue?

**Comment by foss-** [comment]
Polite ping / paging @oculos @informapirata @emkamau @genius6

**Comment by tobiasd** [comment]
Any news on this @oculos @informapirata @emkamau @genius6 can you register new accounts again?

**Comment by annando** [comment]
Since there had been no further feedback for more than a week, I assume that the issue is now solved and that we can continue with the release.

**Comment by tobiasd** [comment]
I agree, lets assume the issue is solved as there was no further feedback.

**Comment by emkamau** [comment]
This is now working for me on 2024.03-RC. Thank you!
