### ISSUE TITLE
Invalid JSON data (false positive)

### ISSUE THREAD

**Issue by ne20002** [friendica/friendica#13969]
- [x ] I have searched open and closed issues for duplicates

### Bug Description

I have a log entry complaining about an invalid JSON data, where the data is no JSON but HTML and the content-type states data is text/html.

It seems as if the content-type is not handled properly.

![grafik](https://github.com/friendica/friendica/assets/39007279/12c3c39c-8268-4e0c-9b92-78c02b9c8cd7)

This is the activity in the timeline:

![grafik](https://github.com/friendica/friendica/assets/39007279/d6d3ae0c-4c08-4b64-8cb7-35a1ca8b93f6)

### Platform Info

Friendica Version: 2024.03-rc

Friendica Source: docker image

**Comment by MrPetovan** [comment]
`fetchMissingActivity` explicitly uses the HTTP request header `Accept: application/activity+json, application/ld+json; profile="https://www.w3.org/ns/activitystreams"` to query remote URLs, so we definitely don't expect `text/html` in the response. The server should have replied with a `406 Not Acceptable` error since the `Content-Type` of the response couldn't match the `Accept` of the request. See https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation#server-driven_negotiation

**Comment by annando** [comment]
In fact, some lines below that message we also check for the received content type and we would quit.

**Comment by MrPetovan** [comment]
Where exactly? I can't find anything about this in `Processor::fetchMissingActivity()`.

**Comment by ne20002** [comment]
I think a better log message based on the content-type would be sufficient.
I will try to file an issue on the other project tomorrow. If they answer with an unrequested content-type this is a bug.
But as they send HTML ... Should HTML be handled and requested by Friendica? Is it a valid format for an activity?

**Comment by annando** [comment]
@MrPetovan see here: https://github.com/friendica/friendica/blob/2024.03-rc/src/Protocol/ActivityPub/Processor.php#L1621

**Comment by MrPetovan** [comment]
Thanks, we really should do this before we try to decode JSON.
