### ISSUE TITLE
[frio] padding on the mobile login page 

### ISSUE THREAD

**Issue by haheute** [friendica/friendica#14053]
- [X] I have searched open and closed issues for duplicates

### Bug Description

On the mobile login page, there is no padding left and right, maybe a little space could be added there. 

### Steps to Reproduce

Open the Friendica homepage in a private tab, and look at the login page. Drag the browser window narrow or look on a smartphone.

Actual Result:

The text and the input fields touch the window edge.. no space there.

Expected Result:

I'm not sure how it would look on other devices, but for my phone, maybe a little padding could be added, similar as it is there on other pages (`/network`, for example).

### Screenshots

![mobile-padding](https://github.com/friendica/friendica/assets/5753419/925ea21a-1792-462e-985e-67fd4af9848f)

### Platform Info

Friendica Version: 2024.06-dev
Datenbankversion: 1559/1559 
Post-Update-Version: 1550/1550

PHP version: 8.2.17

SQL version: mysql  Ver 15.1 Distrib 10.11.6-MariaDB, for Linux (x86_64) using readline 5.1

**Comment by MrPetovan** [comment]
This fix didn't look right to me so I dug into it. It turns out this display is caused by several exceptions that have been made to the Bootstrap base classes. Removing these exceptions restores the expected padding. The main hint was that the display has padding  above 600px wide, and none under.

Would you rather me pointing out where the changes should be made or to make them myself in your branch?

**Comment by haheute** [comment]
Yes, you can make the changes..

**Comment by MrPetovan** [comment]
Hm, after more digging I made these changes myself to remove the padding in the network view. On my single-user node I don't have a login page, so I wasn't able to test this page with my changes 😅

Definitely up to me to fix this.

**Comment by haheute** [comment]
I think it's fixed faster when you do it.
