### ISSUE TITLE
is shortening URLs this much a good default?

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#14098]
https://github.com/friendica/friendica/pull/14080 changed the way URLs are handled and introduced URL shortening.

Personally I am not in favor of that recent change. Let me explain why:

If you look at the following post, which has three URLs linking to a bug tracker, none of the URLs provides any useful information. Since the most important part - the bug number which is at the end of the URL - becomes shortened, the entire post becomes much harder to use / process / make sense of.

![1](https://github.com/friendica/friendica/assets/5708172/16d16554-bbe2-4b6e-a578-0a262a6d481c)
https://pirati.ca/display/ec054ce7-1666-1f98-17ba-548834429014

The URL shortening is especially annoying here, as there really is no gain. E.g. the first URL is `https://bugs.documentfoundation.org/show_bug.cgi?id=127610` which may even fit in a single row and would not have increased the length of the post size wise (character wise it obviously would have).

I understand it is a good idea to shorting URLs that are a few hundred characters long. But maybe the limit when shortening begins should be raised?

**Comment by AlfredSK** [comment]
Just a hint. You can hover your mouse to reveal the complete URL. On mobile it seems to work with a long press.

**Comment by tobiasd** [comment]
After testing the shortened URLs now for two weeks, could we just reverse #14090 (maybe only the shortening part of the PR) or at least make it configurable by the user and off by default? Yes mouse over works, but this is a rather clumsy UX to get the information from the URL that is currently cut off from most of the links (the actual page name).

**Comment by MrPetovan** [comment]
What is the page name for you?

**Comment by tobiasd** [comment]
The name of the actual file the link goes to, not only the domain name. Sometimes also the path is important (e.g. when it shows the department of a news).

**Comment by annando** [comment]
Sadly it can't be configurable for the user, since the parsing is done outside the user context.

**Comment by MrPetovan** [comment]
> The name of the actual file the link goes to, not only the domain name. Sometimes also the path is important (e.g. when it shows the department of a news).

Indeed, but the problem is that it isn't consistent across websites, so we'd be chasing ghost trying to keep "meaningfuly" shortened URLs while there's no standard to publish URLs.

For example, with the URL `https://pirati.ca/display/ec054ce7-1666-1f98-17ba-548834429014`, according to you, we wouldn't be able to shorten it much because `ec054ce7-1666-1f98-17ba-548834429014` would be the page name and `/display/` would be the path.

**Comment by hoergen** [comment]
> Sadly it can't be configurable for the user, since the parsing is done outside the user context.

Then you shouldn't make it as standard for everybody. Obfuscating the URL with noreferrer and similar techniques is absolutely a bad idea and it is completely annoying to take some extra steps, because someone had a major mind drop out and changed this display without consulting the user base or discussing it in public and getting some more perspectives and opinions on that topic.

We had such changes with big influence on the user experience UX in the past, that weren't discussed in public and that drove a lot people really angry.  After the change were reverted and were discussed and the changes were made, they were always configurable. 

Please always consult the user base first, when you want to change some UX related things. 

So if you can't change this in a configurable option, what sounds really silly, when we speak from software, then please change it back and please start discuss such big changes with the user base first. If you then still want to implement this option, then it should always be a configurable option. Software was made for that.

Thank you very much.

**Comment by tobiasd** [comment]
I made it configurable on my node for the admin node-wide yesterday evening and am just testing if there are too many drawback from my changes at the moment.

What I did was basically taking out this block in `src/Util/Strings.php` around line 580.

```
if (strlen($styled_url) > 30) {
   $styled_url = substr($styled_url, 0, 30) . "…";
}
```

For testing you can comment out the block.

**Comment by annando** [comment]
@tobiasd this is not the best place for a change. That function is used for example for the Bluesky addon as well. And that really relies on visually shortened URL. The change needs to be done in the BBCode class. But also there we have to decide for the different targets.

**Comment by tobiasd** [comment]
On 23.07.24 08:06, Michael Vogel wrote:
> @tobiasd <https://github.com/tobiasd> this is not the best place for a
> change. That function is used for example for the Bluesky addon as
> well. And that really relies on visually shortened URL. The change
> needs to be done in the BBCode class. But also there we have to decide
> for the different targets.
TBH for all from my point of view. If a service "needs" a shortened URL,
then shorten it for the service only. So far I have not encountered any
drawbacks from that location for my node.

**Comment by loma-one** [comment]
The shortening of the URL was very well received. This request was made to me by many people. These are the people who make up the user base. The overlong URLs, on the other hand, are extremely annoying because the content was barely recognised, resulting in an extremely poor user experience. And these overlong URLs are on the increase. 

It is therefore a good decision if this can be set per node.

**Comment by foss-** [comment]
Wondering how those overlong URLs were created? I never share such URLs. Do we need to educate (german?) users to remove tracking data from links before sharing them? Sharing tracking links would be rather insensitive as you would be exposing your followers to trackers. Shortening the URL just puts lipstick on the pig and obscures the tracking.

It even adds the problem that it becomes harder for followers (I know url hover exists, but do all users?) to tell whether they are clicking on a tracking link or not.

There even is a feature in Firefox removing URL tracking information from links for above reasons.

**Comment by loma-one** [comment]
The complete URL is still displayed by the browser. In Firefox classically at the bottom left. This is common practice in most applications. It is therefore not to be assumed that you will click on a link completely unexpectedly and your data will be siphoned off. 
UMT attachments can be easily filtered using appropriate add-ons, e.g. in Firefox. I would always recommend this.

No, I'm not surprised how such long URLs come about. These are links like this one (although this is still a benign case):

`https://www.ardmediathek.de/video/checker-reportagen/der-radio-check/br-fernsehen/Y3JpZDovL2JyLmRlL3ZpZGVvL2UyOWJhZTRlLWRmOTItNDNkMi1iNWE0LTQ3MmExYmRhMzI1Mw` 

in which no tracking information is incorporated, which are becoming increasingly popular and are being used more and more widely. 
The providers of such links assume that the displaying application knows a procedure to handle overlong links accordingly. Friendica is the only application I know of in the Fediverse that has continued to act as if it were 2014, when such links were not yet in widespread use. 

All other Fedi projects have long since reacted and only display links in a shortened form.

**Comment by foss-** [comment]
Neither Iceshrimp nor Firefish do shorten links. Is this a Mastodon thing?
EDIT: Answering my own question: of course it is. Can't say I am surprised.

**Comment by hoergen** [comment]
Just a question because I can't find any information here or https://github.com/friendica/friendica/pull/14322 where to configure that behavior in the server settings. Please add always a short descriptions when changing behaviors .

Where can I change this behavior? 

Thank you.

**Comment by annando** [comment]
As a general rule of thumb: All administration settings you will either find on the administration page or in `static/defaults.config.php`. In both places there is always a short description. Values on the administration page aren't in `static/defaults.config.php` and vice versa.

**Comment by hoergen** [comment]
So what you want me to say in a encrypted way is, that there is no option in the GUI. We have to configure it in the servers configuration file?

And If so, how is the syntax?

See that is exactly the reason why I asked to initially document by default all those new features and changes at least in the issues and pull request, so that nobody has to play this absolutely avoidable question and answer games, that are annoying me and annoying you.

Thank you.

**Comment by annando** [comment]
See the documentation on how to work with that type of configurations: https://github.com/friendica/friendica/blob/2024.06-rc/doc/Config.md

The `defaults.config.php` is mentioned here: https://github.com/friendica/friendica/blob/2024.06-rc/doc/Config.md#static-configuration-location and here: https://github.com/friendica/friendica/blob/2024.06-rc/doc/Config.md#config-values-that-can-only-be-set-in-configlocalconfigphp-1 for example.

**Comment by tobiasd** [comment]
It is a new feature in the current release, I will mention the config possibility for the admin of a node in the release notes.
