### ISSUE TITLE
Different information shown in UI vs (Mastodon) API response

### ISSUE THREAD

**Issue by nikclayton** [friendica/friendica#14121]
- [x] I have searched open and closed issues for duplicates

### Bug Description

My test account on pirati.ca (https://pirati.ca/profile/nikclayton) is currently following two accounts. They both appear correctly in the web UI at https://pirati.ca/profile/nikclayton/contacts/following.

However, if I request my account details using the Mastodon API (https://pirati.ca/api/v1/accounts/5245970) that shows:

```
following_count: 1
```

Not the expected `2`.

If I request the list of accounts I am following using the Mastodon API (https://pirati.ca/api/v1/accounts/5245970/following) the result object correctly lists both accounts I am following.

Originally discovered by https://github.com/foss- in https://github.com/pachli/pachli-android/issues/649. They also note other issues there, like:

> Another thing I noticed is that many twitter contacts are still showing as followers. I had revoked the follow via friendica webUI (Contacts > Open contact profile > Actions > Revoke follow) and they no longer show in webUI but Followers still lists all of the accounts. Maybe just another side effect of the sam problem?

### Platform Info

This is Friendica, version 2024.06-dev that is running at the web location https://pirati.ca. The database version is 1560/1560, the post update version is 1550/1550.

**Comment by annando** [comment]
In PR https://github.com/friendica/friendica/pull/14354 I fixed the behaviour with the Twitter contacts mentioned in the quote. The discrepancy between the numbers and the actual list is due to caching and the source of the data. The numbers are taken from the corresponding collection, which means it is public data. So it won't show contacts that a user wants to hide and some other rules. For the actual list, we then decide to take it from some cached data as well. Only when we are looking at our own contact can we get the uncached and accurate data.
