### ISSUE TITLE
Connectivity between Friendica and Hubzilla does not work always 

### ISSUE THREAD

**Issue by rocky-III** [friendica/friendica#14145]
Connectivity between Friendica and Hubzilla does not work always and i asked the main DEV of HZ for reason. That is what he wrote to me:
```
Hab da mal jetzt nachgesehn. Sind wohl drei Sachen die schief laufen:

    Unter bestimmten Umständen fehlte beim Hubzilla Profil hcard Info die vom Diaspora Protokoll benötigt wird (is gefixt)
    
friendica ruft beim verbinden eine hardcoded URL auf die es bei Hubzilla schon lange nicht mehr gibt "https://github.com/friendica/friendica/blob/765af10f00728b1421a9eb633e0afc1948168eee/src/Network/Probe.php#L845
    

Bei Friendica sollte man beim verbinden sichercheitshalber immer das gewünschte Protokoll für die Verbindung angeben. Das geht in der Form [activitypub]nick@server.tld oder eben [friendica-over-diaspora]nick@server.tld
```

thanks for having a look into it

**Comment by annando** [comment]
That probe line doesn't matter, since this is only for informational purposes, since we don't support Zot. But is good to know, that one has to provide some workaround in Hubzilla to provide the protocol. In Friendica we simply collect a list of supported protocols on the other side and then chose the best one. We prioritize ActivityPub here.

**Comment by rocky-III** [comment]
thanks... so what does prevent connectivity between Friendica and Hubzilla from you perspective? It is a pity that this two project do not connect without total fail outs . What could be done to make things better here?   
thanks for looking in to it.

**Comment by annando** [comment]
Well, I could imagine that Hubzilla has got problems, when we reply via ActivityPub although the connection had been established via Diaspora, but this is a very wild guess. I also don't know, if Hubzilla supports the field we added in our ActivityPub posts, so that replies via ActivityPub from Friendica systems can be relayed to Diaspora systems.

**Comment by git-marijus** [comment]
@annando the supported protocols in Hubzilla can vary by channel. I have tested with a channel where AP was disabled. The connection request via diaspora protocol returned 202 from Friendica but the request itself never appeared in the UI at my testaccount on libranet.de

**Comment by rocky-III** [comment]
Ok here what i found out with some help: 

The problem is that in the past things between HZ and Friendica have worked with the Diaspora Protocol - but Friendica has increasingly switched to ActivityPub, which also affects communication with HZ. 

Unfortunately, HZ does not currently automatically switch to ActivityPub when a contact request is sent to Friendica. But you can force this by putting an [activitypub] in front of the address to be contacted.e.g. if you want to contact to channel @name@server.tld

you enter [activitypub]name@server.tld

in the contact request under

/connections

Unfortunately, things seem to get tangled up due to previous failed attempts via the Diaspora protocol... So please do the test with a very fresh HZ channel... i.e. one that has not yet tried to contact name@server.tld via the diaspora protocol.

created an fresh channel under: 

/manage

and see if things work better

**Comment by SpcCw** [comment]
It seems that currently the federation works completely one-way. The posts from Friendica arrive to Hubzilla and Friendica doesn't receive and can't even fetch Hubzilla posts directly (which I think is relatively recent behavior - I could at least fetch missing public posts before by pasting links to search box).

E.g. https://hubzilla.konzurovski.net/item/b3753fa5-3385-4246-a7dc-51a94022c30f - it just hangs for a while until "Gateway TimeOut" error when pasted into the search box.

Since Hubzilla does receive outgoing Friendica posts can something be done about this so posts can be fetched?

Below is the curl of the example (I clipped the content for readability)

```
curl -H Accept:application/activity+json https://hubzilla.konzurovski.net/item/b3753fa5-3385-4246-a7dc-51a94022c30f | jq

{
  "@context": [
    "https://www.w3.org/ns/activitystreams",
    "https://w3id.org/security/v1",
    "https://purl.archive.org/socialweb/webfinger",
    {
      "zot": "https://hubzilla.konzurovski.net/apschema#",
      "schema": "http://schema.org#",
      "ostatus": "http://ostatus.org#",
      "diaspora": "https://diasporafoundation.org/ns/",
      "litepub": "http://litepub.social/ns#",
      "toot": "http://joinmastodon.org/ns#",
      "commentPolicy": "zot:commentPolicy",
      "Bookmark": "zot:Bookmark",
      "Category": "zot:Category",
      "Emoji": "toot:Emoji",
      "directMessage": "litepub:directMessage",
      "PropertyValue": "schema:PropertyValue",
      "value": "schema:value",
      "uuid": "schema:identifier",
      "conversation": "ostatus:conversation",
      "guid": "diaspora:guid",
      "manuallyApprovesFollowers": "as:manuallyApprovesFollowers",
      "Hashtag": "as:Hashtag"
    }
  ],
  "type": "Note",
  "id": "https://hubzilla.konzurovski.net/item/b3753fa5-3385-4246-a7dc-51a94022c30f",
  "diaspora:guid": "b3753fa5-3385-4246-a7dc-51a94022c30f",
  "published": "2024-10-20T10:16:56Z",
  "attributedTo": "https://hubzilla.konzurovski.net/channel/kinen",
  "inReplyTo": "https://tor.lat/users/san/statuses/113335815349041676",
  "content": "...clipped...",
    "mediaType": "text/bbcode"
  },
  "actor": "https://hubzilla.konzurovski.net/channel/kinen",
  "tag": [
    {
      "type": "Mention",
      "href": "https://tor.lat/@san",
      "name": "@Sandro"
    }
  ],
  "to": [
    "https://www.w3.org/ns/activitystreams#Public",
    "https://tor.lat/users/san"
  ],
  "cc": [
    "https://hubzilla.konzurovski.net/followers/kinen",
    "https://friends.deko.cloud/followers/shuro"
  ],
  "proof": {
    "type": "DataIntegrityProof",
    "cryptosuite": "eddsa-jcs-2022",
    "created": "2024-10-20T18:57:21Z",
    "verificationMethod": "https://hubzilla.konzurovski.net/channel/kinen#z6MkqGPvva2myohDK4WijybDpDxCdQpiPZe6zecRQ2355exU",
    "proofPurpose": "assertionMethod",
    "proofValue": "z4Ve5QWBhqnQkGLjmULBw1Hj6mwLxsdCEz6XUH1dJrQqg9pAXwjsBwSQ3aS1kNpKUQV13Kwm7uF6ZjkNbwq25YiCD"
  },
  "signature": {
    "@context": [
      "https://www.w3.org/ns/activitystreams",
      "https://w3id.org/security/v1"
    ],
    "type": "RsaSignature2017",
    "nonce": "9969580518bf2ebd075be307e0d505b9ff9e5257f6434e9708bab24bf94f0612",
    "creator": "https://hubzilla.konzurovski.net/channel/kinen",
    "created": "2024-10-20T18:57:21Z",
    "signatureValue": "...clipped..."
  }
}
```
Probably unrelated thing: when these fetch attempts fail I see messages in the log about JSON compacting errors related to URL `https://purl.archive.org/socialweb/webfinger` being unavailable (as purl.archive.org is down for some time).

**Comment by annando** [comment]
The message is not unrelated, it is the cause of the issue. During compacting we need to fetch some data. When this is not available it will fail. We have internal caches for most paths, but not for that path. Do you have got the content that had been there at that location?

**Comment by git-marijus** [comment]
https://framagit.org/hubzilla/core/-/blob/dev/library/w3org/socialweb-webfinger.jsonld should be it






Am 20. Oktober 2024 21:49:59 MESZ schrieb Michael Vogel ***@***.***>:
