### ISSUE TITLE
Obligation to name a contact person for relay accounts

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#14231]
### Describe the feature you'd like

Relay accounts are unfortunately developing into a new plague in the Fediverse. Not only hashtags, but also words are being fished for and re-shared. 

Often no contact person is named or made transparent as to which hashtags and words are being searched for and shared. There is currently no way to tell the bot that you don't want to be shared.

This all seems very intrusive and puts Friendica in a bad light. This is a pity because the function is a wonderful tool in responsible hands.

It would therefore be good if there was a mandatory field that was obligatory and named a contact person who could be contacted.

General wish: All relay operators should undertake to make transparent how the relay works, which search terms are used and how you can protect yourself from unwanted sharing.

**Comment by SpcCw** [comment]
Isn't just blocking the bot enough to prevent it from sharing your content?

If someone really abuses it then the next step would be reaching out to their server's admins / moderation team.

I am not sure any mandatory fields would help because people who care can already fill the profile with relevant information and/or make pinned posts. People who don't care would just fill this mandatory field with nonsense.

**Comment by loma-one** [comment]
Blocking at user level is not enough. The content will still be shared if a word or hashtag is found. I no longer see it myself. But it is still there.

I am open to a different solution. Even a voluntary commitment. I currently see relays that can be described as unfriendly.

**Comment by sekretaerbaer** [comment]
I think the proposed idea with the mandatory fields makes a lot of sense. 
I have already entered this information in my relays and have come into contact with some users who thought, for example, that the relay would transfer the data to another network. 

I was also able to change the description of my relays in co-operation with the users so that they understand what a relay at Friendica is. 

I was also able to exclude users who did not want their posts to be shared.

Additionally, I would like to have the possibility to automatically exclude accounts that have #nobot in their profile from sharing their posts. But I don't know if this is even possible.

**Comment by SpcCw** [comment]
In my opinion relay account is no different from just any account resharing posts (by hand or other means, e.g. I have a bot doing certain reshares by python script). It is certainly a good practice to leave some description and contact information and it is already possible so I am not sure what this mandatory field will change and how it will be interoperable with other systems.

If any account behaves maliciously (relay, bot or human-operated) we can always report this account or go to their admin and then it will be dealt with. I am not sure if we need to over-complicate things for this particular scenario.
