### ISSUE TITLE
Moving the function "Your old ActivityPub/GNU social account"

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#14344]
### Is the feature request related to a problem? Please describe.

Friendica has a function that can be used to import contacts without a CSV file. The handle of the remote account is specified for this purpose. Friendica contacts the account and imports the contacts to the "new" account (online). 

This function is currently so well hidden that even long-time Friendica users are unaware of it. 
https://.../settings/connectors > General social media settings > Your old ActivityPub/GNU social account

I would expect to find this function in the easily accessible menu: https://.../settings > "Import contacts".

### Describe the feature you'd like

To make online importing easier, it would be an advantage if the online import function for contacts were moved to https://.../settings > "Import contacts" or at least a deep link were set.

![grafik](https://github.com/user-attachments/assets/d20ea033-9e8c-4634-9b09-406df7570e47)

**Comment by foss-** [comment]
Tried to understand the status of this issue in `This is Friendica, version 2024.09-rc that is running at the web location https://pirati.ca. The database version is 1576/1576, the post update version is 1550/1550.`

In `Settings > Social Networks > General Social Media Settings` there is info about ` Your legacy ActivityPub/GNU Social account`.

This should indeed be moved to `Settings > Account > Import Contacts`.

The issue seems half done as the CSV import option has already been moved.

So remaining TODO is to move the other function as well.
