### ISSUE TITLE
addon forum directory

### ISSUE THREAD

**Issue by TupambaeNet** [friendica/friendica#1494]
This is an addon of Thomas so I suppose actually there is no maintainer.
My basic question in which UI it works as supposed. In diabook the about text just runs out of line and screen, in vier it doesn't display any verbose description at all.

**Comment by tobiasd** [comment]
> My basic question in which UI it works as supposed

My guess would be duepuntozero; vier was not there at the time and diabook had its own way to display stuff (and is not unsupported).

**Comment by tobiasd** [comment]
I added some more information to my old forum of the 30c3 and enabled the addon. Got the following displayed in blog, clean, duepuntozero, quaddro and vier. Layout is always the same, but differs a bit in the coloration and fonts.

![friendica_forumdirectory_30c3](https://cloud.githubusercontent.com/assets/433490/7161191/1a633838-e38e-11e4-9a3a-67ffc81e19b5.png)

The errpr I spot is the postcode, but it looks fine for me otherwise.
