### ISSUE TITLE
Global Directory

### ISSUE THREAD

**Issue by mama21mama** [friendica/friendica#1588]
please include

Locations: Argentina

>> http://dir.friendica.com/

**Comment by redmatrix** [comment]
Only the top ten tags and countries are listed by default. This can be patched in the friendica/dir project but then send me a personal message because I rarely watch that repository and the notifications could easily get dropped into my spam folder. The correct number to use as a default could be contentious so probably best to let others weigh in with their preference. Removing the limit could make a rather unpleasant page.

**Comment by mama21mama** [comment]
I mean this > http://upimage.mamalibre.com.ar/galery/index.php?cmd=image&sfpg=KjZkNjY2NGM5NzIzMzRhMWY2Mzk2ZjY4Mjg2YjVhN2RiLnBuZyphNDhkY2ZlMGFhOGRlZGM3ZWY0ZTlkOGMwOTg2MjRlNw

**Comment by redmatrix** [comment]
Right. There are exactly ten of them. The top ten in fact. If you came up with 8 more members from Argentina you could topple Austria and wind up in the top ten.

**Comment by mama21mama** [comment]
source code 

available

**Comment by redmatrix** [comment]
https://github.com/friendica/dir

include/widget.php

I've increased this to 20 which puts Argentina onto the page (number 15 in rank). If folks complain about the length of the sidebar or insist on including Bangledesh or Ukraine I'll have to revert this, as I haven't been directly associated with the Friendica project for several years now.

**Comment by mama21mama** [comment]
Thank you, you have won my friendship.
