### ISSUE TITLE
Post privacy not shown

### ISSUE THREAD

**Issue by strk** [friendica/friendica#1656]
Is it due to the theme I'm using (quattro) or is the privacy settings for posts not shown ?
I cannot tell, for any post I see (mine or of someone else), who is that post shared with.

**Comment by fabrixxm** [comment]
You get a padlock ( top right in quattro theme) when the post is private.
If it's your post, click on it and a popup will show you who can and cannot see the post.
If post isn't your, you know that the post is private, but obviously you don't know who can and cannot see it.

**Comment by strk** [comment]
I do see the padlock in friend's posts that tell me those posts are "private". It doesn't mean much because as you say I don't really know who can and cannot see them. And I guess the poster can always change permissions of posts making my comments suddenly visible to anyone (right?).

What concerns me more is that there is no way to check the privacy of _my_ posts.
Also in this case, if my post were ever public, even if I changed its privacy to "only friends" it would still be leaked around the net, correct ? So I'd not only need to know _current_ privacy but the whole history of privacy change.

Am I making sense ?

**Comment by fabrixxm** [comment]
>  do see the padlock in friend's posts that tell me those posts are "private". It doesn't mean much because as you say I don't really know who can and cannot see them. 

Because if we show you who are the recipients of a private post, that post isn't really private anymore.

>  I guess the poster can always change permissions of posts making my comments suddenly visible to anyone

No, post's access list can't be changed. Allowing to change privacy of a post can expose private comments (either private to full public and private to still private but with added that guy you're talking bad in comment). Allowing to change a post from public to private is more difficult, as we can't send an "edit"  message to other networks like diaspora and ostatus. And also if we could do that on Friendica, someone could already shared your post. Once is out, is out.

> Also in this case, if my post were ever public, even if I changed its privacy to "only friends" it would still be leaked around the net, correct ?

Yes

>  So I'd not only need to know current privacy but the whole history of privacy change. Am I making sense ?

You can't change post's ACL, so no :-)

**Comment by strk** [comment]
I _did_ change the privacy of a post, pretty sure I did. The picture of my couch (you might have seen it) posted from Friendica Android app was initially public, I did change it to only visible to friends.

I'll try again tagging you :)

**Comment by strk** [comment]
Ok, I confirm I cannot change ACL of a post. 
I also confirm I do can see the actual ACL of posts I created. No padlock == public, padlock == non-public, click (or mouse over) to read immutable ACL.

But I can change the ACL of photos, looks like (but this would eventually be for another post).
Thanks for support!

**Comment by strk** [comment]
See #704 for further discussion on this

**Comment by fabrixxm** [comment]
You changed picture's ACL, not post's.
Picture are not copied to remote servers, they are linked back to your server, where the acl is checked on every request. So you can post a public picture and later limit the access to it.

**Comment by strk** [comment]
I'm actually re-opening this because showing post privacy has its own advantage, despite being able to change it.

**Comment by strk** [comment]
I think ideally things should work like this:

 - You should be able to see the ACL of your own posts
 - You should be able to see the list of your own friends having access to a post you have access to, plus a count of how many non-friends also have access
 - The author of a post should be allowed to hide this information (ala BCC for mail)

**Comment by strk** [comment]
I just found out this "need to know who can read a post" is not only mine:
https://github.com/shingonoide/friendica-addons/tree/master/remote_permissions

**Comment by strk** [comment]
@fabrixxm wouldn't it be legit for a post author to decide to make the sharing information available to recipients of the message ? ie: make that info federated as well ?

**Comment by annando** [comment]
With the DFRN protocol and the Diaspora protocol we don't have this piece of information. With ActivityPub we would have it - partially. AP does have the "to", "cc" and "bcc" header - just like mail. Theoretically we could display the "cc" data (the "to" data is already displayed at the bottom of the post). But there will be always the "bcc" and the "followers" collection that we cannot display. So it will be misleading to display the "cc" data, since this wouldn't give you any reliability about the receivers of a post.

I don't think that this issue could be solved in a satisfying way, means that I would like to set the issue to "won't fix".
