### ISSUE TITLE
Login cookie doesn't work

### ISSUE THREAD

**Issue by silke** [friendica/friendica#1839]
If I tell my browser to remember me via cookie, this doesn't work (although the domain is explicitly allowed to save cookies).

**Comment by strk** [comment]
I'm also having troubles having friendica "remember" me, but I'm not sure this is about the cookie rather than the session object stored in the database.

The thing is that the cookie served by the friendica node appears to have a requested lifetime of one year while I find myself in need to re-enter my password after one week or so. I do have "remember me" checked when I log in.

@fabrixxm in IRC said he remembers this feature never worked

**Comment by silke** [comment]
This issue does still exist in Firefox 42, it does not exist in Chromium though.

**Comment by silke** [comment]
Erm..... oh. This was due to my cookie settings. Very sorry!
