### ISSUE TITLE
Don't require real name on sign-up

### ISSUE THREAD

**Issue by naught101** [friendica/friendica#1898]
One of the reasons that people want to leave facebook is their real name policy. On sign-up, Friendica also requires a real name. I realise that probably no servers actually enforce a policy about it, like facebook does, but it *appears* to be a requirement, and may be a stumbling block to some users.

It seems that you can change your name to anything after logging in, so there doesn't seem to be a real reason for this requirement on sign-up.

**Comment by redmatrix** [comment]
% util/config system no_regfullname 1

Be aware that if you remove the requirement for a space in the name your site will likely be bombarded with Russian spammers. We made this the default originally because we were all tired of having cleaning out a couple thousand spammer registrations every day - day in and day out. Your mileage may vary.

**Comment by redmatrix** [comment]
And we don't ever require you to have a real name. We only require a space in the name as a spammer deterrent, but you're free to turn it off.

**Comment by naught101** [comment]
Fair enough. It does say "Full name (e.g. John Smith)" or similar though. Perhaps "Display name" would make it clearer what it's for, and make it less like "real name"?

**Comment by redmatrix** [comment]
To me "Full name" describes what we're after, whereas if you just say "Display name" a lot of folks will try an alias (with no space) and then get mad because we threw an error. Maybe something like "Full name (e.g. John Smith or Flying Meatloaf)". 

I also note that there are documented studies which show that people are much more polite in conversations when using real names and some turn into really nasty trolls when they know that nobody can identify them. These contribute to a feeling of general hostility which occasionally drives people away from small networks such as this. It's a hard line to draw, which is why we let site owners have the choice. Anyway if you have improvements, please suggest a patch as I'm not in the Friendica  development loop any more.

**Comment by n4rky** [comment]
Quoting redmatrix <notifications@github.com>:

>
> I also note that there are documented studies which show that people  
> are much more polite in conversations when using real names and some  
> turn into really nasty trolls when they know that nobody can  
> identify them.

Whereas I'll troll *with* my real name. Because I don't see it as trolling.

But the problem I hear about more often isn't so much about trolling  
as it is about people who do not, for various reasons, feel safe  
posting under their real names. This is, of course, the issue that  
Google and Facebook have been painfully slow to respond to.

Maybe 'Real or real-looking name?'


-- 
David Benfell <benfell@parts-unknown.org>

**Comment by tobiasd** [comment]
> aybe 'Real or real-looking name?'

This could be something, for the hints of the field in the registration form. In the admin panel the hint already states the reasoning for the requirement is all about SPAM accounts, so users should have the same information.
