### ISSUE TITLE
define a coding style standard for friendica

### ISSUE THREAD

**Issue by rabuzarus** [friendica/friendica#2103]
Many parts of friendica does use different coding styles. This does make reading and understanding the code harder than it should be. In addition it's hard to search for a certain piece of code because you have to know all the possible different coding styles. 
I would unify some code but at the present time it is unclear what style is the standard one.

To make developing easier and to attract more developers we should agree on a standard coding style for friendica.
To give a simple example: https://hub.hfrc.de/help/developers&JS=1

This issue should stay open to collect the topics/items/pieces which should go into the standard coding style documentation.
To keep this page readable **please use the friendica forums for the discussion** about which coding style is better or which is not.

Things which come into my mind:
- SQL queries
- `$array['key']` or `$array["key"]`
- deprecated functions:
  - using `z_root()` instead of `$a->get_baseurl()`

**Comment by rabuzarus** [comment]
since the link above is dead here is a new one:
https://hubzilla.site/help/developers

**Comment by fabrixxm** [comment]
I like that
I'm for copying it into friendica's help docs

**Comment by Hypolite** [comment]
It turns out there already are plenty of coding standards out there that we can use. The most obvious is [PSR-2, a widely known set of coding standards for PHP](http://www.php-fig.org/psr/psr-2/). Most PHP projects that have their coding standards often build upon PSR-2, so this is a good starting point.

The good news is that [a command-line tool exists to convert PHP file according to the coding standards](http://cs.sensiolabs.org/). I'm currently running it on my local Friendica install, expect a massive code standards pull request.

Note that this tool doesn't affect the code sanity, just its presentation, so any PHP existing before the coding standard fix will likely remain after. But it is a good start towards #2825.

**Comment by Hypolite** [comment]
> @annando: And before we start with it, I really would like to see that we agree on some details like "tabs vs. spaces".

The coding standards are hardly pick-and-choose. The PSR-2 standards are the most widespread standards for PHP, they are used as a platform for [many well-known PHP frameworks, CMS and packages](http://www.php-fig.org/members/) but they also are the least strict. Some individual projects add more rules on top of PSR-2.

As for tabs vs spaces, I personally don't care (except when they are mixed) but I really don't want to make an exception to the standards.

**Comment by annando** [comment]
I find tabs much more easier to handle (and I miss them at work where the system is only able of using spaces). Additionally - since we are using tabs at the moment - the changes would be easier to review.

But: Why aren't the coding standard "pick-and-choose"? I think that standards like these are just guidelines and aren't cemented in stone. They only should be unified in the main points in the same project. (At my work we are working similar. We have code guidelines from Microsoft but we don't follow them in every point)

**Comment by Hypolite** [comment]
> I find tabs much more easier to handle (and I miss them at work where the system is only able of using spaces). Additionally - since we are using tabs at the moment - the changes would be easier to review.

Not sure where on Github but Git allows to ignore whitespace changes in diffs. The command line would typically be : `git diff -w`

Some Git clients allow you to do that in a GUI-friendly manner like in SourceTree.

> Why aren't the coding standard "pick-and-choose"?

This is for the sake of simplicity. If we say "we follow PSR-2", this is simple, it's a defined set of standards that many people already are familiar with, and we don't have to maintain the standards list. Moreover, many code standards tools (like PHP CodeSniffer) are offering PSR-2 coding standards checks out of the box, which doesn't require any configuration tweaks.

Now, if we become a project big enough that we have the klout to go against well-known standards with no other reasons than personal preference (and tabs vs spaces are just that), I'd say go for it, but for now we cannot afford to irk any potential developer because "we follow PSR-2 but not the space rule".

The good news is, if the "tabs vs space" is your only gripe with the standards, then it just is a matter of configuring your IDE/text editor to behave like tabs but by adding spaces instead. It's obviously easy for me to say that because I was already using spaces before, but coming on Friendica, I just switched to tabs for this particular project and it was seamless to me.

**Comment by annando** [comment]
I am a complicate person. I'm normally doing things not because people and/or rules are telling me so - but because I'm convinced that this or that is the best option.

And concerning the changed code I really need to know two things:

- Why are spaces better than tabs? I think they are more easy to navigate and to control. (With spaces you can easily miss one space without recognizing it)
- Why is there a linefeed before the curly brackets after "function" but not after "if" or the other control structures? From my point of view this should be identical. (And I would prefer the curly brackets behind the class definition, function definition and the control structures)

**Comment by Hypolite** [comment]
I could argue (or agree) with you on details but this isn't really the point. Enabling PSR-2 standards for Friendica doesn't have anything to do with convincing you or anybody else they are somehow better than anything. Everybody seems to agree that we need some sort of coding standards for Friendica, and since it's an open-source project aiming at attracting external contribution, it has to be simple and popular. I believe vanilla PSR-2 fits the description because it's the lowest common denominator in coding standards used in many popular PHP projects.

It just is about making the Friendica code base as familiar as possible for new developers, whether they are junior or senior. It is not supposed to be the exact familiar you (or I, for that matter) are used to, because the simple fact is your (or my) specific set of coding standards are less known than PSR-2. PSR-2 as a whole is easier to check and easier to fix, and I believe this is better for the project in general.

**Comment by rabuzarus** [comment]
valid argument

**Comment by annando** [comment]
I guess it's not that much the tabs or the placing of brackets that are a problem for new developers, but the mixed code quality and the structure (means in which file is which function) that is a problem. Additionally the database structure really has many space for improvement.

BTW: How good are you in classes? For years now I want to replace the whole item handling (fetching, storing, publishing, changing and deleting) in a dedicated class. My plan is to replace all sql queries to the item and thread table with centralized class calls. Then as a next step we could safely change the way that items are stored. Since I'm not very familiar with classes (at work I'm working with a language that doesn't know classes), I would like to delegate that job to someone with much more experience in it.

P.S.: Concerning PSR-2 (and especially the strictness) I would like to hear the comments from @rabuzarus, @fabrixxm and @tobiasd. I'm very stubborn (I know) but open for arguments.

**Comment by Hypolite** [comment]
> I guess it's not that much the tabs or the placing of brackets that are a problem for new developers, but the mixed code quality and the structure (means in which file is which function) that is a problem.

Agreed, for me it doesn't matter which exact coding standards set we're choosing as long as we agree to follow it everywhere. And PSR-2 is convenient to follow (widespread + available tools), which reduce the adoption friction.

> BTW: How good are you in classes? For years now I want to replace the whole item handling (fetching, storing, publishing, changing and deleting) in a dedicated class. My plan is to replace all sql queries to the item and thread table with centralized class calls. Then as a next step we could safely change the way that items are stored. Since I'm not very familiar with classes (at work I'm working with a language that doesn't know classes), I would like to delegate that job to someone with much more experience in it.

I write the best classes. They're going to be **yuge**!

(for anyone not getting it, this was an impersonation of Donald Trump)

It sounds like you want to start separating controllers from the model, is that right? There is a performance cost to it, though, because you cannot write ultra-specialized queries anymore. Model queries often mean you query more data than you need.

**Comment by rabuzarus** [comment]
> Concerning PSR-2 (and especially the strictness) I would like to hear the comments

While I'm not familiar with the pro and contra of the different coding styles I think Hipolite does have some really good arguments.
- PSR-2 seems to be widely uses
- it is one standard and we don't need to discuss and spend time to define our own standard (which is only used in friendica)
- there a some tools available which can check violations
- more people seems to be familiar with this standard and don't need to lern our own standard
- it would be maybe easier to easier for us to contribute to other projects because after some time we would be familiar with a standard which is also used in other projects

I don't want to vote for the one or the other coding style (because it's most important point to me is that at least we have a common coding style). But we should discuss these points because they seems to valid to me. And to fulfill some kind of "official standard" won't hurt.

**Comment by tobiasd** [comment]
Well, it is rather simple for me, as I usually cannot remember such rules, I'll stop merging PRs and most likely only do documentations and translations. If you think enforcing rules about code is a good thing go ahead. I would rather prefer some common sense (like `"` or `'` for strings, so grepping through the code gets easier and some clean indentation rules) that should be followed. Doing things on a MUST basis usually means I'll do other things.

**Comment by Hypolite** [comment]
You don't have to remember such rules. Tools can do it for you. And they are mostly common sense anyway, so you probably are following most of them without knowing it. Enforcing coding standards rules is not about writing them by hand perfectly, it's about reading a code that pass the coding standards. Checking and fixing the code according to the rules can definitely happen after you're done writing your stuff. I believe that over time you will naturally follow the coding standards by mere imitation.

**Comment by annando** [comment]
I still have the problem that I need to know the benefit behind every rule (since I only remember stuff that seems to be logical for me). Is there some document with explanations for each of these rules?

I'm the type of guy who always questions everything. And I mostly have a strong urge inside of me to oppose to rules ;-) (That was the reason why I went into politics several years ago)

In November we will have our yearly hackathon. It will be in Berlin. I guess that's much too far away for you, but maybe you could join remotely and we could discuss about stuff like this.

**Comment by Hypolite** [comment]
There is no such document because aside from obvious rules (always have braces in conditions, no closing PHP tag), these are formatting rules that have no impact on the actual code.

About the spaces versus tabs, this is the only rule that the PSR-2 document explains:
> N.b.: Using only spaces, and not mixing spaces with tabs, helps to avoid problems with diffs, patches, history, and annotations. The use of spaces also makes it easy to insert fine-grained sub-indentation for inter-line alignment.

Most rules apparently have actually been decided according to a survey across the members of the body that created the standards, and for example not everybody was agreeing on tabs vs spaces, but they still published a recommendation for spaces.

I'd love to participate remotely to the hackathon, when is it?

**Comment by tobiasd** [comment]
> You don't have to remember such rules. Tools can do it for you.

Which means I would have to let a tool run every time I want to decide if a PR follows the rules or not, or I write something to fix... This does not sound like something I will remember to do.

> And they are mostly common sense anyway

Then why forcing them? Exchange MUST against SHOULD and I could carry on most likely. Enforcing this means I have to know the rules prior to deciding to accept a PR or having another person who constantly carries out checking code and doing checks against rules. As I do not see this overhead necessary, I'd rather stop doing code checking and concentrate to translations and documentations.

**Comment by Hypolite** [comment]
There are two different situations there:
- You review a PR created by someone else: in that case, while reviewing the code, you just have to spot a single instance of code not following any PSR-2 to ask them to fix it themselves, either manually or tool-assisted. You don't have to do anything more, and nobody should scold you if you merge a non-conforming file this way.
- You create a PR yourself: in that case, you indeed are responsible for enforcing the coding standards on your code. But this is a rather easy task.

> Then why forcing them?

So that the whole code base is looking the same, which it doesn't at the moment. Yes, coding standards are somewhat constraining, for the sake of consistency. Yes, it adds a small overhead because multiple people are working on the same project. If it's your own project and don't expect other people to work on it, then I agree that coding standards are completely unwarranted.

**Comment by tobiasd** [comment]
To spot something I would know the rules myself. Which I said, I know myself, and most likely I wound remember them. So same situation as before and I just let you know that I would nod deal with such PRs. 

But as I've said, if the rest of the core team thinks this is a good idea, please go ahead.

**Comment by annando** [comment]
I want to wait for the opinion of @fabrixxm. AFAIK @rabuzarus is mostly for doing so, @tobiasd is having problems with it and I'm totally unsure because I know myself. So @fabrixxm is the one to decide, I think.

BTW: How can I check if my code doesn't break any regulations? Are there some command line tools that do so?

Concerning checking the pull requests: If the github web frontend doesn't have something built in, I guess I will overlook the most. It's like with the doxygen headers (thanks to @rabuzarus for them). I mostly don't see if they are present and correct. This is something where @rabuzarus has an eye on. When merging a pull request I have a look at the code itself.

**Comment by Hypolite** [comment]
> BTW: How can I check if my code doesn't break any regulations? Are there some command line tools that do so?

[PHP Code Sniffer](https://github.com/squizlabs/PHP_CodeSniffer) is the most well- know tool to check your files. Available on PEAR, composer or as a standalone PHAR executable. Additionally, many IDEs allow you to integrate `phpcs` directly and check files while you type.

> If the github web frontend doesn't have something built in, I guess I will overlook the most.

To do that, you need to enable a [Travis CI](https://travis-ci.com/) build configuration file that will execute a PHP Code Sniffer check. If it fails, it will show in the pull request. The details will be available a click away.

More resources:
- Building a PHP project with Travis CI: https://docs.travis-ci.com/user/languages/php/
- Integrate Travis CI with your GitHub repo: https://github.com/mbonaci/mbo-storm/wiki/Integrate-Travis-CI-with-your-GitHub-repo

**Comment by annando** [comment]
My "IDE" doesn't have this functionality, I guess - I'm just using nano.:-)

I think until @fabrixxm had expressed his opinion about the whole stuff, I'm waiting with accepting pull requests that are based on this. Additionally I would like to delegate the check for pull requests that changes the tabs with spaces to someone who does this check with some magic tool, because github's webinterface (which I use) can't handle that.
