### ISSUE TITLE
Forumlist selection does not filter postings

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#2133]
**Current Situation**
In the develop branch when selecting a forum from the forumlist widget the postings are not filtered anymore for the forum as it was with the forumlist addon. Instead all postings from the network stream are displayed.

**Expected**
When I select a forum from the widget I would expect to see only the postings which belong to that forum.

**Comment by rabuzarus** [comment]
can you please check if in the group widget "all cantacts" is selected. There was an isssue I mentioned at the PR that forum selection won't work if an group is selected.

**Comment by tobiasd** [comment]
Yes the "all contacts" group is selected, and after some more looking through the forum I saw that most of them work as expected. But e.g. the helpers forum contains OStatus only threads. IIRC I've only checked that forum (as it is for some reason sorted to the top place in the list) yesterday evening.

**Comment by rabuzarus** [comment]
There shouldn't be a difference between between the plugin and the one in core because it use exact the same sql query (I only moved to another place)

**Comment by fabrixxm** [comment]
I can't reproduce on my system

**Comment by tobiasd** [comment]
I'll analyse the OStatus threads sorted wrongly over the weekend.

**Comment by tobiasd** [comment]
I've clicked through my forums and found the following:

* the OStatus threads are only in two of them (helpers/support and UX Watchdog)
* both of the threads contains one or more posting which includes parts of the forum name (not the nickname)

I've also discovered that not all postings belonging to one forum are shown in this forum. Mostly if the posting is addressed to more then just one forum.

**Comment by rabuzarus** [comment]
If there is an error it have to be in the way the networkstream is filtered. The forum widget itself only try to get all contacts which are forums and creates a network filter link (network?f=&cid=1 - while 1 would be the cid of the selected forum). It can be done with every contact (but the form widget is only looking for cid which are forums)

Is there a difference between forumlist addon and forumlist in core? To my knowledge it shouldn't because I haven't touched the filter mechanism in network.php. It's hard to say where the bug exactly is without reproducing it :-/

**Comment by tobiasd** [comment]
I've not seen any missorted postings for some weeks now, so I'm moving it to the next milestone as a reminder to watch for reappearance of this.

**Comment by tobiasd** [comment]
The problem has not re-occured so far. Guess it was a singular thing so I'm closing this issue.
