### ISSUE TITLE
Friendica does not accept my mail address. Nor my OpenID service. (FreeBSD)

### ISSUE THREAD

**Issue by dertuxmalwieder** [friendica/friendica#2396]
I installed Friendica c18d17e65b37ab3af7db59be0e0cc80c04c1612e on my web server (FreeBSD 10.2, PHP 5.6.18) yesterday, but I can't register with my instance: Specifying my (valid!) e-mail address leads to:

> dns_get_record(): DNS Query failed in /var/www/friendica/include/network.php on line 715

So does specifying my OpenID service which worked for every other service I tried to use it with. Is this a common problem?

**Comment by strk** [comment]
did you try to resolve the domain part of your email/openid service from a shell on the machine running your friendica node ?

**Comment by dertuxmalwieder** [comment]
Yes, it works.

**Comment by annando** [comment]
Just for the archive: What was the problem?

**Comment by dertuxmalwieder** [comment]
It's not solved yet. I was just answering the "domain resolving" part. The domain (without the OpenID subdomain) contains my main website and I'm quite confident that there is no machine which *can't* resolve it.

**Comment by annando** [comment]
There are workarounds for this situation. You could add the following two lines in your .htconfig.php to continue:

````
$a->config['system']['disable_url_validation'] = true;
$a->config['system']['disable_email_validation'] = true;
````

Please check if the registration then works.

**Comment by annando** [comment]
@dertuxmalwieder Did the workaround worked?

**Comment by dertuxmalwieder** [comment]
Hmm, I'd surely prefer not having to *work around* it ...

(Sorry, currently quite busy.)

**Comment by strk** [comment]
I found the time to inspect the problem and found that mod/openid.php is running a "normalise_openid" function breaking the openid url I enter so that it doesn' match the one I register in the user profile. Removing the normalization part allows me to login:

```
diff --git a/mod/openid.php b/mod/openid.php
index 5d5539f..fffdb81 100644
--- a/mod/openid.php
+++ b/mod/openid.php
@@ -18,7 +18,7 @@ function openid_content(&$a) {
 
                if($openid->validate()) {
 
-                       $authid = normalise_openid($_REQUEST['openid_identity']);
+                       $authid = $_REQUEST['openid_identity'];
 
                        if(! strlen($authid)) {
                                logger( t('OpenID protocol error. No ID returned.') . EOL);
```

**Comment by strk** [comment]
No wonder: mod/settings.php has the normalise_openid commented out !

**Comment by strk** [comment]
@tobiasd it was you with 8367cadeeffec4b6792a502847304b17ceba5882 who removed normalization from settings, but not from mod/openid.php -- please fix!

Since you're at it, it may be good to drop the debug logging in library/openid.php around line 433

**Comment by tobiasd** [comment]
> Since you're at it

I am certainly not - sorry. Last year I could still test it and it worked when tested, but since then my last OpenID related services have dropped out of the web

**Comment by strk** [comment]
@tobiasd there you go: #2530 -- retains all compatibilities

**Comment by strk** [comment]
(and sorry for hijacking this issue which has nothing to do with OpenID)

**Comment by pnoll1** [comment]
I had the same issue as  @dertuxmalwieder

Adding @annando's suggested code to .htconfig.php:
`$a->config['system']['disable_url_validation'] = true;
$a->config['system']['disable_email_validation'] = true;`  
 allowed me to complete registration.

**Comment by kousu** [comment]
I ran into this trying to install Friendica just now. PHP/5.6.27 and also on FreeBSD:
```
$ uname -a
FreeBSD federation.definitelyreal.coffee 10.1-RELEASE FreeBSD 10.1-RELEASE #0 r274401: Tue Nov 11 21:02:49 UTC 2014     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64
```

It showed up as
```
Warning:  Cannot modify header information - headers already sent  by (output started at  /usr/local/www/apache24/data/friendica/include/network.php:415) in /usr/local/www/apache24/data/friendica/index.php on line 502
```
after submitting the form `register.php`.

I traced the problem to `dns_get_request()`, read over http://www.php.net/manual/en/function.dns-get-record.php, and created this test script on my install to see what was up.
```
<?php
# phpinfo();
#error_reporting(E_ERROR);
$domain = "kousu.ca";

echo "<h1>DNS_ANY (the default when unspecified)</h1>";
echo "<pre>";
print_r(dns_get_record($domain));
echo "</pre>";

echo "<h1>DNS_ALL</h1>";
echo "<pre>";
print_r(dns_get_record($domain, DNS_ALL));
echo "</pre>";

echo "<h1>DNS_A + DNS_CNAME + DNS_PTR + DNS_MX</h1>";
echo "<pre>";
print_r(dns_get_record($domain, DNS_A + DNS_CNAME + DNS_PTR + DNS_MX));
echo "</pre>";

echo "<h1>DNS_A + DNS_MX</h1>";
echo "<pre>";
print_r(dns_get_record($domain, DNS_A + DNS_MX));
echo "</pre>";

echo "<h1>DNS_A</h1>";
echo "<pre>";
print_r(dns_get_record($domain, DNS_A));
echo "</pre>";

echo "<h1>DNS_CNAME</h1>";
echo "<pre>";
print_r(dns_get_record($domain, DNS_CNAME));
echo "</pre>";

echo "<h1>DNS_PTR</h1>";
echo "<pre>";
print_r(dns_get_record($domain, DNS_PTR));
echo "</pre>";

echo "<h1>DNS_MX</h1>";
echo "<pre>";
print_r(dns_get_record($domain, DNS_MX));
echo "</pre>";
?>
```

From this I determined that DNS_CNAME and DNS_PTR are failing (at least for my domain) which then fails the entire call for any call that includes them: DNS_ALL, DNS_A + DNS_CNAME + DNS_PTR + DNS_MX, DNS_CNAME and DNS_PTR. Since the (my?) defaults have `error_reporting(E_WARN);` set this also prints out a warning and screws up the PHP headers.

It seems that a better solution is to use DNS_ANY (i.e. the default). In my copy of network.php I removed the type arguments and now registering works:
```
-        if(($h) && (dns_get_record($h, DNS_A + DNS_CNAME + DNS_PTR + DNS_MX, DNS_CNAME) || filter_var($h, FILTER_VALIDATE_IP) ))
+        if(($h) && (dns_get_record($h) || filter_var($h, FILTER_VALIDATE_IP) ))
```

![It can't be the DNS](https://cloud.githubusercontent.com/assets/987487/20613379/5d9f8484-b291-11e6-8a6b-916b2cccf74f.png)

I'm going to submit a patch for this.

**Comment by zotlabs** [comment]
Yes, we had the same issue with hubzilla (derived from the same code originally) and FreeBSD's implementation of dns_get_record() did turn out to be the source of the issue. It would be nice to get it fixed upstream, but we decided to use the same workaround (DNS_ANY) as it comes up every few months and sucks up dev resources; and the added granularity of the original request flags didn't provide much additional benefit. We're mostly trying to prevent folks from putting in totally fake emails because they won't receive the registration email and actually use the software hence they just suck up server resources. Either way, the DNS check is only marginally helpful and at best catches an occasional typo and at worst makes folks with FreeBSD dislike the software.

**Comment by kousu** [comment]
Oh yeah? So it is FreeBSD? Well, I am glad I traced out the problem and was able to patch it!

**Comment by kousu** [comment]
As an aside the messages that show up in the UI just say "Registration successful" or "Invalid email address", when really neither of those things are known at that point; an email is usually validated imo just by regexp; if you want more, you should go all the way and try to deliver a message because you don't know if it's /really/ valid until the remote server accepts it.

**Comment by zotlabs** [comment]
In the early days we used a simple regex and people could (and did) get past the check by typing 'a@b.' so we tried to come up with a better test. This actually works well and has been working for about 5 years now on everything but the occasional bug report from FreeBSD folks (I believe MacOS has the same issue but not many folks run webservers on MacOS).

**Comment by Hypolite** [comment]
Have we changed how we use `dns_get_record()` since?

**Comment by annando** [comment]
We had some change with the DNS calls, possibly it is fixed now?

**Comment by annando** [comment]
Since there hadn't been any answers, I will close this issue when no one disagrees now.

**Comment by kousu** [comment]
What DNS changes happened? Do you use DNS_ANY now? That seemed to be the consensus that would fix it, it just needed a one line patch.

**Comment by MrPetovan** [comment]
Thanks for the feedback, closing for now.
