### ISSUE TITLE
'nowarn_insecure' setting is fetched from DB but there's no GUI to set it

### ISSUE THREAD

**Issue by strk** [friendica/friendica#2591]
I noticed that much code exists querying the user configuration for a "nowarn_insecure" flag, but there is no GUI to set that flag. I confirm it does work after adding a record manually in the pconfig table, but then I wonder what's the point in checking the flag if there's no way to set it...

**Comment by strk** [comment]
I'd add a GUI for setting it, FWIW

**Comment by redmatrix** [comment]
It has always been possible to set config variables in the .htconfig.php file and I backported util/config from redmatrix/hubzilla some time ago so that there is command line access to configuring 'hidden' or otherwise not-very-well documented configuration variables. Many of these were 'one-off' configurations to handle specific use cases. In this case *privacy* groups that contain members on non-private networks can be a huge privacy issue so this toggle was suppressed for the one or two people that understood and accepted the consequences.

**Comment by annando** [comment]
@redmatrix when posting to the groups, the message will be send only to receivers who are able to receive non public messages (Friendica and Diaspora). All other possible group members (OStatus and connector networks) will not receive such messages. So the warning is obsolete.

**Comment by redmatrix** [comment]
I wasn't aware of that change. In that case both the message and config setting should probably just be removed.

**Comment by strk** [comment]
In that case a WARNING should appear when sending non-public messages to recipients not able to receive them. Does that happen ? I'd want to know if a message is not going to be delivered to all the ones I requested as recipients.

**Comment by tobiasd** [comment]
this is fixed with #2940  so I'll close the issue
