### ISSUE TITLE
hcard - vcard info presented twice

### ISSUE THREAD

**Issue by redmatrix** [friendica/friendica#2716]
I'm on libranet.de running Frio. Whilst looking at hcard formats across different protocols I noticed the vcard was presented twice on https://libranet.de/hcard/mike

As a result some HTML id elements are duplicated which could cause parsing issues

**Comment by rabuzarus** [comment]
Can you describe it a little bit more precise? If I visit the your hcard I see it only once. The only thing is, that there is the "vcard-short-info-wrapper" inside the code (with user photo, name and addr). But the "vcard-short-info-wrapper" content does have other ID's than the regular vcard elements which are used for scraping.

Can you please tell me which HTML are duplicated?

**Comment by redmatrix** [comment]
view source, look for vcard-short-info-wrapper

**Comment by rabuzarus** [comment]
Ahhrg, I see. There is second container which is only visible for small displays (while aside is hidden for small displays). While I don't really see a problem to use class names for the "short-info-wrapper" content as identifiers instead of ID's I don't know if this would work also for traditional hcard elements.

@redmatrix @annando 
Are there hcard elements which are scraped by it's ID?

**Comment by rabuzarus** [comment]
This was a good example that commenting code could be very useful & important. After 2h writing js parts to move the content of the aside section in dependence of the display size I read my own comment that the code for the mobile aside isn't in use anymore :-) So I only had to delete it. I would never have recognized this without this comment.

**Comment by annando** [comment]
I guess we can close this issue?
