### ISSUE TITLE
[notifyall] Test mode doesn't work

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#2764]
The addon 'notifyall' has a test mode (only send to administrator). I tried to send a test message to the admin only, but got an error notification "no recipient found". My admin account has a valid email address \<admin[at]libranet[dot]de>.

Edit: Also, the sender of these mails is "Libra☆net Administrator" \<sys[at]libranet[dot]de>. "sys" isn't a valid mail user on my server. Where does it come from? No recipient can answer to these notification mails. Is this the intended behaviour? 
Wouldn't it be better to use something like "no-reply@server.tld" or use the actual email address of the admin as the sender address?

**Comment by zotlabs** [comment]
This was backported from hubzilla it seems and is looking for config.system.admin_email in test mode; whereas in Friendica this is just config.admin_email

'sys' is also a dedicated system channel in hubzilla - although it typically has no email address assigned. noreply would probably be a better choice. The intent was to not leak the real email address (which is considered a privacy issue by some); although it could also be argued that the site admin should always be a reachable human. Perhaps 'postmaster@$domain.$tld' would be a better choice all around, since it's a required address - although few site admins actually set this address any more.

**Comment by zotlabs** [comment]
The most flexible solution would probably be to allow the admin to set the reply-to address to their liking from an array of choices or from a blank text field.

**Comment by rabuzarus** [comment]
I will change this. But at the moment I'm very busy with other stuff

**Comment by zotlabs** [comment]
PS> The hubzilla addon was updated with a choice of sender addresses.

**Comment by tobiasd** [comment]
Admins can set an sender email adress in the page config, the senders name can be configured as well,  I'll have a look today.

**Comment by AlfredSK** [comment]
Great! Will test it as soon it is merged.

**Comment by tobiasd** [comment]
As @AlfredSK had already tested the changes and the PR was merged, I'll close the issue.
