### ISSUE TITLE
Highlight the "Like" link for liked posts/comments

### ISSUE THREAD

**Issue by Hypolite** [friendica/friendica#2792]
When one clicks on the "Like" link on any publication, it should turn to "Unlike" immediately to acknowledge the action. If the action isn't successful, it should of course revert back to "Like".

When a post have been already liked, the "Like" link should already be changed to "Unlike". In that case, clicking on the "Unlike" link should immediately turn it to "Like" to acknowledge the action.

I'll look into the code hopefully this week-end to see if I can make the change myself. Not sure if it is a theme-specific change?

![screen shot 2016-09-23 at 2 18 28 pm](https://cloud.githubusercontent.com/assets/925415/18796740/a490e254-8198-11e6-9db7-785c2f1e21ba.png)
Since I've already liked this post, the "like" link should read "unlinke" instead.

**Comment by rabuzarus** [comment]
> Not sure if it is a theme-specific change?
It is not theme specific. The `like` link call the js `function dolike(ident,verb)` in `main.js` which points to `/mod/like.php` which calls `function do_like($item_id, $verb)` in `/include/like.php`. I guess you should have a look at the code following after https://github.com/friendica/friendica/blob/develop/include/like.php#L138

**Comment by tobiasd** [comment]
I see confusion dawning at the translation front with mixing translations for "I don't like this anymore" and "I dislike this" :-)

**Comment by zotlabs** [comment]
We'll probably be implementing this in hubzilla soon. The toggle has always been problematic; and it's just a matter of squeezing time into the dev schedule to make it happen. For translations we've been discussing something like 'remove like' (and/or just provide a red x in the button next to the thumbs up)  which should distinguish it from a thumbs down. The biggest issue is whether or not to count the likes and not allow more than one (which is what has given us grief all along).  I'm thinking we just remove all the counting logic and not restrict how many times you can like something. If we limit it at all, this will probably be just a 'distinct author' list in the display logic rather than restricting the number of activities posted.

**Comment by Hypolite** [comment]
After a while navigating the code, it turns out the solution was pretty simple and doesn't add any DB query like I feared. Sweet!

The PR only updates the frio theme code but it could easily be ported to other themes.

**Comment by Hypolite** [comment]
I'm sad to report my fix for this issue is not working as expected. As shown on the following example, the "Like" link is active but I never liked the post myself as shown in the the likers list. I suspect this has to do with me being the original author of the post.

![friendica-like-lit-bug](https://cloud.githubusercontent.com/assets/925415/21467824/7fcbc1aa-c9c8-11e6-8b5c-44e508b8eb8f.png)

I'll look into it next week.

**Comment by Hypolite** [comment]
It should be pretty clear by now that I didn't look into it "next week", but I'm still committed to fix this issue.

**Comment by Hypolite** [comment]
The reason I reopened this issue seems to stem from a confusion in the `item` table fields regarding what contact should be the `contact-id` for `like` items. Nothing to do here while #3203 isn't sorted out.

**Comment by Hypolite** [comment]
The solution seems to be using `author-id` and finding an easy way to match it to the current logged in contact id.
