### ISSUE TITLE
Default profile link should be local, not remote

### ISSUE THREAD

**Issue by Hypolite** [friendica/friendica#2803]
Before setting up my Friendica server I had set up a personal Diaspora\* pod where I had ~100 contacts. I manually reconnected to all those accounts with my Friendica account, so my timeline is mostly Diaspora posts coming from Diaspora contacts.

The issue I have is whenever I click on a profile picture or name, it goes to the remote profile URL on Diaspora. Since I'm not connected to their pod, it only shows the public info, which usually isn't much. However, if I trick Friendica into showing the local profile (by going to the contact's "Network Posts" URL and then stripping the end), then it shows the semi-private information you are entitled since you have that contact as a connection.

My suggestion is: why not use the local profile page URL everywhere instead of the remote profile page URL since it holds more informations anyway?

**Comment by tobiasd** [comment]
There is no "trick" needed, it is simply the contact editor which shows some public information about your contact. The remote profile usually has more information hence it is linked.

**Comment by rabuzarus** [comment]
Some note as author of the frio theme. In most of the friendica theme a click on a link opens the link in a new tab. I changed this behavior in frio. In the most cases a link should open in the same tab. This seems to me more natural because most of the other websites out there work in this way (if you want to open a link in a new tab chose right mouse button context menu).
@tobiasd is right with highlighting that remote profiles does have more information (Friendica Network: more profile information with the possibility of per contact personalized profile information, newer posts, information about the connected contacts, information about the calendar entries of the profile owner, and his/her image gallery, personal themes of the profile page).
I also changed the behavior because it feels more natural (like other centralized network platforms) if you stay within the friendica network (because of frios "remote_nav"). So you can jump from profile to profile to profile and back to your own friendica instance.
Sure this doesn't work on other network protocols but we should rather try to find solutions together with the developers of the other open source social networks. But this is a real difficult mission

**Comment by annando** [comment]
You don't need to strip the end of the url. You simply go to the "network posts" page where - depending on your chosen theme you will see the posts on the right and profile information on the left. Or you chose "edit contact" which is the link you get by stripping the end.

**Comment by Hypolite** [comment]
> Some note as author of the frio theme. In most of the friendica theme a click on a link opens the link in a new tab. I changed this behavior in frio. In the most cases a link should open in the same tab. This seems to me more natural because most of the other websites out there work in this way (if you want to open a link in a new tab chose right mouse button context menu).

I am 100% with you on this philosophy. But when I click on a profile, I expect to stay on the same website, unless I know it's an external link, especially since this local profile page exists. For example, since yesterday, I archived two contacts. Each time, I first clicked on their profile pic to reach their profile page where I could hopefully get the opportunity to archive them. And in both case I ended up on a wildly different-looking website with no action menu for me to use.

I understand the concept of having most of your public data on the server where your profile live, but I feel like this particular behavior is confusing compared to conventional centralized networks and even the decentralized ones that are trying to match their look and feel (that has not political charge).

I now know that I have to click on "Edit Contact" even when I don't want to edit anything about the contact, and that's pretty annoying to me. Since I have the power to change it, I'll probably submit a Settings toggle to choose which link should be presented by default, the local profile or the remote one. I'll keep the default as the current behavior because I don't want to alienate current users.

**Comment by annando** [comment]
The naming of the link "Edit Contact" has to be changed. In the last version we changed the function of that link very much - without renaming it (yet).

I completely do understand your concern. We should have both links (the external and the internal) very present (and maybe switchable). Currently there is only the problem that we have different pages for people we follow and who we don't follow. I would like to unify this page in the future.

**Comment by Hypolite** [comment]
I found a new interesting limitation with the frio theme regarding the remote profile links. The hovercard doesn't show on the profile picture/link of the author of an embedded shared post, which means that to add them as contact, you have to go to the remote profile, grab the profile URL/enter yours, even though there is a local profile page that would prevent you to do any manual task.

**Comment by rabuzarus** [comment]
This is not a limitation. The hovercard (as it actual work) starts if there is an element with the class `userinfo` The js does grab the href which should the link to the remote profile url (because we use the profile link - in short `nurl` for normalized url - to identify a certain contact. This is a technique we also us in other parts of friendica. It is because name and nick name aren't a unique identifier for a certain contact). The hovercard (/mod/hovercard.php) searches if the contact is in our db and if we have more information about this contact.) I didn't implement it because many of the shared posts in friendica are from twitter accounts and we don't store twitter contacts in the `gcontact` table. And since searching in the `gcontact` table is a very resource intensive process I thought it would be better to have no hovercard for shared posts

**Comment by Hypolite** [comment]
I don't think there should be an hovercard for shared posts authors either, but that just supports my opinion that profile links should be local.

**Comment by rabuzarus** [comment]
> which means that to add them as contact, you have to go to the remote profile, grab the profile URL/enter yours, even though there is a local profile page that would prevent you to do any manual task.

This isn't need in other places because if it's a friendica contact we use the zrl for transmitting the own profile url. So if you click connect on the foreign friendica profile you only have to apply.
In some cases (e.g. network stream or if you search locally for a contact) you can use frios hovercard (in other themes the dropdown menu) to follow this contact and you won't leave your friendica instance.

> I don't think there should be an hovercard for shared posts authors either, but that just supports my opinion that profile links should be local.

Shared posts are a little bit special because it could be that your instance don't know the author of the post which is shared. A shared posts is doesn't have an own entry in the db. It just exist as some html & bbcode in the entry of the the person who shared the post. If the author of the original post (the one which gets shared) isn't known to your local system there wouldn't be a local profile. If this person is known to the system we don't know about this because at the present time we don't check if this contact is known

**Comment by Hypolite** [comment]
Ha, good point, thanks for the explanation.

> This isn't need in other places because if it's a friendica contact we use the zrl for transmitting the own profile url. So if you click connect on the foreign friendica profile you only have to apply.

Not sure what you mean by that. Using the public directory, I always had to enter my own profile URL to connect. Are you saying "when clicking on a remote Friendica profile URL from our own server"?

**Comment by annando** [comment]
BTW: This is really a good argument to improve the whole reshare stuff. Although it will be tricky to distinct between "real" reshares and imported stuff (fake reshares) from Twitter or Google+.

**Comment by rabuzarus** [comment]
> Are you saying "when clicking on a remote Friendica profile URL from our own server"?

Yes this is what I mean. You can search for contacts in the navbar search field with `@contactname` or use the people search aside widget in /contacts or /directory.
At the present time there is there are to modes of internal behaviour (can be changed in the admin settings). The first one does a request to the global directory and get it results from it. But this method isn't that much powerful because it only requests for certain fields and the result is limited.
The second option would be to let your instance crawle for possible contacts at known servers through the poco routine and let store it in the `gcontact` table. So you would be able to use the internal search which is more powerful.

> Using the public directory, I always had to enter my own profile URL to connect.

I just tried it out. If you call the global directory link  from your local directory page the the global directory is called with the zrl parameter (e.g. http://dir.friendica.com/?zrl=https%3A%2F%2Ffriendica.kommune4.de%2Fprofile%2Frabuzarus ). If I now select one of the first contacts and try to connect with one of these profiles my personal profile url is already available for contact request and I don't have to insert it.

**Comment by Hypolite** [comment]
How do you get this URL with the `zrl` URl parameter? When I go to the dropdown menu -> Directory, the URL is simply http://dir.friendi.ca

**Comment by rabuzarus** [comment]
Yes I already noticed that your directory link points to the global directory. Usually it should direct you to your local directory (`/directory`) where a link (with zrl) to the local directory appears 

@annando do we have a setting for this?

**Comment by Hypolite** [comment]
This is what I have in the Admin -> Site settings:
**Global directory URL** 
[ http://dir.friendi.ca ]
URL to the global directory. If this is not set, the global directory is completely unavailable to the application.

**Comment by rabuzarus** [comment]
yes global directory have to be available. But there exists also a local directory under `/directory` and usually the user menu should link to the local not the global one.

**Comment by Hypolite** [comment]
I just found why, I set up my server as a single-user instance, which is changing the dropdown menu directory URL to the public directory without the `zrl` parameter.

**Comment by fabrixxm** [comment]
> I set up my server as a single-user instance, which is changing the dropdown menu directory URL to the public directory 

which make sense

> without the zrl parameter.

which doesn't.. :-)

**Comment by annando** [comment]
@Hypolite You really find much stuff that we can change :-)

**Comment by Hypolite** [comment]
I'm choosing to take that as a compliment 😄

**Comment by annando** [comment]
You really find much things that can be improved. And you are really, really quick with an improvement by yourself. Only thing that is missing is the communication before the improvement since sometimes the intended behaviour of the system interferes with your intention. This leads to pull requests being closed or massively changed before acceptance - which hopefully doesn't prevent you from continuing your work. So a little bit of communication before the pull request would hopefully make it more smoothly for everyone.

**Comment by Hypolite** [comment]
First time I'm contributing to an open-source project, I'm learning!

**Comment by Hypolite** [comment]
Today I dabbled into making every profile link a local one, but it clearly never was intended in any way, shape or form. I'll submit a lightweight PRs for the things I can change in the current state (the profile icon in the hovercard and the zrl parameter for the public directory), but it clearly is a little defeating.

**Comment by Hypolite** [comment]
Closed via #3339

**Comment by MrPetovan** [comment]
Actually closed by #9331
