### ISSUE TITLE
[install] Add default support for native emojis

### ISSUE THREAD

**Issue by Hypolite** [friendica/friendica#2808]
Currently, whatever the default collation for the database is, all tables and fields created via the web install are assigned the "utf8" charset, which is insufficient to show native emojis.

The correct "utf8mb4" charset is only applied once the .htconfig file is created from the default value or if the database was created from the command line.

I understand the need to keep the "utf8" charset for compatibility reasons (MySQL 5.5.2 and below), but "utf8mb4" is a feature that is around since 2010, I think it now should be the standard and "utf8" the if-everything-else-fail fallback, and not the other way around.

What do you think?

**Comment by tobiasd** [comment]
Isn'T this what#2758 is doing?

**Comment by Hypolite** [comment]
Not completely, since my DB tables and fields ended up being all utf8, although the DB itself was set to utf8mb4 and the default in the config file is utf8mb4. I believe #2815 fixes the lingering issue.

**Comment by annando** [comment]
This is really complicated. I'm thinking about a way to convert the old data to utfmb4. But the problem is that until now we used the charset that was default at MySQL - which is mostly "latin1". That means that all data in the database is crumbled. Problem is that we had to detect the current charset that is used for the connection. The we had to change the collation and this whole stuff without destroying the database.

I guess that it is really hard to do this automatically. I would prefer to create some documentation so that experienced admins can do it on their own.

What do you think?

**Comment by Hypolite** [comment]
The fix only covers new web installs. Migration can be tricky. For me it was easy, I just converted the collation of a few fields in the `item` table, but the database was already UTF-8 and I may have missed relevant fields in other tables.

Not sure about migrating from latin1, it's been a while since I had to do that.

**Comment by annando** [comment]
Yeah, migration is tricky - that's why I wouldn't automate it ;-)

I haven't worked very much with collations. Could you help at improving this whole behavior?

**Comment by Hypolite** [comment]
Apparently, if the latin1 database is coherent (no UTF data stored), the it seems like a simple matter of ALTER TABLE queries as shown here: http://dba.stackexchange.com/a/123844

Thing can get hairy if there are multibyte characters in a single byte collated database but it's a separate issue that should be spotted and fixed independently of the migration.

**Comment by annando** [comment]
Problem is that for Friendica the solution is more like this one: http://blog.hno3.org/2010/04/22/fixing-double-encoded-utf-8-data-in-mysql/ or here http://stackoverflow.com/questions/5951871/how-to-correct-double-encoded-utf-8-strings-sitting-in-mysql-utf8-general-ci-fie

Although we declared the database as UTF8 but the default connection for mysql is latin which leads to UTF8 characters being stored in singled bytes (which is really ugly).

For pirati.ca I did it the "hard way" (means much manual work). For my other server squeet.me I hopefully will find a much smarter way that would lead to a script that would do the whole work automatically.

**Comment by zotlabs** [comment]
Emojis have been available in Friendica for several years, regardless of DB encodings. It's all due to this line...

   $Text = preg_replace('/\[\&amp\;([#a-z0-9]+)\;\]/', '&$1;', $Text);

Raw emojis in UTF-8 is another story.  I'm still not sure how that translates to postgres and I'm not going to tell anybody how to store data. But you can use emojis in your Friendica posts today.

**Comment by annando** [comment]
I'm not sure if the 4 byte unicode characters are only used for emojis but for "serious" stuff as well. But I think that the limitation to 3 byte unicode characters is indead a limitation that needs to be lifted. (Which is done with the next release)

Concerning Postgres: According to the documentation it supports 4 byte unicode characters out of the box: https://www.postgresql.org/docs/8.4/static/multibyte.html

This means that with a Postgres setup with UTF8 there would be no problem at all.
