### ISSUE TITLE
Profile image discrepancy between remote contact local pages

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#2811]
When a new remote contact is created locally, a picture is created for it, usually a stretched version of the original profile image. However, the different tabs of the local pages of the remote profile don't always show the same.

Example:
- Status tab: https://friendica.mrpetovan.com/contacts/334/posts = original aspect
- Profile tab: https://friendica.mrpetovan.com/contacts/334 = stretched image
- Advanced tab: https://friendica.mrpetovan.com/crepair/334 = original aspect

First, is there a canonical way of referencing a remote contact profile image that could be universally used on all pages?

Second, can we stop stretching automatically profile images on contact import? It simply is ugly, and while it can make sense for small thumbnails, I think it is unwarranted for the main profile image?

What do you think?

**Comment by rabuzarus** [comment]
This is because https://friendica.mrpetovan.com/contacts/334 uses the `vcard-widget.tpl`. The other pages you mentioned use the `function profile_load()` which uses the `profile_vcard.tpl`. I guess they use different sources for the picture.
`profile_load()` does take the picture directly from the `contact` table. For `vcard-widget.tpl` it is taken von the app `$a->data['contact']['photo']` (I don't know where the picture originally comes from). You may want have a look in `/mod/contacts.php`

BTW: The different image sources are no Frio issue. It's the data friendica provides

**Comment by Hypolite** [comment]
Thanks, I removed the theme-specific label.

What about the stretching of the remote contact profile picture, do you know if we can stop doing it easily of if it's somehow needed for something?

**Comment by annando** [comment]
We need to find out if there are problems when a profile picture is stretched proportionally. Maybe we need a new function for it. This function should respect some maximum value that would be either the vertical or the horizontal value.

Then we have to see if there are changes needed to the themes (I guess so).

**Comment by tobiasd** [comment]
IIRC @annando changed something recently with the profile image handling - is this still an issue?

**Comment by annando** [comment]
@MrPetovan can we close this?

**Comment by MrPetovan** [comment]
I haven't witnessed this issue in a while.
