### ISSUE TITLE
[frio] Opening notifications in new tabs

### ISSUE THREAD

**Issue by Hypolite** [friendica/friendica#2814]
Currently, clicking on notifications items opens it in the same window, regardless of the clicking method (left, center, Ctrl+click). I'd like to let the users (me included) to choose how I want to open the notifications. I usually open all unseen notifications in separate tabs to save some time but in the current state, I can't do that.

I can't seem to find where this behavior is located in the code, but it seems like a trivial change to me, pretty much transparent for anyone that wasn't trying to open the notifications in a new tab.

**Comment by fabrixxm** [comment]
that's because Frio don't add an `a` tag in notifications but captures the click on `li`.
It should be an easy fix.
This is the current situation:
![notiffrio](https://cloud.githubusercontent.com/assets/309361/18943411/b93bbb94-861f-11e6-91d3-310e4ca114d5.jpg)

An `a` element just after the `li` or in place of the `div.notify-entry-wrapper`, with correct  `href` and `display: block` should work...

**Comment by Hypolite** [comment]
I just tried, and the wrapping `a` tag conflicts with the profile link inside the notification itself. Clicking on a notification just closes the notification dropdown.
