### ISSUE TITLE
Improve code cleanliness

### ISSUE THREAD

**Issue by Hypolite** [friendica/friendica#2825]
I was trying to debug #2823, and I made the mistake to enable and display PHP Notices. The Friendica page I was working on blew to my face with dozens of soft error messages. Mostly missing indexes, missing variables and non-static functions statically called, but it is slightly worrying for me to see a code base in such a state of neglect. Not only it is a debugging display issue, but also a performance one, as PHP Notices, even not displayed/logged will consume CPU cycles.I have no problem starting to fix all those notices, but it seems to be a massive endeavor touching at every part of the code.

And while I was chasing error after error after error, I noticed that there wasn't any coding convention between different files, or even inside single files. I can propose the style I use habitually in my work to be applied (automatically with tools) to every file I'm working on, but I need your approval first.

Sample:
```php
<?php

class ClassA extends ClassB implements InterfaceA, InterfaceB, InterfaceC {

	public $number = 1;
	private $letters = array(
		"A",
		"B",
		"C",
		"D"
	);

	public function method($text, $number) {
		if ($text === NULL) {
			$text = "a";
		} else if ($number == 0 && $text == "Friendica") {
			$text = "empty";
		} else {
			$number++;
		}

		switch ($number) {
			case 1:
				return method("text", 22);
			case 2:
				return 20;
			default:
				return -1;
		}
	}
}

?>
```

**Comment by annando** [comment]
Especially in old code you see massive difference in the coding style. There weren't any checks not even in the way the text was indented.

I would prefer some more coding rules that should be based on how we are working today. The goal should be readability and avoiding of php warnings and notices.

But I think we should be liberal in some points. For example: There are different opinions if single code lines behind an "if" need to be put in curly brackets or not. I - personally - find it more beautiful without the brackets, others are having a different opinion. Or: Strings are sometimes put in ", sometimes in ' - I don't see much regulation needs there as well.

But: I would like to have a regulation of where to put the curly brackets and how to do indenting. The naming of functions (camel case vs. separation via "_") should be unified as well. And the naming itself should be defined as well (e.g. not naming a function "validate_data" but using "data_is_valid" when the function returns a boolean).

The current way is now the use of static classes. They can be applied easily to the existing code and they can contain local functions.

I think that we should continue that way. This means that - step by step - we take old code and replace them with static classes that are coded in a better way. I wouldn't like to use some automatic converter to existing code since this is bad when using "git blame" to find the origin of some problem.

**Comment by rabuzarus** [comment]
I would love to regulate if if we use `$arr["key"]` or `$arr['key']`
The last days also the question arises if we should regulate the writing of translation strings

**Comment by rabuzarus** [comment]
BTW: We already have an issue for this https://github.com/friendica/friendica/issues/2103

**Comment by Hypolite** [comment]
I won't start working on PHP error messages until #2832 is reviewed and merged.

**Comment by annando** [comment]
I see a huge problem in this pull request. Since it changes (nearly) every code line it conflicts with every current development and it cannot easily be reviewed.

I really would prefer to do this step by step. And before we start with it, I really would like to see that we agree on some details like "tabs vs. spaces".

**Comment by tobiasd** [comment]
I totally agree with Michael here, changing so many files in one PR is a bad idea for me.

**Comment by Hypolite** [comment]
Fair enough. I didn't change all those files by hand so it's not a big deal.

@annando: I'll refer you to #2103 for discussion around the standards themselves.
