### ISSUE TITLE
Atom feed does not include poco fields

### ISSUE THREAD

**Issue by Gargron** [friendica/friendica#2858]
While Friendica Atom feeds declare the `poco` (portable contacts) namespace on the root node, no `poco` fields like `displayName` or `note` are included in the `dfrn:owner` tag. (Also, why `dfrn:owner` and no `author`? `author` is included on an entry level but not feed level)

**Comment by tobiasd** [comment]
> Also, why `dfrn:owner` and no `author`? `author` is included on an
> entry level but not feed level

Because the owner starts a thread, but other participant postings from a discussion will be in the Atom feed as well, but they are not from the owner of the thread but from the author of a posting. There is however a crippled feed which does only include postings from the owner which was introduced so StatusNet does not have to deal with replies not from the owner of a posting.

**Comment by annando** [comment]
BTW: Is the atom feed really needed for the OStatus transmission?

**Comment by Gargron** [comment]
Yes! It's the primary source of data for other instances.

**Comment by annando** [comment]
Seems like I have to compare an original GNU Social feed with the one that is provided by Friendica.

**Comment by Gargron** [comment]
I'm a Mastodon developer, not GNU social (though we're compatible). You can check my feed: https://mastodon.social/users/Gargron.atom

**Comment by annando** [comment]
@Gargron Just because I'm curious: How are you developing the protocol stuff? I haven't found documentation and just did some data investigation.

BTW: I would appreciate it if you could tell us every implementation problem that we have done when you find it.

**Comment by Gargron** [comment]
@annando From someone who tried following me from Friendica, I heard that they had an issue with the code trying to fetch `https://https://mastodon.social/users/Gargron/.well-known/host-meta` (and obviously failing). I don't really know about the specifics, but I'm on the #mastodon channel on Freenode and if you need me to help you debug by sending you Salmons we can do that

**Comment by Gargron** [comment]
All of the protocol stuff is already done now and it's only a question of adjusting to the quirks of other platforms. Initially I looked at how GS atom feeds looked, read through rstatus code (another, now abandoned project that was GS-compatible), I read the Webfinger specs, PubSubHubbub specs, Salmon specs and occasionally refererred to ActivityStreams specs. Now the problem with all of those is obviously that they're scattered, hard to find, but most importantly there are now different versions, like JSON-based ActivityStreams, JRD-based Webfinger etc. I stuck to XML/XRD for now. So yeah it's all pretty confusing.

Oh and now a new protocol is being announced, called ActivityPub, that aims to replace ActivityStreams *and* Salmon... I am not sure I am ready for that, but we'll see. Can't imagine how that will work with backwards-compatibility.

**Comment by annando** [comment]
Could you have a look at this feed: https://pirati.ca/dfrn_poll/heluecht/

Is it looking better? Am I still missing something relevant there? If not then I will do a pull request tomorrow.

The probing of mastodon profiles should be fine now. There were some incompatibilities since Friendica hadn't probed with the "acct:" prefix (GNU Social doesn't need it) and it expected a "data:" prefix for the key (which is missing in mastodon - but which (I guess) should be added).

**Comment by Gargron** [comment]
That feed looks good!

I added the `data` prefix a while ago. My question is, can you actually follow/mention me from Friendica now?

**Comment by annando** [comment]
Currently I'm busy with performance issues so all issues other than performance things are done after this. This includes the changes I started in this issue since I have to check why Friendica wants to have the feed like this.
