### ISSUE TITLE
Editing a post, mentions turns to plain text

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#2880]
When first creating a post, mentions correctly auto-complete (on frio). When I start typing `@Fri`, I'm being suggested `Friendica Developers`. If I accept the suggestion, the following gets added to the textarea: `@developers+69`. If I publish the post, a link to the public forum will be correctly added.

However, if I want to edit the post, the textarea content turns into `@Friendica Developers` and if I submit it as is, the mention link disappears from the post displayed content. In order to restore the mention, I have to manually enter `@developers+69` instead of the converted mention in the textarea, and there isn't any auto-complete anymore (on frio, haven't tested elsewhere).

I don't have any bandwidth to look into it, but I don't believe this is a big job. Or is it?

**Comment by tobiasd** [comment]
The connection to the mentioned is persistend though. But I agree it would be nice, if the mentioned account would remain click able.

**Comment by foss-** [comment]
Also from what I described in #3061 it seems the post in question no longer shows in the referenced forum group. So this is a real problem.

**Comment by rabuzarus** [comment]
OK, I have looked into this.
First, the fact that auto completion don't work is a frio bug

Second:
the item comes directly from the db. This means that in the `$item['body']` a mention looks like `@[url=https://helpers.pyxis.uberspace.de/profile/developers]Friendica Developers[/url]`
To get the correct mention à la `@developers+69` we would need to parse the item body, strip out the mentions, normalize their url and check every result against the contact table if they are valid contacts of the post owner. If so, we would need to replace every mention with `"@" . $contact['nick'] . "+" . $contact['id']`

I don't know how performance intensive this would be. But it seems that this could be improved because all used tags and mentions are stored in the `tag` column (bbcode formated) of the item table and all mentioned contacts seems to be in the `inform` column of the item table (e.g. `cid:822,cid:945,cid:324`)

**Comment by rabuzarus** [comment]
But there is another issue we have to think about. Adding or changing mentions musn't be used to change the permissions of the original post. If the added mentioned contact isn't in the original permissions the contact will never get this post

**Comment by annando** [comment]
Please don't refer to the "tag" column. This is some kind of legacy stuff. There is a side table for the mentions (Which I'm planning to rewrite for performance reasons).

**Comment by tobiasd** [comment]
looks like #5086 fixed the problem
