### ISSUE TITLE
MySQL - which versions of friendica are compatible with which versions of MySQL?

### ISSUE THREAD

**Issue by mexon** [friendica/friendica#2883]
My Friendica install has been basically dead for months, ever since I tried to move it from my old server running Ubuntu Lucid to my new server that's on Xenial.  My friendica version seems to be approximately Ginger 3.3.  I'd like to avoid upgrading if I can, because experience has taught me that it generally doesn't work smoothly with my custom plugins.

Most of the problems I have seem to be to do with MySQL incompatibilities from 5.1 to 5.7.  For example, text fields aren't allowed default values any more.  I've hacked up as much as I can, but it's not working very well and I don't have any time to spend on this project.

The current front page just advertises Friendica 3.5, which now supports "MySQL 5.5.3+".  But what's the maximum MySQL version?  And what's the acceptable version range of 3.3 and 3.4?

I'm trying to find a good compromise that doesn't require me to do too much porting work.  Any suggestions?

**Comment by zotlabs** [comment]
You can change your strict mode settings for mysql and everything should work again. If I recall the important settings you'll need are ALLOW_INVALID_DATES. If you're running something less than 5.7.5 you may need to look at NO_ZERO_DATE and NO_ZERO_IN_DATE.

http://dev.mysql.com/doc/refman/5.7/en/sql-mode.html

We've had several hubzilla issues against postgres which forces all NOT NULL string fields to be initialised when a row is inserted. I don't know if mysql strict_mode changes this but it so you may have to remove the NOT NULL on several char and text fields or add initialisers for them in insert statements. 

I'm hoping you won't have to deal with the latter issue because it means a lot of work. I think you'll be able to get away with just ALLOW_INVALID_DATES.

**Comment by mexon** [comment]
I got as far as the invalid dates already, and I guess that's working.  I'm asking about the NOT NULL string fields exactly because I started tackling it and realised how much work it would be.  If there have been a bunch of hubzilla issues, does that mean later versions of Friendica have added the initialisers in insert statements now?

**Comment by mexon** [comment]
My actual issue right now, by the way, is that MySQL is randomly hanging or dying.  Then Friendica spams the logs with millions of "database went away" messages until the disk fills up and the whole server dies.  Fun.

**Comment by zotlabs** [comment]
Any chance you could plug in MariaDB? Or are you tied to MySQL? I don't know if Maria has turned on strict mode yet. It might buy you some time. Anyway, we've tried to fix this all in hubzilla but it was a lot of work. I doubt it is updated in friendica but I haven't checked.

**Comment by zotlabs** [comment]
Possibly see if STRICT_ALL_TABLES or STRICT_TRANS_TABLES are set and turn them off if they are. I don't know how to do this, but these would let you use the old string initialisation behaviour.

**Comment by mexon** [comment]
I could try moving to MariaDB, but that sounds like a whole pile of "now you have two problems".  What I was hoping for was some kind of "this is a combination of specific ubuntu version / mysql version / friendica version that is known to not explode", or preferably several such combos I could choose from.  Substituting specific MariaDB versions would be good too.  Failing that, I guess it's head-down-charge-forward just-make-it-work with the latest version of everything - but given my level of free time, that's probably gonna take a year, by which time everything will have changed again.

**Comment by zotlabs** [comment]
This looks like it should work.

https://serverpilot.io/community/articles/how-to-disable-strict-mode-in-mysql-5-7.html

**Comment by mexon** [comment]
I've already turned off strict mode.  What I've got left is a bunch of miscellaneous failures.  Like my plugin still complains its database tables are at version 0.9 even though when I look in the database it clearly says 1.0.  Stuff that was working fine before.  And now it's complaining that there's no "process" table, so something's not automatically upgrading itself.  I've probably fatally compromised my database by now.

**Comment by zotlabs** [comment]
Apologies - but this is quite possibly beyond my ability to rectify.  I think turning off strict mode is the right thing to do under the circumstances until somebody makes it play nicely with MySQL 5.7+. On the bright side, the entire generation of the DB schema is (I think) automatic. So we need somebody who's more familiar with the current code base to weigh in on how you might repair the schema or over-ride and regenerate any parts that got messed up when it was in strict mode.  I think there's a function you can run to make the schema right no matter what it is currently, but this all happened after I moved on.

**Comment by annando** [comment]
AFAIK the 3.5 now doesn't have a default value for text fields anymore. But there are other incompatibilities with 5.7 due to removed SQL statements. I would suggest switching to MariaDB 10.x if this is possible for you.

Concerning missing tables it is easy. Just execute ````php include/dbstructure.php update```` from the command line to check and update the database structure.

**Comment by mexon** [comment]
Thanks for both of those suggestions, I'll give them a shot.  I've been noticing MySQL's gradual slide into obsolescence and delaying making the switch.  Guess it's time to rejoin the rest of the herd :-)

**Comment by Hypolite** [comment]
Friendica 3.5.2 requires at least MySQL 5.5 or compatible due to the conversion to `utf8mb4` character set.
Friendica 3.5.2 is also compatible with MySQL 5.7+ thanks to @annando and @Alkarex's work.

So the compatibility window has moved from supporting old MySQL version up to MySQL 5.7 not included to supporting from MySQL 5.5 upwards.

**Comment by mexon** [comment]
Thanks for the update!  And I would like to heartily endorse the move to utf8mb4 🐼

**Comment by annando** [comment]
@mexon is the issue solved for you?
