### ISSUE TITLE
what is the difference between friendica and hubzilla?

### ISSUE THREAD

**Issue by topstarnetwork** [friendica/friendica#2894]
what is the difference between friendica and hubzilla?
Thanks.

**Comment by Hypolite** [comment]
Friendica and Hubzilla are two different but similar software both spearheaded by the same man, Mike MacGirvin ( @redmatrix or @friendica on GitHub ). And while he officially left the development of Friendica to start Red/RedMatrix/Hubzilla in 2012 based on a new decentralized social network protocol (named `zot`), both networks are able to interface with each others, on top of a shared Diaspora* and GNU Social (OStatus) compatibility.

From my point of view after installing both on my server, Hubzilla is more advanced and experimental than Friendica is, and in turn Friendica is slightly more intuitive and stable than Hubzilla is.

I hope it answers your question.

**Comment by zotlabs** [comment]
Friendica is at heart and primarily implements a "federated decentralised social network". It is a social network which aggregates other social networks as well as providing its own protocol and social service. 

Hubzilla contains some social networking components, but builds on that to provide a decentralised content management system and publishing platform with some unique and interesting abilities when it comes to decentralised access control, identity, and permissions.

**Comment by topstarnetwork** [comment]
So if I am not mistaking hubzilla has the same "federated decentralised social network" aggregates other social networks but with more functionalities such as cms and publishing functionalities, application server (more enterprise features compare to friendica that friendica does not have?

**Comment by topstarnetwork** [comment]
I mean, is Hubzilla some  kind of portal software where you plug all kinds of thirdparty application such as liferay and exo java portal?

**Comment by zotlabs** [comment]
Actually no.  

Hubzilla represents what I like to think of as state of the art in decentralisation technology. It goes far beyond what we did in Friendica when it comes to decentralising core services which used to be available only on centralised silos. We decentralise *everything*. This builds on work I started in Friendica but it took a platform re-write to fully realise. 

Some federation bits were added a couple of years ago due to popular demand, but they are in conflict with a couple of core features such as nomadic identity. Nomadic identity is really special. You can create online clones of your channel and pop up at another site if your current site is having issues (either temporarily or permanently). This works incredibly well - *unless* you have friends on other networks.  My original account has moved a few times now. All my original friends are still there. My Friendica and Diaspora friends however are not. They need to be reconnected, and this is silly because nomadic identity was created to address that problem. 

The other feature we've spent a lot of time on is decentralised access control. This means you can publish webpages, videos, photos, create chatrooms, etc. and all of your web properties can have privacy settings that work seamlessly with anybody on Hubzilla. They don't need to have an account on your site. We can also create 'access tokens' and allow permissions to folks that don't have hubzilla accounts, so you can share a private video with your mom (as an example). 

These features are totally alien to most every other network and service and you can't just create a patch to make them work. It's a completely different way of looking at the world and would take a complete re-write of most projects to realise or make compatible.  As a result we were kind of forced to develop an entire suite of web publishing and cloud storage components which work with our services. This represents over four years of evolution from the original Friendica code base, so the projects are now quite different.

**Comment by tobiasd** [comment]
No, Friendica and Hubzilla are two different projects. As @zotlabs said, they have two entirely different angles of viewing on the topic of decentralized networking and presences. And those different view angles make the projects hard to compare. They have different sets of features, and different things they focus on. Users from both projects can interact with each other though, if both user nodes/hubs are.configured to allow this.

> what is the difference between friendica and hubzilla?

The more easy question would be, what do they have in common ;-)

For me, Hubzilla is decentral publishing of all kinds of things with a fine rights management. And Friendica is decentral social networking with a fine management of who you socialize with and connections to many other social networks. Publishing of things includes some social networking though, as does social networking include some publishing. And I know that the scope of this comparison is far to limited to grasp the complexity of the question asked.

If you have the time to test both, try them. Write down what you expect before you do. Try their functionalities and check out their rough edges. Then compare what you found with what you were looking for and select the one that fits your needs best.

**Comment by annando** [comment]
With other words: Both projects are different and serve different purposes. Depending on the purpose one should chose the one or the other software.

**Comment by topstarnetwork** [comment]
Very kind of you, thanks!

**Comment by fabrixxm** [comment]
can we close this?

**Comment by lewissam** [comment]
This article gives an excellent overview of Hubzilla.
http://www.talkplus.org/blog/2016/the-history-of-hubzilla/

**Comment by annando** [comment]
@fabrixxm I guess we can.

**Comment by Francewhoa** [comment]
### Article By Sean Tilley

This 2017 interesting article includes a comparison between Friendica and Hubzilla. In this article Sean discussed with Mike Macgirvin the author of both Friendica and Hubzilla. Find the article at https://medium.com/we-distribute/got-zot-mike-macgirvin-45287601ff19

### Extracts

> Friendica is notorious for its ability to connect to many different communication platforms at the same time. Hubzilla connects to even more networks.

> What is Hubzilla, and how is it different from Friendica?
> 
> By 2012 it was apparent that unseating Facebook with a decentralised free web project was not going to happen. Anybody who appeared on the scene with a new “social network” was immediately compared/contrasted with Facebook and then laughed at. There were a lot of these and most have vanished as quickly as they appeared.
> 
> Subsequently we stopped focusing on “social networking” as a project mission. We concentrated on providing a range of privacy respecting services that were decentralised, yet highly integrated. Our focus now is more towards content management, cloud services, and groupware than social networking. You can use the same interface to share a wiki with your basketball team as you can to share private videos with your girlfriend.
>
>We added blogging features, WebDAV, CalDAV and CardDAV, and also a range of content management tools so you can build a company website using the same interface you use to provide customer assistance. You can have loyalty coupons and only those who have the coupon can see your special offers page.

**Comment by velw** [comment]
> My original account has moved a few times now. All my original friends are still there. My Friendica and Diaspora friends however are not. They need to be reconnected, and this is silly because nomadic identity was created to address that problem.

Sorry to revive this ancient thread, but is this still the case now? Or has it been possible to find a way to tell Friendica and Diaspora contacts to redirect to a new place at the same time?

**Comment by MrPetovan** [comment]
We might be able to do so with Friendica contact through the mastodon move API, but I'm not sure there's something available for Diaspora.
