### ISSUE TITLE
What is the difference between  your friendica fork and  from duthied/Free-Friendika?

### ISSUE THREAD

**Issue by topstarnetwork** [friendica/friendica#2895]
What is the difference between  your friendica fork and  from duthied/Free-Friendika?
Thanks.

**Comment by Hypolite** [comment]
Basically, `friendica/friendica` picked up where `duthied/Free-Friendika` left things 5 years ago. There is no forking as such, more like a continuation of the same project under a different name/supervision.

**Comment by zotlabs** [comment]
This is the one true official Friendica repository. Due to some weirdness with github it was "re-parented" in the distant past in their eyes when we went through some license clarifications and we moved the repository to '/friendica/friendica' from an earlier account and repository which no longer exists. Github tried to match it against something in their system and ended up connecting to duthied's fork/mirror of an earlier project instance. I created the project originally and still have the original "mistpark" source from which the friendika and free-friendika and friendica project (and later project evolutions such as redmatrix and hubzilla) were all derived.

**Comment by Hypolite** [comment]
Thanks for the explanation, I always wondered about this weird fork.

**Comment by topstarnetwork** [comment]
Thanks for the enlightment!

**Comment by annando** [comment]
I guess I can close the issue.
