### ISSUE TITLE
Add a way to block contacts without adding them as relationship

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#3016]
Related to #3015.

To avoid seeing any post or reply by someone, there is a blocking mechanism in Friendica. However, blocking requires to first establish a relationship with the contact. This is unpractical because blocking should be discreet.

**Edit**: There already are two official plugins to do so, `blockem` and `superblock`, but @annando asked me to leave this Issue open so that we can offer a better way of doing this directly in Friendica Core.

**Comment by tobiasd** [comment]
There is the blockm plugin for this.

**Comment by Hypolite** [comment]
Thanks for the info.

**Comment by annando** [comment]
We really have to improve that mechanism. The addon isn't so nice. I would like to redo it completely (and in a totally different way)

**Comment by Hypolite** [comment]
Yeah, just activated it, was expecting a link somewhere, but nope, you have to copy-paste the account URL in an obscure part of the interface. Should I reopen this issue?

**Comment by annando** [comment]
I suggest so.

**Comment by tobiasd** [comment]
There is a link in the menu you get when clicking on the small arrow within the avatar picture of the person in your network stream. There is the person you want to block, access the menu, hit the "Block Author" link (most likely at the end of the menu) and the person is in your block list.

**Comment by Hypolite** [comment]
@tobiasd I can't see this small arrow on frio?

**Comment by annando** [comment]
I would like to create a complete new system that is based on the contacts with the "uid=0". (and one additional table). When you ignore a contact there, no items from this user (neither comments nor likes) will reach you.

This is different from the "blockem" addon which simply collapses such posts and which stores the ignored contacts in a very strange way.

**Comment by AlfredSK** [comment]
Sounds like this idea is similar to the superblock addon. With superblock one doesn't need to have a relationship with a user to block him/her.

**Comment by zotlabs** [comment]
superblock

You might also have a look at the hubzilla version which has improved dramatically since I first wrote the friendica implementation. The channel in question disappears from your world view. In our case we have a unique network ID. In your case you'd probably have to use the author url as friendica's superblock does now.

**Comment by rabuzarus** [comment]
> I can't see this small arrow on frio?

I guess it isn't implemented. I don't have look into the code but as far as I remember the superblock addon does use the item_photo_menu hook. But frio doesn't use the item photo menu in the way like the other themes does it. As far as I could rembember the other themes loop through the item menu  array to create a list. Frio does create each list point separately through the template. This is because Frio wants to provide a specific icon to the specific photo menu point.
We could add a list point in the frio template for the superblock addon but there is the problem, that the template will not know if any other addons (which maybe aren't in the official addon repo) does also make use of the item photo menu. Because of this issue I have only included the links of the item photo menu which are in friendica core. https://github.com/friendica/friendica/blob/develop/view/theme/frio/templates/wall_thread.tpl#L81

**Comment by tobiasd** [comment]
The current situation, as it is documented, is:

You have a bi-directional connection to someone, then you can (a) ignore them so you do not have to listen to them, which ignores all incoming stuff [effectively making them a fan without them knowing it] and you can (b) block them which will cut communications in both ways, except for eventually public postings, but they still don't know. As a final measure you can delete the connection.

If you do not have a connection to them, you can use the addons `blockm` or `superblock`. But not with Frio, which is still experimental; you will not be able to use neither of them, nor the `viewsource` addon. as they all use the `item_photo_menu` hook. Those three are AFAIK the only published addons that use the hook. I have some more, but never published them as they never reached a usable state.

**Comment by zotlabs** [comment]
Even in Frio I believe you can use the superblock addon settings page and enter the author-url(s) into the textarea as a comma-separated list. It's not as convenient, but this is how I tested it originally.

**Comment by tobiasd** [comment]
I think so, you can do the same with blockm. But as you said, copy and pasting URIs from the profile into the settings is rather cumbersome.

**Comment by annando** [comment]
Storing all blocked contacts in a single text field isn't the best solution, I think. Because of this I want to rework the whole stuff.

**Comment by tobiasd** [comment]
Maybe it is not the best way to store these information, but that was not the initial question ;-)

I have around 10 accounts in the block list. It works fine. Thankfully Friendica is not that spam prone.

**Comment by annando** [comment]
Thing is that the current solution needs massive re-haul.

**Comment by MrPetovan** [comment]
Is this possible now natively?

**Comment by MrPetovan** [comment]
Yay!
