### ISSUE TITLE
update_network disregards network tab post first ordering

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#3037]
I set my network tab to "Posted Order", and when I load the page, the item order is expected. However, when the regular `update_network` Ajax calls triggers, it sometimes move existing items at the top because they were recently commented or liked, in contradiction with the selected order.

**Comment by Hypolite** [comment]
Example:
![screen shot 2016-12-20 at 12 59 54 pm](https://cloud.githubusercontent.com/assets/925415/21361958/434965be-c6b4-11e6-99e1-69de73aebd62.png)

After liking Aaron Gibson's 20-minutes old post, Harka's 7-months old post appeared before Eugen's 23-minutes old status through the `update_network` process, probably because Andy liked it between 20 and 23 minutes ago.

**Comment by MrPetovan** [comment]
This is still ongoing and my attempt at finding the source of the issue proved fruitless. If anyone else wants to take a look (@annando for example) I'd be grateful.

**Comment by annando** [comment]
I can have a look at it, but want to address the newly created bugs first.

**Comment by MrPetovan** [comment]
Maybe I can take care of some of the bugs in exchange for some of your quality time for this, which is an old created bug?

**Comment by annando** [comment]
I would like to finish the item class first.

**Comment by MrPetovan** [comment]
I guess it can wait another year! 😅

**Comment by MrPetovan** [comment]
Fixed by #4500
