### ISSUE TITLE
Convention - Maybe remove & from $a (App) parameter?

### ISSUE THREAD

**Issue by Quix0r** [friendica/friendica#3039]
I would like to bring up the issue as show here:
https://github.com/friendica/friendica/pull/3036#issuecomment-268282396

The & makes such thing possible:
```
function bla (App &$a) {
$a = new App();
}
```
Now outside code does not notice that $a has been changed (somewhere). It is currently not the case (as my trustworthy Midnight Commander has found nothing about it) but accidents like this should be prevented in the future (more code/features being added).

**Comment by Hypolite** [comment]
I support the removal of the reference operator anywhere, it just makes the code more confusing in general since it's not a common practice to have parameters by reference.

**Comment by annando** [comment]
There can be situations where this is needed. For example when calling hooks. There it really makes sense.

**Comment by Hypolite** [comment]
Hooks function could return value instead of modifying the parameters but I'll admit I don't like the hook concept in the first place.

And yes, I expect memory usage to increase with parameter copy.

**Comment by annando** [comment]
I like the hook concept very much.

**Comment by Hypolite** [comment]
It is handy to add extensions to your core mechanics, but it is a pain to debug since it's harder to know what is going on at any given moment in your code. Basically, each time you have a `call_hooks()`, you have a sort of program flow black hole because you can't immediately know if anything (or nothing) is happening at that point without extensive debug.

I had a bad professional experience with hooks working on a Drupal project started by someone else that wasn't around anymore, and it looked like they used hooks for all the wrong reasons, mainly because it was faster to implement than the expected explicit way. What they didn't realize or didn't care about was that it would take way more time to alter or even fix their code than they took to make it in the first place.

I wouldn't say hooks are useless, but they require a greater context awareness which make sloppy code more probable. Maybe it was Drupal's implementation of hooks that was lacking, maybe it was this developer's lack of care, but I've had a bad opinion about hooks aver since.

**Comment by annando** [comment]
When $a isn't called by reference, is it then a copy of the class, so that changing any class variables wouldn't change the main class?

**Comment by Hypolite** [comment]
This was true in PHP4, but this behavior got changed with PHP5. Even if the parameter isn't explicitly marked by reference, any class instance will be passed by reference. Basically, the parameter is a pointer to the class instance, not a copy of it.

**Comment by Quix0r** [comment]
@annando class != object :-) As always, write yourself a small test code to try out things:
```
<?php
class Foo {
  private $field = null;

  public function setField ($field) {
    $this->field = $field;
  }

  public function getField () {
    return $this->field;
  }
}

function changeFoo (Foo $foo) {
  $foo = new Foo();
  $foo->setField('bar');
}
 
$foo = new Foo();
$foo->setField('foo');
var_dump($foo);
changeFoo($foo);
var_dump($foo);
```
Now add a & to `changeFoo()` **or** remove the first line setting a new instance of `Foo`. You will get different results. Now try to think, why this is happening. :-)

**Comment by annando** [comment]
@Quix0r when I wrote the lines above I was too tired (it was early in the morning), now I'm too well-fed :-)

**Comment by Quix0r** [comment]
Same here, eaten 3 times (OT). :-)

**Comment by MrPetovan** [comment]
The only 207 instances remaining are in the addons and we probably won't go through them all, I consider this issue fixed.
