### ISSUE TITLE
Frio : Improve pagination display

### ISSUE THREAD

**Issue by Hypolite** [friendica/friendica#3195]
I'll just leave this here:
![screen shot 2017-02-28 at 12 11 13 pm](https://cloud.githubusercontent.com/assets/925415/23415991/11f3f2fe-fdaf-11e6-9819-1a341b47f397.png)

Fortunately, [Bootstrap has styles for pagination](http://bootstrapdocs.com/v3.3.6/docs/components/#pagination), it just is a matter of adding the correct classes to the page links.

**Comment by annando** [comment]
Currently I'm working on removing pagination where this does make sense ;-)

Problem is that the pagination needs a SQL count - which is very cost intense since this is always a table scan.

So the pagination is only useful when there is not much data to display.

**Comment by Hypolite** [comment]
This was taken from the Contacts page. I believe it could be replaced by an infinite scroll but styling would be a good easy start.

**Comment by rabuzarus** [comment]
+1 for infinite scroll everywhere :-)

if you want you try a little bit with the bootstrap pagination. As I tried it a year ago I had the feeling that it would need some own adjustments because it didn't look very beautiful for frio. But I can't really remember

**Comment by zotlabs** [comment]
alt_pager() was created as a replacement in 2012 - it didn't require a query to count stuff. @unary added this after a discussion we had about pager performance and I described a solution which basically fetches 'n' posts starting with 'x' until no more posts are returned, offering 'older' and 'newer' or other appropriately named navigational links as needed. WordPress and GNU-Social both use this pagination mechanism. It became the default pagination for Friendica at the time due to its improved performance. 

The performance improvement appears to have been destroyed by checkin faa510befca7b5f2f9 in 2013 and returned to requiring a total.
