### ISSUE TITLE
community home doesn't show community stream

### ISSUE THREAD

**Issue by treellama** [friendica/friendica#3248]
The community home plugin has the ability to display the community stream, via

```
$a->config['communityhome']['showcommunitystream'] = true;
```

That doesn't seem to work in 2.5.1. Probably because it calls `community_content($a, 1);` but in community.php:

```
// Currently the community page isn't able to handle update requests
if ($update)
    return;
```

Changing the call to simply `community_content($a);` seems to fix it. I don't fully understand what that update argument is for, or I'd issue a pull request.

**Comment by annando** [comment]
Thanks for finding it out. The bug was introduced in the 3.5.0 version.

Yeah, it would be wrong to change the addon. This additional parameter changes the output in a way that it only returns the item data and no navigation bar. So the parameter is crucial.

I changed it now for the "develop" branch so that the change will be part of the 3.5.2.

**Comment by annando** [comment]
Does anyone wants to test it? Or do you trust me enough? :-)

**Comment by tobiasd** [comment]
Seems to be working on snarl with 3.5.2, so I'm closing this issue.
