### ISSUE TITLE
Can't subscribe to Diaspora users

### ISSUE THREAD

**Issue by schiessle** [friendica/friendica#3545]
I can't connect with any Diaspora user. I use a up-to-date Friendica server from git master. I tried both, `user@diasporapod.tld` and `https://diasporapod.tld/u/user` in both cases I get the error `The network type couldn't be detected. Contact can't be added.`

The Apache log shows:

````
78.46.92.131 - - [22/Jun/2017:23:20:18 +0200] "POST /receive/public HTTP/1.1" 400 107 "-" "DiasporaFederation/0.1.8"
2003:de:9bc0:3900:6083:38de:9e03:293a - - [22/Jun/2017:23:20:21 +0200] "GET /follow?url=https%3A%2F%2Fpod.geraspora.de%2Fu%2Fblizzz HTTP/2.0" 200 5718 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54.0"
2003:de:9bc0:3900:6083:38de:9e03:293a - - [22/Jun/2017:23:20:22 +0200] "GET /view/theme/frio/style.pcss HTTP/2.0" 200 12309 "https://soc.schiessle.org/follow?url=https%3A%2F%2Fpod.geraspora.de%2Fu%2Fblizzz" "Mozilla/5.0 (X11; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54.0"
2003:de:9bc0:3900:6083:38de:9e03:293a - - [22/Jun/2017:23:20:22 +0200] "GET /view/theme/frio/style.pcss HTTP/2.0" 200 12309 "https://soc.schiessle.org/view/theme/frio/style.pcss" "Mozilla/5.0 (X11; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54.0"
2003:de:9bc0:3900:6083:38de:9e03:293a - - [22/Jun/2017:23:20:22 +0200] "GET /ping?format=json&f=&uid=1&_=1498166421990 HTTP/2.0" 200 1912 "https://soc.schiessle.org/follow?url=https%3A%2F%2Fpod.geraspora.de%2Fu%2Fblizzz" "Mozilla/5.0 (X11; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54.0"
2003:de:9bc0:3900:6083:38de:9e03:293a - - [22/Jun/2017:23:20:22 +0200] "GET /proxy/f1/aHR0cHM6Ly9wb2QuZ2VyYXNwb3JhLmRlL3VwbG9hZHMvaW1hZ2VzL3RodW1iX2xhcmdlXzI0MWU5ODRhY2FjNjdhMTk4NzhkLmpwZw==.jpg:small HTTP/2.0" 200 283 "https://soc.schiessle.org/follow?url=https%3A%2F%2Fpod.geraspora.de%2Fu%2Fblizzz" "Mozilla/5.0 (X11; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54.0
````

**Comment by annando** [comment]
Please activate the friendica logfile and set it to debug. Then go to ````/probe/```` and check for it.

The logfile has an unique session identifier. Please collect and show here all data from that session until the detection failed.

Especially please have a look at log entries with "network.php" in it. Recently I detected a problem on snarl.de where curl mostly failed to fetch a hostname. This seemed to be some IPV6 issue that I temporarily solved with the following line:
````
curl_setopt($ch, CURLOPT_IPRESOLVE, CURL_IPRESOLVE_V4);
````
When you see some error that curl was unable to detect the hostname, then this line should help. Currently there isn't a pull request for this, neither in master nor develop, since I want to search for the reason why this fails and how to fix it on a more general level.

**Comment by schiessle** [comment]
tried it again to collect the infos you asked for and now it works. Maybe there was a temporary problem on the Diaspora server? I didn't changed anything on my side...

**Comment by annando** [comment]
But you said **any** Diaspora user. This irritates me.

**Comment by schiessle** [comment]
Yes, indeed. I tried two Diaspora server. My own account at diasp.eu and a friend at geraspora.de. Both failed a few days ago and both worked today. So it is still strange. I will keep an eye on it. In case it happens again I know what I have to do/check. 😃
