### ISSUE TITLE
Access to hashtag links denied even for visitors

### ISSUE THREAD

**Issue by sesom42** [friendica/friendica#3560]
If I follow a hashtag link to another friendica instance I get an access denied message. The other instance is not public but I'm recognized as visitor.

Should'nt it be visible to visitors?

**Comment by annando** [comment]
You are totally right. This check here needs to be extended to known visitors: https://github.com/friendica/friendica/blob/develop/mod/search.php#L100

**Comment by tobiasd** [comment]
This seems to be working in current develop branch @sesom42 can you check?

**Comment by annando** [comment]
It will only work partially. Best would be if that link included our magic stuff so that a known visitor will be known as known, you know?

**Comment by tobiasd** [comment]
Yes, sure.

**Comment by sesom42** [comment]
@tobiasd I don't can test this because for testing this fix I need a second node. I don't know which other node has pulled the current changes. I have updated mine. If you are known to my node, and for shure you do ;), you can test it here: https://friends.tausys.de/search?tag=security

**Comment by tobiasd** [comment]
When I arrive over a magic-link, thus be authorised by your node and known, I can use the search. Else I'm denied. That was what @annando was referring above.

**Comment by annando** [comment]
I think that this won't be an easy case. Problem is that prohibiting the anonymous search for tags is extremely important to reduce server load due to aggressive search engines.

There are now two possible solutions:
1. We add a magic link to any tag link to an external server
2. Tag links could point to the same server instead to the foreign server

Although this changes some central part of Friendica, I would vote for the second option. Means: Especially when the option "local_search" is activated, then the second option could be activated.

**Comment by annando** [comment]
I did a PR: https://github.com/friendica/friendica/pull/3638

This will add a "magic link" to the hashtag link. This should work great (but only if the second server has got this PR applied as well).

Once the PR is accepted, it will word.

**Comment by annando** [comment]
@sesom42 Please update your system and then try again.

**Comment by sesom42** [comment]
As far as I can tell now works. The error is difficult to test, because there must be at least two nodes on the same commit level. Thank you @annando !
