### ISSUE TITLE
Line feeds in code blocks are broken on Diaspora

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#3639]
I just posted something with a lot of code blocks. The post was delivered to Diaspora as well.
All the line feeds inside the code blocks are broken on Diaspora's side. Instead of line feeds HTML br tags are shown.
Can we do something about this?

See:
https://libranet.de/display/0b6b25a85959981abf47efb116424689
https://despora.de/posts/0b6b25a85959981abf47efb116424689

**Comment by annando** [comment]
In the worst case this is some problem with the used Markdown parser. We have to check this.

**Comment by MrPetovan** [comment]
Parent of https://github.com/vmg/redcarpet/issues/429#issuecomment-345945984
Parent of https://github.com/diaspora/diaspora/issues/7692

**Comment by SuperTux88** [comment]
(I just thought I better comment this here, because it's about this specific issue)

This issue has nothing to do with RedCarpet, because it also doesn't work in markdown-it (which diaspora uses in the desktop UI) which is fully CommonMark compatible.

Friendica sends `<br>` in codeblocks there, which obviously doesn't work, because everything inside a codeblock is handled as code, so html-code is displayed as raw html-code. It's the same here on GitHub:

When you write: `` `foo<br>bar` `` it's displayed as `foo<br>bar`.

Also friendica uses single backticks `` ` `` for multiline codeblocks instead of triple backticks `` ``` ``. Single backticks only create single-line `<code>` blocks (see [spec](http://spec.commonmark.org/0.27/#code-spans)), while three backticks should be used for multiline codeblocks which also supports syntax highlighting (see [spec](http://spec.commonmark.org/0.27/#fenced-code-blocks)).

You can also test the same here on Github:

```markdown
`foo
bar`
```

renders as

`foo
bar`

while

````markdown
```
foo
bar
```
````

renders as

```
foo
bar
```

**Comment by annando** [comment]
Houston, we need a better Markdown converter ;-)

**Comment by MrPetovan** [comment]
@SuperTux88 I suspected as much, but I trusted @annando with the parser issue, thanks for diving into this.

I'm pretty sure the `code` problem lies in the fact that we have a single BBCode for both inline code and multiline code, so I'm not sure the actual Markdown library is to fault for this behavior.

**Comment by annando** [comment]
We have to investigate. To convert to Markdown we first convert to HTML. So we have to check if we can do something at the HTML part.

**Comment by SuperTux88** [comment]
> we have a single BBCode for both inline code and multiline code

Are they displayed differently? So is the inline codeblock actually displayed like `this`, or is a codeblock always displayed like:
```
this
```

If the latter, then you can always send multiline (`` ``` ``) codeblocks.

**Comment by MrPetovan** [comment]
That's how it is supposed to be displayed in HTML, and I believe it works correctly when the language is specified. Anyway, it's clearly on our end.
