### ISSUE TITLE
Size of contact suggestion list

### ISSUE THREAD

**Issue by utzer** [friendica/friendica#3692]
The size of the contact suggestion list is very small, increase the size, preferably also enable multi selection of contacts to suggest.

**Comment by MrPetovan** [comment]
I have about a hundred contacts in the list of my `/suggest` page, how is yours looking?

**Comment by foss-** [comment]
Where can I find the contact suggestion list? Should my.instance/suggest show the list?
When I try that I get a `Not found` page.

**Comment by annando** [comment]
There is `/contact/suggestions`

**Comment by foss-** [comment]
Oh wow and that can be found via UI `Contacts > Friend Suggestions`.

I see 80 suggested contacts. That doesn't seem small. Or are we talking about the UI showing that contact list? Follow is done with a single click per contact. I find that a fair UI. What would multi selection do and how would it save a click? I would then have to tick all contacts and than click "follow" which would complicate the UI unnecessarily as with the current UI I can just follow with a single click per contact.

Are there circumstances under which the suggestion list is very small? Maybe for new users with not many interactions?

Otherwise, can we consider this solved?

**Comment by annando** [comment]
Ahhh, I remember what was meant here: There had been a time when a user could suggest some contact to some other user. That feature is long gone.
