### ISSUE TITLE
Forums with "!" - open issues 

### ISSUE THREAD

**Issue by annando** [friendica/friendica#3860]
There are some open issues with forums with ```!```

- [x] Generated OStatus posts don't display the forum links correctly (https://github.com/friendica/friendica/pull/3862)
- [x] When selecting a single Forum in the ACL, the ```!``` should be used, instead of ```@``` (https://github.com/friendica/friendica/pull/3862)
- [x] When posts from a single forum are shown in the single contact view, the ```!``` should be used, when creating a post. (https://github.com/friendica/friendica/pull/3862)
- [x] Checking OStatus compatibility (#4625)

**Comment by tobiasd** [comment]
Also, the ACL should reflect the actual permissions.

**Comment by annando** [comment]
See this message: https://forum.friendi.ca/display/ec054ce7195a1e5d2a5a185656676047

It is working fine - only the frontend doesn't show it. It would like to delegate this to @rabuzarus

**Comment by rabuzarus** [comment]
It isn't that simple. You need to record the user input and compare it with the available forum names. It would be similar to the js autocompletion (without completion popup and inserting the results). Unfortunately it is not possible to use autocompletion for this task (there is no option in the code to use only the compare part). It would be really helpful to find a js library for the input record part (because there are so many conditions you need to think of - e.g. when the user delete the input or just a character and many many more)

**Comment by annando** [comment]
With PR https://github.com/friendica/friendica/pull/4625 the forum feeds look now like GNU Status group feeds. It is still not perfect, but partly usable. So this issue can then be closed, I think.

**Comment by MrPetovan** [comment]
You can close it yourself!

**Comment by annando** [comment]
When the PR is accepted :-)

**Comment by MrPetovan** [comment]
Closed via #4625
