### ISSUE TITLE
Feature request: number / notification of article reshares

### ISSUE THREAD

**Issue by ghost** [friendica/friendica#3869]
It is very nice that post resharing is enabled on Friendica  but somethign I'm desperately missing is the number of reshares at the bottom of each article.

There'r also no notification about reshares.

**Comment by MrPetovan** [comment]
Due to the way we currently do reshares in Friendica, basically just embed a post in another one using BBCodes, there's no way to count them, or send notifications about them. What is worse for me is that if I follow people resharing my posts, I will see my post in my feed 2 or 3 times which feels like clutter.

I know Friendica has a way to handle real reshares because it used by forums and to translate Twitter's retweets (It shows as "Original poster via Resharer" in the post head) but I'm not sure how to use this feature.

**Comment by annando** [comment]
It's not that easy. The forum posts are different from Reshares. And Twitter and OStatus repeats are having in common that they share the same URI. Diaspora reshares and the faked Friendica reshares don't. BTW: Currently we are "misusing" the Forum functionality for the Twitter and OStatus reshares.

We need a good solution.

**Comment by rabuzarus** [comment]
@annando 
Any progress on this issue? If I remember correctly I've read somewhere in the commit logs that we now import whole threads if they are reshares. But I don't know what the effects of this would be.

Anyway: I want to put the focus on this issue again because having a good share/reshare implementation would be one of the core function of a social network.

I want to highlight two things:

1.) Many of you know that last year I was really active in a - well lets call it - political organisation. I crated a friendica account for this organization. One of the most annoying thing was, that we couldn't see who shares our posts. If you have important press releases or a call for demonstration likes are one thing but the number of reshares (and how reshares your post) gives you an understanding of the outreach of your post. It was really annoying to have to login to diaspora and mastodon every time to get this information at least for this platforms. If you have an political organisation it is all about outreach of your information.

2.) I don't have much practice about how diaspora is handling reshares but according to https://squeet.me/display/962c3e10-645c-46f7-2106-567541109860 the in diaspora the author of the original post gets notified if someone answered to the reshared post. So she could recognize many answers to the question she posted which came from people she doesn't have in her contact lists because of the reshares.

**Comment by annando** [comment]
Currently there is no progress in this. This issue has got a medium priority for me. There had been so many A+++ priorities in the last time, that I hadn't got any time for this - and additionally we do have the problem that AP and Diaspora are handling reshares completely different - which will make it possibly even more complicated.

**Comment by tobiasd** [comment]
Can this be closed? Number of (primary) reshares is displayed now correctly. Not sure about reshares of reshares though.

**Comment by annando** [comment]
I think that we can close it. We do display the reshares that we are aware of.

**Comment by MrPetovan** [comment]
Closed by #6962
