### ISSUE TITLE
login only happening on second attempt

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#3954]
Reproducible 100% on pirati.ca and squeet.me so assuming this affects all (?) instances.

Reproduce:
* click login icon (the door icon)
* fill out login information
* click "Login"

Currently:
Something happens, browser loads and then user finds themselves back in the previous view and not logged in. A second login always works as expected.

Expected:
Login should work on first attempt.

screencast (next 60 days): https://upload.disroot.org/r/bZagnwFX#r6sP0TSK0u64WEnJgShIImEAg1vRknMaW5884tMJNvA=

**Comment by MrPetovan** [comment]
Related to #3942, I’m reviewing the login process, I may be able to fix it. However on my single user instance I never experienced this.

**Comment by rabuzarus** [comment]
@MrPetovan 
Are you still working on this issue?
I'm just asking, because this is really an annoying bug and it does also affect the "magic-auth" (I need to open a redir link to another instance 2 - 3 times to get remote authenticated)

**Comment by MrPetovan** [comment]
I have been caught up with the registration issue (#4041) in the meantime so I didn't make any progress in this regard.

**Comment by MrPetovan** [comment]
Post-mortem: this happened because we stopped storing the session of first-time users in `killme()`, the most common way to end a request, to avoid error messages when the session data was empty. Thankfully, one of the requests a browser makes during login didn’t end in `killme()`, which resulted in the normal write of the session that bears the authenticated state.

The fix was to restore writing the session all the time and accept empty session data as a good write even if we don’t actually write anything, which effectively suppress the notice in the log.

**Comment by rabuzarus** [comment]
thank you for fixing this nasty bug :+1:
