### ISSUE TITLE
[Urgent] Unable to register new users

### ISSUE THREAD

**Issue by atasingorneq** [friendica/friendica#4041]
See this discussion:
[https://forum.friendi.ca/display/0b6b25a8125a297737e6a4e212566317](https://forum.friendi.ca/display/0b6b25a8125a297737e6a4e212566317)

At the moment it is not possible to register new users.

**Comment by MrPetovan** [comment]
Thanks for the report!

**Comment by AlfredSK** [comment]
Arrrr... someone was quicker than me. Pasting my desciption here:

Hello,
see discussion here: https://forum.friendi.ca/display/0b6b25a8125a297737e6a4e212566317

There's an issue with registrations and creation of user profiles. I think this is a high priority bug because it prevents new users from actually using Friendica.

Code base: current 3.6-dev
PHP: 7.0 (don't know if this is relevant)

Description:
After a new user has registered the user is able to login but gets an error notification "profile not available". Each click on buttons/links related to the user's profile triggers the "profile not available" notification. The user cannot post, upload photos, edit profile, add contacts and so on. The user is also not able to delete the account.
Additionally, new users are not visible on admin/users.

What I see in the DB:
The user is created (table user); the profile is created (table profile); there is no 'self' contact (table contact).

Urgency:
Please make this a high priority bug because it keeps us from gaining world domination. :-)

Thank you!

**Comment by MrPetovan** [comment]
I started working on this issue, and I was able to register a user account with the same email address as another one. 🤔

**Comment by MrPetovan** [comment]
I'm leaving my computer until tomorrow 10:00 EST, I just fixed the formatting of `mod/register` 😅

**Comment by MrPetovan** [comment]
I'm done with my, huh, preparation work to tackle this issue. I know this isn't helping, but I get carried away when I see something glaringly wrong even unrelated to the problem I'm trying to solve. I have to do the laundry now, hopefully I'll come back to it in a couple hours when the PR #4046 will be merged.

**Comment by MrPetovan** [comment]
Phew, finally done, found the issue, it was my fault. 😅

**Comment by annando** [comment]
Like always it was some thing :-)
