### ISSUE TITLE
followers.json and friends.json return an empty result when specifying an user_id

### ISSUE THREAD

**Issue by Rudloff** [friendica/friendica#4069]
I'm using Twidere and it calls the following API endpoints on my Friendica 3.5.4 server:
* https://social.rudloff.pro/api/statuses/followers.json?count=20&user_id=13
* https://social.rudloff.pro/api/statuses/friends.json?count=20&user_id=13
* https://social.rudloff.pro/api/favorites/list.json?include_blocking=true&count=20&user_id=13&include_blocked_by=true

They all return empty results (`[]`).

However, when removing the `user_id` paremeter, they return a correct result.
I verified in the `contact` table and it seems to be the correct user ID.
I also tried with other user IDs and got the same empty result every time.

**Comment by MrPetovan** [comment]
Thanks for the report!

**Comment by MrPetovan** [comment]
I looked into it and the behavior is expected.

Basically, we want to show followers and friends only to their owner. However, when you add the `user_id` parameter, it looks into the public contact (self = 0 and uid=0) list and return a contact that is different from the api user's own contact (self = 1 and uid != 0) which isn't public.

Basically, passing a User ID to the API is interpreted as trying to get someone's public profile, even for yourself, except the follower and friends lists aren't public. Removing the User ID parameter allows to normally query your own private stuff since we checked your credentials.

**Comment by Rudloff** [comment]
I understand why I can't get this for other users (even if it is frustrating) but the current behavior means I have no way of getting my own followers, friends, etc with Twidere.

(Also my contact list [is public](https://social.rudloff.pro/viewcontacts/rudloff) so I don't really get why it can't be returned by the API.)

Do you think I should ask Twidere to change their API call? I'm not sure they would accept since the current behavior seems to work correctly with other GNU Social implementations.

**Comment by MrPetovan** [comment]
I agree Friendica API behavior is weird, but I'm skittish about changing it since it would change the behavior of a bunch of other calls as well. I'm not even sure how the user id parameter is guessed in the first place. Can you formally confirm this call prototype is standard across GNU Social implementations?

Also, while investigating this issue, I found out that there's no pagination available for followers and friends, which means the `count` parameter is royally ignored. This is easily fixable.

**Comment by annando** [comment]
Concerning the parameters it is the best to have a look at the official Twitter API. Then we can check how it is implemented.

**Comment by Rudloff** [comment]
I don't know if it is standard but all these requests return a result on Qvitter:
* https://quitter.is/api/statuses/followers.json?count=20&user_id=1
* https://quitter.is/api/statuses/friends.json?count=20&user_id=1
* https://quitter.is/api/favorites/list.json?include_blocking=true&count=20&user_id=1&include_blocked_by=true

**Comment by MrPetovan** [comment]
So it's only a matter of deciding if those lists should be public or not on Friendica, and currently they are explicitly considered as private (see https://github.com/friendica/friendica/blob/develop/include/api.php#L2936).

**Comment by MrPetovan** [comment]
> Concerning the parameters it is the best to have a look at the official Twitter API. Then we can check how it is implemented.

Those calls specifically aren't implemented anymore 😅
https://developer.twitter.com/en/docs/accounts-and-users/follow-search-get-users/overview

The general problem about the `user_id` parameter is that Friendica has multiple IDs for a single account:
1. The `id` in the `user` table, which would make sense but isn't used by the API
2. The `id` in the `contact` table for the self-contact (`self = 1 and uid = user.id`)
3. The `id` in the `contact` table for the public contact (`self = 0 and uid = 0`)

Using 1. would make sense except we wouldn't be able to query remote contact info even if we have it just because they didn't register on our node.
Using 2. also allows to know if the API user is querying its own private info, but suffers from the same drawback as 1.
Using 3. allows to query public info about any contact the node knows about, local and remote, but there's no direct way of knowing if the API user owns the specified contact.

**Comment by annando** [comment]
We have to use the 3. way. Everything else wouldn't work with other parts.

**Comment by MrPetovan** [comment]
So we have to find a way to match the API user with its public contact ID without too many additional requests. It sounds like we can store it in session when we authenticate the API user and match on it later. What do you think?

**Comment by annando** [comment]
We could store this in the App-Class. Possibly we can use this information at other places as well.

**Comment by annando** [comment]
When reviewing PR #4083 I realised that there had been a bug that prevented that the whole stuff was working. This is fixed with my alternate PR #4086.

**Comment by MrPetovan** [comment]
Is this behaving correctly now?

**Comment by annando** [comment]
I guess so.

**Comment by MrPetovan** [comment]
Summoning @Rudloff to close this issue.

**Comment by Rudloff** [comment]
Yes, it works correctly for my own user now.
The only thing I noticed is that `api/favorites/list.json` is really slow (60-70 seconds), even with `count=2`.

**Comment by annando** [comment]
How good are you with MySQL? You could enable these two lines in your .htconfig.php:
```
$a->config['rendertime']['callstack'] = true;
$a->config['system']['profiler'] = true;
```

Then have a look at the logfile ("Debug"-Level) for a line like this:
```[DEBUG]:api.php:351:api_call	Database Read```

**Comment by Rudloff** [comment]
I tried again and it is not as slow as before so it might have a temporary issue with my server.
It think we can close this issue now.

**Comment by annando** [comment]
Trying it a second time is faster because of the SQL cache. I guess some query there is slow and needs to be improved.
