### ISSUE TITLE
Make hash tag links always local

### ISSUE THREAD

**Issue by annando** [friendica/friendica#4227]
Currently there can be two situations when you are clicking on hash tag links:
* On Posts from Diaspora, Twitter or the GNU Social connector the links are local links.
* Hash tag links from posts from Friendica and OStatus are linking to external sites.

This is a confusing behaviour that we should unify. Especially since you now can comment on every public post, all hash tag links should now link to the local site.

**Comment by hoergen** [comment]
It should be always local first. There are a lot places where the links leads to other instances instead of the local one.

**Comment by annando** [comment]
When it was introduced it was intentional that the links lead to other instances.

**Comment by hoergen** [comment]
That's ok, but since most people deactivate magic cookie (maybe wrong expression) - if available - and you like to comment or interact with a post, it's very inconvenient AND if you are point to slow systems it is annoying to search and click after waiting a second time to reach the destination you are searching.

From my point of view the first choice (click option) should always be local.
