### ISSUE TITLE
Remove RINO entirely

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#4281]
As @fabrixxm [suggested it](https://github.com/friendica/friendica/pull/4276#issuecomment-359032528):

> Yet I'm for drop RINO completely. [...] Imho, RINO was useful in a pre-let's encrypt era, when not everyone had the technical skill, time or money to get a verified certificate. Now most if not all of the main webservers are supported by LE tools, and many started to supports LE certificates natively.
With LE, shared hosting can (and started to) offer https out-of-the box.
> So why we should support RINO infrastructure when webservers and curl can do it better than us using https, and can fix bug faster than us?
> I'm not an expert, and maybe my point has some fails, but I don't see the need of server-to-server encryption when the message is transferred over https, and saved decrypted in db anyway...

I do share this view and I'd rather not have a supplemental layer of encryption nobody masters anyway in the Friendica team.

**Comment by annando** [comment]
Since this is more some discussion stuff, I would like to open the communication about this in the developer forum.

**Comment by zotlabs** [comment]
The original premise of RINO was that the security of SSL is suspect and both state and private actors have a number of tools available to MITM the connections and/or subvert communications at the CA level. So this provided an extra layer of protection. One (of many) factors which led me to abandon further development of DFRN was my relatively uneducated choice (at the time) of encryption technology and implementations. 

AES256EBC was in retrospect a very poor choice of algorithm, especially for transmitting private images; as repeating input patterns can be extracted and distorted copies of the original image produced without decryption. AES256CBC (Diaspora's base encryption algorithm) has flaws and can be converted to plaintext in real time on a desktop PC, so it is effectively useless. Zot now uses algorithm negotiation (just like SSH and HTTPS do)  and the protocol no longer defines a default algorithm. It's pluggable so if you don't like the built-in algorithms you can add new ones. You can also encrypt storage if you want. 

ActivityPub has chosen to rely on SSL only, and of course many banks do, so that isn't necessarily a bad choice to make. GNU-Social doesn't have privacy so encryption to that service is pointless. Since Diaspora's encryption is so easily broken, they too are effectively relying only on SSL. 

I still personally prefer the option of being able to provide a bit of extra security in a hostile environment (and the internet is a totally hostile environment). If you can secure the pipes, that reduces your exposure to only leaking at the end nodes; which you and your conversants **might** have some kind of control over. You have absolutely no control over the pipes or with the security of SSL. 

It seems your project choice was already made but I just wanted to weigh in on why these decisions were made long ago. Incidentally when state actors started tracking me a couple of years ago, they didn't bother with decryption or certificates. They installed keyloggers on every single device that was used by me or my family members, both at home and at work.

**Comment by MrPetovan** [comment]
I'm curious about the algorithm negotiation part? I currently prefer a version-based system where the algorithm list is abstracted to a handful of choices, each new one better than the previous because apparently not all ciphers are good, you said so yourself.

**Comment by MrPetovan** [comment]
Locked while we discuss the question on the Friendica Developer forum : https://friendica.mrpetovan.com/display/735a2029165a63dbe4cc2d8547345598

**Comment by MrPetovan** [comment]
The decision doesn't make consensus, let's scrap it for now.
