### ISSUE TITLE
PHP fatal error on settings/connectors

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#4377]
I get a PHP fatal error and an error 500 (whitepage) on settings/connectors with current develop.

```PHP Fatal error: Cannot declare class OAuthConsumer, because the name is already in use in /var/www/html/libranet/library/OAuth1.php on line 12```

Core and addons pulled from develop. Composer install ran successfully.

Discussion here: https://forum.friendi.ca/display/a8e4f565155a733f2fc8b00964618359

**Comment by AlfredSK** [comment]
My active connectors:

buffer
fromgplus
ifttt
pumpio
statusnet
tumblr
twitter
wppost
xmpp

**Comment by MrPetovan** [comment]
Do you get thefatal error as well?

**Comment by AlfredSK** [comment]
Crazy. I've logged in with another account on the same node. The other account has no connectors configured or in other words doesn't use the connectors. But because both accounts are on the same node the identical addons are enabled.
So, I think the error is triggered when some connector is activated by the user.

And yes I I have the above mentioned fatal error.

**Comment by AlfredSK** [comment]
Found it! It is the **tumblr** connector!

If I deactivate the addon on admin panel settings/connectors works again.

**Comment by MrPetovan** [comment]
I believe it has to do with the way Composer includes files using `include` and not `include_once`. Since there are multiple classes in `library/OAuth1.php`, Composer includes the file when any class in the file is requested and marks the class (not the file) as autoloaded. When we request another class from the same file, Composer includes it again because the class wasn’t marked as autoloaded.

I believe separating classes by file would fix the issue but I’m lacking a setup where the error happens consistently.

**Comment by annando** [comment]
Couldn't we just change the autoloader so that we would use "require_once"?

**Comment by MrPetovan** [comment]
Issue explanation: https://github.com/friendica/friendica/pull/4379#issuecomment-362616139
