### ISSUE TITLE
Drop unsecure OPENSSL_PKCS1_PADDING from openssl_private_decrypt()

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#4442]
On a suggestion from @paragonie-scott, there's a known vulnerability in the standard PKCS1 padding and he is recommending to use OPENSSL_PKCS1_OAEP_PADDING instead. However, this isn't a backwards-compatible change, so we can only use it for internal communication (Diaspora is using the default padding as well but we can't change their side).

He offered to add a comment here detailing the best migration/fallback strategy.

I believe I have to say his name three times.
@paragonie-scott!
@paragonie-scott!
@paragonie-scott!

**Comment by paragonie-scott** [comment]
Originally I was going to propose this to PHP itself, but:

Use a RSA decryption wrapper function, that works in 3 ways:

1. OAEP mode
2. PKCS1v1.5 mode (if specified, raise an E_DEPRECATED notice)
3. The default mode, which tries OAEP mode then PKCS1v1.5 mode,

For example:

```php
class FriendicaOpenSSL
{
    const RSA_PAD_DEFAULT = 16777216;
    public static function private_decrypt($ciphertext, $privateKey, $padding_mode = self::RSA_PAD_DEFAULT)
    {
        switch ($mode) {
            case self::RSA_PAD_DEFAULT:
                // Decrypt twice
                $pkcs1 = '';
                $oaep = '';
                openssl_private_decrypt($ciphertext, $oaep, $privateKey, OPENSSL_PKCS1_OAEP_PADDING);
                openssl_private_decrypt($ciphertext, $pkcs1, $privateKey, OPENSSL_PKCS1_PADDING);
                /* Because the incorrect one will be false, we can coerce to string and concatenate
                    since FALSE converts to "" (empty string) and not bother implementing a constant-time
                    conditional swap function. */
                $plaintext = (string) $oaep . (string) $pkcs1;
                if (empty($plaintext)) {
                    throw new Exception('Invalid padding');
                }
                break;
            case OPENSSL_PKCS1_PADDING:
                trigger_error('PKCS1v1.5 padding is deprecated due to it being a security disaster.', E_USER_DEPRECATED);
                // break statement intentionally omitted
            case OPENSSL_PKCS1_OAEP_PADDING:
                $plaintext = '';
                openssl_private_decrypt($ciphertext, $plaintext, $privateKey, $mode);
                // Because the incorrect one will be cast to empty string, we can coerce and concatenate
                if (empty($plaintext)) {
                    throw new Exception('Invalid padding');
                }
                break;
            default:
                throw new Exception('Invalid padding mode');
        }
        return $plaintext;
    }
}
```

By default, this will maximize compatibility, at the cost of a slight performance hit.

The default mode does both decryptions and then only returns data if one of the padding modes was correct, in as close to constant-time as we can hope for.

**Comment by MrPetovan** [comment]
If I understand correctly, if I expect OAEP padding, I should use `FriendicaOpenSSL:: private_decrypt($ciphertext, $privateKey, OPENSSL_PKCS1_OAEP_PADDING)`, and if I don't know what I'm going to receive (from Diaspora for example), I should simply use `FriendicaOpenSSL:: private_decrypt($ciphertext, $privateKey)`, right?

**Comment by MrPetovan** [comment]
I can't see a good reason to ever use `FriendicaOpenSSL:: private_decrypt($ciphertext, $privateKey, OPENSSL_PKCS1_PADDING)` except to fill everyone's log with indecipherable (pun intended) errors they (or we) can't do anything about?

**Comment by paragonie-scott** [comment]
First comment: Right.

Second comment: Only for making explicit migration code go twice as fast.

**Comment by MrPetovan** [comment]
Gotcha, thanks.

**Comment by annando** [comment]
So Diaspora should use another padding as well? I guess then @supertux88 should be informed as well, especially when there is some compatibility way.

**Comment by MrPetovan** [comment]
I believe Dennis already spoke on the subject and believes that the current cryptographic choices are enough. I remember him saying that since keys are generated at 32 bytes, they don't need any padding and therefore aren't affected by a vulnerability in the default PKCS1 padding.

**Comment by denschub** [comment]
Assuming you are talking about the attack [Daniel Bleichenbacher](http://archiv.infsec.ethz.ch/education/fs08/secsem/bleichenbacher98.pdf) described in 1998, fixing this does nothing but increasing the amount of source you have to maintain. Even Bleichenbacher himself made clear that Version 2 of PKCS1 is not vulnerable to this attack in the very same paper.

OpenSSL is using PKCS #1 v2.0 EMSA-PKCS1-v1_5 since *at least* 2007 (I couldn't check further back since I don't have the archives checked out). Both PHP and Ruby use OpenSSLs implementation, so in no way is anything doing PKCS1 these days vulnerable. Even if the implementation *would* be vulnerable, both Friendica and diaspora\* generate keys that do not need padding in the first place, so...

If @paragonie-scott is talking about a different vulnerability, I request them to kindly link the paper here, so I can read it myself. Otherwise, I'd rather not dance around hypothetical padding oracles.

**Comment by paragonie-scott** [comment]
@denschub 

PKCS#1 v2.0 is OAEP. 

OpenSSL supports OAEP, but PKCS1v1.5 is PKCS1v1.5.

When Daniel Bleichenbacher said PKCS1 v2 isn't vulnerable, he was talking about OAEP. That's why the constant is called `OPENSSL_PKCS1_OAEP_PADDING`.

You can do an anti-BB98 dance, but that's an application-level mitigation (it involves using a random value and proceed as if the RSA decryption had succeeded, and avoiding timing leaks). You can't fix that at a library level.

> Otherwise, I'd rather not dance around hypothetical padding oracles.

A practical exploit against the exact mode being specified by default isn't a "hypothetical padding oracle". It's a padding oracle vulnerability, end of.

> Even if the implementation would be vulnerable, both Friendica and diaspora* generate keys that do not need padding in the first place, so...

Assuming 2048-bit keys, RSA ciphertexts are 256 bytes, unpadded. A 32-byte AES key is going to be padded. Unpadded/textbook RSA opens the doors to separate vulnerabilities: When e = 3, you can just take the cube root of the ciphertext to get the plaintext, because it won't wrap the modulus.

**Comment by denschub** [comment]
> PKCS#1 v2.0 is OAEP.

PKCS#1 v.2.0 is [RFC2437](https://tools.ietf.org/html/rfc2437), which obsoletes RFC2313 that was published as version 1.5. The v2.0 RFC explicitly makes adjustments to PKCS1 v1.5, mitigating the issue raised by Bleichenbacher, which results in there being a version 2 of 1.5, and ultimately why OpenSSL calls it `PKCS #1 v2.0 EMSA-PKCS1-v1_5` and `PKCS #1 v2.0 EME-PKCS1-v1_5`. While the fact that both PKCS1 and the RFC have version numbers is horrible, since it creates a horrible ambiguity, there have been multiple confirmations that OpenSSLs mitigations are, in fact, perfectly fine. While it's for sure not a perfect solution, this is the exact reason ZF2015-10 never got uplifted into the PHP core, and the reason why the default is still OpenSSLs PKCS #1 v2.0 EMSA-PKCS1-v1_5 aka `PKCS1_type_1`.

> A practical exploit against the exact mode being specified by default isn't a "hypothetical padding oracle". It's a padding oracle vulnerability, end of.

BB98 is nothing more than a vulnerability that is no longer exploitable with current implementations and current defaults. That is all I care about. The vulnerability you claim exists in our codebases does, in fact, not exist. If you believe that this is horrible, then you would be better up spending your time with language maintainers, to get the defaults in Ruby and PHP fixed, which, at least in Ruby's case, are subject to frequent re-validation based on current research.

Since this is the second "omg your encryption is broken" issue in a short time (although the first one was not raised by you), I question the motives. While lobbying for better encryption is generally good, this behavior is spreading FUD. In no case is the way we encrypt our payloads vulnerable. Not only are we generally not running into padding issues (which has been double-checked for me by two people who work in that very specific field but shall remain anonymous), it is impossible to run a chosen-ciphertext attack on diaspora/friendica payloads unless you control both nodes, in which case the encryption is useless anyway.

Thanks for confirming that you were indeed talking about Bleichenbachers attack. In that case, I consider this a no-op on our side, because multiple researches and myself are certain we do not have a vulnerability in our codebase.

If you consider us vulnerable, that's fine. I'd ask you to actually proof that in any way, because the crypto world would probably enjoy seeing the current implementation being broken again. The only mention of current PKCS1 1.5 implementations being broken are instances of you commenting on other people's projects and a blog post published on your company's website. I do not consider that sufficient enough proof for us to change our implementations. 

Lastly, if you consider the mere existence of an issue that has been mitigated already a vulnerability, however, I'd ask you to also stop promoting OAEP. Although the actual circumstances of this issue is as narrow as the one in PKCS1 1.5, there is a provable chosen-ciphertext attack on OAEP [as outlined in Mangers paper published in 2001](http://archiv.infsec.ethz.ch/education/fs08/secsem/Manger01.pdf).

**Comment by paragonie-scott** [comment]
> While it's for sure not a perfect solution, this is the exact reason ZF2015-10 never got uplifted into the PHP core, and the reason why the default is still OpenSSLs PKCS #1 v2.0 EMSA-PKCS1-v1_5 aka PKCS1_type_1.

I'm the person who was (informally) expected by the PHP internals team to propose the RFC/patch for this change, so, no, the reason you're proposing is one of your imagination. 

The real reason it never got uplifted into the PHP core is I thought ext/sodium was a better solution to focus on with my limited (and diminishing) free time.

> Since this is the second "omg your encryption is broken" issue in a short time (although the first one was not raised by you), I question the motives. While lobbying for better encryption is generally good, this behavior is spreading FUD. 

What do anyone's motives have to do with anything? There's no need to make it personal.

> The only mention of current PKCS1 1.5 implementations being broken are instances of you commenting on other people's projects and a blog post published on your company's website. I do not consider that sufficient enough proof for us to change our implementations.

See: https://robotattack.org

> Lastly, if you consider the mere existence of an issue that has been mitigated already a vulnerability, however, I'd ask you to also stop promoting OAEP. 

@MrPetovan invited me to propose a OAEP data migration strategy that would be backwards compatible, so that's what I did. OAEP is a stopgap, I'd rather suggest Ed25519 (RFC 8032).

**Comment by annando** [comment]
@denschub thanks very much for your detailed expertise!

**Comment by denschub** [comment]
> I'm the person who was (informally) expected by the PHP internals team to propose the RFC/patch for this change, so, no, the reason you're proposing is one of your imagination.

Yeah. Sure, if that goes through, I'll make Ruby release a new hotfix within 48 hours, take my word for it.

**Comment by paragonie-scott** [comment]
> [I won't be further replying to this thread. I confirmed my understanding of the backgrounds with multiple people and consider that final. If friendica does change stuff, I'd appreciate if you people stay compatible with us. :)]

and then

> > I'm the person who was (informally) expected by the PHP internals team to propose the RFC/patch for this change, so, no, the reason you're proposing is one of your imagination.
>
> Yeah. Sure, if that goes through, I'll make Ruby release a new hotfix within 48 hours, take my word for it.

If you want me to take your word for it, maybe consider not lying?

**Comment by MrPetovan** [comment]
This issue wasn't intended to take a cheap shot at Diaspora's cryptographic choice, since I can only act on the Friendica side and Dennis made his point clear the last time I raised an issue with the ECB mode for AES encryption. My invitation for @paragonie-scott was only to suggest a non-OEAP fallback method to keep Diaspora support while we somewhat improve the intra-Friendica crypto side.

**Comment by zotlabs** [comment]
@paragonie-scott Do you know offhand what PHP version first provided support for oeap? This padding option isn't mentioned in the php.net documentation and the documented choices are pkcs1 or none;  so I'm guessing that PHP version dependencies may also need to be taken into consideration.

**Comment by MrPetovan** [comment]
The padding constants are listed here: http://php.net/manual/en/openssl.padding.php

But the introduction version isn't mentioned for any of them.

**Comment by zotlabs** [comment]
After a bit more digging, oaep is listed under the public_encrypt/private_decrypt functions but *not* the private_encrypt/public_decrypt pair, so coverage is at best confusing.  I don't think either of our projects uses the latter algorithm pair but somebody on the Friendica side should probably verify this.  There is a php bug (65193) surrounding this flag but it's from 5.3 and 5.4 and shouldn't affect either project since both of these versions are far beyond end-of-life.

**Comment by MrPetovan** [comment]
I checked, we are using the default padding everywhere, especially with Diaspora since it's in their spec.

I looked into the PHP bug, and it turns out OAEP padding only makes sense for assymetric encryption (public_encrypt/private_decrypt) but not for assymetric signing (private_encrypt/public_decrypt). I'll make sure not to confuse both when I'm working on this.

**Comment by paragonie-scott** [comment]
As a follow-up, I detailed the particulars of the [anti-BB'98 dance](https://paragonie.com/blog/2018/04/protecting-rsa-based-protocols-against-adaptive-chosen-ciphertext-attacks#rsa-anti-bb98) in a blog post.

For interoperability purposes (since moving away from PKCS #1 v1.5 isn't going to happen), if anyone wants to try to make Friendica less vulnerable to chosen-ciphertext attacks, please refer to the linked post as a starting point. Feel free to cannibalize any of the example code you need.

**Comment by MrPetovan** [comment]
Thanks!

**Comment by annando** [comment]
We are moving from DFRN to AP for the internal communication. Which means that we cannot change anything in the encryption stuff.

**Comment by MrPetovan** [comment]
Fair enough, I couldn't find a way to ensure backward compatibility with older versions of Friendica anyway.
