### ISSUE TITLE
frio: Change wall-item-body e-content  to black

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#4606]
I really have difficulties to read the grey'ish on white article text in frio. Could you please change the normal text to black?
As far as i can see it's t **wall-item-body** and **e-content**  CSS styles.

**Comment by MrPetovan** [comment]
The short answer is "No.".

The longer answer is that we can make it slightly darker, but as a general accessibility rule, black text on white background is tiring to read for eyeballs because the maximum contrast between the two colors, and can even seem blurry to dyslexic people (see http://uxmovement.com/content/6-surprising-bad-practices-that-hurt-dyslexic-users/).

The current value is `#555`, let's try with `#444`. The difference is noticeable and hopefully it will solve your reading woes.

**Comment by rabuzarus** [comment]
@hoergen 
I guess your are familiar with css. You can try to write a css scheme for frio?
Have a look at https://github.com/friendica/friendica/tree/develop/view/theme/frio/schema for examples.

**Comment by hoergen** [comment]
@rabuzarus yes I thought already about that. And it's on my long "to-do&wishlist" ;)

**Comment by Andi-K** [comment]
@hoergen can you try out my [frio style.css](https://github.com/Andi-K/friendica/blob/patch-1/view/theme/frio/css/style.css)?

**Comment by MrPetovan** [comment]
Is this still relevant?

**Comment by foss-** [comment]
This should be no longer a problem with the new light, dark, black theme options for frio. Can we close this?
