### ISSUE TITLE
Invite mails are rejected for policy reasons

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#4755]
### Expected behavior
Invite mails are delivered to the recipient

### Actual behavior
Error 554 5.7.9 Message not accepted for policy reasons.

Received: by libranet.de (Postfix)
id F4xxxxxxxx; Thu,  5 Apr 2018 23:04:36 +0200 (CEST)
To: someone@yahoo.com
Subject: Please join us on Friendica
X-PHP-Originating-Script: 33:invite.php
From: friendicauser@yahoo.com
Content-type: text/plain; charset=UTF-8
Content-transfer-encoding: 8bit
Message-Id: <20180405210436.F4xxxxxxxx@libranet.de>

Problem is the FROM domain is not the SERVER domain.
We are sending the invite mails with the user's email address as FROM. These mails may be rejected by the receiving mail server.
 
### Friendica version you encountered the problem
Friendica 'The Tazmans Flax-lily' 2018-05-dev - 1259

### Friendica source (git, zip)
git develop

**Comment by ingoj** [comment]
Where did you configured it to send the invite mails from the registration users domain? I think this is not the correct behaviour in times of anti spam mechanisms like DKIM and SPF. 

For example my Friendica node mails from my own Friendica domain: 

> Von: Nerdica - your friends network <noreply@nerdica.net>
> Betreff: Détails d'inscription pour Nerdica - your friends network (@nerdica.net)
> Datum: 4. Februar 2018 um 21:13:54 MEZ
> An: xxxxxxxxx@gmail.com
> Antwort an: Nerdica - your friends network <noreply@nerdica.net>

In fact it is relaying all the mails from one virtual machine to my main mail server on another virtual machine. And the mail server is stating that the sender is www-data in my case. 

Sadly the provided log snippet from the MDN from Yahoo doesn't provide much detail. I think it would be a) perfectly valid from Yahoo to refuse mails from servers that are not their own and that are using a yahoo domain as a sender, but b) this would be ok when your mailserver (or friendica) would provide a valid X-Sender header. Generally speaking, mailing lists are doing exactly this: they are relaying mails on behalf of the original sender (From: address), but are adding additional header identifying the real sender (mailing list), so that it will pass the policy checking of the receiving mail server.

**Comment by AlfredSK** [comment]
I didn't configure anything. :-) This is the default behavior for **invite** mails, not registration mails.
I (postmaster) got the bounce mail from Yahoo. They seem to be very strict on this.
So, we should do something about it to make sure invite mails are delivered. Maybe it is enough to change the FROM to a local address (the one in admin/site maybe) and set the REPLY-TO to the user's mail address.

**Comment by annando** [comment]
Or we use the "sender"-header.

**Comment by SpcCw** [comment]
The problem still persists as invite e-mails are sent with "from" address identical to "to" address. The mails do get through but many e-mail providers mark them as spam and some email servers will reject it outright.

Here's how it looks on Gmail for example. Not very inviting :)

![image](https://user-images.githubusercontent.com/35988439/104705168-adbcb300-572a-11eb-8c5c-dfb989bb34a0.png)

**Comment by utzer** [comment]
Bounced email looks like this:
```
This is the mail system at host mail.schmitz.pro.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<***@yahoo.com>: host mta6.am0.yahoodns.net[67.195.204.79] said: 554
    5.7.9 Message not accepted for policy reasons. See
    https://postmaster.verizonmedia.com/error-codes (in reply to end of DATA
    command)


Reporting-MTA: dns; mail.example.com
X-Postfix-Queue-ID: ECC17300E15
X-Postfix-Sender: rfc822; admin@friendica.example.com
Arrival-Date: Thu, 14 Jan 2021 19:38:00 +0100 (CET)

Final-Recipient: rfc822; ***@yahoo.com
Original-Recipient: rfc822;***@yahoo.com
Action: failed
Status: 5.7.9
Remote-MTA: dns; mta6.am0.yahoodns.net
Diagnostic-Code: smtp; 554 5.7.9 Message not accepted for policy reasons. See
    https://postmaster.verizonmedia.com/error-codes
```
*** where the same user part in each place. 

Header of a test mail:
```
Return-Path: <admin@friendica.example.com>
Delivered-To: user@mail.example.com
Received: from localhost (unknown [IPv6:2a0a:4c9:4a:393:0:10:0:e6bb])
	by mail.example.com (Postfix) with ESMTPSA id 355D1300E15
	for <user@mail.example.com>; Thu, 14 Jan 2021 21:41:48 +0100 (CET)
Date: Thu, 14 Jan 2021 21:41:47 +0100
To: user@mail.example.com
Subject: Please join us on Friendica.
From: friendica_user_emailaddresse@userdomain.example.com
Sender: admin@friendica.example.com
Content-type: text/plain; charset=UTF-8
Content-transfer-encoding: 8bit
```
In case of yahoo rejected mail I think that the user and the invitee both are at yahoo.com.
