### ISSUE TITLE
"User not found" error in API /statuses/friends_timeline?count=50

### ISSUE THREAD

**Issue by LubuWest** [friendica/friendica#4838]
I get  the error {status{error:"User mit found","code": "400 Bad Request", "request","/api/statuses/friends_timeline?count=50"}}. It disappears if I reduce the count number to a lower value.

**Comment by annando** [comment]
Which version are you using?

**Comment by Andi-K** [comment]
Get the same error with Friendi**qa**.
see https://forum.friendi.ca/display/e18176ef165ad0a9fb5ad5b682883291

Only count=1 works for me.

**Comment by MrPetovan** [comment]
Possibly a unit test target for @rudloff

**Comment by Rudloff** [comment]
@MrPetovan I started writing [tests for `api_statuses_home_timeline()`](https://github.com/Rudloff/friendica/blob/7092951a15d946a985059c2e561ccf5775e497e4/tests/ApiTest.php#L845) but I did not reproduce this issue.
It's not really surprising, if it is triggered by specific items in the database, because the tests use a temporary database with [a very small dataset](https://github.com/Rudloff/friendica/blob/7092951a15d946a985059c2e561ccf5775e497e4/tests/datasets/api.yml#L36) (for now).

**Comment by LubuWest** [comment]
Ich hatte das Problem heute ebenfalls mit meinem anderen Account. Er verschwand erst, nachdem ich folgenden Post bei mir gelöscht habe: https://pirati.ca/display/ec054ce7165ad889c0cacd6055839825.
Ist an dem irgendwas besonders?
