### ISSUE TITLE
CRITICAL! Last git pull set my instance in "install mode"

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#4886]
My instance is unusable after last git pull.
I got the installation screen. Even if I fill out everything I got the message "database is already in use"

https://horche.demkontinuum.de/

**Comment by tobiasd** [comment]
Try copy your `.htconfig.php` file to `config/.htconfig.php`

**Comment by MrPetovan** [comment]
https://friendica.mrpetovan.com/display/735a2029375adb47de4b883830884927

**Comment by hoergen** [comment]
I copied .htconfig.php to /conf and it worked again. Was a little shock, but thank you all !! <3

I wonder. I /conf is a htconfig.php (without the dot) Seems to be the template?

**Comment by tobiasd** [comment]
I reverted that other PR.

**Comment by tobiasd** [comment]
We cannot assume that everybody does this manually. It has to be done automatically!

**Comment by hoergen** [comment]
So should i delete the /conf/.htconfig.php? (after git pull)

**Comment by MrPetovan** [comment]
No, you can leave it, you'll need it eventually.

**Comment by MrPetovan** [comment]
> We cannot assume that everybody does this manually. It has to be done automatically!

I disagree, `develop` isn't a stable branch, and we don't have an update mechanism reliable enough that we can use for this move. Besides, it would add yet another piece of code that isn't needed once you've upgraded, or worse, just installed.

**Comment by tobiasd** [comment]
I think it is fundamentally wrong to do such a thing and pledge the testers to forgive these annoyances of putting the nodes out of order willingly without any warning to do so so that they can prepare that it will happen.

It has nothing to do with stable branch or not. It is something that can be automated and should be for the easy of usage of the software. The installer simply can check both locations and copy the old config over to the new place if it is found but the other not.

Even if we note about this in the next release notes. People skip releases and pick the one in  a year or later. And are then confronted with this bug. All other now have totally forgotten about the change...

**Comment by annando** [comment]
1. There are people who auto update their servers every day. And you can't read a message like https://friendica.mrpetovan.com/display/735a2029375adb47de4b883830884927 when your site is down due to the change.
2. We do need some update mechanism for the master branch as well - so why not implement it right now and try it out in the develop branch?

**Comment by MrPetovan** [comment]
> The installer simply can check both locations and copy the old config over to the new place if it is found but the other not.

Ha, I actually didn't think about that, the update code that was submitted was put in `index.php` and it didn't sit well with me, but the install mod would be the perfect place for that.
