### ISSUE TITLE
Facebook connector

### ISSUE THREAD

**Issue by nupplaphil** [friendica/friendica#4969]
As I read at 
https://github.com/friendica/friendica/wiki/How-to:-Friendica%E2%80%99s-Facebook-connector
Facebook bridge/connector isn't working yet.

Is it planned to re-add this feature again?

What I see is that alternatives to Facebook lacks in their popularity because of the visibility to "non geeks". So for most people it's not understandable why they should switch.

Maybe if we make a more closer bridge to Facebook, we can set up Friendica as a real alternative with a transparent transition-path.

Let's say I move from Facebook to Friendica, non of my friends would recognize it, because I just left Facebook. But if I'm now able to post to Facebook out of Friendica (maybe with a little footnote and further informations about it ;-) ) we could spread the word better.

So the marketing slogan would be: "you can leave Facebook without leaving all your friends" ;)

What do you think? Is this a possible feature/idea? That would be really exciting and I would like to help you if it's possible :)

**Comment by MrPetovan** [comment]
As I understand it, it used to be that you could connect to the Facebook API using a single "app" for the whole server, and all users would communicate with Facebook using their OAuth credentials through that app.

However, Facebook apparently changed their API third-party access policy, and now every single user needs to create an app for the Facebook connector to work. Since it'd be nuts to ask regular users to go through the process of creating an app to connect to Facebook, the connector has been abandoned.

So technically, it would be possible to fix the connector, but it still wouldn't be accessible to regular users because of the app requirement.

**Comment by nupplaphil** [comment]
Hm.. As I understand (generally), there has to be a "connect to Facebook" button in Friendica for a user (who wants to connect) which triggers an app in Facebook for it?

If the process is easy/clear for every user, it seems possible/practical for me :-)

I'll start reading through the Facebook API :-)

**Comment by MrPetovan** [comment]
Yes, the same way there's a "Connect to Twitter" button, except the app setup only has to be done once for a whole node, and if I remember correctly for Facebook, this implies getting a developer account, creating an app, copy pasting obscure app ID and Secret into the addon config before being able to connect with it.

But then again, I don't have access to Facebook so I never tried the Friendica Facebook connector, it's all hearsay. Hopefully it's simpler than that to fix.

**Comment by annando** [comment]
It had been slightly different, but complicated. Only the admin has to request the keys - but in order to get them, one has to explain to Facebook which permissions are required, has to provide screenshots and has to explain why one thinks that this application enhanced the "Facebook experience", and so on. It's a lengthy process - and after this you can only post to Facebook, but not read from it, since Facebook doesn't grant you these permissions.

**Comment by nupplaphil** [comment]
Hm.. I'm currently walking through the docs. It's really not that easy.. Damn ;-)

But I found a API to read feeds: https://developers.facebook.com/docs/graph-api/reference/v3.0/user/feed

**Comment by metafarion** [comment]
I thought the sticking point was with Facebook's terms of service explicitly forbidding their API to be used to replicate their news feed to another site/service.

Cross posting would be great though.  At present, you can do it via the Buffer connector, but I would much rather my FB posts have a "via Friendica" than "via Buffer" tag.

**Comment by tobiasd** [comment]
Yes it was.

**Comment by annando** [comment]
@nupplaphil You won't be able to use this API: https://developers.facebook.com/docs/facebook-login/permissions/#reference-user_posts
> This permission is restricted to a limited set of partners and usage requires prior approval by Facebook.

**Comment by annando** [comment]
@metafarion Facebook completely removed the possibility to post to a profile. Even Buffer can't do anymore.

**Comment by annando** [comment]
Can we close this as "can't fix"?
