### ISSUE TITLE
Addon blockem causes Friendica to output error message due to `null` in $data variable

### ISSUE THREAD

**Issue by Quix0r** [friendica/friendica#5335]
Well, I wrote this with no sleep. ;-) So expect something not fully clear. :laughing: 

The following error was spotted there since type-hint has been changed to `array` (which is correct):
````
    - Fatal error: Uncaught TypeError: Argument 2 passed to blockem_display_item()
      must be of the type array, null given, called in /var/www/../htdocs/src/Core/Addon.php
      on line 246 and defined in /var/www/../htdocs/addon/blockem/blockem.php on
      line 142
````
The first step IMO is to add a type-hint to `callSingleHook()`'s `$data` parameter and remove the `null` there. Also `$hook` can be type-hinted on `array`. Next step is to find the cause step-by-step. Also `callHooks()` has `$data` with `null` and no type-hint.

Ticket at addons is [#600](https://github.com/friendica/friendica-addons/pull/600#issuecomment-403269957).

**Comment by Quix0r** [comment]
That is a very broad change as it touches a lot places. :-/ Hmm, how can it be fixed?

**Comment by Quix0r** [comment]
I think in `includes/conversation.php` in line `724` the `$arr` need to be declared as it is only declared in above `if()` block. Any ideas here? I don't know much the API of Friendica.

**Comment by MrPetovan** [comment]
The problem is only in `include/conversation.php` on line `724`. See https://github.com/friendica/friendica/blob/c6efbcd1aad965aebba1533bdeca26a66ae7339d/include/conversation.php#L720-L731

The `$arr` variable is undefined in this `else` block, unlike here earlier: https://github.com/friendica/friendica/blob/c6efbcd1aad965aebba1533bdeca26a66ae7339d/include/conversation.php#L678-L684

So:
- Either the `Addon::callHooks` is unwarranted and should be removed
- Or it is warranted and a `$arr` variable should be supplied with keys `item` and `output`,  and after it `$arr['output']` should be used to modify the `$threads` variable.

**Comment by MrPetovan** [comment]
Calling @annando to the rescue.

**Comment by annando** [comment]
I guess this can be closed anyway, can't it?

**Comment by AlfredSK** [comment]
Guess so. I use Blockem and I didn't see such an error lately.
