### ISSUE TITLE
Feature request: Show upload limits

### ISSUE THREAD

**Issue by ddeimeke** [friendica/friendica#5547]
Please include a view to see all upload limits that apply to a Friendica instance in the admin view where you can configure the application limits: Administration/ Site/ File Upload

Adding to the application settings there are PHP settings

```
upload_max_filesize 
post_max_size 
memory_limit 
```

And database settings (example for MariaDB/MySQL)

`max_allowed_packet`

that a apply as well.

See here - https://friend.d5e.org/display/a8083242205b60948cb3506246146403 - for a discussion on the topic.

**Comment by JonnyTischbein** [comment]
Displaying these values might not be a problem but how should them be configured since there are so many ways to set them. E.g.
 - .htaccess file (but only when using apache, will not working for nginx)
`     php_value upload_max_filesize 8M`
`     php_value post_max_size 9M`
`     php_value memory_limit 128M`
 - php.ini file via `ini_set('SETTING', 'VALUE')` or `.user.ini` File but will only work with **PHP_INI_ALL**
   - upload_max_filesize | "2M" | PHP_INI_PERDIR 
   - post_max_size | "8M" | PHP_INI_PERDIR 
   - memory_limit | "128M" | PHP_INI_ALL 

The same for the MySQL setting. Reading should be okay but updating the value needs to restart the service

Any idea how to set these values ?

**Comment by MrPetovan** [comment]
I don't think we should provide a way to change PHP/MySQL configuration from Friendica, it is completely out-of-scope. From my point of view, this issue is solved with the new display table.

**Comment by tobiasd** [comment]
I'm agreeing with @MrPetovan. Closing this issue as the limits are now shown in the admin panel.

**Comment by MrPetovan** [comment]
Closed via #5796
