### ISSUE TITLE
Community page needs better paging mechanism

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#5562]
### Expected behavior
When I have read a page on the community pages and I click on the "next" button I get the same content again and again. Sometimes I even get newer content instead older content after clicking the "next" button.. This shouldn't happen. It is expected to read the posts in chronological order.
I think we should improve the paging to get the expected content.
Edit: realkinetix: Infinite scroll on the community page would be FANTASTIC!

### Actual behavior
This is triggered when new content arrives on the community pages while I'm reading the content on the current page. And it is especially bad if you have enabled the relay system with scope ALL. Then you have to click very quickly :-) like 4 or 5 times on the "next" button to get the expected content.

### Steps to reproduce the problem
Go to the community pages. Global community is better to reproduce the issue. Wait some time. Click on the "next" button.
You may even use my global community page to see the behavior: https://libranet.de/community/global

### Friendica version you encountered the problem
2018.08-dev commit fa46e97f2799d19387ccf9ae2e1b0ff6d66efd1a

### Friendica source (git, zip)
git

### PHP version
7.0.30

### SQL version
10.0.34-MariaDB

**Comment by annando** [comment]
Possibly someone can have a look at how the network page is working.

**Comment by AndriyVolosh** [comment]
Hello!
Where is "next" button?
In my browser is only "back to top" button.

**Comment by dslivka1** [comment]
Hello, still open ? I cloud do it.

**Comment by annando** [comment]
Yes, it is still open.

**Comment by realkinetix** [comment]
Infinite scroll on the community page would be **FANTASTIC!**

**Comment by AlfredSK** [comment]
Additional: if you have some profiles/accounts communitysilenced you'll end up with pages that show only one or two items and sometimes even no items at all (if a high frequency poster had been silenced).

**Comment by MrPetovan** [comment]
Unfortunately, it makes sense.

## Technical explanation

The pagination works based on the ordering of items. Newer items are shown first, which means that you have 10 items per page and 10 new items coming every 5 seconds, you need to change page faster than that to get the older pages, because "page 1" content is constantly changing, pushing older content further and further away.

Additionally, we perform community silence/blocks after we paginated the items query, which effectively shortens the actual list of items.

## Remediation

We need a system that:
1. can keep the position you're at while paginating
2. can consistently show the expected number of items in each page

The first issue can be solved by using a `last_item_id` parameter instead of a page number. Let's say the first page shows 10 items from ids 1000 to 991 (reverse ordering). Then the second page shouldn't load any item whose `id` is greater or equal than 991, it's the `last_item_id`. The second page then shows 10 items from 990 to 981, which the becomes the `last_item_id` for the next page. The tricky part is to guess the `last_item_id` for the "previous" page link, so this solution may only make sense in an infinite scroll context.

The second issue is trickier. Either the silence/block is included in the SQL query, which performance may significantly degrade as more and more people are added to the silence/block list, or we take 4 or 5 times more items than the page limit from the database, filter by silence/blocks and only show the first 10 according to the page limit. This assumes there will never be more than 3/4 or 4/5 blocked posts per page, otherwise we would have the same described issue again where fewer items than the page limit show up.

**Comment by AlfredSK** [comment]
Sounds complicated. But with my limit understanding of the code I would say it should be exactly like the /network page. :-)

**Comment by MrPetovan** [comment]
The `/network` page has the same issue with next/previous links, but since items are coming slower it shows less!

**Comment by realkinetix** [comment]
Any chance anyone is working on the bug portion of this, the one handled by: "The first issue can be solved by using a last_item_id parameter instead of a page number. Let's say the first page shows 10 items from ids 1000 to 991 (reverse ordering). Then the second page shouldn't load any item whose id is greater or equal than 991, it's the last_item_id. The second page then shows 10 items from 990 to 981, which the becomes the last_item_id for the next page. The tricky part is to guess the last_item_id for the "previous" page link, so this solution may only make sense in an infinite scroll context."  ?

While getting infinite scroll going would be most excellent, the bug where the position is completely unknown between pages (hence you can get newer posts by going to the next page, which should have the next older posts) is not a lot of fun.

I'm not sure I ever saw @MrPetovan 's comments on this last year... I tried pulling the theme apart a bit and working on it, but there seems to be a lot involved with theming.

**Comment by MrPetovan** [comment]
Since I'm done with my UX improvements for frio, I can look into it over the next week.

**Comment by annando** [comment]
Please have a look at the paging with hashtags. This doesn't seem to work.

**Comment by MrPetovan** [comment]
How is it now?

**Comment by AlfredSK** [comment]
Much better! I can go back on forth and get the expected content. That is a huge increase for the usability of the community pages.
