### ISSUE TITLE
Can't install Friendica into a (sub-)directory

### ISSUE THREAD

**Issue by rabuzarus** [friendica/friendica#5858]
The present stable friendica version (2018.09) can't be installed to a directory because the installer doesn't recognize the `urlpath` anymore. This bug was introduced with https://github.com/friendica/friendica/pull/5295 (Commit: https://github.com/friendica/friendica/commit/5fdff3d8134afdc914bbc3c6fa11c72627325355)

### PHP version
5.6 and 7.2

**Comment by nupplaphil** [comment]
I'm afraid that's because of that:
https://github.com/friendica/friendica/blob/c48fcd4a8f329946cdf09d214596ecf29e859cff/src/Core/Console/AutomaticInstallation.php#L110-L120
The first `$phppath` should be `$urlpath`.

Solved with https://github.com/friendica/friendica/commit/fe6e600dc5ace900d913d10e4b8518c0f0248239 in PR #5828

**Comment by nupplaphil** [comment]
Seen at #5820

**Comment by nupplaphil** [comment]
What steps did you take to install Friendica?

- copied a prepared `local.ini.php` into `/config/` **or**
- installed it per "normal" web installer **or**
- installed it per command `bin/console autoinstall`

**Comment by rabuzarus** [comment]
I installed it per "normal" web installer (`/directory/install`). The problems appear with the the first page (which checks the requirements). The css isn't loaded because of the missing `urlpath`. The next page (the one with the db settings) isn't reachable because friendica doesn't use the `urlpath`

**Comment by MrPetovan** [comment]
I can't reproduce the issue in `/friendica/install` on my Debian server on `develop`. The CSS loads fine and goes to the next page.

However, the URL Rewriting fails by default because the `.htaccess` is missing and using the `.htaccess-dist` triggers a 500 Error because the `Options` value isn't allowed, possibly because I forbid `.htaccess` files to override the base directory config.

**Comment by MrPetovan** [comment]
I'm getting an invalid certificate error which may prevent me from seeing anything. Any error in the PHP log?

**Comment by rabuzarus** [comment]
```Array ( 
[REDIRECT_REMOTE_USER] => 
[REDIRECT_STATUS] => 200 
[HTTP_HOST] => kommune4.no-ip.biz 
[HTTP_USER_AGENT] => Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0 
[HTTP_ACCEPT] => text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8 
[HTTP_ACCEPT_LANGUAGE] => de,en-US;q=0.7,en;q=0.3 
[HTTP_ACCEPT_ENCODING] => gzip, deflate 
[HTTP_DNT] => 1 
[HTTP_CONNECTION] => keep-alive 
[HTTP_UPGRADE_INSECURE_REQUESTS] => 1 
[PATH] => /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin 
[SERVER_SIGNATURE] =>Apache/2.4.34 (Ubuntu) Server at kommune4.no-ip.biz Port 80
[SERVER_SOFTWARE] => Apache/2.4.34 (Ubuntu)
[SERVER_NAME] => kommune4.no-ip.biz
[SERVER_ADDR] => 192.168.1.45
[SERVER_PORT] => 80
[REMOTE_ADDR] => 80.130.196.188
[DOCUMENT_ROOT] => /var/www/html
[REQUEST_SCHEME] => http
[CONTEXT_PREFIX] =>
[CONTEXT_DOCUMENT_ROOT] => /var/www/html
[SERVER_ADMIN] => webmaster@localhost
[SCRIPT_FILENAME] => /var/www/html/friend/index.php
[REMOTE_PORT] => 42092
[REDIRECT_URL] => /friend/install
[REDIRECT_QUERY_STRING] => pagename=install
[GATEWAY_INTERFACE] => CGI/1.1
[SERVER_PROTOCOL] => HTTP/1.1
[REQUEST_METHOD] => GET
[QUERY_STRING] => pagename=install
[REQUEST_URI] => /friend/install
[SCRIPT_NAME] => /friend/index.php
[PHP_SELF] => /friend/index.php
[REQUEST_TIME_FLOAT] => 1539256460.802
[REQUEST_TIME] => 1539256460
)
```
