### ISSUE TITLE
 Admin panel: deleted users time counter

### ISSUE THREAD

**Issue by AndyHee** [friendica/friendica#5916]
The time counter that shows when a user was deleted seems to reset itself. 

Logging in after having deleted a user some time ago, one is presented with deleted "less than a second ago". Deletion of users itself appears not effected though. 

The issue apparently is both in the master and develop branch.

https://forum.friendi.ca/redir/137?url=https://friendica.hubup.pro/display/174591b4455bc35831eaa5d635218267

**Comment by MrPetovan** [comment]
The link isn't public.

**Comment by JonnyTischbein** [comment]
The error accurse because the table header says **Deleted since** but the selected value is `account_expires_on`. Of course is this datetime in future. The function to convert a datetime to a more readable string `Temporal\getRelativeDate()` calculates a negative values and returns

    $abs = strtotime($localtime);
    $etime = time() - $abs; 
    if ($etime < 1) {
        return L10n::t('less than a second ago');
    }

What is the more expected way?
- edit the Temporal Class to return a "in x Days y Minutes .." and edit the table header to **Delete in**
- display the real deleted since time

**Comment by AlfredSK** [comment]
Maybe this is the display... https://forum.friendi.ca/display/0b6b25a8305ba8bb1aefca2707953070
@MrPetovan

**Comment by MrPetovan** [comment]
Closed via #5922
