### ISSUE TITLE
Make magic links not open a new tab

### ISSUE THREAD

**Issue by vinzv** [friendica/friendica#6007]
Referencing #708 as it's somewhat related:
Clicking on a magic button opens a new tab. Could we change the behaviour to `target="_self"`?
E.g. in https://github.com/friendica/friendica/blob/develop/view/theme/frio/templates/nav.tpl#L47?

To elaborate a bit:
I have my node as pinned tab. When I'm surfing around and visiting other user's profiles on foreign nodes I have to go back by Alt + Left or unpin my tab and pin the newly created one.

**Comment by MrPetovan** [comment]
I'm not sure what you are referring to as "magic links". In the Friendica protocol, "magic auth" is the process by which you can authenticate on a different Friendica node if you are a contact of a user on the node. Consequently, "magic links" are the profile link that triggers the "magic auth" and point to the remote node.

Isn't `target="_self"` the default behavior for links anyway?

**Comment by MrPetovan** [comment]
I'm sorry, I read your second paragraph but I'm not familiar with pinning tabs, so I couldn't infer any meaningful information from it.

Thanks for the elaboration!

**Comment by MrPetovan** [comment]
I wanted to verify the issue and I tried to visit other people's profiles but the links you changed in your PR never showed up, is there something specific to do to get magic authed on remote nodes? I remember it working at some point, but I can't seem to be able to do it again.

**Comment by MrPetovan** [comment]
I tried to call on other people to verify but none have the same issue as you described: https://friendica.mrpetovan.com/display/735a2029-425b-eb1f-6bd2-b76210626167

Maybe it's a setting in your browser opening links from a different domain in a new tab by default?

**Comment by rebeka-catalina** [comment]
Yes, I have the same.

1) I click visit profile
2) I am on the profile page on the other node with magic-auth
3) I want to get back to my node and I clicke the 'home' button
4) My home opens in a new tab

In case of a pinned tab this isn't very convenient, because a pinned tab has got it's place in the tabs order. My friendica tab is for example always the first tab and my pleroma tab is the second. Pinned tabs get opened again when the browser was closed and opened again and the tab order of pinnend tabs is the same as before. Pinnend tabs can be reordered of course, but only with other pinned tabs, not with non-pinnend tabs, because they're much slimmer than non-pinned tabs.

![tabs](https://user-images.githubusercontent.com/7385838/61608385-c4c43700-ac52-11e9-9059-c9e202551268.jpg)

Now if I visit a profile in my pinned friendica tab and want to get back, click 'home' and my home opens in a new non-pinned tab then the new tab has to be closed and I have to go back in browsing history in my pinned tab.

**Comment by rebeka-catalina** [comment]
Oh interesting - I just gave it a try in another way and things are different:

If I open the 'view profile' link in a new tab and as next step click on the 'home' button then my 'home' opens in the current tab, not a new one. Seems like the issue happens only in pinned tabs :-)

**Comment by MrPetovan** [comment]
I would wager this is because the Home button links to a different domain, and the pinned tab is pinned to a specific domain.

**Comment by vinzv** [comment]
Yes, I just tried to reproduce this and it really is specific to pinned tabs. I did some research and this is intended by Mozilla:

> Links to other websites open in a new tab so that your Pinned Tab doesn't change. 

https://support.mozilla.org/en-US/kb/pinned-tabs-keep-favorite-websites-open#w_how-are-pinned-tabs-different-than-normal-tabs

So this is not a Friendica bug but a Firefox feature.

**Comment by MrPetovan** [comment]
I would have won my wager!
