### ISSUE TITLE
Excessive mentioning

### ISSUE THREAD

**Issue by clacke** [friendica/friendica#6075]
### Expected behavior

 - The author of a post/comment is using Pleroma.
 - I reply to a post/comment, mentioning only the author or nobody (the author implicitly).
 - The author gets a notification.

### Actual behavior

 - The author of a post/comment is using Pleroma.
 - I reply to a post/comment, mentioning only the author or nobody (the author implicitly).
 - Seemingly everybody in the conversation gets a notification.

https://github.com/friendica/friendica/issues/5874#issuecomment-428586632 is saying that we are *not* notifying everybody in the conversation, but my experience conflicts with this, see e.g. https://libranet.de/display/7284d89280ddf67c6e9c05e322125a8b0b717741 . There are likely subtle issues involved in this, e.g. who has reposted a comment.

### Friendica version you encountered the problem

```
This is Friendica, version 2018.12-dev that is running at the web location https://libranet.de. The database version is 1289, the post update version is 1281.
```

The responsibility for this mismatch in behavior lies between Friendica, Pleroma and the AP spec. As it is, Friendica is the implementation that stands out and is causing confusion with others.

The suggested fix is to not add indirect mentions to `cc`, but rather to just _bcc_ them, that is, to send the reply to their inbox without adding them to any field.

Whether this means just sending to the shared inbox or to the user-specific inbox is up for discussion. As far as I'm concerned, as long as it reaches their server we're fine, the server can decide whether the users in question will want to see the message in their timeline or not. Others have suggested that we make sure to send the message to their personal inbox to make sure they get it. I'm not sure if the behavior on e.g. Mastodon and Pleroma differs depending on which method you use.

**Comment by annando** [comment]
Problem with BCC is that many versions of Mastodon and Pleroma doesn't support the direct delivery to the personal inbox without addressing the account.

It is prepared that we use BCC: https://github.com/friendica/friendica/blob/develop/src/Protocol/ActivityPub/Transmitter.php#L348-L350

I also opened an issue at the repository of Pleroma: https://git.pleroma.social/pleroma/pleroma/issues/341

My opinion is that since we do have "to", "cc", "bto" and "bcc" we should use them differently. So using "to" causing a notification seems like a good idea (although Mastodon doesn't so), but "cc" is something less directly than "to" and shouldn't cause a notification at all. In fact I think that "bcc" should work like "cc", while "bto" should work like "to", means: It should raise a notification.

**Comment by clacke** [comment]
Is your conclusion from w3c/activitypub#326 that `bcc` is an element that can exist in server-to-server delivery?

**Comment by annando** [comment]
I think that "bcc" ant "bto" have to be removed before transport. So "bto" and "bcc" cannot be treated differently. (Yeah, I said something different above, but this had been shortly after waking up).

**Comment by clacke** [comment]
I think this has been resolved?

**Comment by annando** [comment]
I think so.
