### ISSUE TITLE
WordPress OStatus issues

### ISSUE THREAD

**Issue by pfefferle** [friendica/friendica#6103]
### Expected behavior

I build a WordPress OStatus plugin that also supports some basic Diaspora features. If I try to follow my blog on friendi.ca it identifies my blog as diaspora instead of OStatus, so it does not really work because of the very limited Diaspora implementation. Is there a way to hard-code an identifier with a meta-tag and or a webfinger property?

### Actual behavior

My Blog should be detected as OStatus instance.

### Steps to reproduce the problem

My identifier is: @pfefferle@notiz.blog https://client.webfinger.net/lookup?resource=pfefferle%40notiz.blog

### Friendica version you encountered the problem

I used an online version: https://loma.ml/

**Comment by pfefferle** [comment]
@MrPetovan thanks for your answer. I disabled the Diaspora profile and now it shows the correct type on the profile, but I still get an error that the "network type couldn't be discovered".

![bildschirmfoto 2018-11-09 um 16 37 39](https://user-images.githubusercontent.com/2373/48272028-f6d39700-e43d-11e8-800c-f329273769cc.png)
![bildschirmfoto 2018-11-09 um 16 38 34](https://user-images.githubusercontent.com/2373/48272029-f6d39700-e43d-11e8-8b96-e650bc601435.png)

**Comment by MrPetovan** [comment]
The next step is to thoroughly debug the network discovery process using your blog's address on a different node, unfortunately I can't do that until tonight EST.

**Comment by pfefferle** [comment]
Thanks, I appreciate any help, because I am not that familar with friendi.ca.

So if you really find some time to have a look into that problem, it would help me a lot.

**Comment by pfefferle** [comment]
I successfully tested the plugin with mastodon and with gnu.social, so it should generally work... if that info helps...

**Comment by MrPetovan** [comment]
Any info helps, thanks!

**Comment by pfefferle** [comment]
It seems to be correctly discovered (see first screenshot) but stored as PHANTOM: https://github.com/friendica/friendica/blob/8a46c786f37550160d81e7b7ecbcacb4c9fff493/mod/follow.php#L99

**Comment by MrPetovan** [comment]
Test reporting on `develop`:
- Trying to follow `@pfefferle@notiz.org` gave me the error you had because of the leading at-sign
- Trying to follow `pfefferle@notiz.org` worked and created a profile with the following data:
     - Profile name: `Matthias Pfefferle`
     - URL: `https://pfefferle.org`
     - Webfinger address: `matthias@pfefferle.org`
     - Network: Diaspora
- Trying to follow `pfefferle@ichmagdiesen.link`, I was able to submit the follow form but it returned an error.

Digging deeper, this is the result of probing `pfefferle@notiz.blog`:
```php
array (
  'name' => 'Matthias Pfefferle',
  'nick' => 'pfefferle',
  'guid' => '550c239bfa7462032546887d67f3e463',
  'url' => 'https://pfefferle.org/',
  'addr' => 'pfefferle@notiz.blog',
  'alias' => 'ymsgr:fuwa_rocks',
  'photo' => 'https://secure.gravatar.com/avatar/75512bb584bbceae57dfc503692b16b2?s=300&d=https://notiz.blog/wp-content/plugins/semantic-linkbacks/img/mm.jpg&r=g',
  'community' => '',
  'keywords' => '',
  'location' => '',
  'about' => '',
  'batch' => 'https://notiz.blog/receive/public',
  'notify' => 'https://notiz.blog/receive/users/550c239bfa7462032546887d67f3e463',
  'poll' => 'https://notiz.blog/author/matthias-pfefferle/feed/ostatus/',
  'request' => '',
  'confirm' => '',
  'poco' => '',
  'priority' => 0,
  'network' => 'dspr',
  'pubkey' => '-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAteUT/tnw9m9G9KJt1NNe
wYoaemobfjbBl5XMTYSZsNS8mn20h50jz2ITE/yg462U7hHDqDwoiL8lVZ8886Gh
7I5wtTdNUMOsLpSdzG+i8e+d5hUzrGZ0ASOzwK5xR8Y8Dt/pcRGgTJq2mpSwi7hJ
OkP9QIJpT9dp10W3fNFwL7swnigiM368KurtTIG+kZnYn49hnYPFcSma3lvzLLAf
5cEfGmMqHUfGx2SFE8oJd/ieBGn6yuON0XnfEiaXBdbudqLTGcnuXQLqDc31NQku
u8BIc/8Iq2EorZYyYUMl6Shgh63i7hyTIVBkQEwUvmibK1xS9p0nv5UYp4FQQz/2
jwIDAQAB
-----END PUBLIC KEY-----
',
  'baseurl' => 'http://notiz.blog',
)
````

The detected network is Diaspora because we check for Diaspora first and the webfinger for `acct:pfefferle@notiz.blog` returns at least one item with `rel: "http://webfinger.net/rel/profile-page"` and a `href` value, which is taken as the Diaspora profile URL. Then we poll the hcard URL provided and we found a `uid` that we store as the expected Diaspora GUID. You also have a `rel: "http://joindiaspora.com/seed_location"` that we use for the base URL.

Profile URL, GUID, Seed location URL, Public Key, that's all we need to conclude your account is Diaspora.

Aside: you have two webfinger items with `rel: "http://webfinger.net/rel/profile-page"`, one with `href: "https://notiz.blog/author/matthias-pfefferle/"` and one with `href: "https://pfefferle.org/"`, and the latter override the former in our loop.

-----------

Results of probing `pfefferle@ichmagdiesen.link`:
```php
array (
  'name' => 'Matthias Pfefferle',
  'nick' => 'pfefferle',
  'guid' => '',
  'url' => 'https://ichmagdiesen.link',
  'addr' => 'pfefferle@ichmagdiesen.link',
  'alias' => 'https://ichmagdiesen.link/author/pfefferle/',
  'photo' => 'https://secure.gravatar.com/avatar/d76efe7e0e05143a5f73e71a95ea9a6d?s=120&d=https://ichmagdiesen.link/wp-content/plugins/semantic-linkbacks/img/mm.jpg&r=g',
  'community' => '',
  'keywords' => '',
  'location' => '',
  'about' => 'Ich bin Webworker und arbeite als Senior Software Developer für die 1&1 Internet SE in Karlsruhe. Ich blogge, podcaste und schreibe eine Kolumne über das open, independent und federated social Web.',
  'batch' => '',
  'notify' => 'https://ichmagdiesen.link/author/pfefferle/?salmon=endpoint',
  'poll' => 'https://ichmagdiesen.link/author/pfefferle/feed/ostatus/',
  'request' => '',
  'confirm' => '',
  'poco' => '',
  'priority' => 0,
  'network' => 'stat',
  'pubkey' => '-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAx+QGlb5WzOQDmVGsXrZxT
ZBG/yZKzOtncf1NIaWjOMqPUmTSAeb14nCdbzIJ2v7GHwn1DSr5YhwWs+FxByEuVV
zsEiHxfwQnY1HJZOuY6BCbjMlYiDfygGBuSlstBO3Z9XR8tr+R6EtmJQHPjECaOrL
Zhlq2Jciu14wR9gLXkzU+5OSqgXpTzQleaGrcCwWcj3vSEW7SaaaMm0VduU3670wh
yJ5IJ/yzAZdqUBrdhX1HoT/PxApLZxc31TJNUEATtEX77iO2u+g6pYl1Gde3UQAIn
21683hUxiG3tG/EjwRcTy8lJ0M5nnWrpr6gpMr13jHWCZUVjkHzBKusfgE5FwIDAQ
AB
-----END PUBLIC KEY-----
',
  'baseurl' => 'http://ichmagdiesen.link',
)
```
This time the detected network is OStatus, but since the produced profile url `https://ichmagdiesen.link` doesn't have a slash at the end, we discard it when it comes to connect with it.

Disregarding the missing slash, I end up being connected with a profile with the following information:
- Profile Name: 1und1 – LinkLog
- Profile URL: https://ichmagdiesen.link
- Webfinger address: 1und1@ichmagdiesen.link
- Network: OStatus

Is that what you expected? If yes, I'll submit a quick patch for disregarding missing trailing slashes.

**Comment by pfefferle** [comment]
One last question, why is friendi.ca using the main URL as profile URL instead of the profile URL from WebFinger (https://ichmagdiesen.link/author/pfefferle/) ??? Do I have to change something?

**Comment by pfefferle** [comment]
Ok, two last questions ;)

Is there something I could change to also prevent the trailing slash issue?

**Comment by MrPetovan** [comment]
> One last question, why is friendi.ca using the main URL as profile URL instead of the profile URL from WebFinger (https://ichmagdiesen.link/author/pfefferle/) ??? Do I have to change something?

Yes, this was my aside, buried in my comment: You have two Webfinger properties with `rel: "http://webfinger.net/rel/profile-page"`, the first with the expected profile URL, the second with the main URL. Due to the order we are processing the webfinger links, the second value overrides the first.

I don't know how you generate those webfinger links, but I don't think you should have the same `rel` twice. If you can remove the main URL link, Friendica would correctly get the profile URL.

> Is there something I could change to also prevent the trailing slash issue?

Again, I don't know how you are generating your webfinger links, but if you can add a trailing slash to the base URL for `https://ichmagdiesen.link`. You may have to do it in the Wordpress settings. I'll submit the patch shortly, so this will be a non-issue on `develop` soon.

**Comment by MrPetovan** [comment]
I just checked the spec, and the order of links with the same rel indicates a preference order, with the first being most preferred. Our implementation is wrong in that regard.

**Comment by MrPetovan** [comment]
After fixing the link ordering issue, the OStatus contact URL (for `pfefferle@ichmagdiesen.link`) still was the main URL. It turns out the OStatus feed URL (https://ichmagdiesen.link/author/pfefferle/feed/ostatus/) has `https://ichmagdiesen.link` as the `<link rel="alternate">`, and ultimately this is the URL we use for the profile URL.

After checking the relevant RFC (https://tools.ietf.org/html/rfc4287#section-3.2.2), it turns out that if present, the author URI probably should take precedence.

**Comment by MrPetovan** [comment]
After fixing both those issues, both your profile URLs show up as expected.

**Comment by pfefferle** [comment]
Thanks a lot for your fast help!

**Comment by MrPetovan** [comment]
You're welcome, it was a fun challenge and it allowed me to touch the protocol side of Friendica without having to be sucked in it forever,
