### ISSUE TITLE
Normalize Message button handling with remote authentication

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#6410]
From @rabuzarus in https://github.com/friendica/friendica/issues/3838#issuecomment-340836080

> Friendica should provide two different ways of handling the `Message` button.
> 
> If a person is a visitor (no established connection) the `Message` button on the profile page should point the visitor to `/wallmessage` (in frio it is opened in a modal). All messages which are written with `/wallmassege` are submitted as not validated author (because the system can't verify (at the moment) if the author of this wallmessage is really the author he/she claims to be. With other words, at the moment friendica is not able to authenticate contacts who aren't connected to the contact).
> 
> If a person is a guest (remote user - a contact with an established connection) the `Message` button on the profile page should redirect to the guests local `message` page (with additional data to tell the local `message` page the name and address of the recipient. The recipient should be the profile owner of the visited profile page). So it would be possible to send real private messages with authenticated contact information.
> 
> BTW: Frio can handle the two different situations (https://github.com/friendica/friendica/blob/develop/view/theme/frio/js/modal.js#L349)
> 
> 
> Some bug tracing:
> Which of the two links will be used is decided at https://github.com/friendica/friendica/blob/develop/include/identity.php#L268 (and L284).
> 
> When I visit the support forum as authenticated user (guest through magic-link) the `Message` button is pointing me to `/wallmessage/helpers`. But it should point to my local `message` module (because I'm a authenticated guest). Something went wrong here.
> 
> Because of the fact that I'm authenticated, no redirection url is submitted to the helpers forum (we don't need it because all data of an authenticated contact are stored in the contact table and we take all necessary date from this table) and `/wallmesage` will stop if we don't have an URL (https://github.com/friendica/friendica/blob/develop/mod/wallmessage.php#L77). In other themes `/wallmessage` will output an error message. Frio doesn't output this error message because the content of `/wallmessage` is loaded to a modal.
> 
> Back to the real problem? The big question is: Why do we don't get the redirection link to local `message` page for authenticated users? (https://github.com/friendica/friendica/blob/develop/include/identity.php#L268 and some lines below).
> 
> 
> Semi-OT:
> Is it useful to have the possibility to write private messages to forum accounts or should we remove it in such cases.

**Comment by rabuzarus** [comment]
Since introducing remote authentication through OWA we have introduced another issue. The message butten will appear for unknown contacts (visitors) which authenticated through OWA even if the profile owner disabled private messages for unknown contacts.
The source of the problem is https://github.com/friendica/friendica/blob/2019.01/src/Model/Profile.php#L363

If the visitor is `remote_user()` we show the button but if the contact is authenticated through OWA he/she is a `remote_user()`. `/wallmessage` won't let the contact write a message but in Frio you will get an ugly empty modal.

To solve this issue we need to check if the visiting contact does have a connection with the profile owner instead of `remote_user()`

**Comment by MrPetovan** [comment]
Fixed by #7250
