### ISSUE TITLE
Re-introductions

### ISSUE THREAD

**Issue by imattau** [friendica/friendica#6519]
### Actual behavior
Recently had to reinstall the Friendica instance, and did not have an backup (I know). When using the same username/instance name, the DB has no information, but previously contacted users do.

This means that when you go to make contact again with previous accounts, the system states that you've already been introduced. As such, you are unable to add them to your contact list. [Friendica Support comes to mind]
### Steps to reproduce the problem
Not have a DB backup in place
Attempt to make contact/follow a previously followed user.
### Friendica version you encountered the problem
2019.1

### PHP version
7.1
### SQL version
MySQL/MariaDB

**Comment by MrPetovan** [comment]
Unfortunately, with our encryption layer requiring a pair of cryptographic keys to formally identify your account (and not some ill-intentioned stranger), you can't use the same nickname on the same domain without having the correct keys.

Consequently, there are only three solutions to this problem:
1. Find your keys in a database backup
2. Use a different nickname on the same domain
3. Use the same nickname on a different domain (or sub-domain)

**Comment by MrPetovan** [comment]
See #3466, of which this issue is a duplicate.

**Comment by annando** [comment]
To clarify: This is not a bug, but a security issue. Instances open and close all the time. So you could buy a domain name that once had been used for another Friendica instance. When there hadn't been this tests, you would be able to impersonate someone that you aren't.

**Comment by imattau** [comment]
No worries.

**Comment by strk** [comment]
To be honest, I think it's a HUGE bug. There's no security issue as long as you ask the users what to do.
That I can NOT re-introduce myself to a contact I used to have is a bug, keeping to call it a non-bug is really a mistake....

**Comment by MrPetovan** [comment]
It still isn't a bug. It's a strict security default and a massive inconvenience, granted, but not a bug. The code is behaving exactly as expected, even if it is inconvenient. It could be improved through additional work, but there's nothing to fix.

**Comment by strk** [comment]
If you don't consider it a bug in the implementation then it's a huge design issue. Short-sighted design. Defective by design...

I just lost my friendica node once again (and no, I'm NOT taking backups, intentionally).

When setting up a new node and "inviting" someone, the invited party needs to accept/reject the request.
All I'm asking for is to still let targets accept/reject new invitations from people having different encryption key BUT same username/domain name.

I'm not asking to blindly accept the new key (which I agree would be a security flaw) but rather to be prompted to either accept or reject the new key, approving or denying a key change.

Note that being UNABLE to change key is also a security concern. Keys can be compromised, so if my key gets compromised there's currently no way to revoke trust on the old key and build trust on the new key w/out also changing federated identity (username or domain). This is a really bad bug. 

Shall I file a new ticket or could you reopen this one ?

**Comment by MrPetovan** [comment]
I see you have opened a new ticket, that's what I would have suggested, thank you.
