### ISSUE TITLE
"view profile", "view status" and "view photos" in contact pull down menu broken for Friendica contacts

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#6532]
### Expected behaviour

Selecting "view profile" or "view status" links/menu entries from the pull down contacts menu using the vier (duepunto zero, quattro, smoothy) to redirect to the <s>remote</s> profile or status page of the contact.

### Actual behaviour

An error occurs. For me it look like the redir is sending the user to the local instance instead of the remote instance.

**Error 400 - Bad Request**

### Steps to reproduce the problem

* use duepunto zero, quaddro, smoothy of vier as theme
* open the contacts pull down menu in `/network`, `/display` or `/contact`
* follow either of the three menu entries.

### Friendica version you encountered the problem

2019.03-dev

### Friendica source (git, zip)

git

### PHP version

7.2

### SQL version
mysql  Ver 15.1 Distrib 10.1.37-MariaDB

**Comment by tobiasd** [comment]
I've just tested it with a local contact. The issue it the same, regardless of the same or a different server is involved, the redir link is not working.

**Comment by MrPetovan** [comment]
What are the initial redirection links and what do they redirect to?

**Comment by tobiasd** [comment]
Show profile: `/redir/126854?url=profile` which leads to `/profile?zrl=https%3A%2F%2Fexample.com%2Fprofile%2Ftobias`. All on my local server.

The magic link from the contacts name is the same `/redir/126854`, redirects to the correct (in this case remote) profile and I'm welcomed and authenticated.

**Comment by rabuzarus** [comment]
Since https://github.com/friendica/friendica/commit/491fc5f78aadb787a57a0f0630779f457ff1bcb4#diff-c79123bcd9a489c7f30ba7b962726a50 we don't use dfrn-auth anymore. Instead we use OWA if it is available. (Only if it isn't available redir uses dfrn-auth). Because we use OWA we need a full `href` as `url` parameter to get authed and redirected.
So the the address from your example above needs to be `/redir/126854?url=https://remoteinstance.com/profile/name` to work correctly with OWA

**Comment by MrPetovan** [comment]
Another report of 400 errors on profiles: https://forum.friendi.ca/display/fa94cab1-905c-70a1-3ddd-94d238640572

**Comment by MrPetovan** [comment]
trashHeap provided these steps:
```
1. I visit this link: https://social.notlocked.in/contact
2. Submit https://social.notlocked.in/profile/test or test@social.notlocked.in as a contact via the connect button.
3. Arrive at https://social.notlocked.in/follow?url=https%3A%2F%2Fsocial.notlocked.in%2Fprofile%2Ftest&submit=Connect
4. Hit "submit request"
5. Arrive at https://social.notlocked.in/dfrn_request/test
6. Observe "Invalid profile URL."
```

Is it the same issue?

**Comment by tobiasd** [comment]
I have partially fixed this in the Contact::photoMenu() but this only seems to affect the photoMenus in the `/contact` overview. The photoMenus in e.g. `/network` and `/display` seem not to follow this changes. Will investigate this further later.

**Comment by tobiasd** [comment]
Ha... lets see if I broke frio...

**Comment by MrPetovan** [comment]
I have verified the pull down menus links for Friendica contacts in the `/network` page  on the vier theme are working as expected.

**Comment by WNYmathGuy** [comment]
I was about to make a new issue for this because it's failing for me in 2019.01

Is this fixed but not released yet?

![view profile option](https://user-images.githubusercontent.com/28640985/53697206-04ba7880-3d9d-11e9-9c38-070e1b928944.png)

![view profile fail](https://user-images.githubusercontent.com/28640985/53697205-0421e200-3d9d-11e9-9de4-77983110a85d.png)

**Comment by MrPetovan** [comment]
Yes, fixes are first made available in the `develop` or `-rc` branch and they are made available in the `master` branch on release day. Please wait for the 2019.03 version release.
