### ISSUE TITLE
File storage options in Admin Panel

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#6533]
The selection box for file storage systems in the admin panel reads

* none
* database
* file system.

From the reply of @fabrixxm in the forum thread:

> if nothing selected, files are stored just like before, in "data" column in table (Photo or Attach tables)
if you select Filesystem backend, files are stored in a directory you select, and only a reference to it  it's stored in table. if you select Database backend, files are store in a brand new table in database. I don't know why someone would choose the Database backend, but anyway, at least you can exclude the table from database dumps. If you switch backend, already stored files are not moved, unless you move them explicitly using console script. If you change the folder where Filesystem backend stores files after you already used it, you have to move existing subfolders from the old location to the new by hand, or the backend will not find files.

The "none" entry in the selection list is plain wrong, as files are stored.

Additionally the different options need a better documentation (apart from the "Backend used to store uploaded files data" which does not really help in the decision process).

**Comment by copiis** [comment]
What is the recomendation?

**Comment by fabrixxm** [comment]
"None" could be replaced by "Database (Legacy)".
Documentation is in /help : https://kirgroup.com/help/Settings#1_2_3_1 (improvable, of course)
I don't really know what to write in settings page, as is just a description of the setting. I would not put a detailed description of every backend because: 1- that's not the place. we have docs for this (we could add a link to docs) 2- addons can add new backends that will not be described anyway..

**Comment by MrPetovan** [comment]
You can add something like "If you change the storage backend, you have to manually move the existing files, see [link to doc] for more information about the choices and the moving procedure."

**Comment by tobiasd** [comment]
Calling that option "Database (legacy)" sounds a lot better then "none".

The help in the admin panel simply states "Backend used to store uploaded files data" for an option that is named "File storage backend" has no information value for me. I would expect a short explanation of the options available.

**Comment by MrPetovan** [comment]
The limitation is that you can add new storage backends via plugins, and the added options wouldn't be explained in the admin setting blurb.

**Comment by tobiasd** [comment]
But those addons would need to be activated actively by the admin, so one can assume that they would at least skip over the README.md files of the addons as it is displayed in the admin panel.

**Comment by MrPetovan** [comment]
Indeed. I just brought up a limitation of the help text.

**Comment by AlfredSK** [comment]
If I understood the storage system correctly the new description in admin panel isn't entirely correct. It says...

> If you change the storage backend, you **have to** manually move the existing files

But you don't have to move the existing files (in the sense of 'must'). It's more like "you **may** move the files" (in sense of 'can' do it) because it works also w/o moving the already existing files to the new place.

**Comment by miqrogroove** [comment]
Just out of curiosity, I can't seem to find this feature.  Is it still in beta?  Or did I look in the wrong place?

**Comment by MrPetovan** [comment]
It is in the RC branch and will be released in the upcoming 2019.03 version.

**Comment by tobiasd** [comment]
It is available in the develop and the 2019.03-RC branch only at the moment. The it is the `File storage backend` option in the `File Upload` section.
