### ISSUE TITLE
Event activity IRI returns a 404

### ISSUE THREAD

**Issue by lanodan** [friendica/friendica#6603]
### Expected behavior
* `id` of an Event Activity should be reachable (when Public)

### Actual behavior
* Can be seen in the actor’s `outbox`
* Cannot be seen with the `id`’s IRI

### Steps to reproduce the problem
* Post a Public (and shared?) Event
* Get the latest Activity from the outbox: ``curl -H 'Accept: application/activity+json' https://snarl.de/outbox/lanodan_frndk?page=1 | jq .orderedItems[0]``
* Try to get it with it’s id: ``curl -H 'Accept: application/activity+json' https://snarl.de/objects/0bf23919-615c-5c43-5755-801356473003``

Note: Seems to work with the :link: URL on the Interface, on my case: https://snarl.de/display/0bf23919-605c-5c43-5755-cd0840824904

### Friendica version you encountered the problem
* 2019.01

### Friendica source (git, zip)
Unknown
### PHP version
Unknown
### SQL version
“The database version is 1293, the post update version is 1281.” ?

**Comment by MrPetovan** [comment]
Thanks for your report, we'll look into it.

**Comment by annando** [comment]
Thanks for having a look at our events. Currently this is totally untested with AP.

**Comment by annando** [comment]
@lanodan we are fetching all objects via the GUID. The URL always does contain the GUID. Always? No, due to some bug, for events the GUID part of the URL had contained a different GUID.

Thanks to your request the problem had been found and solved. If you want to test it now, you had to use some Friendica server at the develop branch - or wait for the release, which is expected in March.

Or you could test with my test entry: https://pirati.ca/display/ec054ce7-195c-63c4-01de-b45644532384

**Comment by MrPetovan** [comment]
Closed via #6648
