### ISSUE TITLE
at-mentions sometimes dropped

### ISSUE THREAD

**Issue by clacke** [friendica/friendica#6628]
### Expected behavior

 - Person A (not on Friendica) writes a post/comment containing mentions of other users.
 - I see the post roughly as it looks on A's instance.

### Actual behavior

 - Person A writes a post/comment containing mentions of other users.
 - On my Friendica instance some mention(s?) is missing.

Observed case:

https://libranet.de/display/52acf9cd7175f147596b29267af9b682602e7c94

vs

https://mastodon.social/@rysiek/101567725980049179

The particular circumstances around this comment is that it's ActivityPub and the mention stripped is a mention of the author of the post replied to. But I haven't looked into this enough to know whether this is the full and correct description of when this happens.

I know that when I write a mention of the author of a post I'm replying to, in Friendica, that does not get stripped, so I suspect this is not intended behavior. Is it in the AP HTML->bbcode translator?

### Friendica version you encountered the problem

`This is Friendica, version 2019.03-dev that is running at the web location https://libranet.de. The database version is 1302, the post update version is 1297.`

**Comment by MrPetovan** [comment]
This isn't a bug, it's a feature™

Introduced by #6614, it strips implicit mentions from ActivityPub because Friendica doesn't need them to build the thread. As a result, you only see the explicit mentions, those who have actually be written by remote contacts.

Additionally, it works both ways, adding implicit mentions to Friendica posts when it is distributed to ActivityPub targets, as to mirror the common behavior. The absence of implicit mentions in Friendica replies had been reported as confusing by Mastodon users.

**Comment by MrPetovan** [comment]
Although from your example, it seems that it's skipping `@cwebber` when it should have stripped it from this reply: https://mastodon.social/@rysiek/101567725980049179

**Comment by clacke** [comment]
It's confusing. I thought https://libranet.de/display/76deaa7e53e870d9b8ecf5581307cf2a6210a3ec was not directed at me, as it explicitly mentioned another user and didn't mention me. Had I seen the original text with all mentions intact, I would have known it was for me.

Maybe adding the removed mentions to the mentions-and-tags line would help make it less confusing.

I'm not sure what you mean by implicit mentions. The original post contains the text `@clacke` and the post as represented on Friendica doesn't.

Adding explicit mentions when sending to AP is great and will save me a lot of manual effort.

**Comment by MrPetovan** [comment]
The idea is to keep Friendica behavior no matter the remote server software. When someone on Friendica replies to one of your posts, it doesn't generate an explicit mention, either in the text or in the tag, and you only receive a notifications "X replied on your post".

Mastodon's implicit mentions rocked that behavior by adding a mention in the body which changed the notification to "X mentioned you" and recently "X mentioned you on your post". #6614 is an effort to normalize behaviors, both locally and remotely, by restoring the Friendica behavior on Friendica and the Mastodon behavior on Mastodon (and Diaspora that doesn't display nested threads either).

Evidently I'm missing something because it doesn't strip more than one implicit mention.

**Comment by clacke** [comment]
Hmm, yes, I see what you mean and I like the idea, but evidently it's tricky to strike the right balance. Anyway, it's intended behavior and not a bug, so I'm closing and we can discuss elsewhere. I have more comments on this. :-)
