### ISSUE TITLE
Add "replied to you" notification

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#6757]
Follow-up to #6676

### Current behavior

With the new implicit mentions system, someone replying to your comment will trigger a "X tagged you on Y post" notification because your profile URL is included in the `item.tag` virtual field as an implicit mention. But no explicit mention can be seen in the post itself.

### Expected behavior

Someone commenting directly on one of your replies should trigger a "X replied to you on Y post" notification that should replace the "X tagged you on Y post" notification.

### Technical details

- Notifications are emitted from `check_item_notifications()` in `include/enotify.php`.
- Currently we retrieve the top-level parent (identified by the `item.parent` field) but we don't retrieve the immediate parent (identified by the `item.thr-parent` field).
- Additionally, we need to retrieve the public contact ID of the UID we check the notifications for with `Contact::getPublicIdByUserId` to match it against the immediate parent `item.author-id` field.
- This check has done be done last to overwrite the notification type expectedly set to `NOTIFY_TAGSELF` otherwise.
- A new notification type can be created, with the associated constant. Suggested name: `NOTIFY_COMMENTSELF`.
- The actual text of the notification is set in the `notification()` function in the same file.
- The new notification type will probably go in the `if ($params['type'] == NOTIFY_COMMENT || $params['type'] == NOTIFY_TAGSELF) {` block.

**Comment by MrPetovan** [comment]
Nice to have moved to the next milestone.

**Comment by annando** [comment]
The notifications are a huge mess. There is still much stuff in /include for this. I think that we have to completely rewrite this - including a complete new way of performing notifications. For example we don't need to store the notification text for each notification. We only have to store the type of notification and some related data.

**Comment by nupplaphil** [comment]
I already started some refactoring of `include/enotify.php` (creating own classes for Mailing & Storing notifys), but since you have plans for it too, I better suspend my work :-).

**Comment by nupplaphil** [comment]
@annando I already tried to find some common patterns for all the different notifys. So I created a List of every call and what content is in it. You can find it here: https://ethercalc.org/bni01fi70uff

**Comment by annando** [comment]
I currently haven't made too much thoughts about it. I would like to reduce the data that needs to be stored in the "notify" table for example. We need to store:
* What happened (created a post, answered to your post, mentioned you, posted something in a thread where you interacted or that you created, ...) (I would like to use some ENUM value for this)
* Who did it (the public contact id is enough)
* When did it happen (timestamp)
* Where did it happen (the item id or event id)

We don't need to add something to that table for contact suggestions (they are handled in a different place), contact requests or PM. (Although contact requests and PM notifications should be send via e-mail as well)

I also do see that system notifications (like "your account gets suspended if you don't log in" - and similar stuff) could be send as a regular PM from a system account to reduce complexity.

I would like to have only "notify" table related actions in some "Notify" model class. The notifications that are sent solely via mail could be moved somewhere else since they vary too much from the structure that is described above.
