### ISSUE TITLE
Timezone inconsistencies coming out of PHP error logs

### ISSUE THREAD

**Issue by realkinetix** [friendica/friendica#6822]
### Expected behavior

All PHP error logs logged with the set timezone in php.ini.  Mine is set as:
date.timezone = America/Toronto
(as is my system time)

### Actual behavior

3 consecutive log lines show the issue I'm seeing:
```
[07-Mar-2019 09:17:57 America/Toronto] PHP Warning:  mail(): Could not execute mail delivery program '/usr/sbin/sendmail -t -i ' in /home/friendica/friendica/src/Util/Emailer.php on line 100
[07-Mar-2019 14:45:01 UTC] PHP Notice:  Undefined index: url in /home/friendica/friendica/mod/follow.php on line 63
[07-Mar-2019 14:05:11 America/New_York] PHP Notice:  Undefined index: term in /home/friendica/friendica/mod/filerm.php on line 15
```
I'm *really* confused as to how New_York shows up there at all, as I can't find anything that is hard-coded to that.  Lots of fall-backs to UTC in various places in the Friendica code (and additional pieces), but I don't know how the fallbacks would be happening unless something isn't carrying the PHP setting along.

### Friendica version you encountered the problem

Current -RC

### Friendica source (git, zip)

git

### PHP version

7.3.2

### SQL version

mariadb 10.3.12

**Comment by MrPetovan** [comment]
I've also noticed two different timezones in my log, usually UTC and America/New_York, my Friendica timezone.

Your issue might come from the fact that you have an additional timezone set server-wide, you end up with:
- UTC (before any timezone is set?)
- America/Toronto (default PHP timezone)
- America/New_York (user-defined Friendica timezone, used to show local times for posts)

**Comment by annando** [comment]
I really would prefer, always having UTC as log time.

**Comment by MrPetovan** [comment]
It makes sense, this would require the Logger to ignore/bypass:
- the user-defined Friendica timezone
- the php.ini-set timezone
- the server-set timezone

**Comment by realkinetix** [comment]
@MrPetovan - As far as I know, most servers should have a site-wide timezone configured. I would consider it bad practise to not have one set.

@annando - Timezone handling should really be up to the administrator, imho.  I'm aware of the fun that can be had with non-UTC logging, but I'm happy to work with that, and would prefer my logs were consistent (ie: I have the timezone set in my php.ini which matches the system timezone which matches the rest of the system logs, etc....)

**Comment by MrPetovan** [comment]
Servers always have a timezone set, either UTC or the local timezone of the location they are housed in. But it isn't necessarily the same as PHP's timezone, the Friendica node's timezone or the logged in user's timezone.

**Comment by realkinetix** [comment]
Oh, you're suggesting that errors that hit the PHP log could have the user's timezone set on it?  I guess that makes sense as to why I'm seeing that in the logs at all, but I think the user's timezone is something that should be ignored for system logging.   (And the user has no access to these logs, of course, unless it's me.)

**Comment by MrPetovan** [comment]
Yes, currently we set up the user's timezone for the rest of the PHP execution, including logging and template display. Logging should be excluded.

**Comment by tobiasd** [comment]
> I really would prefer, always having UTC as log time.

We always had UTC in the log files for the timestamps. This is important to look at decentralized and federated issues because then everybody in the conversation has the same time zone in the logs and does not need to do additional math to compare the logs from Sydney, Madrid and New York.

**Comment by realkinetix** [comment]
No debate on that point, I can see that being immensely useful in that case.

**Comment by nupplaphil** [comment]
I changed logging timezones to `UTC`. So is there something else which we should change to `UTC`? As already said at #6838 , it isn't possible to change the server timezone through PHP, so syslog logging would remain as is.

Should be changed for 2019.03-RC too with #6837 (so I set the milestone to 2019.03)

**Comment by MrPetovan** [comment]
Fixed with #6837

**Comment by realkinetix** [comment]
Were the changes supposed to affect PHP's own error output?  My php-fpm error log still has alternating timezones:

[11-Mar-2019 15:21:27 America/New_York] PHP Notice:  Undefined index: adjust in /home/friendica/friendica/mod/events.php on line 464
[11-Mar-2019 20:10:05 UTC] PHP Notice:  Undefined index: author-network in /home/friendica/friendica/include/conversation.php on line 960
[11-Mar-2019 16:25:36 America/Toronto] PHP Warning:  POST Content-Length of 18157682 bytes exceeds the limit of 8388608 bytes in Unknown on line 0

Those are 3 consecutive lines from the log.

**Comment by MrPetovan** [comment]
Nope, just the Friendica debug log. This is between you and your server now.

**Comment by realkinetix** [comment]
This seems to be back to square one then... I've set the timezone in the php.ini, which I believe is the only place I can affect this output.  These items are all being generated by Friendica, so, how could this be something between me and the server?

**Comment by MrPetovan** [comment]
There are multiple logs and timezones, bear with me while I describe each:
1. Your physical server: It has an timezone setting that it will use by default for logging to the system logs
2. Your web server: It doesn't have a timezone setting, it uses the server's, and has specific log files.
3. PHP-FPM: It does have a timezone setting in `php.ini`, can have a specific log file or fall back to your web server ones.
4. PHP Script: This is where it becomes hairy. A PHP script can override the timezone settings (per user, in Friendica) and log location settings
5. PHP Software logs: these are independent from everything else and can be whatever we want. This is the Friendica Logger mechanism outputting the debug log with the different log levels.

Knowing this, here's which system the following errors will be handled by:
1. Page/File Not Found/Server Error (wrong rewrite for example): by the web server (physical server timezone, web server log file)
2. Critical PHP startup error (rare)/504 Gateway timeout (nginx): By the web server (physical server timezone, web server log file)
3. PHP Parse Error: By PHP-FPM (PHP global timezone, PHP global log location if set)
4. PHP Fatal/Warning/Notice: By the PHP script (potentially Friendica-server or user-defined timezone, PHP global log file)
5. Friendica Debug message (Error/Notice/Info/Debug): By the PHP script (custom logger timezone, custom logger log file)

#6837 only fixed 5. or all Friendica Debug messages, because we were able to override any timezone that might have been set at this point. 4. is tricky because we use the timezone to display locally relevant date and times (like the post dates), so we have to set the timezone at some point during script execution, and it has to be the user's defined one, which itself replaces the node's defined timezone. Any PHP message before we set the node's timezone will have PHP default timezone, any PHP message before we set the user's timezone will have the node's timezone, and any PHP message after that will have the user's timezone.

However, we may be able to write a PHP error callback that temporarily sets a given timezone just for writing the message and then restores the previous custom timezone, whether it was the node's or the user's or PHP global setting.

I'm not sure we can even catch 3. because it seems to happen before any script actual execution. 2. and 1. are entirely out of reach.

**Comment by redmatrix** [comment]
Dropping this link here for the benefit of future travellers since this comes up quite often...

https://codeberg.org/zot/zap/raw/branch/dev/util/phplogtime
