### ISSUE TITLE
Frio: The ACL window should have a minimal height

### ISSUE THREAD

**Issue by annando** [friendica/friendica#6903]
The ACL window on small displays is too narrow to work with:
![Bildschirmfoto 2019-03-18 um 00 18 39](https://user-images.githubusercontent.com/844208/54499562-8cfb5a80-4913-11e9-8925-abab9a18eca5.png)

Either it should have some minimum height or the connector part should be collapsible.

**Comment by MrPetovan** [comment]
This is an extreme case where there are many connectors and a ridiculously low window height. I'd rather this issue not to delay the release, can we move this to the next?

**Comment by annando** [comment]
This is a real problem for me. Of course I'm not on stable, but I guess that there are others out there who are working on "stable". Question is, if this is an easy solvable problem or not.

**Comment by MrPetovan** [comment]
Of course it is a problem for you, but in the grand scheme of things, it is a corner case because of the combination of specific factors, not something that most people would experience. So it should be fixed, but so close to the release I think it can be pushed to the next one because of the low people impacted/work required ratio.

**Comment by annando** [comment]
You know that I will give the angry mob your address when they are coming with forks and sticks? :grin:

**Comment by MrPetovan** [comment]
I just took a quick stab at it, it definitely is a bigger fix than I thought.

**Comment by annando** [comment]
If it is a longer task then I suggest both a minimum height of the inner ACL frame and some accordion effect (like in the settings) for the connector settings.

**Comment by MrPetovan** [comment]
Yes, I tried to add an accordion to the connectors but the HTML is generated in the different connector addons, so this needs to be refactored first.

**Comment by annando** [comment]
BTW: Some time in the future I want to have a look a the buffer addon, so that I can manually select and deselect the different networks at posting time. So it is important that the free format HTML is kept there.

**Comment by MrPetovan** [comment]
Don't we just need a list of checkbox data arrays?

**Comment by annando** [comment]
The buffer addon would need a multiple list of checkboxes for these future changes.

**Comment by MrPetovan** [comment]
As long as it's only checkboxes, it's okay

**Comment by annando** [comment]
What about allowing checkboxes and dropdown lists?

**Comment by MrPetovan** [comment]
I guess so, thanks for the hint.

**Comment by hoergen** [comment]
Additionally the checkboxes could be arranged in 2 columns
![00_temp](https://user-images.githubusercontent.com/24474762/54883658-41dbcd00-4e68-11e9-9106-14817768c3a4.png)

Or additionally rearrange the whole window like this
![00_temp](https://user-images.githubusercontent.com/24474762/54883753-62585700-4e69-11e9-8f6a-1ef62b4b1560.png)

And make the whole window scrollable, instead of making the scetions scrollable.

**Comment by MrPetovan** [comment]
The checkbox labels may not always be short enough for staying in half the window, so I'm reluctant to add a two-column layout.

**Comment by hoergen** [comment]
I was wondering anyway the there are sentences like "post to Twitter/Wordpress/tumblr ..." The name of the service should be enough. But I already saw you did that colapsing thingy. To be honest, im really no fan of those fidelly thingies. But there are several developements ongoing that makes frio more and more unusable, so I'm anyway thinking of switching my standard theme.

**Comment by MrPetovan** [comment]
What makes frio unusable?

**Comment by hoergen** [comment]
- E.g the new fancy url embed javascript foo https://github.com/friendica/friendica/issues/6721 
- In general that frio uses too much visible space, margins, paddings for nothing. https://github.com/friendica/friendica/issues/4998
-  The name handle besides the avatars are only visible when you hover over the avatar. https://github.com/friendica/friendica/issues/5837
- Readability (the reason why i had to create my own stylesheet)  https://github.com/friendica/friendica/issues/4606
- The continuity (design guideline) is a problem e.g. the textbox for a post is diffrent than a textbox of a comment when you look at the markdown buttons. Why?
![00_temp](https://user-images.githubusercontent.com/24474762/55010062-791ebb00-4fdb-11e9-8d1a-fce48e27e805.jpg)

Get me right, I appreciate, that somebody is working on such a fancy theme, because it attracts people, but as heavy user, it is too much candy.
I sadly don't have the knowledge to develop my own one, that continously follows  ONE desing guideline. Not many or  some.

I was okay with frio but in my opinion it is going now the wrong way. That's why im thinking to switch the theme.

**Comment by MrPetovan** [comment]
Thanks for the elaboration, I actually agree with you on most of your concerns (I'm actually turning around on #5837) so they actually might be addressed in the future.
