### ISSUE TITLE
Improve redis configuration

### ISSUE THREAD

**Issue by nupplaphil** [friendica/friendica#6929]
### Expected behavior

Described at https://freegamedev.net/display/fd12ab70-135c-9788-e593-b06263962776 , it is possible to use
- different databases for redis
- use authentication for redis

See https://www.mikeperham.com/2015/09/24/storing-data-with-redis/ for further information.

### Actual behavior

Both configuration settings are not supported.

### Steps to reproduce the problem

Use redis.

### Friendica version you encountered the problem

2019.06-dev

### Friendica source (git, zip)

git

**Comment by poVoq** [comment]
The existing Redis configuration options are also not mentioned in the default config file I think.

Thanks a lot for looking into this!

**Comment by poVoq** [comment]
https://redis.io/topics/security

and maybe https://stackoverflow.com/questions/16221563/whats-the-point-of-multiple-redis-databases
(note that since Redis is single threaded it might not make sense to use multiple databases, however there is also the redis compatible, but multithreaded fork called KeyDB with apparently is quite a bit faster than default Redis: https://github.com/JohnSully/KeyDB ).

**Comment by nupplaphil** [comment]
Should be solved with merge of #7019
