### ISSUE TITLE
uimport doesn't support `"pwdreset_time":null`

### ISSUE THREAD

**Issue by lapo-luchini** [friendica/friendica#6950]
### Expected behavior
`uimport` simply working.

### Actual behavior
`uimport` failing.

### Steps to reproduce the problem
1. export from Nerdica (I don't know what version they are using)
2. notice that the JSON file contains `"pwdreset_time":null`
3. fresh install
4. try `uimport`, it fails (with a red popup)
5. check the server side, logs, find:
    `uimport:insert user : ERROR : Incorrect datetime value: '' for
column 'pwdreset_time' at row 1 []`
6. substitute `"pwdreset_time":null` → `"pwdreset_time":"0001-01-01 00:00:00"`
7. retry `uimport`: it works!

### Friendica version you encountered the problem
854cc3e47296d4a1b01b893376064cf254d84f79

### Friendica source (git, zip)
git

### PHP version
7.3.3

### SQL version
MySQL 5.7.24

**Comment by MrPetovan** [comment]
Thanks for the report!

**Comment by tobiasd** [comment]
If I see this correctly we either should set the "null" datetime fields in the output to DBA::NULL_DATETO;E; during the export e.g.

    if ($k == 'pwdreset_time' && $v == null) {
        $v = DBA::NULL_DATETIME;
    }

but in a more optimized way to catch all datetime fields that have a null entry instead of catching all in an if clause by field name. Or set the null datetime during the import to the DBA::NULL_DATETIME constant

    if ($account['user']['pwdreset_time'] == null) {
        $account['user']['pwdreset_time'] = DBA::NULL_DATETIME;
    }

for the pwdreset_time. As far as I can see there are several fields exported to "null" and not all of them are datetime entries so I think it would be better to catch them during the output.

**Comment by MrPetovan** [comment]
Thanks for the technical explainer, and both solutions have to be added because of backward compatibility reasons. For example if an older version export is imported in a newer version.

**Comment by tobiasd** [comment]
> Thanks for the technical explainer, and both solutions have to be
> added because of backward compatibility reasons. For example if an
> older version export is imported in a newer version.

Thought so as well.

Do you have an idea how to identify the datetime fields automatically? so if there are new datetime fields they are considered automatically. Could we use the DB structure file for the detection?

**Comment by MrPetovan** [comment]
That's a good idea, all the datetime fields in the field definition have the `datetime` type, conveniently.

**Comment by nupplaphil** [comment]
Fixed by #7193
