### ISSUE TITLE
GUI leftovers from changes to basepath and hostname

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#6983]
### Expected behavior
The settings of basepath and hostname were moved to the config files. They're only set there and not in the admin panel anymore. There should be no useless leftovers in the GUI of the admin panel.

### Actual behavior
There are two empty input fields w/o headlines in the admin panel. I think these are leftovers from the above mentioned changes.

### Steps to reproduce the problem
When you're on develop - look at your admin panel. :-)

Hostname:
![Bildschirmfoto von 2019-04-07 13-47-55](https://user-images.githubusercontent.com/3656054/55683597-cbe46500-5941-11e9-9472-3c53bb1d691e.png)

Basepath:
![Bildschirmfoto von 2019-04-07 13-50-33](https://user-images.githubusercontent.com/3656054/55683600-d3a40980-5941-11e9-9b53-d568618cbf24.png)

### Friendica version you encountered the problem
2019.06-dev

### Friendica source (git, zip)
git

### PHP version
7.2.15

### SQL version
10.1.38 MariaDB

**Comment by nupplaphil** [comment]
I'm working on it, I'm thinking about reverting some parts of my changes, so the admin can change the values through the admin panel again. Sorry for the current WIP

**Comment by MrPetovan** [comment]
I also removed it from my admin module reworking, so you don't need to do it @nupplaphil.

**Comment by nupplaphil** [comment]
What parts are you removing again? To be honest I'm thinking about removing the whole `ConfigFileSaver` and create a own part in the admin site `Basic Config (Be careful!)` where the following settings are possible:
- basepath
- urlpath
- baseurl
- ssl_policy

Because these 4 settings are the base for each node, which shouldn't get changed without **real** care.

If they aren't set in the config or db, the auto determination will set it automatically **once** (inside the config table in the db).

**Comment by MrPetovan** [comment]
I just removed the orphan input field.

**Comment by MrPetovan** [comment]
Fixed by #6920
