### ISSUE TITLE
Forums missing from network widget

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#7057]
Some forums are not listed in the panel widget in the network tab in current development code.

The forums are still in the contact list and one can interact with them, but they are not listed.

Rememder about the discussion in the support forum
https://forum.friendi.ca/display/2196d4ee-345c-bebc-b341-49d969635556

**Comment by rebeka-catalina** [comment]
Thanks for opening the issue! :-)
I'm not sure if it's relevant for this but I refetched the contact data as mentioned in the posting you linked above and the result was that my forum shows up again in the widget, but now I also see a posting, which I couldn't see since a few days. I know that the posting existed, because I viewed the forum with the forum identity this morning and there was that one what I couldn't see as non-forum user, but after crepair the missed posting appeared.

**Comment by MrPetovan** [comment]
The conditions to have forum contacts appear in the widgets are:
- Protocol is DFRN (no AP?)
- Not blocked, ignored, pending, hidden nor archived
- The last successful update has to be more recent than the last failed update. I've had issues with this kind of condition recently where some of my long-standing contacts weren't available in the auto-complete because of this even though I was still receiving posts from them. It seems to have only been temporary as I haven't experienced the same issue again.

So the issue seem to have been with the contact probe/update for a while rather than the forum widget itself or the auto-complete.

Closing for now but feel free to reopen it if it happens again.

**Comment by MrPetovan** [comment]
Probably related to #7408
