### ISSUE TITLE
API - Manage contact

### ISSUE THREAD

**Issue by valvin1** [friendica/friendica#7080]
### Actual behavior

API which allowes to add / remove contacts are not yet implemented. So third party applications cannot manage contacts directly. For example, you can't add a contact when your are using Fedilab, Twidere, Dica. It is also not possible to make easier importing contacts from another social network (#2524)

### Friendica version you encountered the problem

2019.03

**Comment by annando** [comment]
This won't work with connecting legacy DFRN contacts because of the way the connection process is working - but it should work with the new one.

When PR #7095 is merged, I can separate the non DFRN connection process code from the legacy DFRN stuff. When this is done, we can create a new class or function out of this that then can be called either via frontend or API.

**Comment by nupplaphil** [comment]
;-) Don't worry, I skipped it already because I thought "don't touch stuff you cannot care well enough" ;-)

**Comment by annando** [comment]
This shouldn't be an issue anymore.
