### ISSUE TITLE
RSS feed posts imported repeatedly

### ISSUE THREAD

**Issue by ben-utzer** [friendica/friendica#7142]
### Expected behavior
Post created from RSS feed should be created once per specific post. 
### Actual behavior
Posts created from RSS feed are created again after some time, presumably after the last post was deleted by auto cleanup settings or so. 
### Steps to reproduce the problem
Follow a RSS feed in Friendica and set the resulting contacts post to be shared as your own posts. 
### Friendica version you encountered the problem
2019.04, but the problem is know for 1-2 years. 

### Friendica source (git, zip)
git
### PHP version
 7.3.5
### SQL version
not sure.

**Comment by MrPetovan** [comment]
Are your own posts deleted after some time? If yes, we can't possibly know which RSS feed items we already imported since we don't keep deleted items in DB. This is a rather corner case where a RSS feed would have to not change for longer than a set personal post expiration period.

The only way to fix that would be to record in a separate table for each subscriber of each feed if any individual item has already been imported. And I'm not comfortable setting up this system for such a corner case about an optional setting.

What do you think @annando ?

**Comment by annando** [comment]
We shouldn't import stuff that is older than some defined time. I guess we already do have this feature, but obviously there is an issue with it.

**Comment by MrPetovan** [comment]
So if you add a new RSS feed with items older than the expiration post delay, they wouldn't be imported at all?

**Comment by annando** [comment]
Shouldn't.

**Comment by ben-utzer** [comment]
Also it should not import old posts, posts older than the last imported posts. Which happens in my case. The post expiry is set to a longer period than the reimports (I think), so I am not sure why it happend.

**Comment by MrPetovan** [comment]
This is potentially fixed by #7261, can you please pull the latest RC and report on the eventual import of old posts?

**Comment by annando** [comment]
Since @ben-utzer is on the stable branch, I would suggest to close this issue, but we can reopen it when it happens again.
