### ISSUE TITLE
Stop URL parsing at whitespace

### ISSUE THREAD

**Issue by annando** [friendica/friendica#7150]
### Expected behavior
URL parsing should stop at a protected space: ```&#xA0;```

### Actual behavior
It doesn't.

### Friendica version you encountered the problem
Current Develop

See this post:
https://pod.geraspora.de/posts/22f5ad005af30137dad7268acd52edbf

In Friendica it looks this way:
https://pirati.ca/display/22f5ad005af30137dad7268acd52edbf

In XML it looks that way:

```
<status_message>
  <author>taz@pod.geraspora.de</author>
  <guid>22f5ad005af30137dad7268acd52edbf</guid>
  <created_at>2019-05-17T17:00:02Z</created_at>
  <public>true</public>
  <text>### Kein bisschen Restvernunft&#xD;
Weil er Schwule zur H&#xF6;lle w&#xFC;nscht, verliert der Rugby-Star Israel Folau seine Vertrag. Eine Karriere als Laienprediger d&#xFC;rfte ihm aber sicher sein.  http://www.taz.de/Kolumne-Pressschlag/!5596219/&#xA0;&#x2026; #taz #tazgezwitscher #tageszeitung</text>
</status_message>
```

Interpreted it looks that way:
```
Weil er Schwule zur Hölle wünscht, verliert der Rugby-Star Israel Folau seine Vertrag. Eine Karriere als Laienprediger dürfte ihm aber sicher sein.  http://www.taz.de/Kolumne-Pressschlag/!5596219/ … #taz #tazgezwitscher #tageszeitung
```

**Comment by MrPetovan** [comment]
Reopened by #7166

**Comment by annando** [comment]
Seems to work now: https://pirati.ca/display/542034905e390137dad7268acd52edbf

**Comment by MrPetovan** [comment]
Of course it does!

Thanks for the confirmation, though.

**Comment by annando** [comment]
I only really trust real live tests. Everything else is just simulation :-)

**Comment by MrPetovan** [comment]
I'm starting to assume that it's because the only software you've ever worked on have been monolithic applications with no way to separately test parts of them. It's okay, but there's a better software engineering world out there where you can separately trust parts even before getting to integration (real-world) tests.

**Comment by annando** [comment]
I see it more like a rocket launch. You did all tests before the first launch, you tested every component - but still the combination of different events can create a problem that you never thought of in your tests or you couldn't test at all.

**Comment by MrPetovan** [comment]
In this case I precisely identified the issue, and I fixed it at the appropriate level. When I added my changes, I knew that it would fix this specific issue. I wasn't sure if it wouldn't trigger a separate issue with another corner case that we wouldn't have had problem so far until now, but I knew that this specific issue would be resolved.

That's why I make a point a point of following @nupplaphil 's comments like this one: https://github.com/friendica/friendica/pull/7167#issuecomment-493775837

Because corner case by corner case, we're building a library of unit tests specific to the autolinking regular expression to the exception of everything else in the project. And I know that if it passes all these tests, then it doesn't matter which protocol uses autolinking in the real world, these scenarios will pass. Maybe we overlooked one more failing scenario that we don't know about yet like this present one was, but for all the previous cases we stamped, it's done, and it is ensured by this particular unit test no matter which "real world" tests we perform.

To go back to your rocket launch example, it's like we're testing a single bolt. If the bolt breaks under a specific load at a specific temperature, then we know it will always break under this specific load at this specific temperature, we don't need to launch a rocket in space to confirm it.
