### ISSUE TITLE
Notifier/counter for deliveries doesn't work for local posts (anymore)

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#7264]
### Expected behavior
When I post a private post to a user **on the same node** the notifier for delivery should show the success when the post has been delivered and arrived in the network stream of the recipient.

### Actual behavior
It never does. It shows a dark hour glass and the tooltip "delivery to remote servers is pending 0/1" for ever.

![Bildschirmfoto von 2019-06-13 19-49-52](https://user-images.githubusercontent.com/3656054/59456398-85febe00-8e16-11e9-8a7f-791a1909ae39.png)

I'm not sure. I think it worked in the past. There were some changes lately. Maybe #7213 ?

### Steps to reproduce the problem
Well, write a post to users on your own node only and observe.

### Friendica version you encountered the problem
2019.06-rc

### Friendica source (git, zip)
git

### PHP version
7.2.19

### SQL version
10.1.40 MariaDB

**Comment by MrPetovan** [comment]
This counter is only intended for remote deliveries whose time can be variable, unlike local deliveries that should be instantaneous (hopefully we don't send a delivery to ourselves). In this case, I think the right-hand number is wrong since there wasn't any remote delivery.

The real issue seems to be that we count local accounts in the remote delivery count.

**Comment by annando** [comment]
It's easier to also count the local deliveries, see PR #7265

**Comment by MrPetovan** [comment]
Looking at the code, it seems that the local deliveries still go through the worker, even though no actual message is sent? In that case, it does make sense to include them in the count.

**Comment by MrPetovan** [comment]
Fixed by #7265
