### ISSUE TITLE
Not receiving other replies than OP on public post

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#7367]
Local thread: https://friendica.mrpetovan.com/display/0b6b25a8-645d-277a-bbaf-bd1093736695
Remote thread: https://libranet.de/display/0b6b25a8-645d-277a-bbaf-bd1093736695

I'm only following Vladimir, but I should receive the replies he replied himself to.

Am I missing something?

**Comment by annando** [comment]
I just saw that all communication with him is done via AP - and the missing comments are Diaspora posts. I'm not sure if this is important.

**Comment by MrPetovan** [comment]
It probably is, it would be a convincing explanation and also something for you to fix.

**Comment by annando** [comment]
I hope I can reproduce this behaviour. Although I'm away this weekend and have got an open task I want to finish today.

**Comment by annando** [comment]
The fix had been easy, once I realized the problem: From this version on we now do deliver via AP whenever possible. When this is the case we skip delivering via DFRN. But of course we cannot relay posts from accounts that don't support AP, since the keys will be checked when received. So in this case we have to deliver the stuff via DFRN.
