### ISSUE TITLE
Hiding one's profile makes public posts unreachable

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#7638]
This public post isn't reachable on my node when not logged in: https://friendica.mrpetovan.com/display/2196d4ee-325d-80db-f488-7fa376044368
Same issue on the originating node: https://horche.demkontinuum.de/display/2196d4ee-325d-80db-f488-7fa376044368

However, this isn't the case for all public posts, see https://friendica.mrpetovan.com/display/47cb7c429b02981d754b2a4f22765fea12fc66ae

**Comment by MrPetovan** [comment]
The relevant profile has been set to "hidden", which protects even "public" posts from being viewed by anonymous users, even on remote nodes.

**Comment by MrPetovan** [comment]
This behavior for public posts isn't intended.

**Comment by annando** [comment]
This is the origin of this behaviour: https://github.com/friendica/friendica/blob/develop/mod/item.php#L287-L289

I would like to remove these lines.

**Comment by hoergen** [comment]
What do you think?

@nupplaphil @tobiasd @rebeka-catalina @copiis @vinzv @AlfredSK  @ben-utzer

**Comment by vinzv** [comment]
If I set my profile to hidden, I just don't want it to be discovered. But I want the posts to be seen by people who know my profile. At least that's how I understand this feature, which would give removing the lives a +1.

**Comment by annando** [comment]
The intention had been that posts from persons with this setting don't want their posts to be displayed on the community pages. But I think that we just can make some small change to this.

**Comment by MrPetovan** [comment]
One `if` less, thousands more to go.

**Comment by rebeka-catalina** [comment]
> What do you think?
> 
> @nupplaphil @tobiasd @rebeka-catalina @copiis @vinzv @AlfredSK  @ben-utzer  

I think it's unlogical to think, that people, who hide their profiles,
don't want to be able to make publicly viewable posts. I have said
this already years ago, or whenever this was discussed the first time.

I think that's two totally different things. I as person who nearly
never shares publicly and who has set the setting to hide the profile,
want of course also to have the ability to, so post publicly in a way,
that my posts can be viewed by others.

1)
If I don't have the possibility to post publicly if I want to, just
because I didn't really used to and because I hide my profile, then I
feel restricted.

2)
This would also mean, that in case of having the 'hide' feature
activated, the post restriction setting 'public' would not keep what
it's promising.

3)
It's a top down decision, that I get less possibilities for setting my
profile to hidden and that's totally not ok. I a person with such a
hidden profile wants to post publicly, they have reasons for it.

**Comment by AlfredSK** [comment]
Hiding the profile as option is important. But partly hiding public content makes no sense. It's security by obscurity because there are other ways to get the content. Public means public.

Personally, I don't care that much. I'm all public. :-)

**Comment by copiis** [comment]
Maybe an additional option should be possible if I plan to hide my profile which reads "Hide all public posts as well Yes/No".

**Comment by MrPetovan** [comment]
@hoergen Can you please pull the latest RC and publish a public post? It should expectedly show for anonymous users now.

**Comment by hoergen** [comment]
I set my profile to hidden and worte a public posts. It works good! 👍🚀
https://horche.demkontinuum.de/display/2196d4ee-295d-827f-aec3-684745202953

**Comment by MrPetovan** [comment]
Closed by #7640
