### ISSUE TITLE
libpng warnings in cron job

### ISSUE THREAD

**Issue by Rudloff** [friendica/friendica#7732]
### Expected behavior
The cron job does not return any error.

### Actual behavior
I get frequent libpng warnings:
```
libpng warning: iCCP: known incorrect sRGB profile
```
```
libpng warning: Interlace handling should be turned on when using png_read_image
```

### Steps to reproduce the problem
It started happening after I upgraded to 2019.09.

I am running the cron job like this:
```cron
*/10 * * * *    cd /var/www/friendica/; /usr/bin/php bin/worker.php
```

### Friendica version you encountered the problem
2019.09

### Friendica source (git, zip)
Git

### PHP version
7.0.33-0+deb9u5

### SQL version
10.1.38-MariaDB

**Comment by MrPetovan** [comment]
It is a known bug we have no idea how to track. This message is displayed by the underlying libpng used by GD or ImageMagik, and as such doesn't provide any sort of context. We handle a large number of remote images through Friendica, and some of them are corrupted which explains the first message, but I have no idea about the second message.

Since it's triggered by the underlying library, we can't catch these messages in PHP either.

**Comment by Rudloff** [comment]
Thanks for the explanation.

I found this PHP issue about it: https://bugs.php.net/bug.php?id=71316

**Comment by Rudloff** [comment]
I'm getting more and more of these warning, so I added `|grep -v 'libpng warning'` to my crontab.
Maybe this could be documented somewhere?

**Comment by MrPetovan** [comment]
Good idea, not sure we have a permanent "known caveats" documentation page.

**Comment by Casuallynoted** [comment]
Getting a lot of these as well in the docker image
