### ISSUE TITLE
Suggestions, make friendica essentially hootsuite+facebook and it will increase users dramatically

### ISSUE THREAD

**Issue by anubis2814** [friendica/friendica#7790]
This may well be the worst place to post this, but I don't know where to direct this.

Playing with Weme.com and Friendica as alternatives to facebook, the biggest thing they could do is allow you to share onto facebook or even other social media sites as well. As it is right now, you feel trapped and stifled and you have to go onto two different platforms to post. One where all your friends are and one where no one is. If you had the option to share something and then also post it onto other platforms like hootsuite+facebook, people would be much more likely to switch platforms. Until that happens only the people most pissed off will join then leave out of boredom and then come back half a year later when Zuck does something else terrible.

Other needs to compete with facebook 
Groups and pages(i have a feeling you guys are working on this)
Friend recommendations
Checkins(like foursquare)

Small things facebook has that would enrich things in your profile
Quotes
Political leanings
Family and Relationships
Life events

I saw another post of allowing people to download their all their data from facebook and upload it all of it to friendica though thats going to take some doing and is probably low priority at this point.

If you have another place I can post this on, please let me know, I don't want to clog up a site that is much more specific to actual problems.

**Comment by MrPetovan** [comment]
Hi @anubis2814, this is a fine place to post such thoughts. However, we won't be able to make Friendica into Hootsuite. It once was possible for any Friendica site owner to register an app to use the Facebook API, but this possibility has been closed off by Facebook about two years ago.

It still is possible to post to Twitter from Friendica though. And with the widest protocol compatibility, Friendica users have native access to users from Diaspora, Mastodon, Pleroma, GNU Social and more.

Let's go over the other recommendations:
- Groups and pages: We have forums and delegated accounts respectively.
- Friend recommendations: We do have them, although at the moment it only bases itself on the account tags that are voluntarily submitted by users and we can't suggest non-Friendica users.
- Checkins: Due to privacy concerns, I don't think this is an avenue we would like to pursue.
- Import data from Facebook: This is a good idea, I lost access to Facebook before they created the possibility to export your own data, so we would need someone else's profile data to work on this feature.
- Rich profile fields: We currently are in the process of reworking the profile feature, and the goal is to allow any arbitrary profile field. Facebook uses these fields for user profiling to sell targeted ads, but we have nothing to sell so we don't need specific fields.

**Comment by anubis2814** [comment]
Thanks so much for the quick response.  Oddly Using the friendiqa app I can post things from facebook to Friendica on my phone.  i look forward to seeing what you guys do in the future, also kicking around learning php to see if i can't help out with this in the future.

**Comment by mkljczkwwrzk** [comment]
It’s the best time to work on getting more users to join Friendica because of the fact that Minds.com is going to join the Fediverse soon, and then they would become the largest/more active node. And people would keep joining Minds (it’s open source, but requires lots of resources to run + they don’t recommend running it) if they wanted a facebook-like experience.
But I don’t think features are the problem. I believe UI/UX/onboarding is Friendica biggest problem. These aspects are the reasons for Mastodon success, I think…

**Comment by MrPetovan** [comment]
I don't belive Minds.com will exceed Mastodon.social in terms of activity/number of users. However you are right about the onboarding issues. Mastodon simple and straightforward process with inviting pages and seamless interface makes it appealing for people used to commercial products.

**Comment by AlfredSK** [comment]
The last time I created a test account on Diaspora I was pretty impressed about the well done support for new users.

There are info-bubbles all over the interface pointing the user to the most important places/functions of the UI. Also the new user is already having content in their network stream because there are some pre-configured contacts and tags the new user is following right after first login (e.g. the local admin, the local support account and some more accounts plus newhere-tag, ... and so on). The network/server looks alive from the very first moment. Also, the post editor is open and pre-filled with an intro post. The user just needs to press on 'send' to create a public intro post. Pretty cool.

In comparison the first impression on Friendica is something like 'is this thing dead or alive?' The users are pretty much left alone and they have to find out everything by themselves by exploring the interface.

**Comment by AndyHee** [comment]
> There are info-bubbles all over the interface pointing the user to the most important places/functions of the UI. Also the new user is already having content in their network stream because there are some pre-configured contacts and tags the new user is following right after first login (e.g. the local admin, the local support account and some more accounts plus newhere-tag, ... and so on). 

Wow!

> Also, the post editor is open and pre-filled with an intro post. The user just needs to press on 'send' to create a public intro post. 

Wow, again!

**Comment by anubis2814** [comment]
Closing this one.  I was unfamiliar with the purposely limited APIs of other companies at the time.
