### ISSUE TITLE
New custom profile field feature

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#7817]
Offshoot of #7777
Closes #8153

This feature is intended to replace the multiple profile feature to make it easier to use and overall less confusing. instead of multiple full profiles that can be assigned to contacts, users can create custom profile fields beyond the basic public ones that can each be visible to contacts, groups or hidden from specific contacts and groups.

A migration script will convert the existing multiple profiles into custom profile fields with the adequate permission set according to their current visibility.

Task list:
- [x] Display of the basic public profile fields.
- [x] Conditional display of the custom profile fields
- [x] Migration script from multiple profiles to custom profile fields
- [x] "View profile as" feature
- [x] Cross-theme ACL selector (related to #7308)
- [x] Fix birthdate input, storage and display
- [x] Profile field management screen:
    - [x] creation
    - [x] update
    - [x] deletion
    - [x] reordering
- [x] Document feature
- [x] Remove `mod/profperm`
- [x] Deprecate `contact.profile-id`
- [x] Remove `ContactSelector::profileAssign`
- [x] Update User account export
- [x] Update user account import
- [x] Update API

**Comment by MrPetovan** [comment]
For the "View profile as" feature, I have to select all the user's contacts that actually can view the custom profile fields, and this would be the magic-auth enabled remote contacts or the local node users.

I know I can't select contacts on the `network` field alone because new Friendica contacts are made using `apub`. How do I pick the relevant contacts?

**Comment by annando** [comment]
All Friendica **should* have "dfrn" in their network in any case, but "apub" in the field "protocol" (which is empty in all other cases)

Due to some bug in the probing there possibly still are Friendica contacts marked as "apub".

But couldn't you simply use the same ACL settings like they had been chosen for the current profile mechanism? Mapping it to single contacts would cause several problems afterwards.

**Comment by MrPetovan** [comment]
The current multiple profile permission contact filter is just `network = 'apub'`.

**Comment by annando** [comment]
Ah, I just had a look at it, now I understand what you mean. But you should have all contact ids for the non public contacts, haven't you? And for the ACL stuff of the new fields I would suggest filtering for "dfrn" as well - but to allow groups. This is crucial in my point of view, since otherwise you had to define the ACL for each field (which would be a PITA)

**Comment by MrPetovan** [comment]
> But you should have all contact ids for the non public contacts, haven't you?

I don't get it?

And ACLs are defined for each custom field, each have their own permission set, that may or may not be the same as other profile fields. Default is public.

**Comment by annando** [comment]
When you currently create non public profiles, you do select the contacts that are allowed to see it. So this data has to be stored somewhere. This was all that I meant.

Concerning the ACL per field: This isn't practical, having the need to select each and every single contact for every field again. Just imagine doing this for 10 fields, because you want to create some fields for some different people. I guess the best way would be to create new groups based upon the currently allowed contacts per profile and then assigning all the fields to these groups.

**Comment by MrPetovan** [comment]
> When you currently create non public profiles, you do select the contacts that are allowed to see it. So this data has to be stored somewhere. This was all that I meant.

Yes, this is taken care of during the migration from multiple profiles to custom profile fields. the `contact.profile_id` field is converted to a permission set that is assigned to the custom field.

> Just imagine doing this for 10 fields, because you want to create some fields for some different people.

I can imagine it very well, since it's going to use the regular ACL selector with auto-complete for contacts and groups. It isn't supposed to be a feature where we save clicks by doing implicit stuff anyway because it's about privacy and everything has to be clear and explicit.

**Comment by MrPetovan** [comment]
The `View Profile As:` feature is complete, the next big task is the profile settings page and in particular the cross-theme ACL selector.

**Comment by annando** [comment]
I guess we agree that this issue is something for the milestone after the current one?

**Comment by MrPetovan** [comment]
Yes, I already moved the corresponding PR to the next milestone but I didn't change this.

**Comment by MrPetovan** [comment]
UPDATE!

I know have a functioning profile update page on both vier and frio. It currently is missing adding/removing custom profile fields and the reordering.

I also improved the base mode update to just the fields that have been changed. This saves a ton of database writes when saving identical profile fields.

**Comment by MrPetovan** [comment]
UPDATE!

It is now possible to add and remove custom profile fields, but not to reorder them just yet. Additionally, I feel like we need some documentation about this exciting new feature.

**Comment by MrPetovan** [comment]
UPDATE!

The quagmire that was the birthdate entry, storage and display has been cleaned up and is now usable.

**Comment by MrPetovan** [comment]
Nothing to do. The storage is still `0000-mm-dd` for birthdates without a year. I probably should have removed "storage" from my quote above.

**Comment by MrPetovan** [comment]
Grrr, I realized I wasn't nearly as done as I thought. The API is still using the multi-profile structure and I've left a trail of crumbs to clean up about them as well.
