### ISSUE TITLE
Can we get varied levels of posts from people like facebook used to have?

### ISSUE THREAD

**Issue by anubis2814** [friendica/friendica#7830]
Hey,
I was wondering if in the future we could have the option along with the ability to follow it would give an option of "see less" from people you follow, at either random or by most likes posts or a mix of the two?  I remember there being 3 settings back in the day of "see all" and "see less but there was a third option.  Right now I don't have enough friends to make that a need but in the future this could be a useful tool I miss from facebook.  It really helped streamline my feed and see more of certain people than others.

**Comment by MrPetovan** [comment]
This is a tricky option, because no matter what filter we end up choosing, some people won't like it and it will become confusing. As a reminder, any post in your timeline can be removed, possibly unlike in Facebook.

Additionally, if you want to stay in contact with someone but not receiving their post in your timeline, you can mute them and check theirs posts manually on their profile page.

I'm not favorable to this arbitrary filter.

**Comment by nupplaphil** [comment]
I thought about the same topic too ..

Currently, it's strange but I'm missing some of the auto-filtering options of Facebook to avoid this mass of new posts. But as @MrPetovan said, this is a feature which a lot of people will annoy. I think this sounds mostly like an addon.

And inside the addon, we can have a look more deep. Is it really "just" plain see less/see more based on likes ... What about some heuristics and learning algorithm ;-))) ... But again ... Just in case the server addon is enabled and the user actively "opt-in". Someday, this could be a feature which will attract new users to join the decentralized world.. Most of the "normal" users don't want to manually filter/check everything .. They don't want control every single bit they see .. They want a pretty simple UI / UX they like and a guidance through it ..

**Comment by anubis2814** [comment]
Having it as an option shouldn't annoy people so long as its an option.  I loved the facebook option, and we currently have an either or situation, mute or all.  I'd like an in the middle option I'm not against a learning algorithm but I don't know how many of those kinds of resources should be spent on this.

**Comment by AndyHee** [comment]
Perhaps a "snooze" option (don't show any posts from this person for 3 or 8 days) might be less controversial.

**Comment by hoergen** [comment]
We were discussing something similar for new users having random posts, because they don't have any messages in their timeline, when they start. Maybe this could solve one part of the request?

- "Preconfigured Contacts and Tags for New Users" https://github.com/friendica/friendica/issues/7795

The "snooze" option is something that was discussed on friendica several times and would be a feature that is as well very welcome. We talked about

1. daily scheduled snooze : snooze individual people at a specific time of the day e.g. if you don't like those "good morning" posts, or if people are "sapmming" in the morning or evening your timeline with RSS news
2.  time snooze : like @AndyHee already told - silence people for a period of time (hours, time, days)
3. date snooze : snooze someone until a date e.g. if there is a soccer tournament and you can expect from people lots of messages about that until the finals.

**Comment by bkil** [comment]
@hoergen To handle the soccer tournament use case, you should have an option for
* ignoring posts with certain tags or containing certain free form text (or within shared URL)
* ignoring all posts coming from a specified contact that lacks **any** tag (useful for those few odd users who never use tags or forget them often)

**Comment by bkil** [comment]
@nupplaphil The problem with favoring popular content is that it leads to the very same psychological addiction that we were desiring to get away from on Big Tech platforms who strive to maximize your screen time and their advertising revenue.

It creates an incentive for users to only post content and comments that they anticipate will be as favored as possible, also contributing towards a sort of self-censorship.

Certain Fediverse clients are working towards a more livable future by making steps in the opposite direction: hiding like counters or putting a cap on them (i.e., only showing `liked by at least 2 people`).
https://en.wikipedia.org/wiki/Slow_movement_(culture)

**Comment by anubis2814** [comment]
There is now an option for this.
