### ISSUE TITLE
Fail2ban can't catch failed log in attempts because the logger uses UTC as timezone

### ISSUE THREAD

**Issue by Fred-Zweig** [friendica/friendica#7994]
### Expected behavior
After enabling logging, the logger should use the server's time zone and not the default UTC time zone, so that applications that read the log, such as Fail2ban, can actually use it. 
### Actual behavior
The logger logs all events in UTC time, which in my situation means 2 hours earlier than real time. This prevents Fail2ban from doing its job.
### Steps to reproduce the problem
After enabling logging by clicking on profile picture > Admin > Log > under Administration - Logs checking Enabling debugging, entering a path for the log file in the 'Log file' box, selecting 'Warning' in the 'Log level' dropdown and clicking on 'Save settings', the log lines written by Friendica logger use the UTC time zone and not the server's time zone. This prevents Fail2ban from catching failed log in attempts. Since the time zone used by default by the logger can't be changed by any means, I have to use a huge findtime in Fail2ban for the Friendica jail, in order to get around this problem.
### Friendica version you encountered the problem
2019.09
### Friendica source (git, zip)
https://friendi.ca/wp-content/uploads/2019/09/friendica-full-2019.09.tar.gz
### PHP version
7.3
### SQL version
MariaDB 10.3.18

**Comment by AlfredSK** [comment]
Unfortunately, we need logging in UTC because sometimes we have to compare logs between different nodes to hunt down federation issues.
I'm using fail2ban successfully. I've simply set my servers local time to UTC.

**Comment by Fred-Zweig** [comment]
Thank you for your reply and for developing Frendica. I really appreciate Frendica and consider it the best FOSS social media platform in all the Fediverse. I also appreciate that you have chosen PHP, which is the best tool for the task, instead of a mediocre and rapidly declining language like Ruby.

As about logging in UTC, I understand that it can be simpler to solve federation issues by using UTC for logging on all nodes, but what if every administrator had the option to set a custom log timezone with a parameter in `config/local.config.php` like this:
```
'system' => [
              'log_timezone' => '+3',
```
I think this would be indeed professional and even required in a flexible application that Friendica is designed to be. And afterwards, would it be impossible to just take into consideration the time offset from the above parameter to automatically calculate the UTC for each log line and solve any federation issue ? That parameter would also allow every administrator to have normal log lines using the server's time zone, so that Fail2ban and other applications can properly analyze them and trigger various events. 

Please note that in my case, and I'm sure in many other cases, Friendica is not the only application running on the server. I host Friendica only for local use, for a limited number of users, so I can also host a mail server, a CMS, an ERP application as well as a VPN, Nextcloud, a security application that parses logs, etc. So, I need the real time of events in all logs for all these applications to run as they should; it's impossible to just change the server's time zone to UTC. I expect that all the applications be flexible enough to allow me to set the time zone manually, so that they can function in conjunction with Fail2ban and other security applications.

**Comment by annando** [comment]
UTC is a standard. Isn't it possible that failban uses UTC?

**Comment by AlfredSK** [comment]
@annando Unfortunately. that's not so easy. Fail2ban always uses the system time. Maybe you remember I reported the exact same issue some time ago. 

In the ancient days we had a timezone hint in our log - something like ISO date format with 'Z' at the end to mark the timezone used. E.g. `2019-12-23T21:28:55Z` Fail2ban can pickup that date format and timezone and calculate the bans correctly.

Since we switched to the new logger facility (don't ask me for the name) that timezone hint isn't part of the logged time stamps anymore. So, fail2ban thinks the logged time is equal to the system time.

I'm pretty sure you can force fail2ban to rewrite the time stamps via a regex (there is a possibility to run a regex in the filter.conf file before the actual filtering is done). But I never tried that.

The easiest way would be that we switch the date format to e.g. `2019-12-23T21:28:55Z`. We would still log in UTC but fail2ban could read the correct time.

Maybe @nupplaphil has an idea since he introduced the current logging stuff, if I remeber correctly.

**Comment by annando** [comment]
I saw this one: https://manpages.debian.org/testing/fail2ban/jail.conf.5.en.html
```
logtimezone
    Force the time zone for log lines that don't have one. 
```
But of course we should add some timezone hint. This is something that @nupplaphil should be able to fix.

**Comment by Fred-Zweig** [comment]
I just discovered that Fail2ban has indeed the parameter called `logtimezone` that can be set in each jail, in order to force Fail2ban to use a specific time zone for that specific log. So, in the jail for Friendica, in  `/etc/fail2ban/jail.local` I would have to enter:
```
[friendica]
enabled  = true
filter  = friendica
logtimezone = UTC
...
```
A different uglier solution is to set a findtime greater than the intended findtime with 2 hours.
I also found that the use of the `logtimezone` parameter may decrease the speed of parsing logs a bit. So, maybe in the future you'll find a way to let the admin set the time zone for the logger. Thank you.

**Comment by annando** [comment]
I prefer the way that @AlfredSK suggests.

**Comment by Fred-Zweig** [comment]
In principle, every application on a server should log all the events when they really take place. (All the applications that I run on my VPS do so, except Friendica). For example, if at 8:15 an attacker has a failed log in attempt to an application, the log of that application should record a failed log in attempt at 8:15 and not at 6:15.

I have a security application that extracts the failed log in attempts from logs, appends them to an email and automatically sends the email to the abuse address of the ISP of the offending IP. It works well with all the logs that I have because they all record the real time of events but it won't work accurately with the log of Friendica. In such an email, it will say that the last failed log in attempt of a certain IP took place at let's say 16:20 , when in fact it took place at 18:20, because it will take the time from the log lines and it will believe it's the real time. Now I have to apply a hack to my security application to make it treat all the logs normally but when it deals with the log of Friendica it should append UTC to the time mentioned in the email and not UTC +2 as usual.

My point is that such a simple thing as an unusual time zone for a log, can have consequences for other applications that analyze that log: Fail2ban seems to be able to deal with it, but my security application has to be modified.

**Comment by MrPetovan** [comment]
Let's take a step back. First of all, I appreciate the compliments you made to Friendica.

However, I feel like you are a little confused about what is the "real time". 16:20 and 18:20 can be both the real time of a single event, depending on the timezone. Especially for a machine, they represent the same time provided the machine can guess the timezone. The problem here isn't that we are using a specific timezone to display the time in the log, but that we don't display it so that fail2ban could accurately pick it up.

**Comment by AlfredSK** [comment]
> I have a security application that extracts the failed log in attempts from logs, appends them to an email and automatically sends the email to the abuse address of the ISP of the offending IP.

Only a personal plea (from own, unpleasant experience): Please don't do that. Those automatic abuse reports are a pain in the... I once had the case where someone had some failed requests from my server in his logs and the automatic abuse report system he was using sent an abuse report to my provider. I had to report (fill out two forms) to my provider why that happend and what I will do to prevent that in the future. The threatened sanction was that otherwise my IP would be temporarily suspended. In the end it turned out that there were 4 erroneous requests per day which triggered the automatic abuse report.

**Comment by MrPetovan** [comment]
The timestamp format has been updated with the timezone on the `develop` branch.

**Comment by Fred-Zweig** [comment]
I chose the wrong words in my previous messages. Indeed the UTC time is as real as the server's time for any event. By 'real time' I wanted to indicate the server's time, which is the time that feels real to me, the server's admin, and that is taken as such by Fail2ban and other applications that parse the logs. Anyway, I understand that logging in the time zone of the server may complicate other things, so probably it's better to just log everything in UTC on all Friendica nodes, and include the timezone in the log timestamps, so that Fail2ban can process them correctly, without the need to use the little known parameter `logtimezone` in Fail2ban config, and without increasing the `findtime` parameter, so as to include the time zone offset.

Alfred SK, thank you for sharing your experience with your ISP. I'll take your recommandation into account in the future.

This being said, I thank you all for your attention to this small problem, for taking care of Friendica and improving it day-by-day. I hope you'll have time to take a look at a list of suggestions that I'll post later on to a new thread. Thanks again and I wish you all a happy new year !

**Comment by MrPetovan** [comment]
You're welcome, if #8004 resolved the problem for you, feel free to close this issue.
