### ISSUE TITLE
Remote posts with angled brackets are aggressively sanitized

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#8067]
Original post: https://social.tchncs.de/@bekopharm/103437141426117199

Item body:
```
@hypolite <insert ea rant here>
```

Friendica post: https://friendica.mrpetovan.com/display/59e215f121589465e1d14b35fbb3c25f93266ca3

Resulting body:
```
@hypolite
```

**Comment by annando** [comment]
I just looked. The original content of the post looks fine:
```
<p><span class="h-card"><a href="https://friendica.mrpetovan.com/profile/hypolite" class="u-url mention">@<span>hypolite</span></a></span> &lt;insert ea rant here&gt;</p>
```

**Comment by MrPetovan** [comment]
Yep, remember I removed an implicit HTML encode recently to fix the code block angle bracket bug. My working theory is that it was necessary for something else the offending function had no knowledge about.

**Comment by annando** [comment]
Do you want to follow the line from reading the content and decoding it - or should I have a look at it?

**Comment by MrPetovan** [comment]
I will look into it tonight. I'm expecting the final HTML sanitizing (instantiating a DOMDocument from the post body and then saving it back to HTML) to run on an unencoded input, which would strip the de facto unknown tag.

**Comment by annando** [comment]
I must confess: I had a feeling it might come from a completely different side. So I just did some test posts and traced them. The problem had been these lines: https://github.com/friendica/friendica/blob/develop/src/Protocol/ActivityPub/Receiver.php#L910-L920

For some unknown reason the system fetched the content and thought it had been Markdown. So it send it through the Markdown interpreter - which then did its thing. So the best way to solve this problem is to remove these lines. This is the best, since we don't create our own posts that way anymore (remember the language post PR I did some days before).

But there is something else to investigate. See these lines here: https://github.com/friendica/friendica/blob/develop/src/Content/Text/HTML.php#L337-L339

While the first line is absolutely okay (we have to transform the entities into regular text), I'm asking myself what the second line is meant to be and why only this element is transformed. Funny enough during the later processing this doesn't seem to make a difference. But it is too late today for me to have a deeper look - and I don't want to take away the fun from you :grin:

**Comment by MrPetovan** [comment]
Fixed by #8073

See https://friendica.mrpetovan.com/display/52acf9cd645a8dc4a521850bdb5a1c82f2de3a60

**Comment by MrPetovan** [comment]
There still is an issue with `HTML::toPlaintext` that strips `<insert ea rant here>` but it's another problem

**Comment by annando** [comment]
There is another issue with the DFRN transmission of relayed posts, see here: https://pirati.ca/display/52acf9cd645a8dc4a521850bdb5a1c82f2de3a60

I guess the reason for only one side being transformed is this here: https://github.com/friendica/friendica/blob/develop/src/Content/Text/HTML.php#L339

And I guess that this function is responsible: https://github.com/friendica/friendica/blob/develop/src/Util/Strings.php#L57-L60

This function is called here: https://github.com/friendica/friendica/blob/develop/src/Protocol/DFRN.php#L2368

I cannot reproduce it here and I have to get up. So I currently don't have time testing if the solution is to remove the `escapeTags` function or to add the escaping of the other character.

However, I would prefer removing the other escaping (and not adding the other one). But currently it seems as if on internal communications via DFRN between Friendica we are double encoding the stuff. But when we communicate via AP we don't do so.

Means: When communicating from Friendica to Friendica using AP, the 'body' field in the database looks like this: `<rant blubb>` while with DFRN it looks like this: `&lt;rant test&gt;` (And your post looks like this: `&lt;insert ea rant here]`)

**Comment by MrPetovan** [comment]
The `Strings::escapeTags` call in `DFRN.php` seems superfluous. `BBCode::convert` already takes care of `<`, `>` and `&`.

**Comment by annando** [comment]
Somewhere in between we seem to create entities when transferring via DFRN. This we should also fix.

**Comment by MrPetovan** [comment]
Ugh.

**Comment by annando** [comment]
This sounds like a job that you would like to do :-) Or should I, since I do have accounts on several systems?

**Comment by MrPetovan** [comment]
Please do the tests, I'll be able to assist with specific questions about when and where the HTML encoding should happen.

**Comment by MrPetovan** [comment]
The thing I do want to fix is `BBCode::toPlaintext` eating `<insert ea rant here>` and displaying nothing.

**Comment by annando** [comment]
Okay, that's great. I just fixed the other stuff (I hope).
