### ISSUE TITLE
nodeinfo: show real user count

### ISSUE THREAD

**Issue by ingoj** [friendica/friendica#8202]
### Expected behavior
Nodeinfo should report the real user account as shown on /admin page

### Actual behavior
For nerdica.net /admin shows right now 1517 registered users. On the other hand the-federation.info reports 682 total users. 

Apparently users that have configured "Publish your default profile in your global/local site directory?" are not counted for nodeinfo user stats. Reporting the real number of total users are most likely not a privacy leakage for the pure number of total users. Only accounts such as forum accounts should be left out in reporting total users in nodeinfo. 

### Friendica version you encountered the problem
all

**Comment by AlfredSK** [comment]
Sigh. ;-) Yeah, that's an old issue. I share your point of view. It doesn't make sense to only count published profiles. It makes the stats somewhat useless. Also, as far as I know no other network does that - not even Hubzilla (who see themselves as _the_ privacy-first-network).

But I know that some people see it as a privacy issue - especially on small nodes with only a couple of users. I must confess I cannot follow that argument but I know that it exist.

**Comment by MrPetovan** [comment]
Can we get an updated argument about this from @tobiasd, @hoergen  or @annando ?

**Comment by tobiasd** [comment]
If an admin chose to take part in the statistics and publish their node information the count should be accurate. But if the admin does not wish to publish their node information, this information should not be published at all.

The description in the admin panel is talking about "public profiles" which I would interpret as those accounts that do not hide their details from anonymous visitors (and not the profiles not listed in the directories).

**Comment by ingoj** [comment]
How about making it a configuration option whether or not user stats are reported in nodeinfo? But when they are reported, they should be real. 

In the meantime I'm thinking about which argument could convince that presenting the real user count is a privacy issue for a specific user on that (smaller) node... 
An IP address is a personal datum, yes. A personal datum would also be a unique identifier that would be listed publically like a UID or that, but the pure number of total users?

**Comment by ingoj** [comment]
> If an admin chose to take part in the statistics and publish their node information the count should be accurate. But if the admin does not wish to publish their node information, this information should not be published at all.
> 
> The description in the admin panel is talking about "public profiles" which I would interpret as those accounts that do not hide their details from anonymous visitors (and not the profiles not listed in the directories).

Yeah, that's basically the issue here. You say yourself that if the numbers are published, they should be accurate, but they are currently not: 
`

users |  
-- | --
total | 679
activeHalfyear | 409
activeMonth | 230
`
Nodeinfo explicitly says "total" here, not "public". "Total" include all users, public and non-public. YMMV.

**Comment by annando** [comment]
I wouldn't have a problem with counting all user accounts.

**Comment by tobiasd** [comment]
> Yeah, that's basically the issue here. You say yourself that if the numbers are published, they should be accurate, but they are currently not:

Yes. But what I say is the _profiles not published in a directory_ and _profiles hidden from visitors_ are different things. The admin panel option clearly states that _public account numbers_ are included in the nodeinfo. For me this includes those that are not listed in the directory, but are not hidden. Those that are hidden should not be included for me.

For not hidden profiles, the numbers should be accurate.

**Comment by annando** [comment]
Hidden profiles don't hide their existence, they only hide a few personal details.

**Comment by tobiasd** [comment]
Then fix the description of the option in the admin panel...

**Comment by AlfredSK** [comment]
> If an admin chose to take part in the statistics and publish their node information the count should be accurate. 

Yes. I think so too.

But if the admin does not wish to publish their node information, this information should not be published at all.

Absolutely. Yes. The nodeinfo should have no information about the node and no numbers for the accounts then (apart from the technically necessary info).

> How about making it a configuration option whether or not user stats are reported in nodeinfo? 

The option "Publish server information" already exist. Maybe we can extend it with a second option.
1) Publish server information
2) Don't publish the number of users (when option 1 is enabled)

This would allow to publish everything (technical info and user stats), publish technical info only or publish nothing at all.
Also the description has to be adjusted. :-)

**Comment by hoergen** [comment]
I agree mostly with the points @tobiasd is talking about.And @annando brought in a very important differentiation ; existence 

1. public (a lot details visible)
2. hidden (only a few details visible, what is necessary  to communicate with other nodes)
3. not published (to directory) ... but public?

(4.) is `hidden` inherent with `not published (to directory) `?

Finally every user that wants to participate in a social network need to have some public visible information to be able to communicate with other servers. The main topics are

1. visible in a directory 
2. invisible posts (hidden) for visitors but minimal visible profile

So we come to the question: Who decides to report which information to a public statistic server ?

1. Admin decides to report the number of users on his node forced by development decision)
2. User decides to opt-in/opt-out report or not (forced by development decision)
3. Admin can configure to report data and if users are able to opt-out or opt-in. As far as I know in Germany you always have to configure Opt-In .

I would prefer the 3rd point, even there is a security problem for very paranoid admins/users. If you know that a server has e.g. 50 users and an attacker is scraping data and user info from that node. The attacker knows when he got all profiles. In my point of view this is a very weak security by obscurity topic. Because as soon a user joins a public discussion the attacker can do a little big data magic and he knows anyways how many profiles a node has.

**Comment by AlfredSK** [comment]
Can we please not overcomplicate that topic? It's about the stats to be accurate, not about the visibility of profile details (user data) and also not about security issues.

**Comment by hoergen** [comment]
It is at the moment overcomplicated because people don't know what is going on. So, if we untangle it,  bring in some more clarification and making clear what decision you can make, I think it will be less complicated than it is at the moment.

**Comment by annando** [comment]
@AlfredSK the option "Publish server information" is doing exactly this. Means: When it is not activated, basic information is available via nodeinfo. When the option is active then also the user and post numbers are counted.

And concerning the "opt-in" vs. "opt-out" stuff: These are only summarized numbers, they don't contain any personal information at all.

I, personally, would want to count all users who had logged in at least one time.

**Comment by AlfredSK** [comment]
I do agree. I think what @annando said is the right approach. And I also agree to @hoergen  that the privacy options for users are a little complicated and not easy to understand.

So, from my point of view we should do both. But the clarification of the privacy settings is out of the scope of this issue. We should better address them in a separate issue.

**Comment by AlfredSK** [comment]
So... What is the current status? Do we have an agreement? When I understood all arguments it is ok to only change the calculated node statistics to reflect the accurate numbers. Because pure numbers are no privacy issue and we already have a setting to opt-out of the statistics. Right?

If so, is it sufficient to change the query in ...? https://github.com/friendica/friendica/blob/46e89299c56665a083f36de69c5ba4f6eba05084/src/Model/User.php#L1112-L1118

I did that locally to test if it is working. The query works but the statistics at .../nodeinfo/X.0 don't change. I guess the worker has to pick up the CronJob first. Or is there anything else?

**Comment by AlfredSK** [comment]
Ok. My local change works. I'll provide a draft PR this evening. We can then discuss and decide which account types shouldn't be counted.
