### ISSUE TITLE
[Frio] Broken Birthday Reminder style

### ISSUE THREAD

**Issue by nupplaphil** [friendica/friendica#8268]
### Expected behavior

Finding a birthday reminder in a well formed style

### Actual behavior

See the marked text in the screenshot (it is nearly invisible if I haven't marked it)
![Screenshot_2020-02-09 Philipp's Friendica Network](https://user-images.githubusercontent.com/379654/74110755-7004f100-4b8f-11ea-81e7-e9942b8c6455.png)

### Steps to reproduce the problem

- Add a birthday reminder
- Got to the "network" page

### Friendica version you encountered the problem

2020.03-dev

### Friendica source (git, zip)

git

**Comment by annando** [comment]
What about adding the birthday reminder to the notifications?

**Comment by tobiasd** [comment]
For me the calendar in the network tab (quattro style) works best for these reminders. Which is why I ported them to vier for the local node.

The problem with having them in the notifications is, that you cannot set notifications to unread. For me a one shot reminder a week ahead of an event would just be useless, as I would forget having been reminded about it.

The quattro style has a nice visual reminder about the upcoming things over the next week.

**Comment by annando** [comment]
Well, I can imagine both. Having this notification and then the sticky reminder altogether.
