### ISSUE TITLE
Apache mod_cache + mod_cache_disk can lead to session hijacking

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#8349]
### Expected behavior
Session hijacking shouldn't be possible.

### Actual behavior
I enabled Apache mod `cache` with `cache_disk`. I also added `CacheEnable disk /` to the Apache virtual host (recommended setting).
Shortly after I enabled the module a user reported that he was 'logged in' to my account.

Apparently, Apache `mod_cache` can lead to issues with the session cookies.

> The configuration does not take care to use the CacheIgnoreHeaders directive to tell mod_cache not to cache Set-Cookie headers with the responses. When a combination of unusual circumstances coincided for two users - the cached item, with its Set-Cookie header, was returned to another user.

https://confluence.atlassian.com/jirakb/request-assumes-identity-of-another-user-who-logs-in-concurrently-due-to-apache-cacheignoreheaders-226791609.html

I'm not sure if this was a configuration issue on my side or if Friendica doesn't set the `CacheIgnoreHeaders` correctly.

### Steps to reproduce the problem
Enable Apache mod `cache` with `cache_disk`. The user reported that he just reloaded the page and was suddenly in my session.

https://forum.friendi.ca/display/0b6b25a8-125e-5a98-1343-94b047728378

The bad thing is I couldn't reproduce it myself.

### Friendica version you encountered the problem
2020.03-dev

### Friendica source (git, zip)
git

### PHP version
7.3

### Apache version
2.4.41

### SQL version
10.3 MariaDB

**Comment by MrPetovan** [comment]
mod_cache is meant to cache dynamically-generated “static” pages. Friendica has few of them, including:
- /friendica/*
- /.well-known/nodeinfo/*

So it doesn’t make sense to set `CacheEnable disk /` as it instructs Apache to cache all query paths = the whole website.

Unfortunately there’s nothing we can do in Friendica to prevent Apache from caching logged in pages because of a cache configuration too wide.

**Comment by AlfredSK** [comment]
Ok. Thank you for the explanation. I really didn't expect the caching leading to such issues. :-/

**Comment by AlfredSK** [comment]
I understand now it isn't a Friendica issue. Should I close it then?

**Comment by MrPetovan** [comment]
So, I looked into it a little more, just to be sure. The `mod_cache` uses the `Cache-Control` header to decide whether to cache a page or not. However we issue the `Cache-Control: no-store, no-cache, must-revalidate` header on all pages *except* for profile pictures so `mod_cache` should be mostly ineffective with Friendica.

Because even if the `Set-Cookie` header was scrubbed from cached pages, it would still show a cached private page with potential privacy issues even if it isn't a complete session hijack.

Not sure why `mod_cache` is acting the way it is but `CacheEnable disk /` is a big no-no for Friendica.
