### ISSUE TITLE
Notification for someone likes or share my post/comment?

### ISSUE THREAD

**Issue by asherpen** [friendica/friendica#8423]
### Expected behavior
Add an option: When someone likes or share my post or comment, get notification.
### Actual behavior
There's no way to get notification for like/share
### Friendica version you encountered the problem
2019.12

**Comment by MrPetovan** [comment]
Share notifications aren't possible at the moment since the share author isn't necessarily interacting with the shared post itself. Like notifications should be possible, however I'm unfavorable to it.

**Comment by asherpen** [comment]
I see, thank you. Maybe someone will pick the "like notification" up :)

**Comment by annando** [comment]
Share notifications could work in the same way how "like" notifications could work - but less reliable. But I'm also not a fan of it.

**Comment by SpcCw** [comment]
I miss both. However they should be done right.

Reshare notification is definitely interesting to me and not just because someone reshared my post elsewhere but also because there might be new discussion created. It is not uncommon for questions to be reshared. Sometimes it happens not right away, maybe weeks after the post was made. Then the author misses all discussion in the new place unless mentioned. Would be great if reshare notification also included link to reshared post (and fetch it) when possible so the author could go check it out.

Likes are more of personal preference but again some people find it nice to know that someone liked one of their posts, especially older posts where they wouldn't see this interaction otherwise. Like notifications definitely should be turnoffable and condensed per post.

**Comment by wiwie** [comment]
It happens to me on a regular basis that the "my posts and conversations" icon in the top bar shows a counter, I click on it and I have to scroll through all my posts to figure out what the counter actually corresponds to. Sometimes it is a like. I think this behaviour is quite annoying. This way the counter is of little to no use.

In my opinion one of the following would be better, where I'd prefer number 1:

1) instead of a counter on the home icon, show a notification for the like/event instead. Remove the home icon counter.
2) neither show the home icon counter nor a notification.

**Comment by MrPetovan** [comment]
Agreed, it is a legacy artifact I'd like to get rid of.

**Comment by AlfredSK** [comment]
It's not a convenient possibility but one that exists. :-) When there is a notification bubble on the home icon you can go to 'Notifications' in the main menu and then select the 'Home' tab. There you can find the notifications you got for interactions on your content.

**Comment by MrPetovan** [comment]
It doesn't seem to show likes though, even though they trigger the notification badge on the Home icon.

**Comment by AlfredSK** [comment]
Well, it says 'commented on...' also for likes. :-)

**Comment by MrPetovan** [comment]
🤦‍♂️

**Comment by wiwie** [comment]
I'm confused. So it is supposed to be working? I just double checked. There is no notification for a recent like I received. Neither a "commented on" nor "liked"

**Comment by AlfredSK** [comment]
See `https://your.friendica.node/notifications/home`.

**Comment by haheute** [comment]
I remember it this way from diaspora: "User A, User B and 2 others liked your post: "Abcde..". 
Maybe then it would be easier to find out which posts got liked by who.. ..but I am not sure.

**Comment by asherpen** [comment]
There's a new issue [https://github.com/friendica/friendica/issues/10546](url) and this feature is seen on 2021.09-rc. So I guess It's OK to close this issue?
Thank you all :)
