### ISSUE TITLE
wrong request to host-meta

### ISSUE THREAD

**Issue by git-marijus** [friendica/friendica#8567]
I am seeing requests from friendica (libranet.de and sqeet.me) to the channel URL instead of the host in hubzilla:

https://hub.somaton.com/channel/sys/.well-known/host-meta

instead of

https://hub.somaton.com/.well-known/host-meta

I checked if hubzilla is sending the wrong info via xrd but that does not seem to be the case...

**Comment by annando** [comment]
You mostly should also see requests for https://hub.somaton.com/channel/.well-known/host-meta as well, do you?

The other system could be a system that sits in some subdirectory. Because of this we are probing the full path. We do not start with the host, because there could be multiple installations on a single host.

**Comment by git-marijus** [comment]
No, actually i see just what i posted. (Which probably returns a 403 forbidden from my server).
Additional info: i am seeing this after fetching a public object. Fetching fails with error 404

**Comment by git-marijus** [comment]
Is it possible that friendica gives up after receiving a 403 for the first request?

**Comment by git-marijus** [comment]
Checked again. Actually in the server logs i see requests to both
https://hub.somaton.com/channel/sys/.well-known/host-meta and https://hub.somaton.com/.well-known/host-meta but not https://hub.somaton.com/channel/.well-known/host-meta

**Comment by git-marijus** [comment]
I'll close this issue.
