### ISSUE TITLE
export friendica to activitypub (mastodon)

### ISSUE THREAD

**Issue by adrelanos** [friendica/friendica#8574]
Feature request:
Could you please allow exporting from friendica to activitypub (mastodon)?

I.e. I would like messages posted on (or imported on) friendica to forward to mastodon.

**Comment by annando** [comment]
Friendica is fully compatible with the ActivityPub protocol. Means: People from Mastodon can subscribe to your Friendica account and vice versa.

**Comment by adrelanos** [comment]
Meaning forwarding posts from friendica to Mastodon does not make sense?

**Comment by annando** [comment]
What do you mean with "Forwarding"?

**Comment by adrelanos** [comment]
Re-post.
Such as post on (or import from twitter or so) friendica and then re-postto another (self owned) mastodon account.

**Comment by annando** [comment]
I'm not a fan of reposts when the original post is available in that network as well. Means: I think a Twitter mirror is okay when you are active on both networks. But when the original post is already available on that network, then your content gets multiplied and users are confused whom to follow. And if - for example - the Friendica account would only be used for mirroring but wouldn't be monitored, then it would end up with some sort of "ghost account" with people answering that account with never getting any reply.

**Comment by MrPetovan** [comment]
I'm with @annando, please give your Friendica handle to your Mastodon contacts to follow and they will automatically receive the same content as if you had used a post mirroring addon.

**Comment by hoergen** [comment]
> Feature request:
> Could you please allow exporting from friendica to activitypub (masterdon)?
> 
> I.e. I would like messages posted on (or imported on) friendica to forward to masterdon.

If I understand you correct, you want a function that is doing a repost of a source, as if it would be your original post, because you are using Friendica as a bridge from other sources? Maybe it would be much easier, you would use a friendica account to use all of the features you want to have on your mastodon account. Or you request this feature in mastodon, because I see there some flaws with your idea doing it that way. Not only security, also a huge fundamental change in the Activity Protocol philosophy. And this need to happen with all AP projects in the world if it should make sense.
So i would suggest you switching over to use a friendica account as your main account to have all those flexibility you are searching for.

**Comment by copiis** [comment]
He is on my server. I think he means somthink like the post forwarding to Wordpress but that makes no sense because friendica is already talking to Mastodon.

**Comment by schmaker** [comment]
Seems like this issue is safe to close
