### ISSUE TITLE
Move from fxpio/composer-asset-plugin to fxpio/foxy

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#8583]
Branched from https://github.com/friendica/friendica/issues/8578#issuecomment-623776217

## The current situation

We use the [`fxpio/composer-asset-plugin` Composer plugin](https://github.com/fxpio/composer-asset-plugin) to define front-end dependencies in the `composer.json` file from Bower or npm repository. This enabled us not to have to have a full copy of these libraries in our versioning system and manage upgrades centrally.

## The potential problems

- The Composer plugin is meant to be replaced with [the `fxpio/foxy` Composer plugin](https://github.com/fxpio/foxy), although we haven't had any specific issue with it.
- [Bower is deprecated](https://bower.io/blog/2017/how-to-migrate-away-from-bower/). The repository still is maintained, but who knows how long for.

## The migration challenges

The new Composer plugin seems to be slightly more involved that the current one. I like the separation of dependencies between `composer.json` and `package.json` but it now requires local NodeJs, npm and/or Yarn dependencies. It should be a big deal for admins already dabbling with the `develop` branch but it is a hurdle nonetheless.

It also requires someone™ to go over the list of current Bower dependencies and find the counterpart in either npm or Yarn. I've been satisfied with Bower dependencies because they usually were only comprised of distribution files, e.g. only the library itself, not the sources/tests that we have no use for. I wonder if I can find the same convenience in Yarn or if it requires local compiling/building/bundling that I'm unfamiliar with.

## What are the alternative?

I also found [Asset Packagist](https://asset-packagist.org) which is supposed to be a drop-in replacement for `fxpio/composer-asset-plugin`. It wouldn't alleviate our dependency to Bower and would only remove the Composer plugin inconvenience, which has been minimal so far thanks to our use of `composer.lock`. It also duplicates packages in existing repositories in their repository, which requires us to trust a smaller structure to maintain a separate repository, which I'm uneasy about given that even Bower is on the way out.

**Comment by toddy15** [comment]
Hi @MrPetovan,

I've taken a look at the fxpio/foxy composer plugin you've mentioned. It seems to me that this plugin just creates a "package.json" file for npm to use, so that a local installation of npm is required to download and install the JavaScript libraries. Therefore, I don't think that there is much value in using that plugin, because it does not download the JS libraries in the same way that fxpio/composer-asset-plugin does it.

Also, as far as I understand, the custom JavaScript source code used by Friendica (in view/js and scattered around several files in the templates and themes) would need to import the required JS libraries. It would then be possible to use a JS bundler like webpack etc.

However, this seems like a lot of work and a rather big change. Are the Friendica developers willing to do this (or accept help/PRs for this)? Or do you want to stay with the currently used fxpio plugin as long as possible?

Regards,
Tobias

**Comment by MrPetovan** [comment]
Thank you for looking into this. I've never use npm or webpack professionally, so I would gladly accept help for this task, as I would like Friendica to be able to move to Composer 2.

There also has been work on the plugin to make it compatible with Composer 2 but it is depending on PHP 8 which we haven't decided on yet for Friendica: https://github.com/fxpio/composer-asset-plugin/issues/334#issuecomment-1191962525

**Comment by toddy15** [comment]
Thanks for the link, I didn't know about that effort.

Is PHP 8 an issue for Friendica? I've got it running in a local installation with PHP 8.2 and do not notice any issues. It would probably be the easiest way forward to "officially" switch to PHP 8 for Friendica -- that way, you could just continue to use the composer-asset-plugin, avoiding all the work with updating the JavaScript. Or are there any issues with dropping support for PHP 7?

**Comment by MrPetovan** [comment]
We've always had a policy to support as many platforms as possible. This has meant not raising the minimum PHP version if we don't absolutely have to. So Friendica works from PHP 7.4 to PHP 8.2+, and I would like us to be cautious about raising the minimum PHP version "just" to have access to Composer 2. It would be a nice to have, but so far it hasn't been critical.

**Comment by toddy15** [comment]
Fair enough. :smile:

**Comment by MrPetovan** [comment]
Closed by https://github.com/friendica/friendica/pull/14523
