### ISSUE TITLE
Error: "Not a valid email address."  on account creation

### ISSUE THREAD

**Issue by coamtaker618** [friendica/friendica#8630]
I'm getting an error of "Not a valid email address." when I try to create an account.  This is independent of the email input into the new account, and I believe refers to the initial email address that Friendica uses to actually send the email.

1) Is there any way to confirm this is the problem.
2) Is there a way to change what email Friendica uses to send email?  I was not able to find anything in a quick search.

**Comment by coamtaker618** [comment]
So I found "sender email" under "/admin/site" page.  However I still need the rest of the config info to connect Friendica to the email server.

**Comment by MrPetovan** [comment]
This error also can happen if Friendica can't check the existence of the email address domain. You can set `system.disable_email_validation` to `true` in your `config/local.config.php` file to disable this check and probably allow registration.

**Comment by coamtaker618** [comment]
I don't think that's it as I've tried gmail addresses too, and I assume checking the existence of gmail is trivial :p  It really doesn't seem to matter what email address is used.

Thanks for the tip on disabling this feature.  I would like to get it working, but I can try the experience of disabling it to get started.

**Comment by coamtaker618** [comment]
Also, is there an option for "system.disable_email_validation" in the abmin webGUI or just the config php file?

**Comment by MrPetovan** [comment]
Nope, just the config file. You can check all the non-GUI config options in `static/defaults.config.php`.

**Comment by MrPetovan** [comment]
So the only two ways you can get the `Not a valid email address.` error message on account creation are:
1. The email address format is invalid. The expected format is outlined in RFC 822 per PHP's documentation.
2. The email address DNS domain doesn't return a MX record along either a A or CNAME record.

The former seems harder to trigger than the second because it involves more failure points, including remote DNS calls, this is why I suggested you disable this verification. There's no check of the sender email at this point.

The other way you can get a similar message is when you are trying to invite people to Friendica and the provided email address fails a format validity check but it would output the entered email address, unlike during account creation.

**Comment by coamtaker618** [comment]
Ok, NBD to change the config.  Just had to ask! And thanks for pointing out the defaults as a reference file :)

**Comment by coamtaker618** [comment]
That said, I'd still like to fix whatever email issue I may be having.

**Comment by MrPetovan** [comment]
I understand but I'm not personally qualified to assist with that. However once your node is up and running (or with any existing Friendica account) you can ask for help on the Friendica Admins forum (contact address: `admins@forum.friendi.ca`).

**Comment by coamtaker618** [comment]
Understood, I appreciate the help you were able and willing to offer :)

**Comment by MrPetovan** [comment]
Of course, let us know if you have further issues with Friendica!

**Comment by coamtaker618** [comment]
Reporting back that I have a related issue.  While it's related, it's different enough I feel it's worth opening another issue, and as a result I'll close this one.
