### ISSUE TITLE
[feature request] add indicator for and number of unread messages and notifications to favicon / browser tab title

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#8683]
Currently it is not possible to see at a glace at the browser tab whether a new message or notification has been received.

### Expected behavior

- [ ] Add red dot to favicon once a directmessage or notification is received
- [x] Add number to tab title for the number of unread directmessages + notifications e.g. (3) (#8687)

Twitter and Riot solved both challenges:
![favicon indicator](https://user-images.githubusercontent.com/5708172/82751880-93f4e700-9dba-11ea-847c-d2d3ddc9cd85.png)
![riot](https://user-images.githubusercontent.com/5708172/82948968-13dda580-9fa3-11ea-9fc1-3f8b864a9d74.png)
 
### Actual behavior

The friendica tab has to be opened to see on the website whether new messages or notifications have been received. I think that this is a problem, because it slows down communication and makes it easy to miss a response when engaged in a conversation.

**Comment by MrPetovan** [comment]
Yep, I’ve been meaning to add this for a while, thanks for writing a feature request.

**Comment by MrPetovan** [comment]
Adding the number to the tab title is easy.

But adding the badge to the favicon is trickier because the favicon can be changed by the node admin. We then would need to add a separate setting for the badged favicon and I'm not fond of this.

Separately, [the Vivaldi browser rolled out a feature to detect numbers in parentheses in the document title to provide an actual notification badge](https://vivaldi.com/blog/details-matter-vivaldi-1-6-is-ready-2/) (not simulated in the favicon image) so it makes me less likely to want to mess with the favicon image.

I've seen Javascript libraries to edit the favicon image on the fly but this is straight up madness.

**Comment by annando** [comment]
@MrPetovan Please don't follow the path to madness :-)

**Comment by MrPetovan** [comment]
I'll leave to @foss- to decide if they want us to take it or not.

**Comment by foss-** [comment]
Having the number is awesome. Was not aware of that Vivaldi feature, seems like a smart solution to a common problem. So let's close this - curious to test it out soon :)
