### ISSUE TITLE
Links to reshared posts not there anymore

### ISSUE THREAD

**Issue by ben-utzer** [friendica/friendica#8785]
### Expected behavior
The date/time of the reshared post should be linked to the local copy of the reshared post, as it was before, until some days ago. 

### Actual behavior
No link whatsoever, so it is not possible to find the original post anymore. 

### Steps to reproduce the problem
Look for some reshared post in your timeline, i.e. this one [here](https://social.yl.ms/display/f897a1e09286013889d5005056264835). 

### Friendica version you encountered the problem
06.2020-RC

### Friendica source (git, zip)
git

### PHP version
PHP 7.4.6 

### SQL version
same as before.

**Comment by MrPetovan** [comment]
Hi @ben-utzer , I believe there are two separate issue. One is of usability. Share block display has changed on frio to match regular post display. To this end the link to the source post has been moved from the date string to the regular external link icon in the share box top-right. The link on regular posts' time string is meant for local links which we don't support in share blocks at the moment.

Except for Diaspora, which brings me to the second issue: Since we have the local `/display/<guid>` link for share blocks in Diaspora posts, we don't have the original post URL that should go in the external link icon. Instead it is the local Friendica post link that you are looking for.

The solution is glaring: we should support both links, at least for Diaspora, and it's pretty easy: for reshares coming from Diaspora, we store the `guid` in the share block attributes, which would allows us to reconstruct the local post link in its right place.

Share blocks from other networks would have to be examined on a case-by-case basis, for example from Twitter where a local Friendica post link only makes sense to the person who imported the tweet, so we have to make sure that this link wouldn't end up being displayed to other people.

**Comment by ben-utzer** [comment]
> The link on regular posts' time string is meant for local links which we don't support in share blocks at the moment.
Even after the redesign there was a link to the local copy of the link, the date time was link to the local post copy. The red square text had that link, but since 2 or 3 days it does not have the link anymore. 
![Screenshot_2020-06-17_15-55-11](https://user-images.githubusercontent.com/8361662/84910101-c1ca0480-b0b6-11ea-8ac6-0ed15314c3fa.png)

But you're right, not the square arrow symbol in the top right is sometime linked to the local copy of the post. Check the example [here](https://social.yl.ms/display/f897a1e09286013889d5005056264835), top post has the square linked to the remote copy and the reshared post is linked to the local copy. 



> Except for Diaspora, which brings me to the second issue: Since we have the local `/display/<guid>` link for share blocks in Diaspora posts, we don't have the original post URL that should go in the external link icon. Instead it is the local Friendica post link that you are looking for.
Yes, it is kind of inconstant now. 



> The solution is glaring: we should support both links, at least for Diaspora, and it's pretty easy: for reshares coming from Diaspora, we store the `guid` in the share block attributes, which would allows us to reconstruct the local post link in its right place.
Yes, lets keep it as it was till some days ago. :-)



> Share blocks from other networks would have to be examined on a case-by-case basis, for example from Twitter where a local Friendica post link only makes sense to the person who imported the tweet, so we have to make sure that this link wouldn't end up being displayed to other people.
I don't want any change, just keep it as it was if possible.

**Comment by MrPetovan** [comment]
Well, the previous display was inconsistent, the date string would unexpectedly link to the remote post, except for Diaspora reshares. Now share blocks are consistent with the regular post display, except for Diaspora 🤷

So we need to do something about Diaspora reshares first to correct the inconsistency I wasn’t aware of.

**Comment by ben-utzer** [comment]
> So we needed to do something about Diaspora reshares to correct the inconsistency I wasn’t aware of, and we still do after the display change, and I intend to tackle it in this issue.

Thanks. Having the possibility to find the local copy of a post is a real value.

**Comment by MrPetovan** [comment]
I'll reiterate that only Diaspora reshares had this "feature". I'll keep it for Diaspora because we have the required data, but I can't promise a local post link for all reshares.

**Comment by ben-utzer** [comment]
> but I can't promise a local post link for all reshares.

Yes, I got that. For Mastodon we do not need it, as the reshares is only a information attached to the original post. Just like a "Like".
