### ISSUE TITLE
Likes on Friendica are not synced with Twitter and vice versa.

### ISSUE THREAD

**Issue by copiis** [friendica/friendica#8947]
Likes on Friendica should be forwarded to Twitter and vice versa.

Likes on Friendica are not synced with Twitter and vice versa.

Activate and set up the Twitter plugin.

Friendica 'Red Hot Poker' 2020.07 - 1355

git

PHP 7.4.8

### SQL version
MariaDB 10.1.44

**Comment by MrPetovan** [comment]
We can't import likes because this information isn't attached to imported posts.

However we do forward Friendica likes to Twitter, I was able to do it just this morning.

However, it sounds awfully like https://github.com/friendica/friendica/issues/8778, please verify your Twitter app for Friendica isn't limited.

**Comment by copiis** [comment]
Okay i just saw this on the twitter app `RESTRICTED TO API READ ACCESS ONLY`
How did you @MrPetovan contact support to solve this problem?

**Comment by copiis** [comment]
I have now made a new app and now the likes are working too

I'm closing here

**Comment by MrPetovan** [comment]
> How did you @MrPetovan contact support to solve this problem?

There's a link to a contact form in the Twitter Developer area, I've been contacted back in a few days with an admonition that my app was mentioning too much people that didn't interacted with me first. I'm still not sure what they are talking about.
