### ISSUE TITLE
Friendica is spamming my site

### ISSUE THREAD

**Issue by skerkour** [friendica/friendica#9015]
### Expected behavior

Stop spamming. fetch RSS feed something like every 15 mins (minimum), and better detection of updated content: there is no need to crawl the entire site. 

### Actual behavior

I've recently noticed an unusual amount of traffic coming from friendica instances. Something like each instance crawling my website each minute. It's a little bit annoying as today, all cloud providers bill used bandwidth. 

I believe this is a bug in the RSS fetching mecanism

### Steps to reproduce the problem

* point friendica to a website
* inspect website's logs.

### Friendica version you encountered the problem

The user agent is like the following: `Friendica 'Red Hot Poker' 2020.09-dev-1359; https://xxxxx.xx`

**Comment by annando** [comment]
Can you provide some more data? What exactly is crawled? Friendica does fetch for RSS in configurable time frames. Also we need to detect the other system, so we try to fetch data from endpoints via (for example) nodeinfo. We try to not overload other systems by using some negative caching as well.

If you do have the server pirati.ca in your logs as well, it would be totally great if you could send me your access log. Or you could tell your hostname, so I could check at my servers.

**Comment by skerkour** [comment]
Thank you for the quick reply!

Unfortunately I didn't found logs for `pirati.ca` (my website is https://fatalentropy.com).

Here are an excerpt of my logs, from only one friendica instance:

<img width="1254" alt="Screenshot 2020-08-15 at 15 01 11" src="https://user-images.githubusercontent.com/6172808/90312916-827a3180-df08-11ea-9ceb-204ce13770ed.png">

There is this kind of "burst" every 3 minutes for each instance. Each burst is around 74 requests.

The bug seems pretty similar to https://github.com/nextcloud/news/issues/588

The problem is not the number of requests, but more the fact that the instances are fetching all the data each time, which generate a large amount of bandwidth, for 0 utility.

**Comment by annando** [comment]
I had a look at the feed. I can explain what happens - and why it tricks out the existing checks. The system fetches the feed. The time between fetching the feeds can be adjusted, but surely there need to be some better check for minimum pauses.

Then the feed items are fetched. Then it checks if the item has been fetched before. It doesn't seem to be the case. Then the system seems to be set up, so that it fetches additional data from the feed, like keywords or other stuff that can be fetched via the header data. So it crawls the information from each page. Then it posts the content - and the system sees that the content is too old, so the item isn't stored.

What we need to do: Checking the time before fetching the additional data and introducing some minimal fetching interval.

Give me this weekend please.

**Comment by skerkour** [comment]
Thank you for the kind reply, so just to understand, the problem come from that friendica do not cache/store the crawled content because it's detected as too old?

FYI here are the relevant headers regarding caching for an example request: `https://fatalentropy.com/open-source-weekly/13`
```
< HTTP/2 200
< cache-control: max-age=3600
< content-type: text/html; charset=utf-8
< etag: "8fe9a32dd322eb227d21f859a3413a6bca728420dd6f7270ac92a7e2f7fdc57c"
< last-modified: Sat, 15 Aug 2020 13:37:11 GMT
< strict-transport-security: max-age=31556926
< accept-ranges: bytes
< date: Sat, 15 Aug 2020 19:54:09 GMT
< content-length: 31902
```

**Comment by annando** [comment]
In fact this had been a combination of several things. If you are interested in it, you can have a look at the PR. Of course I don't know when the remote systems will update. But since the named one is running on the development branch you should indeed experience a significant change soon.

It would be great if you could have an eye on it.

**Comment by skerkour** [comment]
Hi @annando ,

A quick message to let you know that it seems the fix has worsened the problem,

Now, one instance of Friendica is sending ~2500 requests / hour to my website even if my website has something like 20 pages...
User-agent: `Friendica 'Red Hot Poker' 2020.09-dev-1362; https://xxxx.xx`

<img width="1172" alt="Screenshot 2020-08-20 at 09 58 37" src="https://user-images.githubusercontent.com/6172808/90733086-5544cf00-e2cc-11ea-9bdf-a32fccdd1559.png">

**Comment by annando** [comment]
@skerkour This possibly is related to a lately introduced bug that will be fixed with this PR: https://github.com/friendica/friendica/pull/9040
