### ISSUE TITLE
Why is matomo used?

### ISSUE THREAD

**Issue by tiotrom** [friendica/friendica#9316]
Isn't it collecting data? I see UBlock Origin blocking it. Is there a good reason for using it? Cheers!

**Comment by AlfredSK** [comment]
No idea what matomo is but if uBlock is blocking it it's probably coming from embedded third party content.

**Comment by tiotrom** [comment]
Hm...it might be a Friendica addon https://github.com/friendica/friendica/issues/6711?

**Comment by mkljczk** [comment]
Ask your Friendica node owner, as it’s not a standard feature

**Comment by MrPetovan** [comment]
Matomo (formerly Piwik) is a self-hosted open-source analytics gathering tool without a centralized commercial database. A Friendica node owner using the Matomo addon would collect this data only on their server and it can't ever been cross-referenced with most other websites you visit, even if they also use Matomo, because the data would be physically separated.

**Comment by tiotrom** [comment]
I see. So it is up to the owner of the node to install this. I will contact them, Thank you.
