### ISSUE TITLE
Nested posts often get lost only posting the original poster

### ISSUE THREAD

**Issue by anubis2814** [friendica/friendica#9335]
This problem is probably newish due to high traffic not being so heavy.  I mirror my friendica and twitter feed.  A person will share another person's post with a comment.  I want to share that person's post, however it only posts the original post.  Have had several people really confused why I supported something I usually stand completely against.  I have to go into twitter if I want to share the whole thing.  May have already been addressed and being worked on but I didn't see anything fitting my description exactly

**Comment by MrPetovan** [comment]
This is a remnant from compatibility with Diaspora. Since Diaspora doesn't have a concept of quote-share (a share with a comment), but still starts a new thread instead of sharing a link to the original post, we have been doing this by default as well. At the moment we do not support nested `[share]` blocks but it should be fairly easy to transform a nested share block into a post URL.

**Comment by anubis2814** [comment]
As twitter is now broken, This post is obsolete.
