### ISSUE TITLE
Network stream is showing wrong active order in the tab bar

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#9457]
- [X] I have searched open and closed issues for duplicates

### Bug Description
After the latest fix for 'remember my last used network tab' there is a new issue now. The tab bar doesn't highlight/show the correct stream order

### Steps to Reproduce

1.  Go to /network
2.  Select "Personal" tab
3.  Select the "Network" icon in the main navigation bar

Actual Result:
The network stream is now actually showing the item order by latest activity or latest post (depends what you have used the last time). But in the second nav bar the active tab still shows the "Personal" tab as active stream order.

Expected Result:
The tab bar should show the correct stream order. When I click on the "Network" icon and e.g. the order by latest post is displayed as network stream the tab bar should highlight the tab "order by latest post".

### Platform Info

Friendica Version:
2020.12-dev

Friendica Source: 
git

PHP version:
7.4

SQL version:
MariaDB 10.3

**Comment by MrPetovan** [comment]
The preference has been reset again by this change, please choose your preferred order, and it will stick across devices.

**Comment by AlfredSK** [comment]
No. That's not the issue. Network stream is actually showing e.g. order by posts but the tab bar is highlighting "Personal". That's wrong and a bug.
Please follow the steps I provided.

**Comment by MrPetovan** [comment]
Ah, never mind, I tested and I can reproduce the problem. However, while it's a difference from the previous behavior, I don't think it's wrong. The pagination for the Personal tab works, and going back to the Network page shows the network stream as expected.

The real issue is that the tab bar is mixing the network page orders and two separate stream pages. The best solution would be to move the order setting elsewhere, like in the actual settings, and only have tabs with Stream, Personal, Starred, and Personal Notes.

**Comment by MrPetovan** [comment]
Here's what I experienced:
1. Click on "Latest Posts", network stream appears with the relevant order.
2. Click on "Personal" tab, personal streams appears.
3. Click on "Network" icon, the network stream appears, the tab switched to "Latest posts" which is the order I selected before.

**Comment by MrPetovan** [comment]
I officially don't understand anything about the new session/config values for the network tabs.

Each time my mobile app reloads the "Network" page (new session), it always defaults back to "Last Activity". But when I clicked on the Network icon on my forever opened desktop browser tab, it showed the "Personal" tab from my earlier test, which I didn't expect since I switched to "Latest Posts" on mobile.

Why are we using the session value again, and why the update call cannot using the user config value?

**Comment by carrabelloy** [comment]
![grafik](https://user-images.githubusercontent.com/1060591/97120689-307c3600-1719-11eb-9361-28e6a3f964bb.png)
Unfortunately I have streaming problems and especially in the network I have problems mirroring messages from other servers. It feels like I'm on the move with a modem like in the 80s. At the moment the most reliable is Diaspora and Mastodon. Unfortunately, things are not going so well at Friendica. 
The problem I have here, because I have the first users who have taken a seat on my instance, suffer the most. Because you don't always get the data. As in the picture there is usually a break in the network.

**Comment by annando** [comment]
@carrabelloy can you open a new issue for this? This doesn't seem to be related to the topic of this issue.

@MrPetovan when I work on different systems, I don't expect that changing the tab on the one machine should change the selected tab on the other machine as well.Also when only using the user config value, you had the issue that when you changed the tab on the one machine, the updates on the other machine would change as well. So for example on your desktop you have the tab page open with the marked posts. Then on mobile you change to a different tab. Then on the desktop - without changing the tab - other content would be loaded automatically. Same would happen with the infinite scroll.

**Comment by MrPetovan** [comment]
Ah, I see. So the remaining pain point is one that always existed, the network stream order should be set in the user settings, not through a tab. Said tab shouldn't be saved at all since the Mention, Starred and Personal Notes tabs all will use a query string parameter which is kept for pagination and asynchronous updates.

**Comment by annando** [comment]
Well, the current problem simply is that the order is saved separately. Means: The order of the posts of the personal or marked tab depends upon which tab had been used before.

**Comment by MrPetovan** [comment]
I'm still getting "Latest Activity" updates when the selected tab is "Latest Posts" in the Network page, beyond the first page after having selected "Latest Posts" (when URL actually included `order=received`)

**Comment by AlfredSK** [comment]
Confirmed. There is still something wrong.

**Comment by annando** [comment]
Weird ... I have to check these days.

**Comment by tobiasd** [comment]
Same here, latest activity updates in latest posting ordered view. After a reload of the network page the wrongly inserted updates are cleared out.

**Comment by annando** [comment]
I will have a look, but currently I'm in the middle of another task that will last some days.

**Comment by MrPetovan** [comment]
Another report in #9467

**Comment by MrPetovan** [comment]
The network page behavior seems to be consistent now.

**Comment by AlfredSK** [comment]
The issue is back! I clicked on the 'Personal' tab, then clicked on the main 'Network' icon, content is now 'network, latest posts'. But the highlighted tab is still 'Personal'.

Please reopen. Thanks.

Edit: Same wrong behavior with 'Starred' tab.
