### ISSUE TITLE
Better handling of blocked users

### ISSUE THREAD

**Issue by tiotrom** [friendica/friendica#9464]
So here's something I experienced: it is this guy who trolls us for the past 2 years or so. I had to block him on our NextCloud chats, but now he is commenting on our Friendica's profiles. I blocked the guy and I thought that will stop him from commenting, liking, sharing my posts. Apparently it is not. It only hides his activity from me... But I want to hide his posts or engagements on my posts for everyone.

Imagine if he comments all kinds of crap :D, and everyone can see that. So, is this how the "block" user is meant to be? Couldn't the instance itself say: user A blocked user B, so the comments/engagements of user B to the user A posts, will be deleted?

**Comment by MrPetovan** [comment]
I'm sorry about that guy. The only way to block someone from a whole node is to run the node. So either you can plead your case to the admin of your current node, or you can host your own node. Otherwise blocking mostly affects your own account. All public posts are fair game for anyone because of their nature, however the accounts you block won't be able to follow you directly nor you will see their replies.

**Comment by AlfredSK** [comment]
> you can plead your case to the admin of your current node

# 👋

**Comment by tiotrom** [comment]
I see...but isn't it possible and also a good idea to implement something like deleting/hiding the posts of a blocked user from the posts of the one who blocked the user? Else I fear people will not feel "safe" or comfortable knowing that someone can post comments on their posts and their families and friends and anyone else can see that. As such, there is no way for me to have a private presence on Friendica with posts that can only be for my group of friends? :)

**Comment by tiotrom** [comment]
I tested and if I manually delete a comment, it seems that it deletes it for anyone who sees my profile. So for post C I deleted the comment D, and then visited my profile in an incognito window where I was not logged in, and comment D was not visible. I'd say it is a needed implementation to delete the comments and engagements of a blocked user from the profile of the one who blocks the user. It makes a lot of sense in my mind, and takes the burden from the node admin. What do you guys think?

**Comment by tiotrom** [comment]
Sorry for the many comments, I just wanted to ask you something: what is then the difference between Ignore and Block? Isn't "ignore" doing the same as "blocking"?

**Comment by MrPetovan** [comment]
No, otherwise there wouldn't be separate "Ignore" and "Block" features 😄

Ignore hides the target contact's posts from your Network page, but they still are receiving your own posts if they are following you. It's the equivalent of "Mute" on Twitter. Private messages are still allowed.

Block hides the target contact's posts from your Network page, and they won't receive your posts even if they were following you. Private messages are not allowed.

**Comment by tiotrom** [comment]
I see thanks for the explanation. I still think it makes sense to not allow blocked users to post on your content or interact with it. Else you don't block them per-se (except from messaging you personally and following you), you kinda block yourself from seeing their posts/comments/profiles. :D 

I am thinking that anyone who wants to troll you or simply spam your posts, can continue to do so. You won't see that, but anyone else will, with or without any account if your posts are public. If someone posts scamming links on a youtube video or facebook post, you are able to stop them from posting on your profile. And I think that is useful. ;)

**Comment by MrPetovan** [comment]
It is an interesting angle, maybe @annando can confirm whether it is currently intended to work like this and whether it should be tweaked to completely reject any comment on a thread whose original author blocked the comment author.

**Comment by annando** [comment]
Problem is that we cannot control what other software does. So blocking a user on your system only affect stuff that is directed to your system. Public posts for example will always be readable for these people when only a single person on that servers had subscribed you. It is technically impossible to forbid the distribution of public posts for a single person, since the distribution is done on the remote side (where we don't have any influence).

Also that person could comment. And others would see the comments as well - only you and people on your server wouldn't see them.

**Comment by tiotrom** [comment]
@annando I am thinking if deleting a comment deletes it for good from my post, not being visible to anyone (logged in or not), then what if you use the same function and auto-delete the comments made by blocked users? If user A who I blocked, comments on any of my posts, simply auto-delete the comment.

Don't get me wrong, I hate blocking people and I rarely if ever did it, but I am thinking of trolls and creepos who may post all kinds of weird comments on a user's post, and even if the comments are invisible to that user who blocked the troll, they are perfectly visible to everyone else.

**Comment by MrPetovan** [comment]
@annando You're missing the point, it isn't about the spread of the public posts. It's about allowing blocked authors' comments on your threads at all. Yes, it could break the thread if a blocked person commented on their own node by retrieving the public post manually, and the comment was distributed to another node, and a third person from this node replied to the blocked author and the comment was distributed to the original node where a user blocked them. But it's convoluted enough that we shouldn't throw our hands in the air just because of it.

it would be like Diaspora where you're in control of your thread on your local pod at least.Your blocker contacts can't comment at all on your threads on your pod, and you can remove individual comments that become unavailable at least on your pod as well.

**Comment by tiotrom** [comment]
Diaspora's way of dealing with it sounds like what I was proposing :P. Would be great to have a way to keep your own profile clean ;)

**Comment by annando** [comment]
@MrPetovan the comment distribution on ActivityPub doesn't work that way. You can prevent distributing comments from blocked users via your own system. But you cannot prevent that the blocked person does distribute their comment on their own.

**Comment by MrPetovan** [comment]
Yes, but your node can reject the received comment if it's on a thread where the original author blocked the received comment author.

**Comment by annando** [comment]
Other servers can't know if you had blocked that user. So the comment of the blocked person will be processed like always.

**Comment by MrPetovan** [comment]
It's fine on other servers, the important part is the user's node itself.

**Comment by tiotrom** [comment]
> It's fine on other servers, the important part is the user's node itself.

Yes. Sharing a Friendica profile/page with others means you share your personal space, and it is good to have complete control over that. You can delete comments manually, but would be best if they are automatically deleted for blocked users. That's all.

**Comment by tiotrom** [comment]
Let me give you a recent example. This post of mine https://venera.social/display/85a863ed-575f-9b34-9180-bee170853948 - I have no idea who this guy who commented is or what he wants, but commenting in german when I do not speak german and the post is in english, sounds like spam to me. I blocked him so that he doesn't comment. Well...I can't see his comments but now some of my friends ask me who is this guy that comments in german on my posts...and i'm like what guy? Then I realize that anyone can see his comments...which makes it frustrating for me that I cannot have a clean profile where I can remove unwanted content in an automated way :D. Actually blocking this guy makes me unable to see his comments and also remove them...so it is like blocking gives someone the free access to your posts to comment whatever they want without you being able to see their posts and remove them :P.

Ok, I hope I made enough sense with my comments. I do not want to spam you guys now, but I am surprised about how the "block" option works. In my mind blocking a user should stop the user form interacting with you and your content.

**Comment by MrPetovan** [comment]
Ah yes, I've also received in my timeline posts from them where I'm apparently mentioned but it doesn't appear in the message. He's following me and I'm not following them.

**Comment by tiotrom** [comment]
These days I was talking to other people coming from different social networks to Friendica and I would suggest blocked users to be entirely blocked if possible. Like they should not be able to comment or interact in any way with you posts, not even to see your posts/page if possible. Like say venera.social where I have my account, to detect if user A is blocked and if so, to refuse to display my personal page to them. Could that be possible? I am thinking long-term that users need such control over their profiles. 

I am a bit annoyed that I have blocked a user and he can still share my posts, comment on them, and all that, and I can't even see those to remove them manually :D. But anyone else can see that. He can post spam links and all kinds of weird stuff, and my friends or followers will fall for that, while I am unaware of it and unable to stop it.

Ok. I think I made my point clear I don't want to insist on this is up to you guys what you decide, but I strongly feel a "blocked" user should be properly "blocked". Cheers!

**Comment by MrPetovan** [comment]
@annando I know how to check whether a contact is blocked by a thread owner, but I'm not sure where to put it, does it need to go in every single protocol? Or should we abort the reply creation in the Item class directly?

**Comment by annando** [comment]
We already do have such a check in the item model class. it is called by the `insert` function. This had to be enhanced so that it not only does check for the author/owner/causer being blocked by the current user id but also for the user id of the thread creator user (if the thread creator is on the same machine).

**Comment by MrPetovan** [comment]
Ok, I'll get on it.

**Comment by tiotrom** [comment]
I checked and the blocked users can still interact with the posts. This guy is blocked and yet he can still like, reshare and probably comment on my posts:

![image](https://user-images.githubusercontent.com/34804533/105722736-45d64b80-5f26-11eb-81dc-45b5f13adaa8.png)

And he can follow me too and have me in his contacts list and all that.

**Comment by annando** [comment]
To explain the problem: If the post was public and landet on that system (for example because there is another user following you) then the post is transferred to that server. Once it reached that server we don't have **any** possibility to deny interaction of specific users. So this person will always be able to share or like that post. We can only don't display this to you - and we can stop relaying these interactions to your followers.

**Comment by tiotrom** [comment]
I understand but my point with this entry was to erase the blocked user from the instance where I am from. So that, if anyone visits my profile on say venera.social, it won't see this blocked user's interaction with my posts.

In other words: user A uses the instance 1. User B uses instance 1 and 2. User A blocks user B. User B may be able to interact with the content that user A posts, but it is deleted from instance 1. If user A makes a POST, and user B likes, reshares the post and comments on the post, then the instance itself (1) should delete all of this interaction from the instance itself, so that when anyone sees the posts of user A, they won't see the blocked user B's interactions. 

Else I feel like I am blocking myself from user B. I won't see his interactions with my content, but others are. if user B posts all kinds of spams and such to my posts as comments, then I am not even aware of it, but all of my friends are.

You understand what I mean?
