### ISSUE TITLE
Unarchiving contacts broken

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#9565]
- [X] I have searched open and closed issues for duplicates

### Bug Description
During the last DB structure update 1375 -> 1378 I noticed that some contacts have been archived automatically. These contacts shouldn't be archived at all because they are vivid contacts. For example @MrPetovan has been archived. :-)
I tried to unarchive these contacts. Got a success message. The line 'currently archived' disappeared. But when I go back to /contact/archived the contacts are still listed there.

### Steps to Reproduce

1.  look at /contact/archived
2.  look for contacts that are known 'good' (reachable)
3.  try to unarchive them
4. look at the list again, check the contact details

Actual Result:
The contact stays on the list of archived contacts. Sometimes the line 'currently archived' vanishes. Sometimes that line stays.

Expected Result:
When I unarchive a contact That contact should really be unarchived and also should vanish from the list of archived contacts.

### Platform Info

Friendica Version:
2020.12-dev

Friendica Source: 
git

PHP version:
7.4

SQL version:
10.3 MariaDB

**Comment by MrPetovan** [comment]
So, toggling the contact archive status works as expected, BUT.

The condition to make it to the archived contact list is whether the archive status is set OR the failed status is set. This flag is automatically set during probe if it wasn't successful.

The problem is that we don't display this flag at all nor we make it clear that the Archive list contains both contacts manually archived and automatically archived contacts after a failed probe.

Furthermore, since we now have a manual status (archive) and an automatic status (failed) that seems to amount to the same result, I'd prefer we didn't set the archive status automatically as it will be confusing.

What was the intent @annando ?

**Comment by annando** [comment]
`failed` is set immediately in `OnePoll` when the contact couldn't be reached. `archive` is set in `markForArchival` when a contact hadn't been reachable for several days. `failed` is more or less only informative, while `archive` controls if messages are still delivered to this contact. This means that they serve different purposes.

The `archive` status is both set and removed automatically. So doing this manually doesn't make any sense. (It exists because of legacy stuff). So we possibly should remove the functionality to manually archive and unarchive a contact.

**Comment by AlfredSK** [comment]
But should a *failed* *OnePoll* list the contact under *Archived*? I saw that the last update was unsuccessful. But I would never have thought that this is the reason.

Two Friendica contacts that shouldn't appear there at all and a feed contact that is known good (working):

![image](https://user-images.githubusercontent.com/3656054/99900587-a344e680-2cb0-11eb-8e60-76888112cae1.png)

**Comment by AlfredSK** [comment]
The issue is even weirder. The contact of Philipp is completely fine. But it is still listed under 'archived'.

```
Contact: Philipp Holzer
Status
You are mutual friends with Philipp Holzer
Network type: friendica
Last update: Sun, 22 Nov 2020, 1:23 AM (Update was successful)
```

Contact is not archived. Update was successful. But contact is showing up as archived contact... 🤔

**Comment by MrPetovan** [comment]
My node has been unreachable fr 48 hours now because I started the latest database update, so technically it does make sense that my account would be showing up in this list. But it doesn't show visually why I'm in this list.

**Comment by AlfredSK** [comment]
In the contact details of your contact I have a line telling me that the last contact update wasn't successful.

**Comment by annando** [comment]
I made some "small" changes to `OnePoll` and I changed the query on the "contacts" page. The behaviour should now be more clear.
