### ISSUE TITLE
Installation does not start, "too many redirects" error

### ISSUE THREAD

**Issue by xanathon** [friendica/friendica#9649]
I tried to install Friendica one or two years ago and wanted to try again, I had the same problem then that I have now. I found no solution then and gave up.

I am on premium shared hosting with SSH access.

I git cloned Friendica and addons as per instructions. When I call the Friendica url I get a "Too many redirects" error (ERR_TOO_MANY_REDIRECTS) in (Vivaldi) and other Webkit browsers. The url in browser suddenly looks like this: 

https://fri.mydomain.de/index.php/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install

I tried to look up the "too many redirects" error on Google and here, but found no issues about this.

Help, please?

**Comment by AlfredSK** [comment]
At first glance I would guess that you either don't have a valid .htaccess file in your document root or your virtual host config is missing the AllowOverride option - in case you're using Apache web server.

**Comment by xanathon** [comment]
No idea what web server runs, since this is hosting (and from the Friendica docs I got the impression this runs on hosting), but there is no .htaccess in the root directory of the subdomain, since the install did not run yet, so there is only a .htaccess-dist. Or do I need to rename that, there is nothing about that in the install docs.

**Comment by xanathon** [comment]
I copied .htaccess-dist to .htaccess, but the same happens

**Comment by AlfredSK** [comment]
You should not have the index.php in the URL path. If the URL rewrite (defined in the .htaccess file) is working the path is only https://yourdomain.tld/install

The problem with hosting solutions is that some are pretty restricted. You need to make sure that own .htaccess files are supported and the rewrite mod for Apache is active. If you don't know the hosting environment you should ask the provider about that.

**Comment by xanathon** [comment]
I run complex apps there. Wordpress, Hubzilla, others, without any problems. .htaccess is definitely supported, as I said, it's a premium account. mod_rewrite is definitley active or the multitude of other web based apps there would not work.

**Comment by AlfredSK** [comment]
> I run complex apps there. Wordpress, Hubzilla, others, without any problems.

You didn't mention that before. So I started with the basics.

> as I said, it's a premium account.

Sorry, but that can mean all and nothing. The phrase "premium" says nothing about the actual environment. That's why I ask about it.

But still, the URL rewrite doesn't work like expected. There must be a configuration problem in your virtual host configuration. If you provide the config files here we can have a look why that might be the case.

**Comment by AlfredSK** [comment]
Hi @xanathon 
I saw a post of yours on the friendica support forum. Could you solve this issue? 
If so, I'm curious. :-) What was the cause?

**Comment by xanathon** [comment]
I had to omit `index.php` from the url, then it worked. Funny thing is: when I first called the subdomain after git clone the index.php appeared on it's own, i did not type it. 

However, a lot of other things did not work. Contrary to what is said in the official documentation I was not able to 

1. get the worker cron to run on all-inkl.com 
2. link embedding with preview fetching does not work and as I was told this is a known issue for years and not solved. 

Link preview embedding is a must for me, so that is a showstopper. After investing two days into a software that did not run on premium hosting with SSH access (despite what was said in the documentation) I gave up. I deleted the installation and database a few minutes ago. I guess my Fediverse experiment is over, since Hubzilla ceased to work with the 5.x update and I was looking for an alternative in Friendica.

**Comment by annando** [comment]
Well. It's sad that gave up so fast. I guess that the preview stuff would had been easily solved.

**Comment by xanathon** [comment]
One of the devs said in the support forum thread that it would not.

**Comment by Stratus3D** [comment]
I am having the same issue as @xanathon. I am trying to install Friendica on a shared hosting account and am getting the infinite `/install/` redirects that prevent me from completing the installation. My environment:

Apache/PHP/MySQL.

PHP info:

```
PHP 7.3.25 (cli) (built: Nov 24 2020 11:10:55) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.25, Copyright (c) 1998-2018 Zend Technologies
    with the ionCube PHP Loader + ionCube24 v10.4.5, Copyright (c) 2002-2020, by ionCube Ltd.
    with Zend OPcache v7.3.25, Copyright (c) 1999-2018, by Zend Technologies
```

I know mod_rewrite works on my host as well because I use it for my other static and PHP websites. I have also copied `.htaccess-dist` to `.htaccess` in the web root.

**Comment by Stratus3D** [comment]
Odd. I thought my browser might be doing something strange, so I tried curl and the request worked. Switched back to the browser and it started working. I think my browser must have cached something from when before I had copied the `.htaccess` file.

**Comment by xanathon** [comment]
I gave up on Friendica. Most of these Fediverse projects are way too cumbersome and way too user-unfriendly. After solving the infinite redirects a lot of other problems did arise. This is a ptity since alternatives to Facebook and other company-owned social media are sorely needed. But as long as this installation is not easy and the support ist not really helpful this will go nothing. I had similar problems with other platforms suchas GnuSocial (they just stopped answering a support thread), Hubzilla (that 5.0 update broke my hub) or Misskey (extremely bad and misleading documentation and complicated setup). I did not even try Diaspora since you cannot edit posts there. I would have donated money to any project with real, friendly and concise help, good documentation and easy installation, but I yet have to find such a project.

**Comment by Stratus3D** [comment]
Overall the installation went fine for me, and this issue was due to a mistake I made. I later finished setup and now have a nice working friendica instance. I do hope in the future UI gets more friendly so I have an easier time onboarding people, but I'm really thankful this project exists as it has saved me a lot of time already.

**Comment by MrPetovan** [comment]
>  I would have donated money to any project with real, friendly and concise help, good documentation and easy installation, but I yet have to find such a project.

@xanathon You're free to do whatever you want, but do you realize that this statement is a circular dependency, which probably explains why it didn't happen yet. If you don't donate resources projects need to improve because they haven't improved to your level of satisfaction, then it reduces the chances of them reaching that level om their own, and your subsequent donation would be superfluous since enough resources would already be available.

That said, what Friendica and many other open source projects need isn't money (we have no way to accept donations for example) but time, especially for the user documentation which is a hard challenge for developers, both in terms of perspective shift and motivation to tackle it instead of working on code.

**Comment by xanathon** [comment]
Nope, it isn't. To get helpful and friendly support would have been enough. Instead of that I regularily get "if it does not work, help coding", even here, were a feature stated as finished does not work at all (confirmed). That does not only sound arrogant, it actually is. Projects where developers act that way cannot expect donations from me, be it time or money. There are lots of other OSS projects that actually do not only care about their code but also about the users.

**Comment by annando** [comment]
Open source project require work from the users as well. Also people working on these projects are often developer, consultant and supporter in a single person. This means that time is really limited - which is much more true since this is all done in the spare time. Over the years working at this project I made the experience that the people of Friendica (users, administrators and coders) are a community of equals. There is no "I am the user and you have to help me!" or a "I am the coder and you have to live with what I coded!". It's more helping each other - and understanding when sometimes there is not much time for support.

**Comment by MrPetovan** [comment]
@xanathon Well, you were right about one thing, it did sound arrogant.

**Comment by xanathon** [comment]
Either you want new users for Friendica and the Fediverse or not. It seems the answer is: or not. Zuckerberg will be quite happy about it, because that way the majority of users will stay with Facbook and similar questionable platforms. Good luck with Friendica, you will need it.

**Comment by MrPetovan** [comment]
That's a lot of words to tell people you weren't helping before that you won't be helping them in the future.

**Comment by bkil** [comment]
Getting back to the technical side of the discussion, I had the very same infinite `/install` redirections at the beginning. `. htaccess` and rewrites also work well over here and I did manage to set it up manually, hence I didn't really look into what caused it. Just wanted to share another data point.

**Comment by andrigamerita** [comment]
Hi, today I'm trying to install Friendica (latest version from GitHub releases) on a shared host (Altervista) and I'm too having this issue.

If I go on `/` or `/index.php` of my website (`myname.altervista.org`) i get the infine redirect issue; if I go on `/install`, or any other URL, i get on a blank page with URL `/install`.

The issue happens both with PHP 7.3 and 8.

My host of course supports custom Apache .htacces files and, according to what people in the official forum have said, `mod_rewrite` is supported. I also tried setting the `RewriteBase /` directive in the file, as suggested in the comments, but no luck.

I will try asking for help in my host's forum, and will get back to here if I manage to solve the issue. In the meantime, does anyone have any ideas? Thanks

**Comment by damianwajer** [comment]
I had the same issue (PHP 7.4). As a workaround, you can try an [automatic installation](https://github.com/friendica/friendica/blob/develop/doc/Install.md#option-b-run-the-automatic-install-script):
```
bin/console autoinstall -f config/prepared.config.php
```

**Comment by MrPetovan** [comment]
Troubleshooting the local install of someone, we found out that this error occurs when the `.htaccess` file is ignored by Apache, bypassing the URL rewrite rules.

However I'm not sure why the `.htaccess` file isn't read in his case, as he used the same Virtual Host configuration (with `AllowOverride All`) as I do on my production server.

So the mystery stays complete.

**Comment by MrPetovan** [comment]
So, we've been able to fix this particular instance of an ignored `.htaccess` file because the main Apache2 configuration has a default `AllowOverride None` on `/var/www` on Ubuntu (at least). Any virtual host set in a subfolder of `/var/www` will inherit this value without being able to change it in the `VirtualHost` configuration block. 🤷‍♂️

The solution was to comment out the `AllowOverride None` line in the `<Directory /var/www>` block of the main Apache2 configuration file located in `/etc/apache2/apache2.conf`. This fix was specific for Ubuntu but I believe it would also work for other Debian-based distributions.

**Comment by bkil** [comment]
Just wanted to let you know that commenting it out may not be sufficient on recent versions:

https://httpd.apache.org/docs/current/mod/core.html#allowoverride

> Default: AllowOverride None (2.3.9 and later), AllowOverride All (2.3.8 and earlier)

**Comment by MrPetovan** [comment]
Thanks, hopefully a `AllowOverride All` statement in a VirtualHost block should do the trick.

**Comment by DarkShyMW** [comment]
But i have same issue, BUT - i use NGINX.

nginx config:
```
server {
  listen 80;
  listen [::]:80;
  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  {{ssl_certificate_key}}
  {{ssl_certificate}}
  server_name www.ponysocial.ru;
  return 301 https://ponysocial.ru$request_uri;
}

server {
  listen 80;
  listen [::]:80;
  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  {{ssl_certificate_key}}
  {{ssl_certificate}}
  server_name ponysocial.ru www1.ponysocial.ru;
  {{root}}

  {{nginx_access_log}}
  {{nginx_error_log}}

  if ($scheme != "https") {
    rewrite ^ https://$host$uri permanent;
  }

  location ~ /.well-known {
    auth_basic off;
    allow all;
  }

  {{settings}}

  location / {
    {{varnish_proxy_pass}}
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_hide_header X-Varnish;
    proxy_redirect off;
    proxy_max_temp_file_size 0;
    proxy_connect_timeout      720;
    proxy_send_timeout         720;
    proxy_read_timeout         720;
    proxy_buffer_size          128k;
    proxy_buffers              4 256k;
    proxy_busy_buffers_size    256k;
    proxy_temp_file_write_size 256k;
  }

  location ~* ^.+\.(css|js|jpg|jpeg|gif|png|ico|gz|svg|svgz|ttf|otf|woff|woff2|eot|mp4|ogg|ogv|webm|webp|zip|swf|map)$ {
    add_header Access-Control-Allow-Origin "*";
    expires max;
    access_log off;
  }
  
  # block these file types
  location ~* \.(tpl|md|tgz|log|out)$ {
    deny all;
  }

  # deny access to all dot files
  location ~ /\. {
    deny all;
  }

  # deny access to the CLI scripts
  location ^~ /bin {
    deny all;
  }

  if (-f $request_filename) {
    break;
  }
}

server {
  listen 8080;
  listen [::]:8080;
  server_name ponysocial.ru www1.ponysocial.ru;
  {{root}}

  try_files $uri $uri/ /index.php?$args;
  index index.php index.html;

  location ~ \.php$ {
    include fastcgi_params;
    fastcgi_intercept_errors on;
    fastcgi_index index.php;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    try_files $uri =404;
    fastcgi_read_timeout 3600;
    fastcgi_send_timeout 3600;
    fastcgi_param HTTPS "on";
    fastcgi_param SERVER_PORT 443;
    fastcgi_pass 127.0.0.1:{{php_fpm_port}};
    fastcgi_param PHP_VALUE "{{php_settings}}";
  }

  if (-f $request_filename) {
    break;
  }
}
```
