### ISSUE TITLE
The Archiv widget shows more years/months to chose than the user is active

### ISSUE THREAD

**Issue by rabuzarus** [friendica/friendica#9799]
### Bug Description

There seems an issue with the Archiv widget. It shows more years/months to chose than the user is active.
E.g. https://nerdica.net/profile/xthanys/status is active since 2021 but the Archiv widget shows dates back to 2016

### Friendica Version

2021.01

**Comment by MrPetovan** [comment]
So, huh, funny story, the first year shown is controlled by the user-specific config value `system.archive_visible_years` with a default value of 5 which explains the 2016 shown, but there's no form control to set this value in the user settings. So it's 5 years back for everybody.

Now, the question is, should this config exist at all? I personally believe so. Even if someone had an account since the first release of Friendica, they would still have only 11 lines in their archive widget, which isn't outlandish and doesn't justify the existence of a config value to limit the number of displayed years in the widget.

**Comment by AlfredSK** [comment]
Maybe it is possible to use the 'member_since' value instead of a fix value of 5.

**Comment by MrPetovan** [comment]
It's possible that removing the config value will actually yield the expected number of years for members less than 5 years old.

**Comment by MrPetovan** [comment]
Now I can't reproduce the issue. I've had to fix the widget to even display on my dev node, and it correctly displays only two years for my test account. that started posting in January 2020.

Everything rests on the query to retrieve the first row of the `thread` table related to the user, so I assume that something is fishy in that regard. I'll try to contact the nerdica admin privately to figure this out.

**Comment by AlfredSK** [comment]
If you need something please tell. I have enough accounts. :-)

**Comment by MrPetovan** [comment]
Can you reproduce the issue on any recent profile status page? Say, any account who started posting this month?

**Comment by AlfredSK** [comment]
Hmm. No. I don't have such a fresh account. But I have one that has been created in 2019. The status (/profile/username) page shows the widget as follows...

![image](https://user-images.githubusercontent.com/3656054/105885739-cf127e80-6009-11eb-8ade-7d27a1fea805.png)

The account hasn't posted anything (zero posts).

The network page shows this...

![image](https://user-images.githubusercontent.com/3656054/105885807-ecdfe380-6009-11eb-9e04-aaf2012214af.png)

Maybe the expiration setting is responsible for this on network page.

Btw.: Some accounts don't have an archive widget on status page (/profile/username) 🤔
