### ISSUE TITLE
Minor: String consistency: post actions should all start with capital letter

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#9993]
**Currently**
add tag
save to folder
add star
Languages
ignore thread
Remove locally
Block Hypolite Petovan (I would never do that ❤️)

**Expected**
Add Tag
Save To Folder
Add Star
Languages
Ignore Thread
Remove Locally
Block Hypolite Petovan (Still wouldn't  do that)

<img width="179" alt="post actions" src="https://user-images.githubusercontent.com/5708172/110216337-e36e5480-7eae-11eb-8c42-8b23a9a85a94.png">

**Comment by MrPetovan** [comment]
This has been fixed in the American English translation on Transifex, we just need to import the updated strings like we (well, @tobiasd) do before each release.

> Block Hypolite Petovan (I would never do that ❤️)

❤️

**Comment by tobiasd** [comment]
I've refreshed the EN-US translation from transifex in the RC branch, so this might be solved?

**Comment by urbalazs** [comment]
The issue cannot be fixed with the EN-US translation. Translators of other languages still see the source with lowercase letters, and they cannot know, that the translation should start with uppercase letter.

Take a look at the Hungarian translation. Without context, based on only the source strings on Transifex, how can I realize, that the translation should be Title Case (or Sentence case, because there is no Title Case in Hungarian grammar)? 

![image](https://user-images.githubusercontent.com/1006118/113460524-62589d80-9419-11eb-87b7-f73876fe1a0b.png)

To solve this issue, please change the source strings to the proper case: Sentence case or Title Case.

**Comment by tobiasd** [comment]
> Without context, based on only the source strings on Transifex, how can I realize, that the translation should be Title Case (or Sentence case

Many strings can be translated without the exact context known. For the others part of the translation process is to figure it out. I have not seen a single tool that really helps here, it's always investigative work. The way I'm doing it for the German translation is to look in Transifex where the string is used (Context Tab and there in the additional Information area). This gives me a filename and with that name a rough hint where to look in the Friendica UI for the exact usage of the string.

This works for most of them. If not, just asking about it in the development forum (and translation is part of the development process) should clarify the usage, or give the developers a hint about the problems translators suffer from their work they did not consider. And they don't consider them having bad intentions they just don't care, for them pixel perfect layout is simply more important.

Even if it was written as "Add Tag" in the sources you might need to have a look into the context of the string. In German there is no Title Case as well and the order of these two words is reversed to "Tag hinzufügen" and as tag is a noun, it is written uppercase anyway. Additionally, the German string has the double length compared to the original; something the developers might not have considered as well in their pixel perfect design (I don't remember if it was this string or a string in another context but there were already cases where the developers had to change their code because translations needed significantly more space then the English original).

Or, you see translated text in the Friendica UI and realize that the context was different then thought when doing the translation. Which might be solve-able by search and replace on Transifex, or when the string is used in more places of the code, by contacting the developers and discuss a solution with them.

**Comment by MrPetovan** [comment]
I personally tend to agree with @urbalazs that the source strings are misleading. It doesn't matter who came up with them and why, it will require some work to fix what is now a hindrance. I don't think it is fair to put this burden on people creating a new translation because they already have the steeper job to face the whole translation to do. So I believe we should make the job of translation newcomers easier, even if it means that we have to update all the other translations for this. Transifex stores the previous translations and suggests them, even if the translation string has changed, so this inconvenience is made easier.

**Comment by tobiasd** [comment]
Yes, change it I agree. But I don't think that it will help newcomers.

And please also change all other such strings so that all the wrongs are fixed.

**Comment by urbalazs** [comment]
I found another problem. See the Hungarian action bar:

![kép](https://user-images.githubusercontent.com/1006118/113505572-f2910280-953f-11eb-8a20-a147347cbf79.png)

As I said, there is no Title Case in Hungarian grammar, and my translations are:

```
$a->strings["dislike"] = "nem tetszik";
$a->strings["Quote Share"] = "Idéző megosztás";
```
As you see, the strings are converted to Title Case by the framework. This is not good. It should use the translations as is.

**Comment by MrPetovan** [comment]
Thanks for raising this issue, the capitalization was added in Javascript for translators not to have to re-translate uncapitalized titles in source translations. I guess we now have to fix the capitalization in the source strings and remove this CSS rule.

I'm not sure how to find all the wrong source strings though. I could comb Transifex for the capitalized English translations when the source isn't, but it will be painstaking, I'm welcoming suggestions.

**Comment by annando** [comment]
The CSS rule doesn't make sense in German as well. Although the starting letter of a title most likely will be upper case, the following doesn't need to be.

**Comment by MrPetovan** [comment]
The CSS rule only capitalize the first letter of these labels.

**Comment by MrPetovan** [comment]
I forgot to remove the frio CSS rule.
